### ISSUE TITLE
Fix configure_dev.sh so that it includes everything to build libsodium.

### ISSUE THREAD

**Issue by derbear** [algorand/go-algorand#1]
On Mac at least we need to brew install libtool, autoconf, and automake. These should be added to configure_dev.sh to simplify dev machine setup.

**Comment by iamswain25** [comment]
I was installing it on `golang:latest` docker, I needed to install `autoconf, sudo`

**Comment by jsign** [comment]
Just to mention in my env (almost vanilla Ubuntu 18.04.1) only `autoconf` was missing.

**Comment by algoradam** [comment]
PR #42 only fixes the mac build, we still need autoconf (and sudo?) on Linux

**Comment by jsign** [comment]
I guess this can be closed considering #189
