### ISSUE TITLE
ASC/TEAL - Application transaction types should be reflected in the type enum

### ISSUE THREAD

**Issue by jeapostrophe** [algorand/go-algorand#1006]
I think that `txn TypeEnum` should be expanded for the new application events, like creation and so on, rather than having to infer that a creation is happening based on global state being empty, etc.

**Comment by yaovi-a** [comment]
Verify if we already do this. If so, close.

**Comment by algoanne** [comment]
We'll make sure the documentation is clearer for the specific ambiguous cases you mention, but are not going to move forward with this change as of now.
