### ISSUE TITLE
goal clerk send displays a generic error when signing for multisig accounts

### ISSUE THREAD

**Issue by fabrice102** [algorand/go-algorand#1047]
### Subject of the issue

When the sender address is a multisig account, `goal clerk send ...` without `-o` option fails  with the following error message:
```
Couldn't sign tx with kmd: key does not exist in this wallet
```
even if the secret keys of all the public subkeys of the multisig are actually in `kmd`.

### Your environment
* Software version: `algod -v`

```
8589934598
2.0.6.stable [rel/stable] (commit #d9badc17)
go-algorand is licensed with AGPLv3.0
source code available at https://github.com/algorand/go-algorand
```

(same issue with version 2.0.5)

* Operating System details: Docker Ubuntu 18.04 on macOS. But same issue appears inside sandbox and also directly on macOS.

### Steps to reproduce

```
root@985994e08db3:~# goal account new
Created new account with address H7UTPL54CYL7SDDZI3L2GBBNCZAO72W4HZH6DZVH7KKW5IVMXFDCFGACRY

root@985994e08db3:~# goal account new
Created new account with address HOLAGH6TJOEB4UBMWSS5SGVANEYOUYQHAKDAGCZ5ORPV6LHBUBGYJAGE3M

root@985994e08db3:~# goal account multisig new -T 1 H7UTPL54CYL7SDDZI3L2GBBNCZAO72W4HZH6DZVH7KKW5IVMXFDCFGACRY HOLAGH6TJOEB4UBMWSS5SGVANEYOUYQHAKDAGCZ5ORPV6LHBUBGYJAGE3M
Created new account with address Y4HZICTIAJR7GOKI64B6I7SRSRSIWIMX627BOU5IIC3RYWWIME6Q54OOXM

root@985994e08db3:~# goal clerk send -a 1 -f Y4HZICTIAJR7GOKI64B6I7SRSRSIWIMX627BOU5IIC3RYWWIME6Q54OOXM -t Y4HZICTIAJR7GOKI64B6I7SRSRSIWIMX627BOU5IIC3RYWWIME6Q54OOXM
Couldn't sign tx with kmd: key does not exist in this wallet
```

### Expected behaviour

* Either have an error message which explains that transactions from multisig account cannot be signed by `goal clerk send`, but rather should be expored using the `--out` option and signed using `goal clerk multisig sign ...`;
* Or actually sign the messages if possible (and if impossible, also make clear that the reason is that not enough multisig secret subkeys are known). However, it is most likely the case that in most settings, `kmd` does not know all the secret keys necessary for signing (there might be exceptions, but they should be rare).

### Actual behaviour

Error message:
```
Couldn't sign tx with kmd: key does not exist in this wallet
```

**Comment by tzaffi** [comment]
@algoanne and @fabrice102 

I recently attempted to re-create this problem. However, I got a much friendlier message:

```
Couldn't sign tx with kmd: key does not exist in this wallet (for multisig accounts, write tx to file and sign manually)
```

This better message is thanks to @jannotti 's PR #4175.

I propose that we consider this issue resolved, but others can opine as well.

**Comment by algoanne** [comment]
I concur @tzaffi , thanks for looking into it.
