### ISSUE TITLE
documentation link

### ISSUE THREAD

**Issue by astefano** [algorand/go-algorand#1050]
At [agreement-service](https://github.com/algorand/go-algorand/blob/master/docs/agreement_service.md) it is stated: 

> Reading the Algorand SOSP paper before diving into this package will be super helpful for understanding what's going on.

However, the terminology in the documentation is the one from the [whitepaper](https://eprint.iacr.org/2018/377), isn't it?

**Comment by algorandskiy** [comment]
Hello, sorry for the late response. The link you posted is a correct one.
