### ISSUE TITLE
TEAL/ASC - Document usage pattern for applications transferring ALGOs

### ISSUE THREAD

**Issue by jeapostrophe** [algorand/go-algorand#1052]
I talked to @algobolson last week about using the new application contracts for managing accounts and presented the following problem to him.

Suppose I have an account X that contains 100 ALGOs. I want to have that account X managed by an application J. Next, I have three users: A, B, and C, each with accounts. I want to have C initiate the following group of atomic transfers:

- A removes 50 ALGOs.
- B removes 50 ALGOs.
- C sends in 10 ALGOs.
- C makes call K on the application.

I can represent this as a transaction set like the following:

```
to_a = { type = pay, from = X, to = A, amount = 50 }
to_b = { type = pay, from = X, to = B, amount = 50 }
from_c = { type = pay, from = C, to = X, amount = 10 }
c_call = { type = appl, from = C, app-id = J, args = K }
```

However, what do they get signed with? I believe that `from_c` gets signed by C's private key, as does `c_call`, because they are both claim to be originated from C. It is more confusing about what `to_a` and `to_b` should be signed with?

There is nothing inside of Algorand that lets me operationalize the phrase, "I want to have that account X managed by an application J."

I believe what I should do is create a new TEAL contract, Z, that does approves if "Is this transaction part of a group that contains an `appl` transaction for app-id `J`?" is true. Then, I would sign `to_a` and `to_b` with Z. (However, this means that I have to embed the application id J into Z, which means I have to access to the compiler at runtime (i.e. after I create the application) which is #1051 is especially important.

I believe that SDK function `signLogicSigTransaction`, which only takes one transaction, knows the transaction is part of a larger group because I have already called `assignGroupID` and there's some sort of global state hidden behind the SDK that allows it to see the details of the other transactions in the group?

Is this the correct and intended path for such a thing?

**Comment by algoanne** [comment]
stale
