### ISSUE TITLE
ASC application limit

### ISSUE THREAD

**Issue by jeapostrophe** [algorand/go-algorand#1055]
I don't understand how many applications there can be.

As far as I can tell, applications are only identified by the `ApplicationID` and are globally allocated into a pool with `uint64` addresses. I base this on the fact that transaction fields don't have any identifying information about applications other than this.

I think that `uint64` drastically underestimates the number of applications that people will want to make. There should be as many or more applications slots as there are account addresses.

Instead, I think that `uint64` is a reasonable limit on the number created by a single account, although obviously the more the merrier. However, I did some digging and it is even worse than I thought! In this code --- https://github.com/justicz/go-algorand/blob/a3200f5e0b6485629191ad844612e136336193bf/config/consensus.go#L672 --- we see `vFuture.MaxAppsCreated = 10` --- and the comment says "// Maximum number of apps a single account can create". Only 10 applications? That is laughably small. In the DApp ecosystem, many products are designed to create a new contract instance for each use of the program. For example, in our game wager DApp, we create a new Algorand application each time you want to have a wager, which would mean that you could only play e.g. Chess 10 times before you've used all of your Algorand applications for all time!

I think that the creator of an application should be saved in the database (presumably it already is to keep track of the limit) and added to the transaction fields to be part of the lookup. Finally, I think that application creation transactions should explicitly have the creator as a field. Presently, I assume the creator is based on the signer of the creation transaction, because they aren't a field.

**Comment by suefay** [comment]
I think the stateful TEAL(application) is still in the scope of layer 1. So for the performance consideration, the limitation is required.  ASC2(if planned,. or another name)  could be good for more applications.

**Comment by yaovi-a** [comment]
Thanks for submitting, we'll take it under consideration.
