### ISSUE TITLE
TEAL - expt, left and right shifts

### ISSUE THREAD

**Issue by jeapostrophe** [algorand/go-algorand#1062]
It would be nice to have exponent, left, and right shifts. These are really convenient for working with bitvectors. I have a Tic-Tac-Toe implementation in TEAL that I have to use an array of bools for, which is very inefficient during communication.

**Comment by jeapostrophe** [comment]
Implemented in #1640

**Comment by jannotti** [comment]
The user need has been addressed by the addition of getbit, setbit (and to a lesser extent, getbyte, setbyte)
