### ISSUE TITLE
Sending logs to stdout

### ISSUE THREAD

**Issue by ksemaev** [algorand/go-algorand#1081]
Hi guys! Is it possible to use some option, feature or build argument to send logs to stdout/stderr instead of local file?

**Comment by JasonWeathersby** [comment]
right now a file is required. You can set the Max size in the config file and then just tail -f the log file.

**Comment by ksemaev** [comment]
@JasonWeathersby TY for your response. I kind of can't, I'm doing docker and I need 1 main process so things won't get ugly :(

**Comment by pbennett** [comment]
You could do something similar to https://docs.docker.com/engine/reference/builder/#exec-form-entrypoint-example (in the 'if you have some extra cleanup'). ie:

```
goal node start
tail -F data/node.log&
# wait for SIGTERM
read
goal node stop
```

**Comment by ksemaev** [comment]
@pbennett TY I can, but it's also not looking right, I don't need tail process for logs, having logs sent to stdout is a best practice for docker setups due to many reasons, that's why I ask to place it in code

**Comment by pbennett** [comment]
It's a pretty trivial code change to be honest, but the default runtime method of the goal node XX sub-command spawning algod on your behalf (with completely different parameters complicates things a bit).
Changing algod itself it take a parameter requesting stdout log output (and/or config.json setting) would be a start.  You'd then use it as your docker entrypoint.

**Comment by brianolson** [comment]
I'm not sure who's using it, but:
`./docker/build/algod.Dockerfile`
runs
`./docker/release/algod_docker_init.sh`
and that does a cute thing at the end `goal node start; sleep 5; goal node status`, but maybe it shouldn't and the more Docker-ish thing would be to just exec `algod` with stdout logging.

**Comment by onetechnical** [comment]
> I'm not sure who's using it, but:
> `./docker/build/algod.Dockerfile`
> runs
> `./docker/release/algod_docker_init.sh`
> and that does a cute thing at the end `goal node start; sleep 5; goal node status`, but maybe it shouldn't and the more Docker-ish thing would be to just exec `algod` with stdout logging.

I think the thing that keeps the process open is the `tail -f /dev/null`, which obviously will just not log. (I'd be curious if a `goal node status -w 1000`would also work.)

STDOUT with on-disk logging disabled would probably be preferred for docker. I think if you `tail -f node.log` it'll stop logging after log rotation happens (and will chew through up a bunch of container disk, 2 GB by default).

**Comment by brianolson** [comment]
> STDOUT with on-disk logging disabled
I'd presume that stdout replaces node.log and trying to do both would be a feature outside the scope of this ticket. Probably the implementation is that whatever configuration names "node.log" treats "-" as the name for stdout and logs go to that without rotation.

**Comment by onetechnical** [comment]
> > STDOUT with on-disk logging disabled
> 
> I'd presume that stdout replaces node.log and trying to do both would be a feature outside the scope of this ticket. Probably the implementation is that whatever configuration names "node.log" treats "-" as the name for stdout and logs go to that without rotation.

On a side note there is no config currently (it's hardcoded). Turning it into a config would also be needed.

**Comment by algoanne** [comment]
I believe this is stale and no longer an issue. lmk if not
