### ISSUE TITLE
`Make Test` is broken

### ISSUE THREAD

**Issue by stechu** [algorand/go-algorand#1087]
### Subject of the issue
`make test` is broken

### Your environment
* Software version: `algod -v`
* Node status if applicable: `goal node status`
* Operating System details. 
* In many cases log files and cadaver files are also useful to include. Since these files may be large, an Algorand developer may request them later. These files may include public addresses that you're participating with. If that is a concern please be sure to scrub that data.

### Steps to reproduce
`./scripts/configure_dev.sh`
`make install`
`make test` 
Running on Ubuntu 18.04 LTS
### Actual behaviour
Get error like:
`can't load package: cannot find module providing package github.com/stechu/go-algorand/agreement: module github.com/stechu/go-algorand/agreement: reading https://gocenter.io/github.com/stechu/go-algorand/agreement/@v/list: 404 Not Found`

**Comment by brianolson** [comment]
This is only because you checked out your fork of go-algorand, if you check it out as algorand/go-algorand, but then add your fork as an additional secondary repo (`git remote add ...`) and check out your changes on your fork, that should work (that's how my checkout is organized)

**Comment by stechu** [comment]
@brianolson thanks, somehow I screwed up my local go environtment.
