### ISSUE TITLE
Remove dead v8 and v10 upgrades and bring agreement fuzzer up to date

### ISSUE THREAD

**Issue by algoradam** [algorand/go-algorand#109]
The agreement fuzzer currently tests pre-FPR agreement behavior and breaks when deprecating v10 (and possibly also v8?). Fix the agreement fuzzer to properly deal with FPR-enabled agreement and then deprecate the dead v8 and v10 upgrade code.

**Comment by tsachiherman** [comment]
The agreement fuzzer logic was brought up-to-date.

**Comment by ian-algorand** [comment]
old issue, deferring for now until it becomes a priority

**Comment by ian-algorand** [comment]
oh, looks like it was handled
