### ISSUE TITLE
Remove dead upgrades v10 through v16

### ISSUE THREAD

**Issue by algoradam** [algorand/go-algorand#110]
Mainnet launched with v17, so all previous upgrade code should be removed. This is the continuation of #59 , which was too big to do all at once.

**Comment by ian-algorand** [comment]
let's also take into account this flaky test (As seen on travis):

– FAIL: TestAccountsCanSendMoneyAcrossUpgradeV12toV13 (134.51s)
require.go:794: 
Error Trace:	send_receive_upgrade_test.go:166
send_receive_upgrade_test.go:64
Error: Received unexpected error:
failed to see confirmed transaction by round 22
Test: TestAccountsCanSendMoneyAcrossUpgradeV12toV13
Messages: waiting for txn
FAIL
