### ISSUE TITLE
REST API /v1/account/{address}/transactions incorrect error message

### ISSUE THREAD

**Issue by fabrice102** [algorand/go-algorand#1126]
### Subject of the issue

When calling the REST API endpoint `/v1/account/{address}/transactions?firstRound=...&lastRound=...` on a range after the current round on a *non-archival* node, the following error message is displayed:

```this is a non-archival node and the requested block has been already delete```

(error 500)

### Your environment
* Software version: `algod -v`
```
8589934598
2.0.6.dev [stable] (commit #d9badc17)
go-algorand is licensed with AGPLv3.0
source code available at https://github.com/algorand/go-algorand
```
* Operating System details. macOS

### Steps to reproduce

See subject of the issue.

### Expected behaviour

Expecting the same error message as for an archival node, like:
```ledger does not have entry 7134600 (latest 7029513, committed 7029513)```

### Actual behaviour

Got error message:
```this is a non-archival node and the requested block has been already delete```

**Comment by fabrice102** [comment]
Additionally, with a non-archival node, if `lastRound` is after the current round, the following error message:
```this is a non-archival node and the requested block has been already delete```
is displayed, while an archival node, the expected transactions are returned

**Comment by ian-algorand** [comment]
Fixed in V2.
