### ISSUE TITLE
Adding default values for optional parameters in REST API

### ISSUE THREAD

**Issue by fabrice102** [algorand/go-algorand#1128]
**Is your feature request related to a problem? Please describe.**

Many REST API calls do not specify the default value of optional parameters

See for example: https://github.com/algorand/go-algorand/blob/b6524b69c33e6a87cd6033bd245773132b81734b/daemon/algod/api/server/v1/handlers/handlers.go#L894

**Describe the solution you'd like**

Add a text `(default to ...)` in all these cases, as in https://github.com/algorand/go-algorand/blob/b6524b69c33e6a87cd6033bd245773132b81734b/daemon/algod/api/server/v1/handlers/handlers.go#L1507

**Comment by ian-algorand** [comment]
This got fixed in V2. Closing but let myself or @rotemh know if you have any questions/concerns.
