### ISSUE TITLE
v2 API missing asset-by-id lookup

### ISSUE THREAD

**Issue by brianolson** [algorand/go-algorand#1141]
Transactions refer to assets by uint64 asset-id. It's important to be able to look up the asset metadata by asset-id. The handler /v1/asset/{index} has no replacement in /v2/ APIs.

**Describe the solution you'd like**

Re-create /v1/asset/{index} as /v2/asset/{index}
(likely with updated data structures consistent with other V2 APIs)

**Additional context**

`algod` has to have fast lookup by id internally when processing transactions, so may as well make that info available.

The same thing applies to /v1/application/{index} (still on a development branch)

**Other Solutions**
1) add `/v2/asset/{id}/creator` and `/v2/application/{id}/creator`, these would return the creator account which can then be looked up with `/v2/account/{addr}`
2) add `creator_of={id}` to `/v2/accounts` to allow looking up the creator of a particular application/asset directly.

**Comment by algorandskiy** [comment]
Implemented in https://github.com/justicz/go-algorand/pull/139
