### ISSUE TITLE
Is RoundInterrupted a normal status code ?

### ISSUE THREAD

**Issue by haow85** [algorand/go-algorand#117]
I ran a carpenter -d ~/.algorand command and got a full screen of status code of RoundInterruped. Is this a normal status code ? It was only interrupted by an "Attest" or something else similar once in a while.

**Comment by Karmastic** [comment]
When you first install the software, or if you have not run it for a while,
your node needs to catch up with the network.  The RoundInterrupted output
from carpenter is what you see when the consensus code gets interrupted by
the catch up code retrieving blocks.  The network is currently > 430000
rounds - once you catch up you'll see the normal consensus process output
from carpenter.

**Comment by Vervious** [comment]
(closing since the question appears to be resolved. But feel free to reopen or ask a follow-up.)
