### ISSUE TITLE
Fix warning spam: "http block fetcher response status code : 400"

### ISSUE THREAD

**Issue by winder** [algorand/go-algorand#12]
Noticed these warnings in the logs at a rate of about 3/second. We probably don't need to keep making requests when the status is 400

```
{"file":"fetcher.go","function":"github.com/algorand/go-algorand/rpcs.(*NetworkFetcher).FetchBlock","level":"info","line":221,"msg":"networkFetcher.FetchBlock: asking client xxxx:4161 for block 237179","time":"2019-06-13T15:28:08.423330Z"}
{"file":"httpFetcher.go","function":"github.com/algorand/go-algorand/rpcs.(*HTTPFetcher).GetBlockBytes","level":"warning","line":88,"msg":"http block fetcher response status code : 400","time":"2019-06-13T15:28:08.451490Z"}
```

**Comment by tsachiherman** [comment]
It's true that we should make requests that would return 400 ( i.e. BadRequest ). But more important is to understand the reason we received 400, which isn't returned and logged.
I'd suggest adding to the HTTP response either a header or a body content that would allow us to communicate the reason for which this is a "bad" request. Then, we should log the reason along with the returned error.
That would give us visibility for the best fix for the problem.
