### ISSUE TITLE
Conversion from uint11 to byte array may lead to wrong result.

### ISSUE THREAD

**Issue by mxmauro** [algorand/go-algorand#120]
Hi,

Near the end of function `toByteArray` in `crypto/passphrase/passphrase.go`, it incorrectly checks if the current `buffer` value is not zero instead of checking if the number of bits (`numberOfBits`) is different than zero.

Regards,
Mauro.

**Comment by rotemh** [comment]
The buffer always contain the last bits (see line 167) so it provides the same result. Can you provide an example that produces an incorrect result?

**Comment by zeldovich** [comment]
The check looks at the value of buffer, so if all the bits are zero, then nothing happens in the current code.

**Comment by mxmauro** [comment]
The current use of the function won't raise the issue because when a mnemonic is generated, it is padded with extra zeroes and, when converted back to a pk, as the code says, 264 bits is a multiple of 8.

But in the future, if the function is used with other purpose, the problem may appear if the last processed bits are not zero.

Also you can refer to the original stackoverflow code where `accBits` is checked in the `flush` function.

**Comment by rotemh** [comment]
Good catch. See PR #122

**Comment by rotemh** [comment]
@zeldovich I'll do a pass on the SDKs to make sure it does the right thing as well.

**Comment by mxmauro** [comment]
Excellent 😊
