### ISSUE TITLE
goal clerk compile accepts programs that jumps after last instruction

### ISSUE THREAD

**Issue by fabrice102** [algorand/go-algorand#1212]
### Subject of the issue

If a program jumps to a label at the end of the program after which there is no instruction, `algod` will reject the program systematically. However, `goal clerk compile` does compile the program without issue.

See also https://github.com/algorand/pyteal/issues/5

### Your environment
* Software version: `algod -v`

```
8589934599
2.0.7.dev [HEAD] (commit #7b6d4d47)
go-algorand is licensed with AGPLv3.0
source code available at https://github.com/algorand/go-algorand
```

* Node status if applicable: `goal node status`

```
Last committed block: 7680192
Time since last block: 3.7s
Sync Time: 0.0s
Last consensus protocol: https://github.com/algorandfoundation/specs/tree/e5f565421d720c6f75cdd186f7098495caf9101f
Next consensus protocol: https://github.com/algorandfoundation/specs/tree/e5f565421d720c6f75cdd186f7098495caf9101f
Round for next consensus protocol: 7680193
Next consensus protocol supported: true
Last Catchpoint: 7680000#UINZMCTITNOSEMF2I2CTBRHHBK7CNCPJYWPSWJ7WRNZ5ABGXTQLA
Genesis ID: testnet-v1.0
Genesis hash: SGO1GKSzyE7IEPItTxCByw9x8FmnrCDexi9/cOUJOiI=
```

* Operating System details. macOS

### Steps to reproduce

Create a file `basic.teal`:

```
int 1
bnz l
l:
```

And run:
```bash
$ goal clerk compile basic.teal
basic.teal: ZV47DPGNBFFHWBNSI3WDA4RH5LCWIVTTZKJAP45DCCXR5J5ZOFJH7RCICU

$ goal clerk send --from-program basic.teal --to GCBRBIIMS7IVTHC3Y7ML6WAGGPK4L3LVSHDWXPTMD5YO2E7CFWNN5X2KOE --amount 10
Couldn't broadcast tx with algod: HTTP 400 Bad Request:   8 bnz target beyond end of program

$ goal clerk compile -D basic.teal.tok
// version 1
intcblock 1
intc_0
bnz label1
```

### Expected behaviour

`goal clerk compile` and `algod` should both either accept or reject the program.

### Actual behaviour

`goal clerk compile` accepts while `algod` rejects.

Decompilation also uses a non-existing label `label1`.

**Comment by algorandskiy** [comment]
Starting from TEAL v2 branching behind the last instruction is allowed see [the relevant code in `logic/eval.go`](https://github.com/algorand/go-algorand/blob/master/data/transactions/logic/eval.go#L1092)

So that the following program works in TEAL v2:
```
#pragma version 2
int 1
bnz l
l:
```

In the same time we still have problem with TEAL v1 compiler, as described in the ticket.
