### ISSUE TITLE
Stream Mobile Indexer Logs to Datadog

### ISSUE THREAD

**Issue by bricerisingalgorand** [algorand/go-algorand#1232]
Right now we can see rest calls to indexer through the streamed nginx logs, but since indexer is running on fargate the logs aren't being streamed by the datadog daemon.

**Comment by ian-algorand** [comment]
@bricerisingalgorand can you estimate this ticket? The dev ops team wasn't sure how to approach this in your stead.

**Comment by onetechnical** [comment]
I think we may want to migrate away from Fargate in general, so I'm going to close this.
