### ISSUE TITLE
Cannot get latest version: module contains a go.mod file, so module path should be github.com/algorand/go-algorand/v2

### ISSUE THREAD

**Issue by KateGo520** [algorand/go-algorand#1272]
## Background
The `github.com/algorand/go-algorand` uses [Go modules](https://github.com/golang/go/wiki/Modules) and the current release version is `v2`. And it’s module path is `"github.com/algorand/go-algorand"`, instead of `"github.com/algorand/go-algorand/v2"`. It must comply with the specification of "Releasing Modules for v2 or higher" available in the Modules documentation. Quoting the specification:
> A package that has opted in to modules _must_ include the major version in the import path to import any v2+ modules
> To preserve import compatibility, the go command requires that modules with major version v2 or later use a module path with that major version as the final element. For example, version v2.0.0 of _example.com/m_ must instead use module path _example.com/m/v2_.
https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher

## Steps to Reproduce
GO111MODULE=on, run `go get` targeting any version >= v2.0.3-stable of the `algorand/go-algorand`:
```
$ go get github.com/algorand/go-algorand@v2.0.15-beta
go: finding github.com/algorand/go-algorand v2.0.15-beta
go: finding github.com/algorand/go-algorand v2.0.15-beta
go get github.com/algorand/go-algorand@v2.0.15-beta: github.com/algorand/go-algorand@v2.0.15-beta: invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v2
```
SO anyone using Go modules will not be able to easily use any newer version of `algorand/go-algorand`.

### 1. Kill the go.mod files, rolling back to GOPATH.
This would push them back to not being managed by Go modules (instead of incorrectly using Go modules).
Ensure compatibility for downstream module-aware projects and module-unaware projects projects

I see these dependencies in your go.mod file, which need modle awareness. So you'd better not use third-party tools(such as: Dep, glide, govendor…).
```
github.com/labstack/echo/v4 v4.1.16
```
You also need to update the import path to:
```
import github.com/labstack/echo/…
```

### 2. Fix module path to strictly follow SIV rules.
Patch the `go.mod` file to declare the module path as `github.com/algorand/go-algorand/v2` as [per the specs](https://github.com/golang/go/wiki/Modules#semantic-import-versioning). And adjust all internal imports.
The downstream projects might be negatively affected in their building if they are module-unaware (Go versions older than 1.9.7 and 1.10.3; Or use third-party dependency management tools, such as: Dep, glide,govendor…).

If you don't want to break the above repos. This method can provides better backwards-compatibility.
Release a v2 or higher module through the major subdirectory strategy: Create a new v2 `subdirectory` (github.com/algorand/go-algorand/v2) and place a new go.mod file in that subdirectory. The `module path` must end with `/v2`. Copy or move the code into the v2 subdirectory. Update `import statements` within the module to also use `/v2` (import "github.com/algorand/go-algorand/v2/…"). Tag the release with `v2.x.y`.

### 3.  Suggest your downstream module users use hash instead of a version tag.
If the standard rule of go modules conflicts with your development mode. Or not intended to be used as a library and does not make any guarantees about the API. So you can’t comply with the specification of "Releasing Modules for v2 or higher" available in the Modules documentation. 
Regardless, since it's against one of the design choices of Go, it'll be a bit of a hack. Instead of `go get github.com/algorand/go-algorand@version-tag`, module users need to use this following way to get the `algorand/go-algorand`:
   (1) Search for the `tag` you want (in browser)
   (2) Get the `commit hash` for the `tag` you want
   (3) Run `go get github.com/algorand/go-algorand@commit-hash`
   (4) Edit the go.mod file to put a comment about which version you actually used
This will make it difficult for module users to get and upgrade `algorand/go-algorand`.

**[*]** You can see who will be affected here: [2 module users, e.g., outerdev/algoc, gemerio/go-gemer]
https://github.com/search?q=algorand%2Fgo-algorand+filename%3Ago.mod&type=Code&ref=advsearch&l=&l=

## Summary
You can make a choice to fix DM issues by balancing your own development schedules/mode against the affects on the downstream projects.

For this issue, `Solution 2` can maximize your benefits and with minimal impacts to your downstream projects the ecosystem. 

## References
* https://github.com/golang/go/wiki/Modules#semantic-import-versioning
* https://golang.org/cmd/go/#hdr-Module_compatibility_and_semantic_versioning
* https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher

**Comment by KateGo520** [comment]
@tsachiherman  @btoll  
Could you help me review this issue? Thx :p

**Comment by tsachiherman** [comment]
For the short-term, I don't think that we're going to do much about this one. At this time, I'm unaware of other projects which includes this as a base-project. ( this is not the case with SDKs, where we want to have that ).
However, I do think that this is a valuable feedback, and I will try to take this into account for the subsequent releases.
( note that in either way it will not be fixed "retroactively", and will affect only future branches )

**Comment by tsachiherman** [comment]
@KateGo520 just thinking out loud : what would happen if the GitHub release tags would be called r2.0.15 instead of v2.0.15 ?
would that make the tag into a semantic version v0.0.0-XXXX which would no longer force us from doing any additional change ? 
According to go documentation : `In semantic versioning, changing the major version number indicates a lack of backwards compatibility with earlier versions.`. The go-algorand repository is not a single library, and I'm pretty sure that the internal interfaces are getting `broken` very frequently.
I can't honestly see how we apply the above strategy to this repo without breaking this repo into series of smaller units.

**Comment by KateGo520** [comment]
@tsachiherman   The tag `r2.0.15` doesn't follow Semantic Versioning, which means that tag will be ignored by Go modules and replaced by pseudo-versions. Else the mod file shows something like `github.com/algorand/go-algorand v0.0.0-20200813213404-379c5d554170` which is not very readable and difficult to upgrade.

**Comment by yaovi-a** [comment]
Thanks for the submission but we're not looking to change the versioning structure at the moment.
