### ISSUE TITLE
Add Get Tx by ID to v2 API

### ISSUE THREAD

**Issue by Priegle** [algorand/go-algorand#1398]
**Is your feature request related to a problem? Please describe.**

Currently, when an entity submits a transaction to the network and wants to make sure it was confirmed there are two options:
1. Look for the transaction in the pending queue
2. Look for the transaction in the indexer

If you're using the pending queue to confirm a transaction has been accepted, your application will not work reliably in a clustered node environment (due to the queues being different across nodes) which makes transaction submission at scale (or just via a 3rd party service) hard.

If you are using the indexer it means you have to spin up additional infrastructure and manage that for a very small singular need, which feels like overkill.

**Describe the solution you'd like**

An API endpoint in algod that returns transaction by ID.  There is an understanding that it would be limited to the last 1000 blocks which reduces the use cases here to effectively just "is the transaction that i just submitted confirmed".

**Comment by winder** [comment]
@Priegle this is the current behavior of the `/v2/transactions/pending/{txid}` endpoint. Attached below is the documentation. This case would be the "transaction committed" case. If that sounds like what you're looking for lets close this ticket.

```
Given a transaction id of a recently submitted transaction, it returns information about it.  There are several cases when this might succeed:
- transaction committed (committed round > 0)
- transaction still in the pool (committed round = 0,      pool error = "")
- transaction removed from pool due to error (committed round = 0, pool error != "")

Or the transaction may have happened sufficiently long ago that the node no longer remembers it, and this will return an error.
```

**Comment by Priegle** [comment]
@winder no, can't be pending tx as the pool is not guaranteed to be there same across nodes and it needs to work for clustered node environments

**Comment by winder** [comment]
I'm closing this issue based on discussions we had yesterday.

To summarize: "pending" also includes recently committed transactions, just like the proposed `/v2/transaction/{txid}` endpoint. Once the transaction has been committed it can be looked up from any node. This can be verified by starting a testnet sandbox, and querying for any recently committed transaction found on https://testnet.algoexplorer.io/
