### ISSUE TITLE
Fix KMD deadlock discovered by arm64 integration tests

### ISSUE THREAD

**Issue by egieseke** [algorand/go-algorand#1402]
Running the following test on arm64 generated the kmd-err.log file below.

`test/scripts/e2e_client_runner.py`

**kmd-err.log**

`cat /tmp/tmphn5s735i/net/Node/kmd-v0.5/kmd-err.log
POTENTIAL DEADLOCK:
Previous place where the lock was grabbed
goroutine 138 lock 0x40000243a0
~/go-algorand/daemon/kmd/wallet/driver/sqlite.go:367 driver.(*SQLiteWalletDriver).CreateWallet { swd.mux.Lock() } <<<<<
~/go-algorand/daemon/kmd/api/v1/handlers.go:175 v1.postWalletHandler { err = walletDriver.CreateWallet(walletName, walletID, []byte(req.WalletPassword), req.MasterDerivationKey) }
~/go-algorand/daemon/kmd/api/v1/handlers.go:1264 v1.wrapCtx.func1 { handler(ctx, w, r) }
/usr/local/go/src/net/http/server.go:1995 http.HandlerFunc.ServeHTTP { f(w, r) }
~/go-algorand/daemon/kmd/api/v1/handlers.go:1277 v1.reqCallbackMiddleware.func1.1 { next.ServeHTTP(w, r) }
/usr/local/go/src/net/http/server.go:1995 http.HandlerFunc.ServeHTTP { f(w, r) }
~/go-algorand/daemon/kmd/api/v1/auth.go:50 v1.authMiddleware.func1.1 { next.ServeHTTP(w, r) }
/usr/local/go/src/net/http/server.go:1995 http.HandlerFunc.ServeHTTP { f(w, r) }
~/go-algorand/daemon/kmd/api/cors.go:55 api.corsMiddleware.func1.1 { next.ServeHTTP(w, r) }
/usr/local/go/src/net/http/server.go:1995 http.HandlerFunc.ServeHTTP { f(w, r) }
~/go/pkg/mod/github.com/gorilla/mux@v1.6.2/mux.go:162 mux.(*Router).ServeHTTP { handler.ServeHTTP(w, req) }
/usr/local/go/src/net/http/server.go:2774 http.serverHandler.ServeHTTP { handler.ServeHTTP(rw, req) }
/usr/local/go/src/net/http/server.go:1878 http.(*conn).serve { serverHandler{c.server}.ServeHTTP(w, w.req) }

Have been trying to lock it again for more than 30s
goroutine 143 lock 0x40000243a0
~/go-algorand/daemon/kmd/wallet/driver/sqlite.go:367 driver.(*SQLiteWalletDriver).CreateWallet { swd.mux.Lock() } <<<<<
~/go-algorand/daemon/kmd/api/v1/handlers.go:175 v1.postWalletHandler { err = walletDriver.CreateWallet(walletName, walletID, []byte(req.WalletPassword), req.MasterDerivationKey) }
~/go-algorand/daemon/kmd/api/v1/handlers.go:1264 v1.wrapCtx.func1 { handler(ctx, w, r) }
/usr/local/go/src/net/http/server.go:1995 http.HandlerFunc.ServeHTTP { f(w, r) }
~/go-algorand/daemon/kmd/api/v1/handlers.go:1277 v1.reqCallbackMiddleware.func1.1 { next.ServeHTTP(w, r) }
/usr/local/go/src/net/http/server.go:1995 http.HandlerFunc.ServeHTTP { f(w, r) }
~/go-algorand/daemon/kmd/api/v1/auth.go:50 v1.authMiddleware.func1.1 { next.ServeHTTP(w, r) }
/usr/local/go/src/net/http/server.go:1995 http.HandlerFunc.ServeHTTP { f(w, r) }
~/go-algorand/daemon/kmd/api/cors.go:55 api.corsMiddleware.func1.1 { next.ServeHTTP(w, r) }
/usr/local/go/src/net/http/server.go:1995 http.HandlerFunc.ServeHTTP { f(w, r) }
~/go/pkg/mod/github.com/gorilla/mux@v1.6.2/mux.go:162 mux.(*Router).ServeHTTP { handler.ServeHTTP(w, req) }
/usr/local/go/src/net/http/server.go:2774 http.serverHandler.ServeHTTP { handler.ServeHTTP(rw, req) }
/usr/local/go/src/net/http/server.go:1878 http.(*conn).serve { serverHandler{c.server}.ServeHTTP(w, w.req) }

Here is what goroutine 138 doing now
goroutine 138 [runnable]:
golang.org/x/crypto/scrypt.blockMix(0x40003e2ea0, 0x400027c800, 0x40, 0x40, 0x400027c880, 0x20, 0x20, 0x1)
	/home/ubuntu/go/pkg/mod/golang.org/x/crypto@v0.0.0-20200604202706-70a84ac30bf9/scrypt/scrypt.go:131 +0x208
golang.org/x/crypto/scrypt.smix(0x4000388300, 0xd00, 0xd00, 0x1, 0x10000, 0x4001bd2000, 0x200000, 0x200000, 0x400027c800, 0x40, ...)
	/home/ubuntu/go/pkg/mod/golang.org/x/crypto@v0.0.0-20200604202706-70a84ac30bf9/scrypt/scrypt.go:156 +0x1f8
golang.org/x/crypto/scrypt.Key(0x17d0fe8, 0x0, 0x0, 0x4000340b00, 0x20, 0x20, 0x10000, 0x1, 0x20, 0x20, ...)
	/home/ubuntu/go/pkg/mod/golang.org/x/crypto@v0.0.0-20200604202706-70a84ac30bf9/scrypt/scrypt.go:209 +0x1b8
github.com/algorand/go-algorand/daemon/kmd/wallet/driver.deriveEncryptionKeyWithSalt(0x17d0fe8, 0x0, 0x0, 0x4000340b00, 0x10000, 0x1, 0x20, 0xba2bdc, 0x20, 0xd19500)
	/home/ubuntu/go-algorand/daemon/kmd/wallet/driver/sqlite_crypto.go:79 +0x84
github.com/algorand/go-algorand/daemon/kmd/wallet/driver.deriveEncryptionKey(0x17d0fe8, 0x0, 0x0, 0x10000, 0x1, 0x20, 0x1ffffff, 0xee6748, 0x40003e31c8, 0x4a5240)
	/home/ubuntu/go-algorand/daemon/kmd/wallet/driver/sqlite_crypto.go:116 +0xac
github.com/algorand/go-algorand/daemon/kmd/wallet/driver.encryptBlobWithPasswordBlankOK(0x4000340aa0, 0x20, 0x20, 0xe8c6c4, 0xa, 0x17d0fe8, 0x0, 0x0, 0x40002ca138, 0x40003e9fe0, ...)
	/home/ubuntu/go-algorand/daemon/kmd/wallet/driver/sqlite_crypto.go:138 +0x31c
github.com/algorand/go-algorand/daemon/kmd/wallet/driver.(*SQLiteWalletDriver).CreateWallet(0x40002ca0b0, 0x40000aaf40, 0x20, 0x20, 0x40000aaf20, 0x20, 0x20, 0x17d0fe8, 0x0, 0x0, ...)
	/home/ubuntu/go-algorand/daemon/kmd/wallet/driver/sqlite.go:440 +0x448
github.com/algorand/go-algorand/daemon/kmd/api/v1.postWalletHandler(0x400006e1c0, 0x10ab640, 0x40002069a0, 0x40000bef00)
	/home/ubuntu/go-algorand/daemon/kmd/api/v1/handlers.go:175 +0x218
github.com/algorand/go-algorand/daemon/kmd/api/v1.wrapCtx.func1(0x10ab640, 0x40002069a0, 0x40000bef00)
	/home/ubuntu/go-algorand/daemon/kmd/api/v1/handlers.go:1264 +0x48
net/http.HandlerFunc.ServeHTTP(0x400000e6c0, 0x10ab640, 0x40002069a0, 0x40000bef00)
	/usr/local/go/src/net/http/server.go:1995 +0x40
github.com/algorand/go-algorand/daemon/kmd/api/v1.reqCallbackMiddleware.func1.1(0x10ab640, 0x40002069a0, 0x40000bef00)
	/home/ubuntu/go-algorand/daemon/kmd/api/v1/handlers.go:1277 +0x64
net/http.HandlerFunc.ServeHTTP(0x400009e4a0, 0x10ab640, 0x40002069a0, 0x40000bef00)
	/usr/local/go/src/net/http/server.go:1995 +0x40
github.com/algorand/go-algorand/daemon/kmd/api/v1.authMiddleware.func1.1(0x10ab640, 0x40002069a0, 0x40000bef00)
	/home/ubuntu/go-algorand/daemon/kmd/api/v1/auth.go:50 +0xe4
net/http.HandlerFunc.ServeHTTP(0x400024aae0, 0x10ab640, 0x40002069a0, 0x40000bef00)
	/usr/local/go/src/net/http/server.go:1995 +0x40
github.com/algorand/go-algorand/daemon/kmd/api.corsMiddleware.func1.1(0x10ab640, 0x40002069a0, 0x40000bef00)
	/home/ubuntu/go-algorand/daemon/kmd/api/cors.go:55 +0x198
net/http.HandlerFunc.ServeHTTP(0x400024ab10, 0x10ab640, 0x40002069a0, 0x40000bef00)
	/usr/local/go/src/net/http/server.go:1995 +0x40
github.com/gorilla/mux.(*Router).ServeHTTP(0x40002ec150, 0x10ab640, 0x40002069a0, 0x40000bef00)
	/home/ubuntu/go/pkg/mod/github.com/gorilla/mux@v1.6.2/mux.go:162 +0xc8
net/http.serverHandler.ServeHTTP(0x40002f0410, 0x10ab640, 0x40002069a0, 0x4000281100)
	/usr/local/go/src/net/http/server.go:2774 +0xc0
net/http.(*conn).serve(0x40000baf00, 0x10ae1c0, 0x400006f0c0)
	/usr/local/go/src/net/http/server.go:1878 +0x708
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2884 +0x2a4`

**Comment by brianolson** [comment]
alternative possible fix: change `test/scripts/e2e_client_runner.py` to change the kmd config json before kmd starts and do something like `jq '.drivers.sqlite.allow_unsafe_scrypt=true|.drivers.sqlite.scrypt.scrypt_n=4096'`
