### ISSUE TITLE
Issue compiling the node

### ISSUE THREAD

**Issue by pipaman** [algorand/go-algorand#1460]
### Subject of the issue
When executing ./scripts/configure_dev.sh I get an error related to go-swagger

### Your environment
* Software version: latest stable version
* Node status if applicable: latest stable version
* Ubuntu 18.04.5 LTS
* Log
++ VERSION=
++ echo
++ return
+ VERSION=
+ '[' -z '' ']'
++ GO111MODULE=off
++ go get -u github.com/go-swagger/go-swagger/cmd/swagger
+ OUTPUT='# github.com/go-swagger/go-swagger/scan
../../go/src/github.com/go-swagger/go-swagger/scan/meta.go:201:3: error: unknown field ‘URL’ in ‘spec.ContactInfo’
   URL:   url,
   ^
../../go/src/github.com/go-swagger/go-swagger/scan/meta.go:215:3: error: unknown field ‘Name’ in ‘spec.License’
   Name: name,
   ^'

### Steps to reproduce
git clone https://github.com/algorand/go-algorand
cd go-algorand
./scripts/configure_dev.sh

### Expected behaviour
It configures successfully 

### Actual behaviour
It throws an error

**Comment by mukulrevelin** [comment]
We were facing the same issue.Seemed like error from go-swagger https://github.com/go-swagger/go-swagger/issues/2210.  We tried with Go v1.14.2 and it worked. You can try upgrading Go

**Comment by pipaman** [comment]
Will do when I come back to this

**Comment by ian-algorand** [comment]
Please re-open this issue if it's still an issue after updating to Go v1.14.7

**Comment by pipaman** [comment]
I updated go-lang to 1.15.1 and I am getting another error:
../../go/src/golang.org/x/tools/go/packages/golist_overlay.go:543:15: error: reference to undefined identifier ‘strings.ReplaceAll’
  re = strings.ReplaceAll(re, `\.\.\.`, `[^`+vendorChar+`]*`)
