### ISSUE TITLE
Expose ForeignApps and ForeignAssets as txn fields in TEAL

### ISSUE THREAD

**Issue by algorandskiy** [algorand/go-algorand#1461]
Per discussion with @derbear and @algomaxj

**Comment by Priegle** [comment]
@algorandskiy does this require a consensus upgrade?

**Comment by algorandskiy** [comment]
Yes, it does. Any API change in TEAL is a protocol upgrade.

**Comment by jannotti** [comment]
PR #1906

**Comment by jannotti** [comment]
#1906 Adds these
