### ISSUE TITLE
Update each of our mobile services staging environments

### ISSUE THREAD

**Issue by bricerisingalgorand** [algorand/go-algorand#1471]
After the last release, each of our mobile service staging environments are now out of date. We should update them so that we're prepared for future releases

**Comment by egieseke** [comment]
Used run book to setup kubectl access to the cluster.  Need to update the environment now.

**Comment by egieseke** [comment]
I updated test environments for the node, and archival node to 2.1.4, and updated the test environment for the indexer to 2.1.1. 
Ben did the beta and stable environments.
