### ISSUE TITLE
Update.sh fails to update on Mac.

### ISSUE THREAD

**Issue by egieseke** [algorand/go-algorand#1483]
update.sh -i -c stable -p ~/algorand-v2.1.4/ -d ~/.algorand-testnet-3/ -n
fails on Mac with
Current Version = 0
Latest Version = 4295007115
New version found
Checking for files matching: 'channel/stable/node_stable_darwin-amd64_' in bucket algorand-internal
Update Downloaded to /var/folders/xj/xbv6cd7n0y70pqm7k8wnbpx00000gn/T/tmp.o4jruXHw/4295007115.tar.gz
Expanding update...
Validating update...
Starting the new update script to complete the installation...
... Resuming installation from the latest update script
/var/folders/xj/xbv6cd7n0y70pqm7k8wnbpx00000gn/T/tmp.o4jruXHw/a/bin/update.sh: line 135: /Users/pzbitskiy/algorand-v2.1.4//algod: cannot execute binary file
Current Version = 0
Stopping node...
... node not running
Backing up current binary files...
Backing up current data files from /Users/pzbitskiy/.algorand-testnet-3...
Installing new binary files...
Installing new data files into /Users/pzbitskiy/.algorand-testnet-3...
Copying genesis files locally
Checking for new ledger in /Users/pzbitskiy/.algorand-testnet-3
/var/folders/xj/xbv6cd7n0y70pqm7k8wnbpx00000gn/T/tmp.o4jruXHw/a/bin/update.sh: line 333: /private/var/folders/xj/xbv6cd7n0y70pqm7k8wnbpx00000gn/T/tmp.o4jruXHw/a/bin/../bin/algod: cannot execute binary file
Updating genesis files for default network
/var/folders/xj/xbv6cd7n0y70pqm7k8wnbpx00000gn/T/tmp.o4jruXHw/a/bin/update.sh: line 352: /private/var/folders/xj/xbv6cd7n0y70pqm7k8wnbpx00000gn/T/tmp.o4jruXHw/a/bin/../bin/algod: cannot execute binary file
Cannot determine new genesis ID. Not updating. This may be a problem!
*** UPDATE FAILED: Error updating ledger in /Users/pzbitskiy/.algorand-testnet-3 ***

**Comment by onetechnical** [comment]
Is this an old version of update.sh? This line doesn't seem right:
`Checking for files matching: 'channel/stable/node_stable_darwin-amd64_' in bucket algorand-internal`

**Comment by egieseke** [comment]
@algorandskiy reported the issue, Pavel do you know if the update.sh is an old version?

**Comment by algorandskiy** [comment]
I used update.sh from master.

**Comment by onetechnical** [comment]
From Tsachi: "Pavel might have had a different bucket configured on his computer. you might want to ask him to run export and have the output logged to this ticket." By default this should be pulling from algorand-releases, so I'm curious how this went astray.

**Comment by algorandskiy** [comment]
yes, I do have ```S3_RELEASE_BUCKET=algorand-internal``` possibly from some tests. After unsetting it all works fine. Thank you for your help.

**Comment by egieseke** [comment]
The `algorand-internal` release bucket is used when creating Algonet environments for performance testing.
