### ISSUE TITLE
 Nodes fail to catch up quickly

### ISSUE THREAD

**Issue by shixiaofeia** [algorand/go-algorand#1488]
I am building the main network node and used quick catch-up, but the Catchpoint accounts processed is always repeating, and there is no total number of blocks in the development document and the number of blocks that need to be downloaded. I have been waiting for a long time. How can I solve this problem? ?
![image](https://user-images.githubusercontent.com/63829677/92374976-153a7480-f133-11ea-979a-aa5226887ca1.png)

**Comment by shixiaofeia** [comment]
The fast synchronization of the main network has never been completed. The number of account processing always restarts from 0 after reaching it. Is there any good way? I also adjusted the number of retries and the timeout period

![image](https://user-images.githubusercontent.com/63829677/92441504-e975c800-f1e0-11ea-9223-5b372f03f0ba.png)

**Comment by tsachiherman** [comment]
Could you please try and grep the content of the node.log file by the catchpoint keyword and add these to this ticket ? ( if possible, as a text rather then an image, so it could be searchable ).
If it reached the number of accounts and retried over, there should be a reason for that. That reason should appear in the log file.

**Comment by tsachiherman** [comment]
Could you please try and grep the content of the node.log file by the catchpoint keyword and add these to this ticket ? ( if possible, as a text rather then an image, so it could be searchable ).
If it reached the number of accounts and retried over, there should be a reason for that. That reason should appear in the log file.

**Comment by ian-algorand** [comment]
We see your corresponding question on the forum, and we'll continue the discussion there if you have more questions.
