### ISSUE TITLE
Wrong fedora dependency: yum-cron

### ISSUE THREAD

**Issue by gianlucamazza** [algorand/go-algorand#1489]
Hello everybody,

I'm trying to install the binary from the algo repository on my Fedora 31.
I see that yum-cron is required as dependency but actually on Fedora for installing the rpm package.
I think dnf-automatic should be the right dependency.

Actually I'm not capable to install the binary because of the following error:
$ sudo dnf install algorand
Error: 
 Problem: conflicting requests
  - nothing provides yum-cron needed by algorand-2.1.4-1.x86_64
(try to add '--skip-broken' to skip uninstallable packages)

The option --skip-broken doesn't fix the problem.

**Comment by tsachiherman** [comment]
Please be aware that there is no official release for Fedora. Algorand officially supports Ubuntu, Red Hat ( centos ), Raspberry PI, arm64 and MacOS (amd64).
As I'm unaware of the extent of the required change, I cannot estimate the likelihood of which this issue would get addressed.

**Comment by ian-algorand** [comment]
We're noting this as a feature request for Fedora since we currently don't support it. Thanks for your input!

**Comment by limburgher** [comment]
I'm a Fedora package maintainer. If you'd like assistance crafting a single spec file that will generate correct RPMs for RH, CentOS, or Fedora depending on build host, I can help.

**Comment by ipaleka** [comment]
> I'm a Fedora package maintainer. If you'd like assistance crafting a single spec file that will generate correct RPMs for RH, CentOS, or Fedora depending on build host, I can help.

Hi @limburgher !

This is still an issue and the [official docs](https://developer.algorand.org/docs/run-a-node/setup/install/) bring no workaround.

I'm working on a provisioning script, what steps should I make for a successful install on Fedora 34?

**Comment by ipaleka** [comment]
Release; the official documentation uses `https://releases.algorand.com/rpm/stable/algorand.repo` and I want to use the same repo in my project's provisioning script if it's possible. In the case of Fedora 34, the process raises this error and I want to know what changes I should make to successfully install the Algorand node using the package manager.

I'm not getting any error by provisioning the Fedora 34 system using steps from https://developer.algorand.org/docs/run-a-node/setup/install/#installing-with-other-linux-distros.

**Comment by limburgher** [comment]
Ah, I see. Yes, the RPM won't work on modern Fedora because of the yum-cron requirement.  I use algo on my f34 system using the other distros instructions, too, and it's fine. I also packaged the Python SDK and it's in Fedora as python-py-algorand-sdk.

To use the RPM, the maintainers here would need to not only update the spec files (see installer/rpm/) but release new rpm builds from those.

**Comment by ipaleka** [comment]
I see... Thank you for your answer.

Nothing to do but wait for them to do that.

**Comment by ipaleka** [comment]
Something's [going on](https://github.com/algorand/go-algorand/commit/01248d28f3ddccedd25888074f4334df6f23b774)! :)

**Comment by ipaleka** [comment]
Just a note that [2.8.0 stable release](https://github.com/algorand/go-algorand/releases/tag/v2.8.0-stable) has been successfully installed in the following distros:

Fedora 34
CentOS 7.9
CentOS 8.4
Rocky 8.4
AlmaLinux 8.4
OracleLinux 8.4

**Comment by limburgher** [comment]
Excellent!

**Comment by onetechnical** [comment]
That's great to hear, thanks for testing it! We need to update our install instructions for centos 8, but I'm happy to hear it's working for you.

**Comment by onetechnical** [comment]
@gianlucamazza Can you verify the new release works for you, and if so, close this?

**Comment by gianlucamazza** [comment]
It works, I'm closing the issue. Thank you
