### ISSUE TITLE
How to create V2 endpoints for Algod using curl and header key value names?

### ISSUE THREAD

**Issue by rfustino** [algorand/go-algorand#1496]
This statement has been used to generate Swagger REST endpoints, and is currently in our [docs](https://developer.algorand.org/docs/reference/sdks/#rest-endpoints). This produces only V1 Endpoints.

`curl http://$(cat ~/node/data/algod.net)/swagger.json`

These are the endpoints below for oas w V2. We can certainly point folks to these in the docs but should the above work and is is still supported? If so, we should update the curl command to provide V2 endpoints.

Algod
https://github.com/algorand/go-algorand/blob/master/daemon/algod/api/algod.oas2.json
https://github.com/algorand/go-algorand/blob/master/daemon/algod/api/algod.oas3.yml

Indexer
https://github.com/algorand/indexer/blob/develop/api/indexer.oas2.json. (this needs to be fixed as it errors on import to postman - [https://github.com/algorand/indexer/issues/173](https://github.com/algorand/indexer/issues/173)
https://github.com/algorand/indexer/blob/develop/api/indexer.oas3.yml

kmd
curl http://$(cat ~/node/data/kmd-v0.5/kmd.net)/swagger.json

Also is there a way to include Header key value names in the oas files for each end point? Right now the user needs to edit every end point at copy and paste the name of the name of the key. Pasting in just the value for that key would make it easier to use.

Like X-Indexer-API-Token for indexer endpoints. And X-Algo-API-Token for Algod? It would be easier to use API testing tools with that pre-filled key name on import to say Postman.

**Comment by rfustino** [comment]
Also is there a way to include Header key value names in the oas files?

Like `X-Indexer-API-Token` for indexer endpoints. And `X-Algo-API-Token` for Algod? It  would be easier to use API testing tools with that pre-filled on import to say Postman.

**Comment by winder** [comment]
These are not currently implemented for the v2 endpoints. We have tickets:
https://github.com/algorand/go-algorand/issues/1105
https://github.com/algorand/indexer/issues/98

I'm not sure about the second part of your question.
