### ISSUE TITLE
Add EnableDeveloperAPI flag to goal node

### ISSUE THREAD

**Issue by ryanRfox** [algorand/go-algorand#1514]
A nice to have `goal node` feature would be a flag to set EnableDeveloperAPI on/off. I agree we want `algod` to start with these endpoints disabled by default and it's not too difficult to modify the `config.json` file directly, then `goal node restart`. However, it's more difficult to access/modify this file in `sandbox`. 

Hoping for something like:
```
$ goal node --dev-apis [ true | false ]
```

Forward looking, it may be worth investigating adding a `config` command to `goal node` to configure many node settings rather than this one off --dev-apis flag.

**Comment by brianolson** [comment]
`algocfg` is shipped with distros and could do this. May be a documentation opportunity.

**Comment by ryanRfox** [comment]
I learned a new tool today :) Thanks @brianolson for the guidance. Yes, I believe we could improve documentation here. I'll take that on within DevRel.

Solved by:
```
$ algocfg set -p EnableDeveloperAPI -v true
$ goal node restart
```
