### ISSUE TITLE
TEAL - arguments counts and traps

### ISSUE THREAD

**Issue by jeapostrophe** [algorand/go-algorand#1530]
Application contracts can check the number of arguments they have been provided via `NumAppArgs`, but normal arguments do not have a similar field or opcode to look at.

For application contracts, there's no discussion in the docs about what happens if you attempt to read an argument after this limit. I expect it should trap. For non-application contracts, I'd expect the same behavior, but again, this is not discussed.

Finally, application contracts in the same group can read each other's arguments via `gtxna` but non-application contracts cannot read each other's arguments (nor can application contracts read the arguments of non-application contracts in the same group.)

**Comment by jeapostrophe** [comment]
The code causes a trap on reading past the last arg in sig mode: https://github.com/algorand/go-algorand/blob/master/data/transactions/logic/eval.go#L1089

And in app mode: https://github.com/algorand/go-algorand/blob/master/data/transactions/logic/eval.go#L1329

**Comment by jeapostrophe** [comment]
This line could have an indirection

https://github.com/algorand/go-algorand/blob/master/data/transactions/logic/eval.go#L1089

like this line

https://github.com/algorand/go-algorand/blob/master/data/transactions/logic/eval.go#L1485

And then you'd be able to read the arguments of other transactions.

**Comment by jeapostrophe** [comment]
Here's an implementation: https://github.com/algorand/go-algorand/pull/1533

**Comment by jeapostrophe** [comment]
The pull-request does not address the docs problem.

**Comment by jannotti** [comment]
Agreed that all the array txn opcodes should discuss their behavior when reading part the end. I'm going to close this issue because it is mostly talking about the args issue which has been addressed (to the extent that it will be addressed, anyway)
