### ISSUE TITLE
Error formatting names convention

### ISSUE THREAD

**Issue by jsign** [algorand/go-algorand#154]
In `cmd/goal/messages.go` I noticed that the error formatting strings don't follow a naming convention. Some of them prefix `err`, `error`, or suffix `Error`.

I'm not sure if there's the desired naming convention, which helps using hints while coding (e.g: since all errors start with `err`, and ide can hint existing errors). Possibly, this may apply to more places.

If that's the case, this could be tagged as an easy issue for someone to get involved in the code?

**Comment by HowJMay** [comment]
May I take this issue and unite the suffix into `err`?

**Comment by Marcuccio** [comment]
It seems already closed, am I wrong?

**Comment by ian-algorand** [comment]
Thanks for the contribution!
