### ISSUE TITLE
Debian Algorand 2.1.5 upgrade overwrites `genesis.json`

### ISSUE THREAD

**Issue by jecassis** [algorand/go-algorand#1550]
### Subject of the issue
In nodes using unattended upgrades with `--force-confdef` and `--force-confold` as specified in `51algorand-upgrades` the Debian package still overwrote `genesis.json` which set the nodes to use testnet instead on mainnet.

### Your environment
* Software version: 8590000133 2.1.5.stable [rel/stable] (commit #b0063b1b)
* Operating System details: Ubuntu 18.04 x86_64

### Steps to reproduce
1. Install Debian package 2.1.4.
2. Modify `genesis.json` for mainnet in 2.1.4.
3. Upgrade to 2.1.5.
4. Notice that `genesis.json` overridden back to testnet by the upgrade without prompting.

### Expected behaviour
The `genesis.json` file is in `conffiles` so based on the options for Dpkg in `51algorand-upgrades` should not be changed if modified.

### Actual behaviour
From `/var/log/unattended-upgrades/unattended-upgrades-dpkg.log`:
```
Log started: 2020-09-23  06:53:31
Preparing to unpack .../algorand_2.1.5_amd64.deb ...
Unpacking algorand (2.1.5) over (2.1.4) ...
Setting up algorand (2.1.5) ...
Installing new version of config file /var/lib/algorand/genesis.json ...
algorand@* is a disabled or a static unit not running, not starting it.
Log ended: 2020-09-23  06:53:41
```

Suspect some change in #1492 might be the culprit or maybe it did not get packaged correctly. And analyzing the package directly is not possible as it's no longer available (see #1548).

**Comment by Priegle** [comment]
Hey @jecassis - we pulled that release and put out 2.1.6 to resolve.  thanks for reporting!
