### ISSUE TITLE
Release 2.1.6-stable deploys TestNet genesis.json as default on fresh algorand install (no prior install)

### ISSUE THREAD

**Issue by Thireus** [algorand/go-algorand#1557]
### Subject of the issue
Release 2.1.6-stable for Debian packaging scripts still deploys TestNet genesis.json as default instead of the MainNet genesis.json. On a fresh install (no prior install of algorand) this is the installer's behaviour.

### Your environment
Debian

### Steps to reproduce
```
apt-get purge -y algorand
rm -rf /var/lib/algorand/
apt-get install -y algorand
service algorand start
goal node status -d /var/lib/algorand
```

### Expected behaviour
The Algorand v2.1.6 release description mentions "release 2.1.6 will resolve the issue". However, on a fresh 2.1.6 Debian install, the default genesis file used is TestNet. User has to manually change this file for MainNet to switch to that network instead.

### Actual behaviour
```
goal node status -d /var/lib/algorand
Last committed block: 13394
Time since last block: 69.1s
Sync Time: 0.0s
Last consensus protocol: https://github.com/algorand/spec/tree/a26ed78ed8f834e2b9ccb6eb7d3ee9f629a6e622
Next consensus protocol: https://github.com/algorand/spec/tree/22726c9dcd12d9cddce4a8bd7e8ccaa707f74101
Round for next consensus protocol: 20001
Next consensus protocol supported: true
Last Catchpoint: 
Genesis ID: testnet-v1.0
Genesis hash: SGO1GKSzyE7IEPItTxCByw9x8FmnrCDexi9/cOUJOiI=
```

**Comment by onetechnical** [comment]
Hi @Thireus , can you verify the version of algod with `algod -v`?

**Comment by Thireus** [comment]
Hi @onetechnical,

Here it is:

```
$ algod -v
8590000133
2.1.5.stable [rel/stable] (commit #b0063b1b)
go-algorand is licensed with AGPLv3.0
source code available at https://github.com/algorand/go-algorand
```

Installed from https://releases.algorand.com/deb/ Debian repo, as documented here: https://developer.algorand.org/docs/run-a-node/setup/install/

**Comment by onetechnical** [comment]
No problem -  please try the upgrade again and let us know if it works okay. I'm going to close this; re-open if it's still an issue.

**Comment by Thireus** [comment]
I confirm it works just fine on a fresh install of v2.1.6 (I just tested that now)
