### ISSUE TITLE
tealdbg --- too aggressively paternalistic about localhost

### ISSUE THREAD

**Issue by jeapostrophe** [algorand/go-algorand#1571]
I run Algorand dockerized and tealdbg has many checks to ensure it is only being connected to by localhost which are not helpful. We have firewalls and other things to protect ports like this, it is not necessary for tealdbg to do this, especially when the only remedy is a patch. A better option, if you insist on something like this built in, is to have the configuration/command line take the IP address to listen on and we can give 0.0.0.0 or 127.0.0.1 or whatever.

https://github.com/algorand/go-algorand/blob/master/cmd/tealdbg/server.go#L35

**Comment by yaovi-a** [comment]
@algorandskiy, have we already done this or is it still open?

**Comment by algorandskiy** [comment]
Listen option implemented
```
Flags:
  -f, --frontend string             Frontend to use: cdt, web (default "cdt")
  -h, --help                        help for tealdbg
      --listen string               Network interface to listen on (default "127.0.0.1")
      --no-source-map               Do not generate source maps
      --remote-debugging-port int   Port to listen on (default 9392)
  -v, --verbose                     Verbose output
```
