### ISSUE TITLE
Regular connection refusal

### ISSUE THREAD

**Issue by jeapostrophe** [algorand/go-algorand#1576]
I am running a test scenario with about a dozen transactions that I run through, including polling from an indexer and my test script querying the indexer. The test uses the JS SDK.

I find that the vast majority of the time, a connection to algod will be refused. For example, in the past hour, I've run the test 10 times and it finished executing only 1 time, with all 9 other times getting connection refused from algod.

I investigated whether the TCP backlog was set too low on my system and increased it by eight times, but this made no difference.

I noticed that the indexer has the same problem and repeatedly disconnects and reconnects. It is even programmed to have a backoff and retry loop --- https://github.com/algorand/indexer/blob/44c0cf72872637f71fe344ed39aeb686c8d81f99/fetcher/fetcher.go#L144

I don't see anything interesting in my logs.

I know this is a pretty terrible error report, but maybe you'll see a bunch like this and find some clue.

**Comment by tsachiherman** [comment]
Please move this to the forum at https://forum.algorand.org; The GitHub issue tracker isn't the place for that.
