### ISSUE TITLE
Create an installer

### ISSUE THREAD

**Issue by tsachizehub** [algorand/go-algorand#1588]
Few notes:
Install.sh ( external )
Part 1:
     Some shell code
Find self-name ( the name & directory of the current bash script, i.e. /bla/../install.sh )
Check that the script is being executed by an administrator
Check OS
Create temp directory
Extract to temp directory
Execute install-internal.sh from temp directory
Part 2:
     Barrier ( series of known expected bytes )
Part 3:
     The content of a gzip tar file.

Install-internal.sh would need to :
Copy python scripts to correct location
Copy the service file to the correct location
Register the service file
Delete the content of temp directory

**Comment by tsachiherman** [comment]
reference : https://stackoverflow.com/questions/29418050/package-tar-gz-into-a-shell-script/29418549
