### ISSUE TITLE
[Investigate] Using dry dryrun on OptIn operation can fail if the TEAL uses the app_local_get

### ISSUE THREAD

**Issue by pipaman** [algorand/go-algorand#1607]
### Subject of the issue
Describe your issue here.

### Your environment
* Software version: 2.1.2.beta [rel/beta] (commit #2fc19135)
* Operating System details. Ubuntu 20.04

### Steps to reproduce

goal app optin --app-id yyyyy --from xxxxxx --out=dumptx.tx --dryrun-dump
goal clerk dryrun-remote -D dumptx.tx --verbose

when it reaches to a app_local_put it finishes but when it is executed on a transaction it works. As an example:
tx[0] messages:
ApprovalProgram
REJECT
failed to fetch app local state for acct 252PVVY7LK4R5IUJ7AKSJYMAA5FI7A6NUORM4WKOJEJMQHZYXELRJZJZYE: addr 252PVVY7LK4R5IUJ7AKSJYMAA5FI7A6NUORM4WKOJEJMQHZYXELRJZJZYE not opted in to app 2677814, cannot fetch state
tx[0] trace:
   1 (0001): // version 2 []
   2 (0012): intcblock 0 5 4 1 2 5000 1000 2671688 10000 []
   3 (0070): bytecblock 0x41 0x4d41 0x4753 0x734753 0x734d41 0x734141 0x734153 0x73 0x776166 0x76 0x66656573 0x734d46 0x4d46 0x734246 0x4246 0x50726f6772616d 0x022001b6b8a301260120 0x31072812483300182212 0x6d 0x6d77 0x7741 0x6277 []
   4 (0071): intc_0 [0]
   5 (0073): txn ApplicationID [0 2677814]
   6 (0074): == [0]
  19 (0089): label1: []
  20 (008a): bytec_0 [QQ==]
  21 (008b): app_global_get [tuleu1WacC4nw8EkAAPQaeGBnosjiXcUiwT+Uh5/lLY=]
  22 (008c): dup [tuleu1WacC4nw8EkAAPQaeGBnosjiXcUiwT+Uh5/lLY= tuleu1WacC4nw8EkAAPQaeGBnosjiXcUiwT+Uh5/lLY=]
  23 (008e): store 4 [tuleu1WacC4nw8EkAAPQaeGBnosjiXcUiwT+Uh5/lLY=]
  24 (0090): txn Sender [tuleu1WacC4nw8EkAAPQaeGBnosjiXcUiwT+Uh5/lLY= 13T61x9auR6iifgVJOGAB0qPg82jos5ZTkkSyB84uRc=]
  25 (0091): == [0]
  26 (0093): store 0 []
  27 (0094): bytec_2 [R1M=]
  28 (0095): app_global_get [1]
  29 (0097): store 1 []
  30 (0099): load 0 [0]
 226 (01ef): label4: []
 227 (01f1): load 1 [1]
 228 (01f4): bz label2 []
 229 (01f5): intc_3 [1]
 230 (01f7): txn OnCompletion [1 1]
 231 (01f8): == [1]
 232 (01fb): bz label12 []
 233 (01fd): txn NumAccounts [1]
 234 (01fe): intc_3 [1 1]
 235 (01ff): == [1]
 236 (0202): bz label2 []
 237 (0203): intc_3 [1]
 238 (0204): balance [0]
 239 (0205): intc_0 [0 0]
 240 (0206): == [1]
 241 (0209): bz label2 []
 242 (020b): bytec 15 [UHJvZ3JhbQ==]
 243 (020d): bytec 16 [UHJvZ3JhbQ== AiABtrijASYBIA==]
 244 (020e): concat [UHJvZ3JhbQIgAba4owEmASA=]
 245 (0210): txn Sender [UHJvZ3JhbQIgAba4owEmASA= 13T61x9auR6iifgVJOGAB0qPg82jos5ZTkkSyB84uRc=]
 246 (0211): concat [UHJvZ3JhbQIgAba4owEmASDXdPrXH1q5HqKJ+BUk4YAHSo+DzaOizllOSRLIHzi5Fw==]
 247 (0213): bytec 17 [UHJvZ3JhbQIgAba4owEmASDXdPrXH1q5HqKJ+BUk4YAHSo+DzaOizllOSRLIHzi5Fw== MQcoEkgzABgiEg==]
 248 (0214): concat [UHJvZ3JhbQIgAba4owEmASDXdPrXH1q5HqKJ+BUk4YAHSo+DzaOizllOSRLIHzi5FzEHKBJIMwAYIhI=]
 249 (0215): sha512_256 [sWrqC/KLxHbcKLRokrCvzN915N8Ah0ZrwB5GOZ6jqn4=]
 250 (0216): dup [sWrqC/KLxHbcKLRokrCvzN915N8Ah0ZrwB5GOZ6jqn4= sWrqC/KLxHbcKLRokrCvzN915N8Ah0ZrwB5GOZ6jqn4=]
 251 (0218): store 8 [sWrqC/KLxHbcKLRokrCvzN915N8Ah0ZrwB5GOZ6jqn4=]
 252 (021b): txna Accounts 1 [sWrqC/KLxHbcKLRokrCvzN915N8Ah0ZrwB5GOZ6jqn4= sWrqC/KLxHbcKLRokrCvzN915N8Ah0ZrwB5GOZ6jqn4=]
 253 (021c): == [1]
 254 (021f): bz label2 []
 255 (0220): intc_0 [0]
 256 (0222): bytec 9 [0 dg==]
 257 (0224): load 8 [0 dg== sWrqC/KLxHbcKLRokrCvzN915N8Ah0ZrwB5GOZ6jqn4=]
app_local_put -->>> 257 (0224): load 8 [0 dg== sWrqC/KLxHbcKLRokrCvzN915N8Ah0ZrwB5GOZ6jqn4=] 

### Expected behaviour
It should work as executing within a transaction

### Actual behaviour
I can't debug the optin

## Scope
Let's spend some time reproducing the issue before we plan out a fix

**Comment by algorandskiy** [comment]
Fixed in #1721
