### ISSUE TITLE
Any reason to not use Go Vendoring Mode?

### ISSUE THREAD

**Issue by mxmauro** [algorand/go-algorand#1614]
Hi,

The code depends on some libraries like `swagger` and `golint` but they are installed by the configure_deps script and `GO111MODULE` can be set to `off` leading to conflicts if the user already has another version of the module.

Building the whole project locally with the new package managers would avoid this.

Kind regards,
Mauro.

**Comment by ian-algorand** [comment]
Thanks for your contribution! We'll definitely look into this.

**Comment by ian-algorand** [comment]
After discussions with the team, we aren't planning on implementing this soon when considering our other priorities. There are workarounds (as you mentioned) but let us know if this ends up posing a large problem. Closing but will reopen if needed.
