### ISSUE TITLE
Mac installers/update.sh Update $PATH

### ISSUE THREAD

**Issue by ryanRfox** [algorand/go-algorand#1620]
### $PATH not updated
The install script for Mac does not set the `$PATH` environment variable to the install location. Documentation provides `~/node` as the suggested installation location. New users are expecting to run `update.sh` and then `goal node start` but the program is not in the path. 

### Your environment
* Software version: 2.1.6
* Node status if applicable: 
* Operating System details: MacOS 10.11.16

### Steps to reproduce
* Install new OS
* Follow OS specific [install directions](https://developer.algorand.org/docs/run-a-node/setup/install/#installing-on-a-mac)
* Troubleshoot with [user](https://forum.algorand.org/t/algorand-environment-on-mac/2119/8)

Recommend adding to `update.sh` script
```
export PATH=$PATH:$PWD
```
That _should_ append to $PATH the installation folder (in case the user installs outside `~/node`)

### Expected behaviour

* Follow OS specific [install directions](https://developer.algorand.org/docs/run-a-node/setup/install/#installing-on-a-mac)
* `$ goal node start` (the instructions alerted them to set the $ALGORAND_DATA already)

### Actual behaviour
* `zsh: command not found: goal`

**Comment by onetechnical** [comment]
I'm not sure if this is entirely a good idea; the updater script right now modifies specified program and data directories, but limits its changes to there. This would be modifying a person's profile, which may or may not be desired. Maybe make it a run time option requiring approval? We would also need to check what shell people were using - while new Mac default is zsh, previously it was bash and can be set to that. This would also affect Ubuntu/CentOS installs.

This is also challenging if you are doing multiple installs on a single machine - i.e., doing a separate betanet and mainnet install on one machine would make pathing interesting - which would take priority?

**Comment by ryanRfox** [comment]
Upon further consideration, I feel this issue should be closed in favor of improved documentation, rather than a change to the build/deployment process. I'll look thru the docs to see where to suggest changes within a separate Issue/PR.

**Comment by onetechnical** [comment]
Sounds reasonable - let me know if you need help!
