### ISSUE TITLE
TEAL - substring variant

### ISSUE THREAD

**Issue by jeapostrophe** [algorand/go-algorand#1641]
`substring` and `substring3` take a `start` and an `end` argument, but I think it is more convenient for them to take a `start` and a `len` argument, because the `end` should always be `start+len` or else it is an error. This also has the advantage that if `end` would be more than `255` but `len` is smaller, you can still use `substring` rather than going to `substring3`. My preference is to just make TEAL3 work this way, but that would be a major pain for people updating their programs, so it would be more ergonomic to make it a new instruction.

**Comment by jeapostrophe** [comment]
#1633

**Comment by jannotti** [comment]
I'm closing this because I think the "functions" of v4 will address this. If it's so common that having the code as a function in everyone's teal scripts becomes a burden, we'll reassess.
