### ISSUE TITLE
User-friendly constants in TEAL disassembler

### ISSUE THREAD

**Issue by fabrice102** [algorand/go-algorand#1655]
**Is your feature request related to a problem? Please describe.**

TEAL disassembler `goal clerk compile -D` keeps the instructions `intcblock` / `bytecblock` / `intc` / `bytec`.
This is convenient to check the exact behavior of the program and has the advantage that re-assembling the program will yield the exact same binary.

However, to analyze a TEAL program, `intc` and `bytesc` are not very user-friendly.

**Describe the solution you'd like**

Provides a constant user-friendly mode (e.g., with a flag `--cst-user-friendly`) where `intcblock` / `bytecblock` are removed and `inc` / `bytec` are replaced by `int` / `byte`.

Regarding `byte`, sometimes hexadecimal makes more sense, sometimes base32 makes more sense, sometimes base64 makes more sense. Maybe the disassembler can add a comment showing the values in base32/base64 too.

If an API endpoint is designed as proposed in #1654, ideally the API endpoint would also have the option to enable this constant user-friendly mode.

**Additional context**

Such features would be very convenient for https://algodesk.io/app-manager

**Urgency/Relative Priority**
While this definitely cleans things up, this isn't a high priority since this isn't posing immediate problems. That being said, if we can get to it soon, it'd be good to tackle to have the output of the disassembly being more readable (user friendly). Also extremely low risk.

**Comment by jannotti** [comment]
If someone can help me be confident that the exact format is disassembly is not depended up on by any other code, I'm happy to do this. I'm thinking of (perhaps) the debugger which I'm not familiar with. I'll also fill in the field names when using txn opcodes.

**Comment by fabrice102** [comment]
I agree the default should not be changed but rather should be an additional flag such as `--cst-user-friendly`

**Comment by jannotti** [comment]
I have a PR #1970 where I didn't change any output opcodes (so you can see exactly what's going on), but I added comments to the lines that load constants with the actual constant.  In the case of byte constants, it guesses and decodes the constant as an address or a string if it is the right size, or all ascii.  I figure by doing it in a comment, we remove the need for flags, add more info, and won't break anything.

**Comment by algoanne** [comment]
I think this is not necessary anymore given our our recent work on assembly with source map and disassembly options (see #1654). Let me know if that's incorrect though and we can rediscuss
