### ISSUE TITLE
Document instructions for how to use the Algod Docker image

### ISSUE THREAD

**Issue by egieseke** [algorand/go-algorand#1696]
## Summary
Document instructions for how to use the Algod Docker image.

## Scope/Requirements
Create instructions for using the docker image and test to make sure that the instructions are accurate. 
Share with DevRel to be published on the developer portal.

## Urgency/Relative Priority
This is for whoever uses the Algorand Docker image, need to figure out urgency based on the use cases here. For now, it's not a high priority but can easily be brought up if we have specific use cases.

**Comment by ian-algorand** [comment]
@JasonWeathersby do you have any thoughts on this ticket? Trying to figure out the specific use cases of people using these docker images. How urgent do you think this would be?

**Comment by ian-algorand** [comment]
@JasonWeathersby ping

**Comment by JasonWeathersby** [comment]
is this the sandbox?

**Comment by JasonWeathersby** [comment]
or another docker install option?

**Comment by onetechnical** [comment]
This is another docker install option: https://hub.docker.com/r/algorand/stable

I believe this was an approach we looked at with e.g. this article: https://medium.com/algorand/running-algorand-with-docker-b843002325ff

I'm not sure this is how anyone would actually run algorand in a meaningful workload, though. Do we know of anyone actually using this image?

**Comment by JasonWeathersby** [comment]
We can add docs to install it this way but I agree this seems like if you want docker, why not just use the sandbox?

**Comment by onetechnical** [comment]
We need to review what the purpose of this docker container is. It's not clear who uses it or why.
