### ISSUE TITLE
Allowing to specify ASA's management addresses using goal asset create

### ISSUE THREAD

**Issue by cusma** [algorand/go-algorand#1705]
## Summary
Using SDKs (I tested Python) is possible to specify ASA's management addresses directly on asset creation transaction, since it is only a special case of [AssetConfigTxn](https://py-algorand-sdk.readthedocs.io/en/latest/algosdk/transaction.html#algosdk.transaction.AssetConfigTxn). This is not possible using `goal`, with which is it necessary first to use [`goal asset create`](https://developer.algorand.org/docs/reference/cli/goal/asset/create/) to issue an asset create transaction and then [`goal asset config`](https://developer.algorand.org/docs/reference/cli/goal/asset/config/) to assign management addresses different form creator one.

## Scope/Requirements
We should have the [flags] `--clawback`, `--freezer`, `--manager` and `--reserve` also under `goal asset create`. This will avoid issuing two distinct transactions for the creation of an ASA with management addresses different from the creator one.

## Urgency/Relative Priority
Low priority.

**Comment by ian-algorand** [comment]
Thanks for the feedback, we agree that this should be implemented. No reason not to.

**Comment by cusma** [comment]
Closing this since it's being addressed in https://github.com/algorand/go-algorand/pull/3369
