### ISSUE TITLE
Investigate why test networks take longer than 5 seconds to start as part of the integration tests. 

### ISSUE THREAD

**Issue by egieseke** [algorand/go-algorand#1708]
Related to this PR that works around by extending the timeout from 5 seconds to 60 seconds.  
https://github.com/algorand/go-algorand/pull/1706

@algorandskiy @tsachiherman 

## Scope
TBD, investigation needed

## Urgency/Priority
We just increased timeouts for arm64 integration tests (to hopefully have them succeed more often) and we want to wait until we see the results of that before we do this. Generally needs more investigation, not sure why it's failing

**Comment by onetechnical** [comment]
Much has changed since this, including many fixes to expect tests. Closing this, create a new issue if we're still experiencing problems.

**Comment by algonoah** [comment]
Closing this for now. Can create a new issue if new if it recurs
