### ISSUE TITLE
Missing Links to this Repo ("Algorand is NOT Open Source")

### ISSUE THREAD

**Issue by ghost** [algorand/go-algorand#173]
(please feel free to move this issue to another repo)

The website:

https://www.algorand.com/

does not contain any links to this repository.

So, that explains possibly why I read somewhere "Algorand is NOT Open Source" - just a few days ago.

## Solution

- Mention "Open Source" in a prominent position on the site.
- add a github "corner-banner"
- add a github symbol in the "follow-us" footer

**Comment by Vervious** [comment]
Thanks for the feedback, I'll pass it along, you make a good suggestion!

**Comment by ian-algorand** [comment]
the spooky ghost is right, we need clear links.

**Comment by ian-algorand** [comment]
From both inc and foundation sites, you can access https://developer.algorand.org/ which has links to the github repos. This is done
