### ISSUE TITLE
TEAL applications should to create cause transfers. - Implementation

### ISSUE THREAD

**Issue by jannotti** [algorand/go-algorand#1734]
## Summary
Today, if you want to build a Smart Contract with TEAL that creates transactions, it must be done in a roundabout way that involves recording the allowable transaction in application state, and then using a second transaction using a logicsig to perform that transaction.  The contract is then complicated by questions about how to escrow the funds in the meantime, what to do if the second call never happens, and so on. Algorand should support this common use case more directly

## Scope/Requirements
TEAL application need to be able to dynamically determine (at least) the amount of a pay txn, rather than just approve a txn made by a caller.  More generally, the need may be better addressed by generating the txns as needed (maybe it requires two payments, maybe it needs to determine the recipient in code).

## Urgency/Relative Priority
It seems VERY useful for a Uniswap-like AMM and other dApp projects which appear to have high-priority.

**Comment by krotkiewicz** [comment]
This is a great idea, any progress in TEAL 3?

**Comment by jannotti** [comment]
Current points about design.

- Don't think of apps as creating transactions, instead think of the specific "micro ops" they can perform
- Apps will have an associated account = hash(appId)
- Apps should be able to transfer algos from that account by using teal instructions
- Apps can opt their account into ASAs
- Apps should be able to transfer those ASAs
- Can apps opt into accounts? It has some interesting uses, but requires invoking app from app.
