### ISSUE TITLE
Inefficient serialization method 

### ISSUE THREAD

**Issue by aybehrouz** [algorand/go-algorand#1773]
## Summary
msgpack codec should be configured in `toarray` mode instead of `map` mode.
## Scope/Requirements
In a conversation that I had with @jannotti I noticed that the codec serializer is configured in its default mode which means it encodes structs as maps. Therefore every field of any struct will be serialized and stored with a tag name. For example, a `TealValue` struct:
```
type TealValue struct {
	_struct struct{} `codec:",omitempty,omitemptyarray"`

	Type  TealType `codec:"tt"`
	Bytes string   `codec:"tb"`
	Uint  uint64   `codec:"ui"`
}
```
is encoded in this way:
```
temp := basics.TealValue{
		Type:  basics.TealUintType,
		Bytes: "",
		Uint:  123456789,
	}
------------------------
serialization:
 ��tt�ui�I��  length:13
```
As u can see strings "tt" and "ui" which are tag names are encoded and they are a part of the serialization. 6 bytes are used for storing tag names while the uint itself is only 5 bytes! By using `codec:toarray` structs can be serialized without saving those tag names on the disk...

## Urgency/Relative Priority
...

**Comment by jannotti** [comment]
The trouble with that approach is that the serialized forms become extremely fragile. If the struct is rearranged, or a field is added anywhere except the end, all existing serialized forms would break.

We do use short names because of this, but we're not quite willing to throw out that extra safety for the 2x or so or might save.

**Comment by ian-algorand** [comment]
While we appreciate your contribution, we likely won't pick up this change in the foreseeable future. We might end up wrapping some of this into some bigger changes we have planned but it likely won't get done here. Closing this but as always, let us know if you have any additional thoughts or comments.
