### ISSUE TITLE
Design: Move Checkpoint Logger to Task Framework

### ISSUE THREAD

**Issue by bricerisingalgorand** [algorand/go-algorand#1787]
## Summary
The checkpoint logger that populates our checkpoint hash endpoints is currently running on an ec2 instances with algod instances we have to maintain. We should move this to EKS using the task framework so we can have more monitoring/reliability and be able to reuse the instances of algod that we are maintaining there.

## Scope/Requirements
We need to create a new task that queries algod and logs the catchpoint hashes to s3 on a cron schedule. This has already been done once, so it'll just be refactoring/rewriting what we already have and throwing it in a docker image.

When developing a solution, it should run alongside the current catchpoint logger but write to another bucket so that we can verifiy that it works over a period of time before changing the current process.

## Acceptance criteria 
Generate a list of potential solutions to move off of EC2 and achieve self healing for the checkpoint service. 
Potential solutions (lambda, autoscaling, EKS) 
- Create followup stories (include stories for triggering checkpoint service off rounds rather than using a time interval) 

## Urgency/Relative Priority
This is mildly urgent. The current setup we have works, but we don't have much monitoring built around it. When we have it running in eks we'll have more alerting if it stops working and we'll be spending less money on compute since it'll use a shared algod instance.

**Comment by yaovi-a** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Algorand-Main-Workspace-5ea71fda6d554d53dda36f16/issues/algorand/go-algorand/1787?planning-poker) with ZenHub @algobarb @algojack @bricerisingalgorand @egieseke @onetechnical

**Comment by onetechnical** [comment]
I'm not sure the task framework is sufficient for this, unless we modify running nodes. The catchpoint logger is occasionally memory-intensive, which is why we've disabled it on nodes in cluster. To move this to cluster, we'll likely need to also enable it on archival nodes, and possibly increase their memory requirements. (Note that we could only increase it for mainnet nodes I think.)

**Comment by bricerisingalgorand** [comment]
The impact of the memory issues catchpoint loggers had in the past was that archival nodes would need 30gb+ memory in order to progress blocks. This hopefully will not happen anymore, but we should have good monitoring for this set up when we design a new catchpoint logging process

**Comment by algojack** [comment]
according to this thread, we don't need archival node for catchpoint logger, just non-archival node https://algorand-internal.slack.com/archives/C911FDB5W/p1631640321191200
