### ISSUE TITLE
Add test automation for update.sh

### ISSUE THREAD

**Issue by btoll** [algorand/go-algorand#1790]
## Summary
The `update.sh` script keeps growing in complexity (for example, https://github.com/algorand/go-algorand/pull/1776) , and we need to address this by having solid automated testing since it is public-facing and well-used.

## Scope/Requirements
Some things to consider:
- install as a system service
- installing as a user service
- test that when an upgrade is performed or any other operation that would shutdown and restart the node that it not only performs correctly i.e., acts upon the correct service
- what if user isn't in sudoers and tries an upgrade?
- what if installed as a user service and a user that didn't install the service does an upgrade?
- much more

We should also consider refactoring the script to make testing easier and to avoid false positives.

## Urgency/Relative Priority
High priority

**Comment by onetechnical** [comment]
I believe this is part of PR #1776 so closing this in favor of that.
