### ISSUE TITLE
Additional checks to prevent incorrect permissions of participation keys

### ISSUE THREAD

**Issue by fabrice102** [algorand/go-algorand#1791]
**Is your feature request related to a problem? Please describe.**

If `goal account addpartkey` is run as a different user as `algod`, then no error is displayed after running `goal account changeonlinestatus` and `goal account listpartkeys` mark the key as registered = yes.
(I have not run advanced checks whether the node is participating or not, but I think it is not properly participating either, as it cannot update the participation key file, which is necessary for participating.)

Furthermore, if `algod` is stopped, then it cannot be started again: `node.log` ends with 
```
{"file":"main.go","function":"main.main","level":"error","line":295,"msg":"couldn't initialize the node: AlgorandFullNode.loadParticipationKeys: cannot load account at XMD7GODP4SSZ5F4WSS7VYWOTLAJOI3DWN7TWV7ZM5F6Y3TT5DX6TPWFBHE.11000000.14000001.partkey: attempt to write a readonly database","time":"2020-12-23T22:45:24.212224-05:00"}
```

This issue can be triggered if the Debian package is used and `goal account addpartkey` is run through
```
sudo account addpartkey ...
```
instead of:
```
sudo -u algorand -E goal account addpartkey ...
```

**Describe the solution you'd like**

It would be great to have additional checks / errors to prevent incorrect permissions of participation keys.
Here are some potential ideas:
* When `goal account addpartkey` and/or `goal account changeonline status is called, it checks that the current user matches the user owning `$ALGORAND_DATA` and/or that this matches the user running `algod` (if `algod` is currently running).
* `algod` stops and records the above error as soon as it detects an impossible-to-load participation key is registered (even if `algod` is not restarted).

**Comment by ian-algorand** [comment]
Hey @fabrice102 it looks like your PR addressing this was merged, can we close this issue? Thanks

**Comment by fabrice102** [comment]
The documentation PR was merged.
However, I think it would be great if the Algorand code itself do these additional checks.
Currently, if you don't read the warning in the documentation, you may not realize there is an issue until too late (that is if you restart your node and it does not start - in the meantime, you thought you were participating but you actually were not).

**Comment by ian-algorand** [comment]
@tsachiherman how would you like to proceed with this?

**Comment by yaovi-a** [comment]
The solution here needs to be reviewed.

**Comment by tsachizehub** [comment]
@ian-algorand - I think that the current model, where the console-user process is the one that installs the participation key is the source of the problem. The above is a bandaid which would be better than nothing, but the core issue would remain.

**Comment by winder** [comment]
For reference, we have an issue to address the core issue here: https://github.com/algorand/go-algorand/issues/864

**Comment by winder** [comment]
This is no longer an issue with the new participation key interface.
