### ISSUE TITLE
Please add support for RHEL/CentOS 8 with RPM build

### ISSUE THREAD

**Issue by jrhodes10** [algorand/go-algorand#1803]
**Is your feature request related to a problem? Please describe.**

The current RPM package does not work on REHL/CentOS 8.  They have switched from `yum-cron` to `dnf-automatic` for automatic updates.  As such, the RPM fails to install because of missing required packages:

```
[root@algo-node2 ~]# yum install algorand
Last metadata expiration check: 0:06:21 ago on Wed 30 Dec 2020 07:33:51 PM EST.
Error: 
 Problem: conflicting requests
  - nothing provides yum-cron needed by algorand-2.3.0-1.x86_64
```

**Describe the solution you'd like**

A REHL/CentOS 8 specific package would probably be required.

**Comment by ian-algorand** [comment]
Let's bump the priority up on this issue
