### ISSUE TITLE
[REPO] Revise Description, add URL

### ISSUE THREAD

**Issue by lazaridiscom** [algorand/go-algorand#185]
This github repo current description is:

> Algorand's official implementation in Go. 

which does not tell much.

Possibly something like:

=> Pure Proof-of-Stake (pPoS) Open Blockchain Client with Transaction Finality for Billions of Users

In any case, a URL should be added to the Website field, most possibly:

=> https://developer.algorand.org/

**Comment by derbear** [comment]
The URL is a good idea and has been added. Thanks for the suggestion!
