### ISSUE TITLE
Raise TTL on indexer deployments

### ISSUE THREAD

**Issue by bricerisingalgorand** [algorand/go-algorand#1862]
## Summary
Anya needs to do queries against the internal indexer that take a long time to execute (I haven't gotten info about specifically how long). To unblock her I manually raised the ttl on the mainnet ingress rules and the aws load balancer to 1 hour in the internal environment. We should probably come up with a reasonable ttl for indexer that's greater than the default of 60s for the internal environments and automate that in the deployment.

## Scope/Requirements
We need to automate longer timeouts for the indexer apis in the internal environments.
* Update Indexer deployment values files with appropriate annotations to extend timeouts
        nginx.org/proxy-connect-timeout: 3600s
        nginx.org/proxy-read-timeout: 3600s
* We need to update our ingress controller deployment to use a longer timeout

## Urgency/Relative Priority
Probably not too urgent since it only affects one person and can be fixed manually. The ingress changes will be wiped out on each deployment though so we need to keep it in mind.

**Comment by tsachiherman** [comment]
The issue with higher values is that it opens up the server for an attack : a single malicious user can make a query that would take a long time. For the attacker, it wouldn't "cost" too much bandwidth. If an attacker could keep making these requests, the indexer would become non-usable pretty quickly.
As long as these timeouts are set on a non-production indexer, I don't see any harm done. If we need to expose that, than we might want to try and limit the number of concurrent requests as well as handle request cancelation.

**Comment by onetechnical** [comment]
I haven't heard anyone ask about this recently, so closing.
