### ISSUE TITLE
Block proof

### ISSUE THREAD

**Issue by b00f** [algorand/go-algorand#1863]
Is there any way to see the block committee as a proof of a block?
I used the SDK but I couldn't find a way to find a proof for a given block.

Imagine I know block `N` is valid, for block `N+1` should be a proof for that block. right?

**Comment by b00f** [comment]
I am trying to understand how Algorand consensus engine works. Forgive me if I ask some questions here. 

PBFT is able to tolerate up to 2/3 of faulty replicas which is almost 67% of the nodes.
Can we say this threshold in Algorand is 80% (Algorand white paper @ section 7.5: Committee size) 

I m Also  interested to know how do you calculate these numbers:
```
NumProposers:           30,
SoftCommitteeSize:      2500,
SoftCommitteeThreshold: 1870,
CertCommitteeSize:      1000,
CertCommitteeThreshold: 720,
NextCommitteeSize:      10000,
NextCommitteeThreshold: 7750,
LateCommitteeSize:      10000,
LateCommitteeThreshold: 7750,
RedoCommitteeSize:      10000,
RedoCommitteeThreshold: 7750,
DownCommitteeSize:      10000,
DownCommitteeThreshold: 7750,
```

They are not same as algorand [spec_v1](https://github.com/algorandfoundation/specs/blob/master/overview/Algorand_v1_spec-2.pdf). 

I am also curios to know if  Algorand stores signatures from committee members as a proof of block commitment.
If yes, how can I check them?
If No, why?

**Comment by tsachiherman** [comment]
The question above is legit, but I don't think that this is the correct place for that; would you mind posting it on the Algorand forum ? https://forum.algorand.org

**Comment by b00f** [comment]
I have posted there. I close this issue. Thanks


https://forum.algorand.org/t/consensus-parameters/2489
https://forum.algorand.org/t/proof-of-block-commit/2491
