### ISSUE TITLE
[investigate] Nginx ingress controller - Fix response on errors

### ISSUE THREAD

**Issue by bricerisingalgorand** [algorand/go-algorand#1866]
## Summary
It looks like some errors are returning a 502 from the nginx ingress controller. We want any error from indexer to be propogated to the client, rather than swallowed by nginx. Below is an example

curl  "https://indexer-betanet.internal.aws.algodev.network/v2/accounts/4YDUBDLNMVD4SBNKZBVUE6B3KA5BWMRNKAD4SWZZAWNMOCC2S4ZDKRTC24?pretty&round=6000000"

## Scope/Requirements
There is probably some configuration issue that's causing this problem. We'll need to figure that out and update the configurations so that this doesn't continue to happen.

## Urgency/Relative Priority
Low urgency. This is something that is only affecting developers using the internal apis (not currently blocking anyone it would seem)

**Comment by onetechnical** [comment]
This might get a revisit with the next indexer release.
