### ISSUE TITLE
Consider Grouping Source-Code into... a "src" folder

### ISSUE THREAD

**Issue by lazaridiscom** [algorand/go-algorand#187]
## Is your feature request related to a problem? Please describe:

The first contact with the Algorand project brings up a problem:

The sources are not grouped in one folder.

The effect is a (kind of "sloppy") root-folder, which intermixes source with non-source folders.

A visitor cannot focus on sources.

## Describe the solution you'd like

Group related information together, like scripts, tests, docs, ..., and naturally(!) sources.

**Comment by Vervious** [comment]
What you are proposing is not typical golang project structure, nor do I think it would add value, as our entire repo is essentially source code.

**Comment by lazaridiscom** [comment]
> What you are proposing is not typical golang project structure

I found this "rationale" here:

>  If you can help yourself try not to adopt this Java pattern. You really don't want your Go code or Go projects to look like Java :-)

which is of course a tragedy. My comments here: https://github.com/golang-standards/project-layout/issues/28

> nor do I think it would add value, as our entire repo is essentially source code.

No, it's not (you can possibly argue this to some kiddo devs).

And you violate (again) basic system-design-principles, at the cost of the users, simply to look "fancy-go" like. This is really ridiculous at some point, you need to realize that.

**Comment by Vervious** [comment]
I'm going to put the burden-of-proof back on you. What basic system-design problem does putting all of our code into a single src folder solve?

At the top level we'd have a readme, a src folder, and some travis/github metadata. What does this accomplish?

**Comment by lazaridiscom** [comment]
>  What basic system-design problem does putting all of our code into a single src folder solve?

See, this is so basic, that my professional pride simply does not allow me to discuss this further. Already typed too much (even in a payed context, I would most possibly refuse to discuss this).

Just this:

>>It is beyond sloppy to have code-folders and non-code-folders alphabetically intermixed in root.

https://github.com/golang-standards/project-layout/issues/28#issue-473619554

**Comment by lazaridiscom** [comment]
and if you don't want to look like java (using "src"): I saw somewhere the suggestion to use "pkg".
