### ISSUE TITLE
Improve goal error message for too large TEAL programs

### ISSUE THREAD

**Issue by jasonpaulos** [algorand/go-algorand#1870]
## Summary
Currently when sending an app creation transaction with goal, if the approval program or clear state program is too large, you'll get a message similar to "kmd: could not decode transaction". This causes some confusion as to what the actual problem is, so we should have a better error message for this case.

## Scope/Requirements
Have goal detect if TEAL programs are too large and display a more useful error message.

## Urgency/Relative Priority
I've seen developers get confused by this, and since it's a small fix I'd like to get it done soon.

**Comment by jannotti** [comment]
Seems like we have at least two things to fix: `goal compile` should do error detection of size and cost, and `goal dryrun` should as well.  Currently `goal dryrun` will return success for an lsig that exceeds cost.

**Comment by jannotti** [comment]
I have PR #1970 that addresses compile and dryrun. Not sure if you also want to do the various commands that also submit transactions.

**Comment by jasonpaulos** [comment]
#1969 does not currently address the specific issue here. This issue is referring to `goal app create` and `goal app update` attempting to use an approval program or clear state program that is too large. That PR would help avoid this issue but wouldn't actually fix it.
