### ISSUE TITLE
[GOAL] Highly Confusing Tool Naming

### ISSUE THREAD

**Issue by lazaridiscom** [algorand/go-algorand#188]
## Is your feature request related to a problem? Please describe"

I'm always frustrated when tools (especially cli-tools) are named "non-naturally" / non-intuitive.

The main cli of "Algorand" was named "goal", which is a far too general term.

A cli looks like this:

```sh
./goal node status -d ~/node/data
```

## Expected|

A "natural" naming, kind of "algorand" or "algo"

```sh
./algo node status -d ~/node/data
```

## Curiosity

What is the rationale of naming Algorand's main cli "goal" instead of e.g. "algo" ?

## Related

Eosio for example has "nodeos, keosd, cleos". When I suggested to rename those to the more natural "eosd, eoskd, eos", someone told me that those were the original names, but were changed, thus the names can be pronounced better in... speeches.

**Comment by derbear** [comment]
I think the rationale behind naming the CLI `goal` was that it was an abbreviation of *goAl*gorand. I think "algo" would be confusing because it collides with the name of the currency.

**Comment by lazaridiscom** [comment]
Forget "go", the Product/Brand is "Algorand"/"Algo". Use a "algor" or "alg", but not "goal", it just sounds like... "Goal" as in "Goal" (absolutely unrelated to Algo).

Ask some more newcomers if you don't believe me. Or professional namers/branders.

**Comment by rotemh** [comment]
@lazaridiscom  -- Thank you for your suggestion. We will take this into account when naming new tools.

**Comment by lazaridiscom** [comment]
This issue is EXISTENT and OPEN.

You closing it (you are the 3rd person in this project which closes my issues far too fast), does not change the reality.

I think I'll simply stop filing issues at this point.

Very discouraging project.
