### ISSUE TITLE
Document Muleci

### ISSUE THREAD

**Issue by bricerisingalgorand** [algorand/go-algorand#1892]
## Summary
We need to document the new muleci cli.

## Scope/Requirements
* Documentation that explains how it works and how to get started with a new project

## Urgency/Relative Priority
We're hoping that this will be something teams can use on their own, so it would be good to do soon.

**Comment by ian-algorand** [comment]
Consider a presentation to the engineering team

**Comment by jsgranados** [comment]
We want to get away from muleci, so rather than document we would like to remove. Closing this.
