### ISSUE TITLE
[GO] Find a way to create finer grained subsystems

### ISSUE THREAD

**Issue by lazaridiscom** [algorand/go-algorand#191]
(draft)

see https://github.com/algorand/go-algorand/issues/186

## Problem

package-folders contain sometimes many files

## Possible Solution

find a way to group some files into folders, without the need to create a go-package.

(this would be possibly a feature-request for the go-language project)

**Comment by algoradam** [comment]
According to the Go language spec (https://golang.org/ref/spec#Package_clause):
> An implementation may require that all source files for a package inhabit the same directory.

And indeed, the standard Go compiler seems to require all source files for a package to inhabit the same directory. So reorganizing our agreement code into subdirectories without creating new package boundaries is impossible.

(I do agree that our agreement code should be better organized / documented. We're working on that...)

**Comment by lazaridiscom** [comment]
@algoradam , I opened this issue here because of this:

https://github.com/algorand/go-algorand/issues/186#issuecomment-516151145

>  is impossible.

No. What is impossible is your behavior, e.g. suggesting that no other person can find a solution to this (obvious and existent) problem.

You should really not close issues in that way, especially if they are follow-up issues from already closed issues.

From one point on its simply rude.
