### ISSUE TITLE
Algorand 2.4.1 node stopped syncing at 11665201. No errors in logs.

### ISSUE THREAD

**Issue by vishalgupta96** [algorand/go-algorand#1919]
### Subject of the issue
Algorand 2.4.1 node stopped syncing at 11665201. No errors in logs.

As explained on https://github.com/algorand/go-algorand/pull/1736

@algorandskiy : As discussed with you on Issue 1736 thread, i am creating this new issue. My algorand node (which was previously running on 2.3.0) stopped syncing at block#11665201. I have even upgraded it to 2.4.1 but it does not sync further.

As requested below are the required details:
OS Details: Ubuntu 18.04
1. a config file
{
    "Archival": true,
    "isIndexerActive": true,
    "GossipFanout": 4,
    "BaseLoggerDebugLevel": 1,
    "IncomingConnectionsLimit": -1,
    "NetAddress": "4160",
    "EndpointAddress": "0.0.0.0:8887",
    "LogSizeLimit": 1073741824,
    "EnableMetricReporting": false,
    "EnableOutgoingNetworkMessageFiltering": true,
    "EnableIncomingMessageFilter": false,
    "CatchupParallelBlocks": 50
}

2. aglod -v output:
![image](https://user-images.githubusercontent.com/25690537/108450936-f9afca00-728b-11eb-9b91-ad682ed681d1.png)

3. part of the log from the restart until stuck - 

++++++++++++++++++++++++++++++++++++++++
Logging Starting
Telemetry Disabled
++++++++++++++++++++++++++++++++++++++++
{"file":"trace.go","function":"github.com/algorand/go-algorand/agreement.makeTracer","level":"info","line":94,"msg":"agreement: cadaver set to agreement","time":"2021-02-19T03:14:36.199409Z"}
{"file":"interface.go","function":"github.com/algorand/go-algorand/network/messagetracer.NewTracer","level":"info","line":53,"msg":"graphtrace factory DISabled","time":"2021-02-19T03:14:36.199830Z"}
{"details":{"Version":"2.4.1","CommitHash":"573a34c4","Branch":"rel/stable","Channel":"stable","InstanceHash":"5X5UQC7224FXAPXBDR6H3MW6RXDX5IICQK5TDAC22B3BNLTVR4WQ"},"file":"telemetry.go","function":"github.com/algorand/go-algorand/logging.(*telemetryState).logTelemetry","instanceName":"x/3Rs01OsVNFBG3a","level":"info","line":212,"msg":"/ApplicationState/Startup","session":"","time":"2021-02-19T03:14:36.199885Z"}
{"file":"server.go","function":"github.com/algorand/go-algorand/daemon/algod.(*Server).Start","level":"info","line":156,"msg":"Trying to start an Algorand node","time":"2021-02-19T03:14:36.199939Z"}
{"file":"wsNetwork.go","function":"github.com/algorand/go-algorand/network.(*WebsocketNetwork).Start","level":"error","line":681,"msg":"[Stack] goroutine 1 [running]:\nruntime/debug.Stack(0xc0000f6f50, 0xc0002060b8, 0xc00027d810)\n\truntime/debug/stack.go:24 +0x9f\ngithub.com/algorand/go-algorand/logging.logger.Errorf(0xc0000f6f50, 0xc0002060b8, 0x123e90c, 0x1f, 0xc001a398a0, 0x2, 0x2)\n\tgithub.com/algorand/go-algorand/logging/log.go:229 +0x4a\ngithub.com/algorand/go-algorand/network.(*WebsocketNetwork).Start(0xc0000b3c00)\n\tgithub.com/algorand/go-algorand/network/wsNetwork.go:681 +0xa35\ngithub.com/algorand/go-algorand/node.(*AlgorandFullNode).Start(0xc0000e8d80)\n\tgithub.com/algorand/go-algorand/node/node.go:336 +0xce\ngithub.com/algorand/go-algorand/daemon/algod.(*Server).Start(0xc00060fbf8)\n\tgithub.com/algorand/go-algorand/daemon/algod/server.go:158 +0x136\nmain.main()\n\tgithub.com/algorand/go-algorand/cmd/algod/main.go:363 +0x13da\n","name":"4160","time":"2021-02-19T03:14:36.199996Z"}
{"file":"wsNetwork.go","function":"github.com/algorand/go-algorand/network.(*WebsocketNetwork).Start","level":"error","line":681,"msg":"network could not listen 4160: listen tcp: address 4160: missing port in address","name":"4160","time":"2021-02-19T03:14:36.200023Z"}
{"details":{"Metrics":{"branch":"rel/stable","channel":"stable","commit-hash":"573a34c4","ledger_accountsinit_count":"1","ledger_accountsinit_micros":"476","ledger_blockq_getblock_count":"1321","ledger_blockq_getblock_micros":"153206","ledger_blockq_getblockhdr_count":"2","ledger_blockq_getblockhdr_micros":"94","ledger_blockq_init_count":"1","ledger_blockq_init_micros":"47","ledger_initblocksdb_count":"1","ledger_initblocksdb_micros":"7394","ledger_verifygenhash_count":"1","ledger_verifygenhash_micros":"67","version":"2.4.1","version-num":"8590196737"}},"file":"telemetry.go","function":"github.com/algorand/go-algorand/logging.(*telemetryState).logTelemetry","instanceName":"x/3Rs01OsVNFBG3a","level":"info","line":212,"msg":"/ApplicationState/Heartbeat","session":"","time":"2021-02-19T03:14:36.200069Z"}
{"file":"node.go","function":"github.com/algorand/go-algorand/node.(*AlgorandFullNode).Start","level":"info","line":357,"msg":"Indexer was started successfully","name":"4160","time":"2021-02-19T03:14:36.200207Z"}
{"file":"server.go","function":"github.com/algorand/go-algorand/daemon/algod.(*Server).Start","level":"info","line":159,"msg":"Successfully started an Algorand node.","time":"2021-02-19T03:14:36.200265Z"}
{"file":"persistence.go","function":"github.com/algorand/go-algorand/agreement.restore.func3","level":"info","line":157,"msg":"restore (agreement): crash state not found (n = 0)","time":"2021-02-19T03:14:36.200426Z"}
{"file":"persistence.go","function":"github.com/algorand/go-algorand/agreement.restore.func3.1","level":"info","line":138,"msg":"restore (agreement): resetting crash state","time":"2021-02-19T03:14:36.200468Z"}
{"Context":"Agreement","Hash":"","ObjectPeriod":0,"ObjectRound":0,"ObjectStep":0,"Period":0,"Round":11665202,"Sender":"","Step":1,"Type":"StepTimeout","Weight":0,"WeightTotal":0,"file":"trace.go","function":"github.com/algorand/go-algorand/agreement.(*tracer).logTimeout","level":"info","line":191,"msg":"timeout fired on (11665202, 0, 1) with value 4s (napping: false)","time":"2021-02-19T03:14:40.200875Z"}
{"Context":"Agreement","Hash":"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA","ObjectPeriod":0,"ObjectRound":11665202,"ObjectStep":0,"Period":0,"Round":0,"Sender":"","Step":0,"Type":"ProposalFrozen","Weight":0,"WeightTotal":0,"file":"trace.go","function":"github.com/algorand/go-algorand/agreement.(*tracer).logProposalFrozen","level":"info","line":214,"msg":"froze proposal {{} 0 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAY5HFKQ AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA} for (11665202, 0)","time":"2021-02-19T03:14:40.201033Z"}
{"Context":"Agreement","Hash":"","ObjectPeriod":0,"ObjectRound":0,"ObjectStep":0,"Period":0,"Round":11665202,"Sender":"","Step":2,"Type":"StepTimeout","Weight":0,"WeightTotal":0,"file":"trace.go","function":"github.com/algorand/go-algorand/agreement.(*tracer).logTimeout","level":"info","line":191,"msg":"timeout fired on (11665202, 0, 2) with value 17s (napping: false)","time":"2021-02-19T03:14:53.200846Z"}
{"Context":"Agreement","Hash":"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA","ObjectPeriod":0,"ObjectRound":0,"ObjectStep":0,"Period":0,"Round":11665202,"Sender":"","Step":3,"Type":"VoteAttest","Weight":0,"WeightTotal":0,"file":"actions.go","function":"github.com/algorand/go-algorand/agreement.pseudonodeAction.do","level":"info","line":372,"msg":"attested to {{} 0 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAY5HFKQ AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA} at (11665202, 0, 3)","time":"2021-02-19T03:14:53.201050Z"}
{"Context":"Agreement","Hash":"","ObjectPeriod":0,"ObjectRound":0,"ObjectStep":0,"Period":0,"Round":11665202,"Sender":"","Step":3,"Type":"StepTimeout","Weight":0,"WeightTotal":0,"file":"trace.go","function":"github.com/algorand/go-algorand/agreement.(*tracer).logTimeout","level":"info","line":191,"msg":"timeout fired on (11665202, 0, 3) with value 19s (napping: false)","time":"2021-02-19T03:14:55.200847Z"}
{"Context":"Agreement","Hash":"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA","ObjectPeriod":0,"ObjectRound":0,"ObjectStep":0,"Period":0,"Round":11665202,"Sender":"","Step":4,"Type":"VoteAttest","Weight":0,"WeightTotal":0,"file":"actions.go","function":"github.com/algorand/go-algorand/agreement.pseudonodeAction.do","level":"info","line":372,"msg":"attested to {{} 0 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAY5HFKQ AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA} at (11665202, 0, 4)","time":"2021-02-19T03:14:58.124271Z"}
{"Context":"Agreement","Hash":"","ObjectPeriod":0,"ObjectRound":0,"ObjectStep":0,"Period":0,"Round":11665202,"Sender":"","Step":4,"Type":"StepTimeout","Weight":0,"WeightTotal":0,"file":"trace.go","function":"github.com/algorand/go-algorand/agreement.(*tracer).logTimeout","level":"info","line":191,"msg":"timeout fired on (11665202, 0, 4) with value 23s (napping: false)","time":"2021-02-19T03:14:59.200787Z"}
{"Context":"Agreement","Hash":"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA","ObjectPeriod":0,"ObjectRound":0,"ObjectStep":0,"Period":0,"Round":11665202,"Sender":"","Step":5,"Type":"VoteAttest","Weight":0,"WeightTotal":0,"file":"actions.go","function":"github.com/algorand/go-algorand/agreement.pseudonodeAction.do","level":"info","line":372,"msg":"attested to {{} 0 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAY5HFKQ AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA} at (11665202, 0, 5)","time":"2021-02-19T03:15:04.453500Z"}
{"Context":"Agreement","Hash":"","ObjectPeriod":0,"ObjectRound":0,"ObjectStep":0,"Period":0,"Round":11665202,"Sender":"","Step":5,"Type":"StepTimeout","Weight":0,"WeightTotal":0,"file":"trace.go","function":"github.com/algorand/go-algorand/agreement.(*tracer).logTimeout","level":"info","line":191,"msg":"timeout fired on (11665202, 0, 5) with value 31s (napping: false)","time":"2021-02-19T03:15:07.200793Z"}
{"Context":"Agreement","Hash":"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA","ObjectPeriod":0,"ObjectRound":0,"ObjectStep":0,"Period":0,"Round":11665202,"Sender":"","Step":6,"Type":"VoteAttest","Weight":0,"WeightTotal":0,"file":"actions.go","function":"github.com/algorand/go-algorand/agreement.pseudonodeAction.do","level":"info","line":372,"msg":"attested to {{} 0 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAY5HFKQ AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA} at (11665202, 0, 6)","time":"2021-02-19T03:15:19.656824Z"}
{"Context":"Agreement","Hash":"","ObjectPeriod":0,"ObjectRound":0,"ObjectStep":0,"Period":0,"Round":11665202,"Sender":"","Step":6,"Type":"StepTimeout","Weight":0,"WeightTotal":0,"file":"trace.go","function":"github.com/algorand/go-algorand/agreement.(*tracer).logTimeout","level":"info","line":191,"msg":"timeout fired on (11665202, 0, 6) with value 47s (napping: false)","time":"2021-02-19T03:15:23.200840Z"}
{"Context":"Agreement","Hash":"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA","ObjectPeriod":0,"ObjectRound":0,"ObjectStep":0,"Period":0,"Round":11665202,"Sender":"","Step":7,"Type":"VoteAttest","Weight":0,"WeightTotal":0,"file":"actions.go","function":"github.com/algorand/go-algorand/agreement.pseudonodeAction.do","level":"info","line":372,"msg":"attested to {{} 0 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAY5HFKQ AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA} at (11665202, 0, 7)","time":"2021-02-19T03:15:26.187535Z"}
{"Context":"Agreement","Hash":"","ObjectPeriod":0,"ObjectRound":0,"ObjectStep":0,"Period":0,"Round":11665202,"Sender":"","Step":7,"Type":"StepTimeout","Weight":0,"WeightTotal":0,"file":"trace.go","function":"github.com/algorand/go-algorand/agreement.(*tracer).logTimeout","level":"info","line":191,"msg":"timeout fired on (11665202, 0, 7) with value 1m19s (napping: false)","time":"2021-02-19T03:15:55.200914Z"}
{"Context":"Agreement","Hash":"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA","ObjectPeriod":0,"ObjectRound":0,"ObjectStep":0,"Period":0,"Round":11665202,"Sender":"","Step":8,"Type":"VoteAttest","Weight":0,"WeightTotal":0,"file":"actions.go","function":"github.com/algorand/go-algorand/agreement.pseudonodeAction.do","level":"info","line":372,"msg":"attested to {{} 0 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAY5HFKQ AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA} at (11665202, 0, 8)","time":"2021-02-19T03:16:58.673684Z"}
{"Context":"Agreement","Hash":"","ObjectPeriod":0,"ObjectRound":0,"ObjectStep":0,"Period":0,"Round":11665202,"Sender":"","Step":8,"Type":"StepTimeout","Weight":0,"WeightTotal":0,"file":"trace.go","function":"github.com/algorand/go-algorand/agreement.(*tracer).logTimeout","level":"info","line":191,"msg":"timeout fired on (11665202, 0, 8) with value 2m23s (napping: false)","time":"2021-02-19T03:16:59.200819Z"}
{"file":"logger.go","function":"github.com/algorand/go-algorand/daemon/algod/api/server/lib/middlewares.(*LoggerMiddleware).handler.func1","level":"info","line":56,"msg":"172.22.0.1:58744 - - [2021-02-19 03:17:35.9648712 +0000 UTC m=+180.622797201] \"GET /v1/status HTTP/1.1\" 200 0 \"curl/7.58.0\" 109.2µs","time":"2021-02-19T03:17:35.965017Z"}
{"Context":"Agreement","Hash":"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA","ObjectPeriod":0,"ObjectRound":0,"ObjectStep":0,"Period":0,"Round":11665202,"Sender":"","Step":9,"Type":"VoteAttest","Weight":0,"WeightTotal":0,"file":"actions.go","function":"github.com/algorand/go-algorand/agreement.pseudonodeAction.do","level":"info","line":372,"msg":"attested to {{} 0 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAY5HFKQ AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA} at (11665202, 0, 9)","time":"2021-02-19T03:17:43.139584Z"}

**Comment by vishalgupta96** [comment]
@algorandskiy : Could you please check and let me know the issue, its been a month now that our node is not syncing.

**Comment by onetechnical** [comment]
A few suggestions/questions...

- Can you set `"NetAddress": "4160"` to `"NetAddress": ""` (or delete it altogether)?
- Can you add the Version parameter e.g. `"Version": 15` to it as well?
- Can you include other information, such as type of hardware (CPU/mem/disk), and operating system?

**Comment by algorandskiy** [comment]
I agree to John, an obvious error from the log is
```
{"file":"wsNetwork.go","function":"github.com/algorand/go-algorand/network.(*WebsocketNetwork).Start","level":"error","line":681,"msg":"network could not listen 4160: listen tcp: address 4160: missing port in address","name":"4160","time":"2021-02-19T03:14:36.200023Z"}
```

Secondary, back to the original DNSSEC problem, need to add `"Version": 12` and `"DNSSecurityFlags": 0` to the config file.

**Comment by ian-algorand** [comment]
Did you try any of the suggestions above?

**Comment by ian-algorand** [comment]
@vishalgupta96 closing this issue but if you'd like to continue this discussion, please feel free to post on forum.algorand.org

**Comment by vishalgupta96** [comment]
Yes, i did the below changes as suggested above and it seemed to work. Now my node started syncing:

Can you set "NetAddress": "4160" to "NetAddress": "" (or delete it altogether)?
Can you add the Version parameter e.g. "Version": 12 to it as well?
added "DNSSecurityFlags": 0 to config file

Thanks a lot for your valuable support on this.

**Comment by onetechnical** [comment]
Great to hear it's working now!
