### ISSUE TITLE
Allow re-submitting transaction with higher fee without risk of double commit

### ISSUE THREAD

**Issue by zeldovich** [algorand/go-algorand#195]
If a transaction is submitted with a low fee, it sits in a limbo state until its `LastValid` expires: the transaction might have a fee that's too low to get in the pool, but the sender has no guarantee that it will not be committed.

A sender may want to re-submit the transaction with a higher fee when they observe the transaction isn't getting into the pool.  Currently, this runs the risk that both transactions are committed, because neither is a duplicate of the other.  The transaction ID is computed based on the hash of the transaction, which includes the fee field.

It might be useful to add an extra field to the transaction that makes the two transactions in the above paragraph conflict with one another, so that only one can be committed.  Some kind of "uniquifier" field would be generated by the client, and the rules are that only one transaction with a given uniquifier from a given sender can be committed.  The ledger's txtail tracker can keep track of these additional (sender, uniquifier) pairs to determine if a transaction with the same uniquifier has already been committed recently.  I expect this uniquifier should work only if the transactions in question have the same `LastValid` rounds.

This uniquifier would allow a sender to re-issue a transaction with a higher fee, but as long as they keep the same uniquifier, they know that only one of these transactions will be committed.

**Comment by ian-algorand** [comment]
This is covered by leases.
