### ISSUE TITLE
TEAL 4 Epic

### ISSUE THREAD

**Issue by jannotti** [algorand/go-algorand#1950]
Collecting issues and initiatives for TEAL4.  Targeting next consensus upgrade - April/May? - release.  Should improve TEAL for direct authors, high-level language compilers, and layer two speculative execution.

**Comment by krotkiewicz** [comment]
`divw`

takes 128 bit from two uints on stack and pushes 64 bit result

**Comment by krotkiewicz** [comment]
@jannotti April release means when it can be deployed on mainnet?

**Comment by jannotti** [comment]
I'm going to just remove that April comment in my description. I don't want to make any claim stronger than, intended soon, probably the next time there's a consensus upgrade.

**Comment by jannotti** [comment]
> `divw`
> 
> takes 128 bit from two uints on stack and pushes 64 bit result

Agreed, we need something like this. Probably also need the remainder, so modw?

You say it returns a 64 bit result. Part of me likes that, with a panic if your result doesn't fit. Is that what you'd expect? I've been meaning toward returning 2 uints though, and letting programmer decide.

**Comment by jannotti** [comment]
Current plan is to return four(!?) uint64s. Returns the quotient (as two uint64s) and the remainder (as two more uint64s). Currently the proposed opcode is `divw` but willing to hear calls for `divmodw`.

**Comment by krotkiewicz** [comment]
I saw your proposition in #1967. I cannot comment which is preferred, I think divw and modw (that takes 2 128b ints) sounds reasonable but `divmodw` looks quite crazy to me. 
Why we need it? To better optimise program size limit to fit into 1kb? Is it proper reason to add that extra opcode? 

Thinking about this problem a little bit longer I think it is brutal for developers to have to think about these kind of things. Sure, you give all necessary tools for the developers (like mulw, divw etc) but these tools are hard to use. Imagine wrapping that with PyTEAL.

How to solve the problem with simpler tools? Only u128 comes to my mind. We would probably need a separate issue to discuss it properly but let me start here.
If outer world is always 64bit (amount of Algos, ASAs etc) then it should be quite easy to use u128 internally and then cast to u64, right? At least you would be able to calculate proportion in easy way :) 
On Algorand Forum you said that you are afraid of having mulw for u128, what would happen if we didn't support it?

**Comment by jannotti** [comment]
Since division is relatively heavyweight, and the operation being done behind the scenes produces the quotient and remainder anyway, it's very common to offer a single function that yields both, so callers don't have to do the same work twice.  See, for example, Go's big.Int package and the QuoRem function.

I agree it's a bit messy, but this feels like a place where the primitive is provided in the most efficient way possible, and TEAL users can build on top.  We can separate them and provide it as two different opcodes, but they'll probably each have a TEAL "cost" around 10 (?), so if you do need both, it'll cost 20.  I think you're right that PyTeal can hid some of this complexity and offer you a convenient way to do: X*Y/Z in a single call, and have the right TEAL emitted.

As for u128, I'm pretty opposed to introducing a new wider type, as the request for u256 will just follow immediately on its heels, and we'd have to define a bunch of semantics around whether you can add u128 to u64, implicit conversion, and so on  Instead, I suspect the next thing we offer would be arbitrary arithmetic on byte strings, interpreted as integers.  It keeps the TEAL language model simple, and just offers some opcodes that "add/sub/mul/div" long bytestrings as though they were integers.  This gives you u128, u256 and so on.  I suppose the "cost" may have to be proportional to string length.

**Comment by krotkiewicz** [comment]
Ok, so then `divmodw` sounds like a way to go.

**Comment by barnjamin** [comment]
Maybe there is a better way to do what I'd like but please consider making the Signature fields on a txn available via Teal opcodes.

Specifically for one rekey txn I'd like to see that its rekeying to a multi-sig where the 2 accounts are ones that I'm expecting and match other fields within a grouped txn. 

https://github.com/algorand/go-algorand/blob/5b441e37cde66c169752c0c35616ce3d09f93706/data/transactions/signedtxn.go#L31 dug around a little bit and it does look like the SignedTxns are accessible in the evalContext but maybe there are other reasons they arent made available?

**Comment by barnjamin** [comment]
Digging a bit more here, it appears the multisig address is deterministic.  I should be able to just check that the rekey to field is the result of https://github.com/algorand/go-algorand/blob/75a15c737ba1973dddf0cf191591c55d48180b59/crypto/multisig.go#L83

**Comment by jannotti** [comment]
Yes, that's right, I'm glad that's enough for you.  I thought you needed to
inspect *another* transaction to see if it was signed by the multisig that
the first transaction is being rekeyed to.  That sounds like a plausible
need, but I think we'd prefer to avoid it.  We considered exposing the
logicsig args in the last teal update, but decided that it's too easy to
misunderstand them - unlike ApplicationArgs, they are not themselves part
of what is being signed, so it would have been easy for tx1, reading tx0's
logicsig args, to misinterpret the guarantee being offered.

I'm not sure I see a way this could be a problem with multisig args, as
they have less "flexibility" to contain extraneous data that could be
changed by a malicious node.  But given the subtlety here, I'd rather avoid
exposing them.

**Comment by barnjamin** [comment]
Understood. Appreciate the response.  

Some other opcodes I'll half heartedly suggest are string manipulation functions.  Functions like string replace/index/to upper/to lower have some potential as the note field may contain structured data that needs to adhere to a standard.

Additionally or maybe instead of that, some unmarshal function that converts note field json/msgp contents to a map with arbitrary key/value fields.  Again, useful to validate in the case that the note field is storing a payload with a specific format. 

This can currently be validated with args passed into the logic sig and some existing substring/concat/hash type logic but its not super clear whats going on.

**Comment by gidonkatten** [comment]
Opcode similar to `err` but takes in a string (error message). Useful for debugging and just general information for why a transaction failed.

**Comment by jannotti** [comment]
The trouble is that it is unclear where that error would be reported, since
the transaction would never make it to the chain.  I suppose that we could
make it part of the REST API response when the txn gets rejected upon
submission to the network, but that is not the only way transactions can
fail.  They might get admitted because they look ok, but because of an app
state change that occurs after their submission, they get rejected late in
the game.

A feature we have contemplated is the ability to say "Please put this txn
on the chain, explicitly marked as a failure."  No effects (except payment
of the fee) would occur, but observers could see the failed
transaction, and perhaps the reason.  Do you think your use case matters
enough that you'd want such a record, and pay the fee to get it?  Or is
this mostly about debugging?  Have you tried the TEAL debugger or dry-run
facilities?

**Comment by jannotti** [comment]
> Some other opcodes I'll half heartedly suggest are string manipulation functions. Functions like string replace/index/to upper/to lower have some potential as the note field may contain structured data that needs to adhere to a standard.

We're giving some thought to a couple string manipulation primitives, though probably just along the lines of index oriented manipulations (replace, splice, etc).  You've seen getbyte in teal3?  I don't think we'd offer case changing ops, because we don't want to say anything about the character encoding of the raw bytes in your strings/byteslices. 

> Additionally or maybe instead of that, some unmarshal function that converts note field json/msgp contents to a map with arbitrary key/value fields. Again, useful to validate in the case that the note field is storing a payload with a specific format.

This seems important - we want to publish recommendations for data encoding soon, along the lines of Ethereum's ABI.  If we recommend any kind of packing scheme, we'll certainly give you a way to unpack easily. I suspect we'd go with msgpack if we do this, for compactness.

**Comment by giuliop** [comment]
It would nice to have "functions".
The simplest way to implement them so that they just fit in the current framework is to introduce two new opcodes: _func_ and _ret_.
A function would be a block of code like this:

```
func <name>
...code...
ret
```
They would follow these rules:

-  A branch instruction can jump to a function by using its <name> as a label
- The code inside a function cannot branch outside the function itself
- The _ret_ opcode branches back to the instruction following the function call

The simplest compiler implementation is to just inline each function call and then delete the function "declarations" from the code

**Comment by barnjamin** [comment]
> I don't think we'd offer case changing ops
This is probably the right decision, should be left to the caller to have correct casing on w/e

>  we want to publish recommendations for data encoding soon
Great! If this is available the string manipulation stuff is less desirable.

**Comment by jannotti** [comment]
We expect to add `callproc` and `retproc` which will be similar to your
description, slightly simpler. Callproc is an unconditional jump that
pushes pc+3 (the location of the next instruction) on a call stack that is
not directly visible by teal code. Retproc pops from that stack and jumps
to the location found.

**Comment by jannotti** [comment]
I'm closing this as I think most things we discussed have made it into Teal 4 / AVM 0.9.  We're currently contemplating a small set of opcodes to extract integers of different sizes from byte arrays here: #2347
