### ISSUE TITLE
divw and friends

### ISSUE THREAD

**Issue by jannotti** [algorand/go-algorand#1967]
TEAL has addw and mulw but divw is lacking.  It's quite hard to implement "long" division properly with the remaining operations in TEAL.  Some possibilities

divw: takes two 128 uints, in the form of two pairs of uint64s on the stack. pushes the quotient as two uints. cost ~ 4?
modw: same, but gives remainder. cost ~ 4?
divmodw: returns both, at lower cost than 8?

Is there a need for subw? I think less so because "long" subtraction is more easily implemented with the rest of TEAL.

Also add the following opcodes: shl, shr, exp, expw, sqrt, log2

**Comment by krotkiewicz** [comment]
@jannotti do we already have the next network update date? can we have `divmodw` by then?

**Comment by jannotti** [comment]
There is the teal v3 update that I think will be on mainnet very soon.  v4
will have divmodw (or similar) but is not done yet.  So I suspect that will
be in the following update.  Usually that's a couple months?

**Comment by krotkiewicz** [comment]
@jannotti so basically no chances in adding it to v3?

we are basically waiting for that one to finish having full precision for our AMM solution https://github.com/ulamlabs/asaswap

**Comment by krotkiewicz** [comment]
@jannotti I know I am late but any chance for this in v3? https://github.com/algorand/go-algorand/pull/2041

**Comment by jannotti** [comment]
Teal 3 left the building a few weeks ago. It's just in the somewhat lengthy process of making its way through betanet, testnet, mainnet upgrade. So nothing else can get in.

Thanks for working on divmodw. I'm afraid I've also written it, so your code might not end up directly merged, but a form of divmodw will certainly make it into v4. It's actually pretty nice to have another implementation to look at, as I might catch a bug by comparing.

**Comment by krotkiewicz** [comment]
Understand, thanks for a fast reply. 

We are currently trying to emulate calculating a proportion (A x B / C). Without that opcode, it [looks](https://github.com/ziomq1991/asaswap/commit/c3faab8b1a8f1573f0553b4701c29e6aaa8e9846#diff-44d5c605439350e88c1d2586677a522ba97767d689fb210cdce2a628a841f75cR23) like a nightmare (it takes 2kb to have full precision).

**Comment by jannotti** [comment]
We will end up calling this instruction `divmodw` (though the current PR calls it divw), to make it clear that both results are returned.  We may add `divw` and `modw` as conveniences to do less popping when you only care about one result.  We have not chosen a cost yet, but expect all three to have the same cost, as the same work must be done, so the short forms are only for convenience.
