### ISSUE TITLE
Goal/SDKs need to be able to create accounts that are non-participating

### ISSUE THREAD

**Issue by ian-algorand** [algorand/go-algorand#197]
Summary: There are accounts that exist in genesis that are non-participating (accounts with tokens that don't earn rewards). If we had to rotate keys because of a security breach or for some reason create new non-particpating accounts, currently we wouldn't be able to.

Requirements: Regardless of implementation (whether it's forked or not), we need to give the foundation and inc the ability to do this.It's not the fact that we need to create these accounts right now that gives it urgency, but rather it's the possibility that if we needed to create one of those accounts, we couldn't and we'd be in trouble. 

---------------------------------------------------------------------------------------------
Jira conversation:
ian Ian Cross added a comment - 17/Jun/19 1:26 PM
Rotem Hemo wanted to meet with Liz Baran before we do this. Seems like there was some concern on whether to do this or not.

david David Shoots added a comment - 03/Jul/19 11:17 AM
This is something the Foundation would like added ASAP. I can’t see a reason to not enable this - most genesis accounts are non-participating so we’re equipped to handle them.

ian Ian Cross added a comment - 10/Jul/19 1:59 PM
Rotem Hemo is there something you still wanted to investigate here?

rotem Rotem Hemo added a comment - 11/Jul/19 9:42 AM
Where this requirement came from? AFAIK, the foundation and us are the only people who have “Non participating” keys. If the foundation needs it, maybe it worth for them to have a fork. I’m not convinced that it should be part of the general purpose SDK.

ian Ian Cross added a comment - 11/Jul/19 9:55 AM
Rotem Hemo we'll talk about the implementation details today, but this is still a high priority for both foundation and inc. I won't pretend to know what's best to include in the general purpose SDK so I totally defer to your expertise. Let's talk at sprint planning.

rotem Rotem Hemo added a comment - 16/Jul/19 3:36 PM
Ok after looking into it - This change is much larger than changing the SDK. The change requires changing some sensitive layer 1 code. we need to crate a new transaction type that can make an account non participating. Ian Cross That’s probably a good couple of days worth of work (Mainly because of testing). Let’s see how we prioritizing it.

ian Ian Cross added a comment - 22/Jul/19 3:49 PM
@derbear  we need to meet to talk about this task. Seems that it's a combo of FDE + consensus work that needs to happen

**Comment by ian-algorand** [comment]
This is a risky change that involves changing the actual transaction validation logic. The consensus team is estimating maybe 2 sprints to complete this.

**Comment by ian-algorand** [comment]
@EvanJRichard you'll want to watch this issue. Once @algoradam has a solution, that'll kick off your work.

**Comment by EvanJRichard** [comment]
@ian-algorand auditing issues ahead of today's sprint planning. moving this to "in review" - it's implemented but needs a spec and protocol upgrade

**Comment by algoradam** [comment]
Foundation just merged the spec PR for this: https://github.com/algorandfoundation/specs/pull/5
