### ISSUE TITLE
FlakyTest: TestStartAndPartitionAuctionTenUsersTenBidsEach

### ISSUE THREAD

**Issue by ian-algorand** [algorand/go-algorand#198]
As seen on Travis, multiple times:

 FAIL: TestStartAndPartitionAuctionTenUsersTenBidsEach (268.07s)
    auctionFixture.go:992: found a nonzero auctionID {AuctionKey:PLME2SHGZF3PW5PO5BBMEWAMDGKIVEQC7CBOTRSH4W4AZZ5PYNORQRH6QA AuctionID:1}
    auctionFixture.go:922: Made and posted a deposit with bid when lastRound was 14
    auctionErrors_test.go:344: MakeAndPostBidAndDeposit() returned transaction id M5U5KWSPUIGU2QOPWAOJP4N5WSFKY6EDPB7DJW3XYTW5ZO2Z55VQ
    auctionFixture.go:922: Made and posted a deposit with bid when lastRound was 14
    auctionErrors_test.go:344: MakeAndPostBidAndDeposit() returned transaction id RCYLDA67WLCFSDYUJC5MKNTEPSLRZSFSXCVLZDNSMDYT6MF5SAWA
    auctionFixture.go:922: Made and posted a deposit with bid when lastRound was 14
    auctionErrors_test.go:344: MakeAndPostBidAndDeposit() returned transaction id DYYU46SK3DB3CVZAVGTXOBNH3CTDN4CIRRCLDIJN47CMS4C2DMCQ
    auctionFixture.go:922: Made and posted a deposit with bid when lastRound was 14
    auctionErrors_test.go:344: MakeAndPostBidAndDeposit() returned transaction id G2QCXXLU5LMUETZRSCNJOKKAKK3GRTWEYY6BPUQS2CNSWNS5ZHUQ
    auctionFixture.go:922: Made and posted a deposit with bid when lastRound was 14
    auctionErrors_test.go:344: MakeAndPostBidAndDeposit() returned transaction id N3D43A4IBAZPPULBQNCXGCYH6CVOEGXV2QVSOB4QOOPNF2WF2O5Q
    auctionFixture.go:922: Made and posted a deposit with bid when lastRound was 14
    auctionErrors_test.go:344: MakeAndPostBidAndDeposit() returned transaction id WDZPWLMFTU7QARCFLK4D26TP7CZGCEI3SVGF4MJR6AAU35NTL2IA
    auctionFixture.go:922: Made and posted a deposit with bid when lastRound was 14
    auctionErrors_test.go:344: MakeAndPostBidAndDeposit() returned transaction id 6DFYHIFGYL7PVRWMUEGP2SDDGYVD6E2TZG6NWDI72NRBYOY2KX7A
    auctionFixture.go:922: Made and posted a deposit with bid when lastRound was 14
    auctionErrors_test.go:344: MakeAndPostBidAndDeposit() returned transaction id 3V5BSTC3EH2SJETJ5ZROXWCC7KI7VSJOKH62EXBIOEMQIKZTGNRA
    auctionFixture.go:922: Made and posted a deposit with bid when lastRound was 14
    auctionErrors_test.go:344: MakeAndPostBidAndDeposit() returned transaction id HK45MBSGLGQBRPLGZLBSGAYOCLZE5JOXNVFAC5TWFZQY5N3AUXYQ
    auctionFixture.go:922: Made and posted a deposit with bid when lastRound was 14
    auctionErrors_test.go:344: MakeAndPostBidAndDeposit() returned transaction id CEQNUK33G6MRMUEUIUWSVMVDOWD4QY624J2BLWLXGEMTETMBUK2A
    auctionFixture.go:922: Made and posted a deposit with bid when lastRound was 14
    auctionErrors_test.go:344: MakeAndPostBidAndDeposit() returned transaction id 4TZ6UODLV4SYJEZZMOWIOXOW26NNJQQNHK6GQWAGDNUM32B55RHA
    auctionFixture.go:922: Made and posted a deposit with bid when lastRound was 14
    auctionErrors_test.go:344: MakeAndPostBidAndDeposit() returned transaction id XXXDBWF4ZBMJNTLLVBOLHZG32KULFFTSQ4OSQ6UVFR2BOUVN25AQ
    auctionFixture.go:922: Made and posted a deposit with bid when lastRound was 14
    auctionErrors_test.go:344: MakeAndPostBidAndDeposit() returned transaction id PQVEXHD32BKMWH4MAXKMOEBWO3BO3FCXJ5C4ION7HOULECFVJHTQ
    auctionFixture.go:922: Made and posted a deposit with bid when lastRound was 14
    auctionErrors_test.go:344: MakeAndPostBidAndDeposit() returned transaction id 5UVZGPRTXUBFDQDX7ULA2JZAAK5MGTJHABPPXILOQ3OYMB2XGR7Q
    auctionFixture.go:922: Made and posted a deposit with bid when lastRound was 14
    auctionErrors_test.go:344: MakeAndPostBidAndDeposit() returned transaction id YQZSLJPYWA2AHMPBTLWVEP5BGHA6WJ7HALPMWPDGU3BAED72JNLA
    auctionFixture.go:922: Made and posted a deposit with bid when lastRound was 14
    auctionErrors_test.go:344: MakeAndPostBidAndDeposit() returned transaction id GFZ5AXH5E52IWFEC5W4OYEHQNPEWOMNHD7D5OOAUD7CDHELPDP5Q
    auctionFixture.go:922: Made and posted a deposit with bid when lastRound was 14
    auctionErrors_test.go:344: MakeAndPostBidAndDeposit() returned transaction id YTPD3FKJDVG4WWJOLE5W4ST5N6SMT24GPAKFMOPXOHFTAYVOCVBQ
    auctionFixture.go:922: Made and posted a deposit with bid when lastRound was 14
    auctionErrors_test.go:344: MakeAndPostBidAndDeposit() returned transaction id SUX4KEIWVF5NO4YLABBAXKXO5FADYMO2XN7KC6GCYBEUGGWPBUQA
    auctionFixture.go:922: Made and posted a deposit with bid when lastRound was 14
    auctionErrors_test.go:344: MakeAndPostBidAndDeposit() returned transaction id HTJCIJUE77EM4RPKRWCCZELBBXMF3GFWAOYIMKMK725RCIJB2N6Q
    auctionFixture.go:922: Made and posted a deposit with bid when lastRound was 14
    auctionErrors_test.go:344: MakeAndPostBidAndDeposit() returned transaction id J7SYVUDJQYDOGC4SYWY6TB4WHIMK3BYMTWCI7E5UM3HBFZBRUYLQ
    auctionFixture.go:922: Made and posted a deposit with bid when lastRound was 14
    auctionErrors_test.go:344: MakeAndPostBidAndDeposit() returned transaction id U3427JQ72U7QCQOTB37QZR6KFSIISXSGCLKAUOU3BFBDXXQXMZDA
    auctionFixture.go:922: Made and posted a deposit with bid when lastRound was 14
    auctionErrors_test.go:344: MakeAndPostBidAndDeposit() returned transaction id O5U7OZAMZF4O4P3MUMNA7Z3Q2KWNWEHCKP7GKPSYM6BXBMZOISLA
    auctionFixture.go:922: Made and posted a deposit with bid when lastRound was 14
    auctionErrors_test.go:344: MakeAndPostBidAndDeposit() returned transaction id AKFQER742ZOVILN6CUEKGM2BVOYNLSXNLMBR2B5G4F3SCQFTCT6A
    auctionFixture.go:922: Made and posted a deposit with bid when lastRound was 14
    auctionErrors_test.go:344: MakeAndPostBidAndDeposit() returned transaction id J5EXWXTPQD3QTJF2VIVG4T6E6G6QE2QGBQYCT4NQMLBYYILQFROQ
    auctionFixture.go:922: Made and posted a deposit with bid when lastRound was 14
    auctionErrors_test.go:344: MakeAndPostBidAndDeposit() returned transaction id 5VHSUOXKLRC2WTGAUBMTRU6NP24L6VLMI22OJGRCUZIFFTIMMI5A
    auctionFixture.go:922: Made and posted a deposit with bid when lastRound was 14
    auctionErrors_test.go:344: MakeAndPostBidAndDeposit() returned transaction id 5AD6RKY3B62DT4GLRHZLO6JTUQSB3FEAMMTACJL2GHUZMBT2L6PA
    auctionFixture.go:922: Made and posted a deposit with bid when lastRound was 14
    auctionErrors_test.go:344: MakeAndPostBidAndDeposit() returned transaction id LLWPKLKEHS6FAAPATA5TBEULY2I5A74PFJMUN7DL6F5RGFRCZKWQ
    auctionFixture.go:922: Made and posted a deposit with bid when lastRound was 14
    auctionErrors_test.go:344: MakeAndPostBidAndDeposit() returned transaction id 5QIUMIF4WXOTF6DRXQNVN33HYIAFBEE5ZANP6375OQZGL4JKWCTA
    auctionFixture.go:922: Made and posted a deposit with bid when lastRound was 15
    auctionErrors_test.go:344: MakeAndPostBidAndDeposit() returned transaction id V44UB7D3BK7H4LVJZPWVLNCSG7MSRZIUDVH3Z4GNLQU2CSYJJU3A
    auctionFixture.go:922: Made and posted a deposit with bid when lastRound was 15
    auctionErrors_test.go:344: MakeAndPostBidAndDeposit() returned transaction id 6GFHP4KA5C62YRYTET7DFVRG37XMNA6HNKQ3JK34AFMFCUD7EFPQ
    auctionFixture.go:922: Made and posted a deposit with bid when lastRound was 15
    auctionErrors_test.go:344: MakeAndPostBidAndDeposit() returned transaction id 6645U6B3FJ2UYI7PBRWICWAQYBUBNJKTI3UAPLIFXA232FXIGBSA
    auctionFixture.go:922: Made and posted a deposit with bid when lastRound was 15
    auctionErrors_test.go:344: MakeAndPostBidAndDeposit() returned transaction id PJWF75KQRBFZJDLE4MHADQDEWXHNKKTBHWSFUC6G2Y7MXCCCKG2Q
    auctionFixture.go:922: Made and posted a deposit with bid when lastRound was 15
    auctionErrors_test.go:344: MakeAndPostBidAndDeposit() returned transaction id V4VN3YLHM5WDVPHAMWQ4W65DQDT374TSAVDU45I3YG26UYN4F74Q
    auctionFixture.go:922: Made and posted a deposit with bid when lastRound was 15
    auctionErrors_test.go:344: MakeAndPostBidAndDeposit() returned transaction id 5KFESA56LZ4JEWMIKNLFLIV2BHLNUQQXG7YXOMALWLHRXMN3QK2Q
    auctionFixture.go:922: Made and posted a deposit with bid when lastRound was 15
    auctionErrors_test.go:344: MakeAndPostBidAndDeposit() returned transaction id 7VLF5DENXGY6MDCCMI7LBWYFS7AA7TNG7WZ7WECFHJEJ6Y776OUA
    auctionFixture.go:922: Made and posted a deposit with bid when lastRound was 15
    auctionErrors_test.go:344: MakeAndPostBidAndDeposit() returned transaction id 7IKCNQYTIGTSOOTVOXSKJQNZ7AAO7KRO7H6YXXL7FJWZWOFV3ACQ
    auctionFixture.go:922: Made and posted a deposit with bid when lastRound was 15
    auctionErrors_test.go:344: MakeAndPostBidAndDeposit() returned transaction id BAYOALYUIE27AAK3EDQC5XL7KBYNS3UM7N3IWHB3DPTKVTOF6NIA
    auctionFixture.go:922: Made and posted a deposit with bid when lastRound was 15
    auctionErrors_test.go:344: MakeAndPostBidAndDeposit() returned transaction id EOSL356JER7OTH7PWFD7A7GRI43ZBVXF26ZT5XCIIJZ65YZUX3HQ
    auctionFixture.go:922: Made and posted a deposit with bid when lastRound was 15
    auctionErrors_test.go:344: MakeAndPostBidAndDeposit() returned transaction id GFTLTVQREE6XNN3JJP7MHUEMRKD72HOX5EMIJQYGDHT5OFVO3UUQ
    auctionFixture.go:922: Made and posted a deposit with bid when lastRound was 15
    auctionErrors_test.go:344: MakeAndPostBidAndDeposit() returned transaction id TUVYF256XSSVCLPRQJ3YBUIX2QMNW2GVS4NMKXECGDEWRWSAD3FA
    auctionFixture.go:922: Made and posted a deposit with bid when lastRound was 15
    auctionErrors_test.go:344: MakeAndPostBidAndDeposit() returned transaction id 7ID45TWQLXQSGDDMWTDME6HJCGO4LIEYQWCURVUUUYJ3E6YV4RPA
    auctionFixture.go:922: Made and posted a deposit with bid when lastRound was 15
    auctionErrors_test.go:344: MakeAndPostBidAndDeposit() returned transaction id OZSHBJ4PY57MIREFSPFRBP75DO3K43N4M46AF3OWPVYBNVEZ6RDQ
    auctionFixture.go:922: Made and posted a deposit with bid when lastRound was 15
    auctionErrors_test.go:344: MakeAndPostBidAndDeposit() returned transaction id O6RIQMX7BZC4ZWEFNJO3WJ34BB2OFVSMARPFNQU34KCPPUXX7VKQ
    auctionFixture.go:922: Made and posted a deposit with bid when lastRound was 15
    auctionErrors_test.go:344: MakeAndPostBidAndDeposit() returned transaction id FI3RGPEHX2ZDF7HQMDK24SQU2LPNUTHWYZRT4PKFM6GPMIWTOW3Q
    auctionFixture.go:922: Made and posted a deposit with bid when lastRound was 15
    auctionErrors_test.go:344: MakeAndPostBidAndDeposit() returned transaction id 2XT3REKYUXQIHEN4ZZ6MGT2OHWFITUQWTW7NTFSXMO53N5MVPMKA
    auctionFixture.go:922: Made and posted a deposit with bid when lastRound was 15
    auctionErrors_test.go:344: MakeAndPostBidAndDeposit() returned transaction id HYWITFHUVZB4Q5VJFL44EZONR24HXJ7ARP46IVVJKQS2PORGDANQ
    auctionFixture.go:922: Made and posted a deposit with bid when lastRound was 15
    auctionErrors_test.go:344: MakeAndPostBidAndDeposit() returned transaction id IEJT44SM3WIUIYWZJO3SNE77VQZIP3V5ZMTNFOCLCHC4KKPWVEOQ
    auctionFixture.go:922: Made and posted a deposit with bid when lastRound was 15
    auctionErrors_test.go:344: MakeAndPostBidAndDeposit() returned transaction id FWTXTR6HPAHRKCY2P7E6U4MTRDXUEGUM4UN7YRBPOPYOAP25ADFA
    auctionFixture.go:922: Made and posted a deposit with bid when lastRound was 15
    auctionErrors_test.go:344: MakeAndPostBidAndDeposit() returned transaction id NRLD2VADDGC2W4LXQ3SF5XXPGOB4GKGP35YLERIY4I4D5O63VOPA
    auctionFixture.go:922: Made and posted a deposit with bid when lastRound was 15
    auctionErrors_test.go:344: MakeAndPostBidAndDeposit() returned transaction id RCAXMEBJTKUBUPS4WZ3EVTV6QN2QEETICKGC6DXPFHXW4NGHYLRQ
    auctionFixture.go:922: Made and posted a deposit with bid when lastRound was 15
    auctionErrors_test.go:344: MakeAndPostBidAndDeposit() returned transaction id GEYUPRVXAUEYMSNLITKBJDYWAUJZUDNUAEJ36OF2HWQLZDWKX6KQ
    auctionFixture.go:922: Made and posted a deposit with bid when lastRound was 15
    auctionErrors_test.go:344: MakeAndPostBidAndDeposit() returned transaction id XIFGFRC2JAACHOLSR4BTF3OWOXW7RBBF7OGWO23OG53DXR4PQXCA
    auctionFixture.go:922: Made and posted a deposit with bid when lastRound was 15
    auctionErrors_test.go:344: MakeAndPostBidAndDeposit() returned transaction id BJA5OWO6UAA4PLSB5URD7B7BDVRUU2CIJJ4KYJK3MNDGBJZEIK7Q
    auctionFixture.go:922: Made and posted a deposit with bid when lastRound was 15
    auctionErrors_test.go:344: MakeAndPostBidAndDeposit() returned transaction id R5DNKE22REJWAQW6GEHJ5UM3E24WZX73Y5M3NDYS4L4FLDF5SP4Q
    auctionFixture.go:922: Made and posted a deposit with bid when lastRound was 15
    auctionErrors_test.go:344: MakeAndPostBidAndDeposit() returned transaction id D3NLG2SC3SJZEGOG3WKT6SPRQAWVKPNPDGXVIHEBLHNFK7VRZ3JA
    auctionFixture.go:922: Made and posted a deposit with bid when lastRound was 15
    auctionErrors_test.go:344: MakeAndPostBidAndDeposit() returned transaction id BTO7AIY3LMVM43HWIRQVOVIKH4AD6FIMP6GAF2VGYGZKC2FH6X2A
    auctionFixture.go:922: Made and posted a deposit with bid when lastRound was 15
    auctionErrors_test.go:344: MakeAndPostBidAndDeposit() returned transaction id WTKZYH43LSLCJ4UXX724WM5JPQHL2QPA3GADCX7GFL2GTGABB7EA
    auctionFixture.go:922: Made and posted a deposit with bid when lastRound was 15
    auctionErrors_test.go:344: MakeAndPostBidAndDeposit() returned transaction id XJVWAJDIMETPK4N4KSKBXG4NJV6DZFVXNU62QNADR7QP3YALZ5DQ
    auctionFixture.go:922: Made and posted a deposit with bid when lastRound was 15
    auctionErrors_test.go:344: MakeAndPostBidAndDeposit() returned transaction id OKSN4QHD2VXD7TZQLSBBZDKZ5CKKRRNHADBTSQYEWWKRNPRE3D4Q
    auctionFixture.go:922: Made and posted a deposit with bid when lastRound was 15
    auctionErrors_test.go:344: MakeAndPostBidAndDeposit() returned transaction id UFFHAPUXTUAJHWO7RVMTCP2DYTG5IGQ7P7THCCRJFUNYBF4A3RFA
    auctionFixture.go:922: Made and posted a deposit with bid when lastRound was 15
    auctionErrors_test.go:344: MakeAndPostBidAndDeposit() returned transaction id O5PX3HXMYGA76LGLT5NRRDV6DARRWKWWOINIELWEV5VOVQUAIBVA
    auctionFixture.go:922: Made and posted a deposit with bid when lastRound was 15
    auctionErrors_test.go:344: MakeAndPostBidAndDeposit() returned transaction id KQKBBYXS4JXT4HSKXTNBGBZGQK5IP63JMPK2YMNWKGJ3MLX3BHWQ
    auctionFixture.go:922: Made and posted a deposit with bid when lastRound was 15
    auctionErrors_test.go:344: MakeAndPostBidAndDeposit() returned transaction id 6VPGLIFH3W5U47FK43CTNK5SLPEEFHWFTCWONQ6WQD2LLOD4TD5A
    auctionFixture.go:922: Made and posted a deposit with bid when lastRound was 15
    auctionErrors_test.go:344: MakeAndPostBidAndDeposit() returned transaction id DWCR7MIPMMPYJV4DFYRC6VGR6X6GGN5IM5BZPFN5BUQI2SJKYVKA
    auctionFixture.go:922: Made and posted a deposit with bid when lastRound was 15
    auctionErrors_test.go:344: MakeAndPostBidAndDeposit() returned transaction id UU3OER4NDZOXWGNVHNWLFGQKA2YEO6ZM6CQZ7QW3YNF6M6Z646BA
    auctionFixture.go:922: Made and posted a deposit with bid when lastRound was 15
    auctionErrors_test.go:344: MakeAndPostBidAndDeposit() returned transaction id MX2OYYUASTSEG46YVOBXRWFDMZNSAPCGGFDCR4MUONEOUDKEPSAA
    auctionFixture.go:922: Made and posted a deposit with bid when lastRound was 15
    auctionErrors_test.go:344: MakeAndPostBidAndDeposit() returned transaction id Z6C3BXEKMI4TLBARI54QDQ3J7OKRJNH7S5ARV4BKPML4S2PC7RLA
    auctionFixture.go:922: Made and posted a deposit with bid when lastRound was 15
    auctionErrors_test.go:344: MakeAndPostBidAndDeposit() returned transaction id ZDBPHW3UJBEZQLVXSXWEW24SODV6CUTDEIRUA6RD4PMHYFKHP7LQ
    auctionFixture.go:922: Made and posted a deposit with bid when lastRound was 15
    auctionErrors_test.go:344: MakeAndPostBidAndDeposit() returned transaction id BXFJRRXVREG2UWBCDBBWJUPLUDWEJRPHOPK6JDL6VDESWCLI34UA
    auctionFixture.go:922: Made and posted a deposit with bid when lastRound was 15
    auctionErrors_test.go:344: MakeAndPostBidAndDeposit() returned transaction id DYMTADCBR6TXXP5FW73Y4PJDBJHV2HWOOLATSSTX4XT3AZPU623A
    auctionFixture.go:922: Made and posted a deposit with bid when lastRound was 15
    auctionErrors_test.go:344: MakeAndPostBidAndDeposit() returned transaction id 5N47725B5MQEFHV5JWW3W3ZMPWQMCVEQUZSZNOPSAKKZN72C5PHQ
    auctionFixture.go:922: Made and posted a deposit with bid when lastRound was 15
    auctionErrors_test.go:344: MakeAndPostBidAndDeposit() returned transaction id NGXZC3DS7BFJEC6BEREVAPPJV74ANFQJSIAD4GZV3PIGII7RGSBQ
    auctionFixture.go:922: Made and posted a deposit with bid when lastRound was 15
    auctionErrors_test.go:344: MakeAndPostBidAndDeposit() returned transaction id PVHR5VPVXNQE4C3UPUKM7L5WGUTX7IP2ORIIYARQR5VDD6OMKGGQ
    auctionFixture.go:922: Made and posted a deposit with bid when lastRound was 15
    auctionErrors_test.go:344: MakeAndPostBidAndDeposit() returned transaction id VPIJ7QN3ESSLDSCA42QJKQTUAZJMRJIH3CGWX4BEPF2PHRI6IFUQ
    auctionFixture.go:922: Made and posted a deposit with bid when lastRound was 15
    auctionErrors_test.go:344: MakeAndPostBidAndDeposit() returned transaction id 5SKCKT6QSGQCATMQCEEVYERIACJU2EFAPYG5T5SUJH74NLINIRTA
    auctionFixture.go:922: Made and posted a deposit with bid when lastRound was 15
    auctionErrors_test.go:344: MakeAndPostBidAndDeposit() returned transaction id TZXUXK2WEJYVU3D6NDZNMEUQ35V7KJHGCUF5WXPWSTPFYQD225XQ
    auctionFixture.go:922: Made and posted a deposit with bid when lastRound was 15
    auctionErrors_test.go:344: MakeAndPostBidAndDeposit() returned transaction id REKY27LA455XNIIPKQDANWUT4RNVQIUSQNV3EUXJW2XUC3LQ2FJQ
    auctionFixture.go:922: Made and posted a deposit with bid when lastRound was 15
    auctionErrors_test.go:344: MakeAndPostBidAndDeposit() returned transaction id P5ROGC3J65BNXT2MO32WM67VLF4WKHDV7Q2Q7AK7ZIPZTPDDS2FQ
    auctionFixture.go:922: Made and posted a deposit with bid when lastRound was 15
    auctionErrors_test.go:344: MakeAndPostBidAndDeposit() returned transaction id STHJFANVN3SJVWCDUYL77TVNGN4RADP44PSTL5MCOUZGOUCKTSAA
    auctionFixture.go:922: Made and posted a deposit with bid when lastRound was 15
    auctionErrors_test.go:344: MakeAndPostBidAndDeposit() returned transaction id 333DMXQMQCQHZZ3HTI5YIWJT4ZKNG5HTKPNUCENKXVTYEHXY45BQ
    auctionFixture.go:922: Made and posted a deposit with bid when lastRound was 15
    auctionErrors_test.go:344: MakeAndPostBidAndDeposit() returned transaction id 4DFWARFKYJWDKTGP234N5A44T24T3Q6OBDQBD55TJ4QI4T7PO3VQ

**Comment by Vervious** [comment]
Happened again
[auction10bids.log](https://github.com/algorand/go-algorand/files/3510771/auction10bids.log)
