### ISSUE TITLE
Multi-Region Support - Geolocating DNS

### ISSUE THREAD

**Issue by bricerisingalgorand** [algorand/go-algorand#1988]
## Summary
Automate creation of Geo routing in cloudflare.

https://support.cloudflare.com/hc/en-us/articles/200168236-Configuring-Cloudflare-IP-Geolocation

## Scope/Requirements
* This should have a way to find all loadbalancers for mobile service deployments and register them under one dns entry that resolves differently based on the region they are based in

## Urgency/Relative Priority
This needs to be done soon to help us support multiple regions, which will make our api's faster and more reliable for users

## Notes
Cloudflare Traffic Steering
https://developers.cloudflare.com/load-balancing/understand-basics/traffic-steering

**Comment by egieseke** [comment]
https://developers.cloudflare.com/load-balancing/understand-basics/traffic-steering

**Comment by egieseke** [comment]
![Geo based load balancing Component Diagram](https://user-images.githubusercontent.com/9044640/115909512-9e3fbb00-a439-11eb-98c9-96ebd146e3a1.png)

**Comment by egieseke** [comment]
Load balancer is working https://dispenser-load-balancer.algodev.network/

**Comment by algobarb** [comment]
I know we tested the dispenser, but isn't the story to geo-locate mobile service deployments?
The dispenser code should also be moved to dispenser right and replicated similarly for mobile.

**Comment by egieseke** [comment]
This story was to make sure that we could provision a geo load balancer for the mobile services.  Since the mobile indexer is not yet provisioned in Korea, I setup a second dispenser in korea to test and validate that we could distribute load based on the nearest dispenser or the one with the lowest latency.  Once the mobile indexer is provisioned in Korea, we should be able to repurpose the load balancer terraform file for the moible services.

**Comment by algobarb** [comment]
> This story was to make sure that we could provision a geo load balancer for the mobile services. Since the mobile indexer is not yet provisioned in Korea, I setup a second dispenser in korea to test and validate that we could distribute load based on the nearest dispenser or the one with the lowest latency. Once the mobile indexer is provisioned in Korea, we should be able to repurpose the load balancer terraform file for the moible services.

Yup I misunderstood the scope earlier. I thought we had to set up the geoloadbalancer for the existing US indexer as part of this even if the korea origin isn't up yet.
