### ISSUE TITLE
algod crashes - panic: assignment to entry in nil map

### ISSUE THREAD

**Issue by biocodz** [algorand/go-algorand#1999]
## Summary

The process ran OK for a few weeks, and then crashed all of a sudden.
Running algod built from master. 
```
git branch
* master

git log --name-status
----------------
commit ec505a8c8b78abb7e2b486faa541d07a6818be35 (HEAD -> master, origin/master, origin/HEAD)
Author: egieseke <eric_gieseke@yahoo.com>
Date:   Thu Mar 4 09:53:22 2021 -0500

    Integrate package signing into CI pipeline (#1931)

M       test/muleCI/mule.yaml
----------------
```

```
uname -a
Linux pi-ubuntu 5.8.0-1016-raspi #19-Ubuntu SMP PREEMPT Tue Feb 9 20:12:43 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux
```

```
lsb_release -a
Distributor ID: Ubuntu
Description:    Ubuntu 20.10
Release:        20.10
Codename:       groovy
```
```
df -h
Filesystem      Size  Used Avail Use% Mounted on
tmpfs           776M  4.4M  772M   1% /run
/dev/sda2       235G   15G  211G   7% /
...
```

```
goal node start -d ~/a01_data/algorand/node
Algorand node successfully started!
```

`less ~/a01_data/algorand/node/algod-err.log`:
```
panic: assignment to entry in nil map

goroutine 2860 [running]:
github.com/algorand/go-algorand/ledger.applyStorageDelta(0x0, 0x135851, 0x2aebf, 0x319, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        github.com/algorand/go-algorand/ledger/appcow.go:623 +0x76c
github.com/algorand/go-algorand/ledger.(*roundCowState).deltas(0x40028ccf00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        github.com/algorand/go-algorand/ledger/cow.go:97 +0x100
github.com/algorand/go-algorand/ledger.eval(0x146a898, 0x40000340a0, 0x14771f8, 0x40002c6900, 0xc1b201, 0x2a721eea415f1c49, 0xa86029a61132f477, 0xf6c7869bea2fb991, 0x556f08f427f65c32, 0xe217a814124f0d76, ...)
        github.com/algorand/go-algorand/ledger/eval.go:1218 +0x2e4
github.com/algorand/go-algorand/ledger.(*Ledger).AddBlock(0x40002c6900, 0xc1b201, 0x2a721eea415f1c49, 0xa86029a61132f477, 0xf6c7869bea2fb991, 0x556f08f427f65c32, 0xe217a814124f0d76, 0x2ec9c868c67615e7, 0x230f03bb409ba0c, 0xa801d15b9213cf52, ...)
        github.com/algorand/go-algorand/ledger/ledger.go:548 +0xac
github.com/algorand/go-algorand/catchup.(*Service).fetchAndWrite(0x4000150e00, 0x146aa58, 0x4002fb6600, 0xc1b201, 0x40001cc380, 0x40001cc310, 0x1)
        github.com/algorand/go-algorand/catchup/service.go:278 +0x738
github.com/algorand/go-algorand/catchup.(*Service).pipelineCallback.func1(0x4002fb6660)
        github.com/algorand/go-algorand/catchup/service.go:309 +0x60
github.com/algorand/go-algorand/catchup.(*Service).pipelinedFetch.func2(0x400515ea80, 0x4002fb6660, 0x4000146380)
        github.com/algorand/go-algorand/catchup/service.go:354 +0x5c
created by github.com/algorand/go-algorand/catchup.(*Service).pipelinedFetch
        github.com/algorand/go-algorand/catchup/service.go:351 +0x17c
```

**Comment by tsachiherman** [comment]
@biocodz Thanks for letting us know about the issue. Two followup questions for you : 
1. which network was your node connected to ? ( i.e. betanet, testnet or mainnet )
2. which catchpoint have you attempted to catch up to ?

I hope that with the above information, we would also be able to reproduce the exact issue you've been seeing.

**Comment by biocodz** [comment]
@tsachiherman Network is the mainnet. No idea about the catchpoint. I run algod for couple months already, so the data was synced long ago. One day found the algod stopped and refusing to run.

**Comment by tsachiherman** [comment]
@biocodz thanks for letting me know. I was able to reproduce a use case that *looked* exactly like you described, and I'm pretty confident that we'll be able to address that. In case you might still have it on your terminal history, this piece of information could help us to verify that we're fixing the very same issue you were facing.
i.e.
```bash
history | grep "catchup"
```

**Comment by biocodz** [comment]
It wouldn't be in the history as I Never used such a command. The commands I ever used are
```
goal node start -d $DATA_DIR/algorand/node
goal node status -d $DATA_DIR/algorand/node -w 5000
```
First time I started the node it took a few days to sync. I verified the sync against the `algoexplorer.io`. And it was in sync for quite awhile.
I had no time to dig/debug into this problem myself, so the program didn't run since I published this issue. The state of the data, configuration, and logs is intact. Let me know if you need more info.

**Comment by biocodz** [comment]
rebuild the master today, and so far runs OK
```
git log   # ->  commit db1c0659d8f33d6f4451578886d17cfd0ba4ae02

goal node status -d ~/a01_data/algorand/node -w 5000
   Last committed block: 12699902
   Time since last block: 0.1s
   Sync Time: 437.5s
   Last consensus protocol: https://github.com/algorandfoundation/specs/tree/3a83c4c743f8b17adfd73944b4319c25722a6782
   Next consensus protocol: https://github.com/algorandfoundation/specs/tree/3a83c4c743f8b17adfd73944b4319c25722a6782
   Round for next consensus protocol: 12699903
   Next consensus protocol supported: true
   Last Catchpoint:
   Genesis ID: mainnet-v1.0
``

**Comment by tsachiherman** [comment]
> rebuild the master today, and so far runs OK
> 
> ```
> git log   # ->  commit db1c0659d8f33d6f4451578886d17cfd0ba4ae02
> 
> goal node status -d ~/a01_data/algorand/node -w 5000
>    Last committed block: 12699902
>    Time since last block: 0.1s
>    Sync Time: 437.5s
>    Last consensus protocol: https://github.com/algorandfoundation/specs/tree/3a83c4c743f8b17adfd73944b4319c25722a6782
>    Next consensus protocol: https://github.com/algorandfoundation/specs/tree/3a83c4c743f8b17adfd73944b4319c25722a6782
>    Round for next consensus protocol: 12699903
>    Next consensus protocol supported: true
>    Last Catchpoint:
>    Genesis ID: mainnet-v1.0
> ```

glad to hear. I wasn't able to reproduce it against mainnet, but I'm happy to hear that the fix works for you.
