### ISSUE TITLE
[Investigate] Swagger generation issue with binary

### ISSUE THREAD

**Issue by ian-algorand** [algorand/go-algorand#200]
Summary: The typestring format binary annotation for swagger might have problems with the swagger generated go-client.

Requirements: If there's a problem, we need to file a new ticket with the fix. This is just the investigation task.

--------------------------------------------------------------------------------------------
Jira conversation:
Jason Weathersby added a comment - 05/Jun/19 4:05 PM
When generating go client with swagger file using swagger generate client -f swagger.json

This field 
"noteb64":

{ "description": "Note is a free form data", "type": "string", "format": "binary", "x-go-name": "Note" }
,
generates this in the client transaction.go file

// Note is a free form data
// Format: binary
Note io.ReadCloser `json:"noteb64,omitempty"`

This will not compile as that is an interface. In the go SDK this is modified to Bytes which is defined as []byte

Benjamin Chan added a comment - 06/Jun/19 4:34 PM
How do you mean by that it won't compile?
`io.ReadCloser` is a standard abstraction for moving bytes. Clients can just do `byteSlice, _ := ioutil.ReadAll(txn.Note)`...

`"type": "string", "format": "binary"` is absolutely the correct swagger content to generate for binary data; I beleive if we use "format": "byte" instead, all generated methods give us strings (base64 encoded).

Jason Weathersby added a comment - 06/Jun/19 4:56 PM
I mean it want run, sorry. Go will compile it but it wont run. It fails unmarshalling the response from the Rest API.

Benjamin Chan added a comment - 06/Jun/19 5:03 PM
oh i see. worth looking into, then!

**Comment by Vervious** [comment]
@JasonWeathersby I updated all the string formats to `byte` recently as part of nickolai's `gomod` PR. Can you check if you are still seeing the problem? Thanks

**Comment by ian-algorand** [comment]
@JasonWeathersby is this still an issue? @rotemh is unaware of any problems currently. I want to close this if we can.
