### ISSUE TITLE
[COMPLAINT] Who is Responsible for the Overall Architecture and the Developer-Experience?

### ISSUE THREAD

**Issue by lazaridiscom** [algorand/go-algorand#207]
I raised the following question:

> May I ask who's the person responsible for the overall architecture and the developer-experience?

from: https://github.com/algorand/go-algorand/issues/186#issuecomment-516155644

Which was ignored.

I could not extract this information from the team-overview:

https://www.algorand.com/who-we-are/our-team
So, again my question:

**Who is Responsible for the Overall Architecture and the Developer-Experience?**

## Context

I am asking in context of a complaint I like to make (e.g.: complaining about the behavior of the authority-holding contributors in the main Algorand repository "go-algorand").

https://github.com/algorand/go-algorand/search?q=commenter%3Alazaridiscom&type=Issues

Remember: Algorand claims to be an open project. So it is essential that this basic transparency is provided.

## Product-Manager

Out of curiosity (again, I was not able to extract this information from https://www.algorand.com/who-we-are/our-team) :

**Who is the Algorand's Product-Manager?**

**Comment by Priegle** [comment]
Hey lazaridiscom, I'm the head of product here at Algorand.  Our full team reads and responds to issues as appropriate.  

You suggestion in the previous issues was heard and responded to reasonably.  Further breaking out the agreement package (and the node software in general), is in fact a goal for the project.  The specific example you gave is not something we think is the best route forward at this time.

In general, we would like to have technical issues represented in the Github issues section, not general questions so I am closing this issue.

**Comment by lazaridiscom** [comment]
@Priegle , @ian-algorand , to avoid opening anther issue:

where do I file an issue (this time I want to include a complaint about the "Head of Product", which in my opinion processed this issue here in a sloppy manner, leaving the core-issues at hand once again unprocessed, which in the end is at the cost of the Algorand-Userbase).

So? Where do I file my complaint?

**Comment by Priegle** [comment]
Consider it filed!
