### ISSUE TITLE
Allow nodes to be relays but not archival

### ISSUE THREAD

**Issue by algoradam** [algorand/go-algorand#21]
Right now `mergeConfigFromFile` in `config/config.go` forces the Archival flag to true -- regardless of what's in the config file -- if the node has a listening address (i.e., acts as a relay). This makes it impossible to configure a non-archival node to listen for incoming connections.

We should instead have relays *default* to being archival but allow overriding this in the config file. (Alternatively, make the options completely independent)

**Comment by Vervious** [comment]
This may be helpful for reducing load on relays. There is, however, also an argument that theoretical liveness depends on peers (read: relays) having blocks for complete catchup. Making them independent might motivate a more nuanced liveness argument.

**Comment by ian-algorand** [comment]
Not going to be worked on in the foreseeable future. Will re-open if the need arises.
