### ISSUE TITLE
ARM APT Repo Support 

### ISSUE THREAD

**Issue by Blackglade** [algorand/go-algorand#2117]
## Is your feature request related to a problem? Please describe.

I'd like to be able to use algod on an ARM architecture. I followed the instructions before running into this:

```
N: Skipping acquire of configured file 'main/binary-arm64/Packages' as repository 'https://releases.algorand.com/deb stable InRelease' doesn't support architecture 'arm64'
```
on apt-get update. Would like this to be supported. 

## Describe the solution you'd like.

Support for ARM64

## Acceptance criteria
Test the deploy to ensure that it works properly 

## Dependencies
This will involve editing some the release scripts -- package deploy. 

scripts/release/mule/deploy/deb/deploy.sh
FILENAME_SUFFIX="${CHANNEL}_linux-amd64_${VERSION}.deb"

## Urgency
We need to eventually have support for ARM but nothing urgent. Something we should definitely take care of though.

**Comment by brianolson** [comment]
Oops, it looks like it's not in the repo for automated download and install from `apt`, but there is an arm64 linux build
https://releases.algorand.com/

**Comment by brianolson** [comment]
Probably this very ticket. Which ARM Linux distro? I see that it's looking for a deb

**Comment by Blackglade** [comment]
Debian 10 Buster

![Screen Shot 2021-04-30 at 3 18 29 PM](https://user-images.githubusercontent.com/6363077/116743764-656a8d80-a9c7-11eb-8f7a-06d85f2ede13.png)

**Comment by Blackglade** [comment]
Is there an update/timeline on when this might be added? Definitely prefer going through the apt-get install process vs. just manually pulling the package

**Comment by Blackglade** [comment]
Any update on this?

**Comment by audiomason** [comment]
I ran into this issue when trying to install the algorand package from the deb repo in a docker container on an Apple M1.

**Comment by onetechnical** [comment]
I believe this is now done.
