### ISSUE TITLE
simple generator for TEAL like ETH has

### ISSUE THREAD

**Issue by andrewarrow** [algorand/go-algorand#2142]
## Is your feature request related to a problem? Please describe.

Reading through [transactions/logic/README.md](https://github.com/algorand/go-algorand/blob/master/data/transactions/logic/README.md) and looking at the [examples](https://github.com/algorand/go-algorand/tree/master/tools/teal/templates) I don't see an example like:

![gui](https://user-images.githubusercontent.com/127054/117522892-9b30e880-af6a-11eb-8afc-20df8ac5a1fe.jpg)

I'm looking for an example like [erc20-generator/](https://vittominacori.github.io/erc20-generator/) with all these options for making a new currency on top of algorand like you can with ETH.

## Describe the solution you'd like.

A gui like above would be amazing, but just a README or new example file with how to do this (or explain why it's not possible.)

**Comment by barnjamin** [comment]
Certainly not as easy as a GUI but did you see https://developer.algorand.org/tutorials/create-dogcoin/? 

Also see the goal CLI command `goal asset create ...` here: https://github.com/algorand/go-algorand/blob/master/cmd/goal/asset.go#L58

**Comment by andrewarrow** [comment]
ah, thank u, just what I was looking for. I'll make the GUI now :)
