### ISSUE TITLE
Manager not able to configure ASA

### ISSUE THREAD

**Issue by barnjamin** [algorand/go-algorand#2160]
### Subject of the issue

Trying to reconfigure an ASA back to the creator but getting an error claiming it cant find the asset.

I believe its this line: https://github.com/algorand/go-algorand/blob/041e1f92d9c190bdc6d6c78b1dd04ef19b8ec03b/ledger/apply/asset.go#L62

It is using the creator instead of the manager. 

### Your environment
Sandbox release version

### Steps to reproduce

1. Create ASA
2. Reconfigure to be managed by another acct (in my case its a contract acct)
3. Attempt to reconfigure manager back to creator 

### Expected behaviour
It lets me

### Actual behaviour
It doesnt

**Comment by barnjamin** [comment]
![image](https://user-images.githubusercontent.com/520236/118833734-af8cb380-b88f-11eb-8ba9-5550f46f54e5.png)

**Comment by barnjamin** [comment]
if i change the `--manager` flag to the creator it doesnt complain but the sender is set to the creator when i think it should be the `34M...` address

**Comment by barnjamin** [comment]
Jason suggested I include the --creator flag with the creator and it works, though I'm not sure it _should_ be required? Leaving this open for now

**Comment by winder** [comment]
Could you include the specific commands which cause this problem?

**Comment by barnjamin** [comment]
Produces the error:
```
../sandbox goal asset config --assetid 18\
        --manager UHSN4BL44YPZPUUTL3DZ74K2UN6TCTIPJBAL7VRAZHZT4U4GLRJOJWU6PI \
        --new-manager  6EVZZTWUMODIXE7KX5UQ5WGQDQXLN6AQ5ELUUQHWBPDSRTD477ECUF5ABI \
        --new-freezer  6EVZZTWUMODIXE7KX5UQ5WGQDQXLN6AQ5ELUUQHWBPDSRTD477ECUF5ABI \
        --new-reserve  6EVZZTWUMODIXE7KX5UQ5WGQDQXLN6AQ5ELUUQHWBPDSRTD477ECUF5ABI \
        --new-clawback 6EVZZTWUMODIXE7KX5UQ5WGQDQXLN6AQ5ELUUQHWBPDSRTD477ECUF5ABI  \
        -o asa_cfg.txn
 ```
 
Succeeds and generates txn:
 ```
 ../sandbox goal asset config --assetid 18\
        --manager UHSN4BL44YPZPUUTL3DZ74K2UN6TCTIPJBAL7VRAZHZT4U4GLRJOJWU6PI \
        --creator 6EVZZTWUMODIXE7KX5UQ5WGQDQXLN6AQ5ELUUQHWBPDSRTD477ECUF5ABI \
        --new-manager  6EVZZTWUMODIXE7KX5UQ5WGQDQXLN6AQ5ELUUQHWBPDSRTD477ECUF5ABI \
        --new-freezer  6EVZZTWUMODIXE7KX5UQ5WGQDQXLN6AQ5ELUUQHWBPDSRTD477ECUF5ABI \
        --new-reserve  6EVZZTWUMODIXE7KX5UQ5WGQDQXLN6AQ5ELUUQHWBPDSRTD477ECUF5ABI \
        --new-clawback 6EVZZTWUMODIXE7KX5UQ5WGQDQXLN6AQ5ELUUQHWBPDSRTD477ECUF5ABI  \
        -o asa_cfg.txn
 ```

**Comment by winder** [comment]
And what is the error?

**Comment by barnjamin** [comment]
`Cannot construct transaction: asset ID 18 not found in account UHSN4BL44YPZPUUTL3DZ74K2UN6TCTIPJBAL7VRAZHZT4U4GLRJOJWU6PI`

**Comment by barnjamin** [comment]
I don't think this is a bug really, probably just need some mention in the docs and a check in the config command function that if the manager != creator, the creator is also a required flag
