### ISSUE TITLE
Add support for sending node log output to custom destinations

### ISSUE THREAD

**Issue by onetechnical** [algorand/go-algorand#2174]
## Summary

It would be useful to be able to customize the destination of node.log output, as well as potentially directing it to stdout. This would be especially useful for running in long lived containers. (You could, for example, tail the node.log file, but it would eventually either exhaust disk or stop reporting after log rotation.)

## Scope/Requirements

Add a config file option to specify a custom destination for node.log. (Default / undefined could preserve the old behavior.)

If this parameter is special, e.g. STDOUT, we should direct to stdout, and disable log rotation.

## Urgency/Relative Priority

Medium - anyone running in a container for extended periods would find this useful to generate log output continuously.

**Comment by brianolson** [comment]
This is a generalization of #1081  ?

**Comment by yaovi-a** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Algorand-Main-Workspace-5ea71fda6d554d53dda36f16/issues/algorand/go-algorand/2174?planning-poker) with ZenHub @algobarb @algojack @egieseke @onetechnical @bricerisingalgorand

**Comment by onetechnical** [comment]
Recent work to redirect logs has been implemented separately.
