### ISSUE TITLE
Formatted logs?

### ISSUE THREAD

**Issue by i-schuetz** [algorand/go-algorand#2194]
It would be nice to be able to read the node's logs in a formatted way, instead of the raw JSON.

carpenter seems to not display "normal" logs messages, like:

> {"file":"server.go","function":"github.com/algorand/go-algorand/daemon/algod.(*Server).Start","level":"info","line":159,"msg":"Successfully started an Algorand node.","time":"2021-05-26T13:12:01.612179+02:00"}

It only appears to show "Agreement" (?) messages. Filtering out agreement messages with `carpenter -file node.log -no-agree -cat`  leaves only this:

```
could not decode line from JSON: ++++++++++++++++++++++++++++++++++++++++
could not decode line from JSON: Logging Starting
could not decode line from JSON: Telemetry Disabled
could not decode line from JSON: ++++++++++++++++++++++++++++++++++++++++
```

**Comment by yaovi-a** [comment]
We prefer to keep the logs in JSON format for ingestion. Thanks.

**Comment by i-schuetz** [comment]
@yaovi-a clarifying that I didn't mean to change the format in the log file but to have a possibility to read them in a formatted way (e.g. using carpenter).
