### ISSUE TITLE
Fee Pooling SDK work (Go & Java)

### ISSUE THREAD

**Issue by jannotti** [algorand/go-algorand#2214]
Once #2173 is merged, SDKS will want to support creating transactions with a fee under mintxnfee, because other txns in the group will be paying.  The python sdk, and probably others, automatically increase the fee on your txn to the minimum, and/or they treat 0 as meaning "please fill in the suggested fee".  We'll need an interface that allows setting these low fees without the SDK "fixing" them.

Notes: 

- If using flat fee option and set it to 0, then accept.
- Confirm the encoded transaction does not contain a 0 fee field if the field is 0 (should just be missing)

**Comment by winder** [comment]
Yes, they all set the fee to `min(provided, 1000)`.

I believe all SDKs have a "FlatFee" option, maybe we can change its behavior to ignore the minimum value
