### ISSUE TITLE
opcode `opGetByte` and `opSetByte`

### ISSUE THREAD

**Issue by amityadav0** [algorand/go-algorand#2221]
### Subject of the issue
Index check for the set byte should have `>=`.

In `opGetByte`
https://github.com/algorand/go-algorand/blob/23bfcd799470618e59abbc6b0247357225ffb20f/data/transactions/logic/eval.go#L2454
we are checking for equal condition because the indexing assumed here starts from `0`.

but in case of `opSetByte`
https://github.com/algorand/go-algorand/blob/23bfcd799470618e59abbc6b0247357225ffb20f/data/transactions/logic/eval.go#L2471
This one should be same as `opGetByte`

Please correct me if i am not understanding it right.

**Comment by jannotti** [comment]
Thank you.  Addressing with #2236
