### ISSUE TITLE
Write logs to ‘tmpfs’ rather than local storage

### ISSUE THREAD

**Issue by bhmltn7** [algorand/go-algorand#2222]
### Subject of the issue

Performance impact is observed due to log messages written to '~/node/data/node.log' file.

### Your environment

* Software version: `2.6.0 stable`
* Operating System: Armbian 5.91
* Hardware: NanoPC T-4
* Storage: Samsung 970 EVO Plus M.2 NVMe SSD

### Steps to reproduce

1. Install node
2. Complete fast catchup
3. Monitor '~/node/data/node.log'
4. Collect performance data 
- Capture Disk IO 'iostat -x 1 30 | grep ${volumeName}'
- Capture CPU 'IO Wait' reported by 'top' 
5. Stop node
6. Create 'tmpfs':

mount -t tmpfs -o size=256m tmpfs ~/node/tmpfs; 
ln -s ~/node/tmpfs/node.log ~/node/data/node.log;

7. Start node
8. Collect performance data

### Expected behaviour

Moving 'node.log' from disk to memory based 'tmpfs' results in improved performance. 

Reduced Disk IO utilization and lower write speed 'wkB/s' for the volume are observed.

CPU statistics from 'top' output show lower 'IO Wait' value after the change.

Changing to 'tmpfs' by default will optimize performance and reduce storage IO operations.

### Actual behaviour

Performance impact is observed due to log messages written to '~/node/data/node.log' file.

At default log level the file size of 'node.log' increases by 75 mB/h.

**Comment by brianolson** [comment]
dup of #2174

**Comment by Priegle** [comment]
@bhmltn7 going to close given its covered by #2174.  Appreciate you opening it up though!
