### ISSUE TITLE
[Research] Ledger firmware build process 

### ISSUE THREAD

**Issue by yaovi-a** [algorand/go-algorand#2223]
Application on the ledger device test are currently executed manually to validate that new applications integrate with the the ledger firmware. These test are currently executed in docker with the hopes of automating the test. 

The goal of this ticket is to understand the build process of the ledger firmware. In the current process, there is the build, a docker is launched, the appropriate ports to run the test are created, and the test is executed.

**Comment by jsgranados** [comment]
Closing. If needed we'll reopen
