### ISSUE TITLE
Update github engineering template 

### ISSUE THREAD

**Issue by yaovi-a** [algorand/go-algorand#2256]
# Updated Ticket Spec

We want all 17 zenhub repositories to have standardized bug report and feature request templates.

Ensure each repository has `bug_report.md` and `feature_request.md` templates in `.github/ISSUE_TEMPLATE/`. Remove the `algorand-engineering-team-issue-template.md` if it exists.

## Feature Request Template
```
name: "\U0001F514 Feature Request"
about: Suggestions for how we can improve the algorand platform.
title: ''
labels: new-feature-request
assignees: ''

---

## Problem
<!-- What is the problem that we’re trying to solve? -->

## Solution
<!-- Do you have a potential/suggested solution? Document more than one if possible. -->

## Dependencies
<!-- Does the solution have any team or design dependencies? -->

## Urgency
<!-- What is the urgency here and why? -->
```

## Bug Report Template

```
---
name: "\U0001F41C Bug report"
about: Report a reproducible bug.
title: ''
labels: new-bug
assignees: ''

---

### Subject of the issue

<!-- Describe your issue here. -->

### Your environment

<!--
* Software version: `algod -v`
* Node status if applicable: `goal node status`
* Operating System details.
* In many cases log files and cadaver files are also useful to include. Since these files may be large, an Algorand developer may request them later. These files may include public addresses that you're participating with. If that is a concern please be sure to scrub that data.
-->

### Steps to reproduce

1.
2.

### Expected behaviour

### Actual behaviour

```

---
# Old Ticket Information

## Details

This needs to be added across repositories - anywhere we might file a ticket. See placements of our engineering template in repos currently.

## Template

**Requirements Template**
**Problem**: What is the problem that we’re trying to solve?

**Solution**: What is the potential/suggested Solution? Document more than one if possible.

**Dependencies**: Does the solution have any team or design dependencies?

**Urgency**: What is the urgency here and why?

**Comment by onetechnical** [comment]
Update the 17 repos that are present under Repos on the Zenhub board.

This is likely the file: `.github/ISSUE_TEMPLATE/algorand-engineering-team-issue-template.md`

**Comment by onetechnical** [comment]
Sorry @algojack did not mean for the spec to change out from under you. I have updated the description.

**Comment by onetechnical** [comment]
Bumping estimate to 1 due to spec change
