### ISSUE TITLE
AssetCreator should be an available field from asa_params_get

### ISSUE THREAD

**Issue by jannotti** [algorand/go-algorand#2270]
Although the creator is not really a field *of* the assetparams, it is a useful thing for a smart contract to look at.  Especially with respect to NFTs, contracts may want to use the creator as a form of grouping NFTs.

**Comment by jeapostrophe** [comment]
This is also essential to be able to "burn" a token by sending it back to the creator, who will then be able to destroy the asset, without the app caller telling it who the creator is.

**Comment by jasonpaulos** [comment]
This was implemented with https://github.com/algorand/go-algorand/pull/2301
