### ISSUE TITLE
Node stop and start errors. Stopped node still increasing in logs

### ISSUE THREAD

**Issue by alemens** [algorand/go-algorand#2281]
### After the node was successfully stopped. The issue is related to logs are still increasing 
e.g. `~/node/data/node.log` see below

###### Stop node success
```bash
pi@raspberrypi:~/node $ ./goal node stop -d data 
The node was successfully stopped.
pi@raspberrypi:~/node $ 
```

###### Clean to empty log ~/node/data/node.log
```bash
pi@raspberrypi:~/node $ truncate -s 0 data/node.log
pi@raspberrypi:~/node $ 
```

###### But still node.log does increase instantaneously 
```bash
pi@raspberrypi:~/node $ ls -lah data
total 2.7G
drwxr-xr-x 6 pi pi 4.0K Jun 13 02:47 .
drwxr-xr-x 5 pi pi 4.0K Jun 12 22:01 ..
-rw-rw-rw- 1 pi pi 716M Jun 13 02:54 agreement.cdv
-rw-rw-rw- 1 pi pi 1.1G Jun 10 15:45 agreement.cdv.archive
-rw------- 1 pi pi    0 Jun  9 06:04 algod-err.log
-rw------- 1 pi pi  359 Jun  9 06:13 algod-out.log
-rw-r--r-- 1 pi pi   64 Jun  9 03:07 algod.admin.token
-rw------- 1 pi pi    0 Jun  9 03:07 algod.lock
-rw-r--r-- 1 pi pi   15 Jun 13 02:47 algod.net
-rw-r--r-- 1 pi pi    4 Jun 13 02:47 algod.pid
-rw-r--r-- 1 pi pi   64 Jun  9 03:07 algod.token
drwxr-xr-x 2 pi pi 4.0K Jun  9 02:16 backup
-rw-r--r-- 1 pi pi 3.3K Jun  9 02:19 config.json.example
-rw-r--r-- 1 pi pi  25K Jun  9 02:19 genesis.json
drwx------ 2 pi pi 4.0K Jun  9 02:19 goal.cache
drwx------ 3 pi pi 4.0K Jun  9 05:51 kmd-v0.5
-rw-r--r-- 1 pi pi  225 Jun 13 00:59 logging.config
drwxr-xr-x 2 pi pi 4.0K Jun 13 02:47 mainnet-v1.0
-rw-r--r-- 1 pi pi 1.0G Jun 10 12:58 node.archive.log
-rw-r--r-- 1 pi pi 5.5K Jun 13 02:54 node.log
-rw-r--r-- 1 pi pi   13 Jun  9 02:19 wallet-genesis.id
pi@raspberrypi:~/node $ 
```

###### A sample lines of ~/node/data/node.log
```bash
pi@raspberrypi:~/node $ tail -3 data/node.log 
{"Context":"Agreement","Hash":"","ObjectPeriod":0,"ObjectRound":0,"ObjectStep":0,"Period":0,"Round":185742,"Sender":"","Step":0,"Type":"RoundInterrupted","Weight":0,"WeightTotal":0,"file":"demux.go","function":"github.com/algorand/go-algorand/agreement.(*demux).next","level":"info","line":292,"msg":"agreement: round 185742 ended early due to concurrent write; next round is 185743","time":"2021-06-13T02:51:32.545706+01:00"}
{"Context":"Agreement","Hash":"","ObjectPeriod":0,"ObjectRound":0,"ObjectStep":0,"Period":0,"Round":185743,"Sender":"","Step":0,"Type":"RoundInterrupted","Weight":0,"WeightTotal":0,"file":"demux.go","function":"github.com/algorand/go-algorand/agreement.(*demux).next","level":"info","line":292,"msg":"agreement: round 185743 ended early due to concurrent write; next round is 185744","time":"2021-06-13T02:51:32.625922+01:00"}
{"Context":"Agreement","Hash":"","ObjectPeriod":0,"ObjectRound":0,"ObjectStep":0,"Period":0,"Round":185744,"Sender":"","Step":0,"Type":"RoundInterrupted","Weight":0,"WeightTotal":0,"file":"demux.go","function":"github.com/algorand/go-algorand/agreement.(*demux).next","level":"info","line":292,"msg":"agreement: round 185744 ended early due to concurrent write; next round is 185745","time":"2021-06-13T02:51:32.681529+01:00"}
pi@raspberrypi:~/node $ 
```

###### I tried to killall algod but of course does auto nicely restart 
```
pi@raspberrypi:~/node $ killall algod
pi@raspberrypi:~/node $ ps aux | grep algod
pi         962  0.0  0.0   4784   516 pts/0    S+   03:00   0:00 grep --color=auto algod
pi@raspberrypi:~/node $ ps aux | grep algod
pi         963 50.0  1.1 824304 47004 ?        Ssl  03:00   0:01 /home/pi/node/algod -d /home/pi/node/data
pi         973  0.0  0.0   4784   488 pts/0    S+   03:00   0:00 grep --color=auto algod
pi@raspberrypi:~/node $ 
```

###### Moreover I double get node ID after stopping does auto start running
```bash
pi@raspberrypi:~/node $ pgrep algod
998
pi@raspberrypi:~/node $ ./goal node stop -d data 
The node was successfully stopped.
pi@raspberrypi:~/node $ pgrep algod
pi@raspberrypi:~/node $ pgrep algod
1047
```

###### Software version: `algod -v`
```bash
pi@raspberrypi:~/node $ ./algod -v
8590327808
2.6.0.stable [rel/stable] (commit #8fe22d4e)
go-algorand is licensed with AGPLv3.0
source code available at https://github.com/algorand/go-algorand
```

###### Node status `goal node status`
```bash
pi@raspberrypi:~/node $ ./goal node stop -d data 
The node was successfully stopped.
pi@raspberrypi:~/node $ ./goal node status -d data 
Last committed block: 198134
Time since last block: 0.0s
Sync Time: 0.0s
Last consensus protocol: https://github.com/algorandfoundation/specs/tree/5615adc36bad610c7f165fa2967f4ecfa75125f0
Next consensus protocol: https://github.com/algorandfoundation/specs/tree/5615adc36bad610c7f165fa2967f4ecfa75125f0
Round for next consensus protocol: 198135
Next consensus protocol supported: true
Last Catchpoint: 
Genesis ID: mainnet-v1.0
Genesis hash: wGHE2Pwdvd7S12BL5FaOP20EGYesN73ktiC1qzkkit8=
pi@raspberrypi:~/node $ 
```

### Steps to reproduce
1. Launch a fresh headless_setup no gui install new Raspberry Pi OS Lite on a Model B 4GB RAM 
2. Securing `pi` https://www.raspberrypi.org/documentation/configuration/security.md
3. Get success on MicroSD Card Speed Test (on command line) https://www.raspberrypi.org/blog/sd-card-speed-test/ 
4. Install the minimum node (non-relay node) with related https://developer.algorand.org/docs/run-a-node/setup/install/
5. Start the sync via catchup with success `./goal node catchup $CATCHPOINT -d data` 

### Issue behaviour
1. After a couple of days the sync was still not completed, 
2. And searching into `~/node/data/node.log` the service `db.atomic` thrown `err: database is locked` here the related on going post [Sync Algorand Node Network using Fast Catchup (default install) on Raspberry Pi 4 Computer Model B 4GB RAM on 32 GB MicroSD](https://forum.algorand.org/t/sync-algorand-node-network-using-fast-catchup-default-install-on-raspberry-pi-4-computer-model-b-4gb-ram-on-32-gb-microsd/3524) because this above error is related to a Unix network permission denied to be clarified and solved needs time ... 
3. I decided to stop the node. But unfortunately I saw it does actually not turning off and keep increasing logs in size

**Comment by consiglieri-cfi** [comment]
![image](https://user-images.githubusercontent.com/30444483/121795233-761c3f00-cbd4-11eb-81f3-37791a75591f.jpeg)

I encountered the issue as well with RPi 3 and SDHC.

**Comment by alemens** [comment]
> ![image](https://user-images.githubusercontent.com/30444483/121795233-761c3f00-cbd4-11eb-81f3-37791a75591f.jpeg)
> 
> I encountered the 'database is locked' issue as well. In my case using RPi 3 with SDHC.

Hi @consiglieri-cfi again, thanks for the answer you already gave into a Discord thread. By the way your comment it is an out of scope answer since the subject of this bug here is about `a stopped node but still increasing in logs` like `~/node/data/node.log`

Moreover I asked you to show us `sudo fdisk -l` but you did not. Anyway yes we faced the same error message: "Unable to write event" && "database is locked". Which are clearly related to Unix network permission denied. Yes you solved with an SSD storage but I am sure we can prove it can be solved also by giving the rights to that service into `pi` related allocation.

**Comment by tsachiherman** [comment]
@alemens,
My guess, is that the node is installed as a daemon, and was attempted to be stopped as a non-daemon. The listing above doesn't have the "system.json" file. Could you please provide more detailed information regarding how you installed the node ?

**Comment by tsachiherman** [comment]
It looks like systemd-setup.sh is installing the node without creating the system.json file in the node's data directory.
This makes `goal node stop` think the node is managed by the user, and conflict with the daemon service.

**Comment by alemens** [comment]
> It looks like `systemd-setup.sh` is installing the node without creating the `system.json` file in the node's data directory.
> This makes `goal node stop` think the node is managed by the user, and conflict with the daemon service.

Should I create it manually? 

Yeah no `system.json` found. 

```bash
pi@raspberrypi:~ $ sudo find / -name 'system.json'
pi@raspberrypi:~ $ sudo find node/ -name 'system.json'
pi@raspberrypi:~ $ sudo find / -name 'systemd-setup.sh'
/home/pi/node/systemd-setup.sh
pi@raspberrypi:~ $ 
```

###### To help your architecture see the existing structure of a fresh raspberrypi as for `system` and `*.json` 
```bash
pi@raspberrypi:~ $ sudo find / -name 'system'
/etc/systemd/system
/run/systemd/system
/usr/lib/systemd/system
/sys/devices/system
/sys/devices/virtual/dma_heap/system
/sys/class/dma_heap/system
/sys/firmware/devicetree/base/system
/dev/dma_heap/system

pi@raspberrypi:~ $ sudo find / -name '*.json'
/home/pi/node/genesisfiles/genesis.json
/home/pi/node/genesisfiles/betanet/genesis.json
/home/pi/node/genesisfiles/testnet/genesis.json
/home/pi/node/genesisfiles/mainnet/genesis.json
/home/pi/node/genesisfiles/devnet/genesis.json
/home/pi/node/data/genesis.json
/usr/share/iso-codes/json/schema-3166-1.json
/usr/share/iso-codes/json/schema-639-5.json
/usr/share/iso-codes/json/iso_4217.json
/usr/share/iso-codes/json/iso_3166-1.json
/usr/share/iso-codes/json/schema-639-2.json
/usr/share/iso-codes/json/iso_15924.json
/usr/share/iso-codes/json/iso_3166-3.json
/usr/share/iso-codes/json/schema-3166-2.json
/usr/share/iso-codes/json/iso_639-3.json
/usr/share/iso-codes/json/schema-15924.json
/usr/share/iso-codes/json/iso_639-2.json
/usr/share/iso-codes/json/schema-4217.json
/usr/share/iso-codes/json/iso_3166-2.json
/usr/share/iso-codes/json/schema-639-3.json
/usr/share/iso-codes/json/iso_639-5.json
/usr/share/iso-codes/json/schema-3166-3.json
```

**Comment by bricerisingalgorand** [comment]
Could you try running this? That script actually sets up a systemd service that takes a path as an argument, so that users can manage multiple nodes using systemd. 

```
sudo systemctl status algorand@$(systemd-escape `pwd`/data)
```

Outside of that, the system.json file that @tsachiherman is referring to is found [here](https://github.com/algorand/go-algorand/blob/master/installer/system.json). This gets installed by apt/yum installs by default, but it looks the systemd-setup script should be creating that file too. Sorry for the inconvenience. Here are docs with more details and how to use that system.json file

https://developer.algorand.org/docs/run-a-node/operations/switch_networks/#debian-or-rpm-installs

**Comment by alemens** [comment]
> Could you try running this? That script actually sets up a systemd service that takes a path as an argument, so that users can manage multiple nodes using systemd.
> 
> ```
> sudo systemctl status algorand@$(systemd-escape `pwd`/data)
> ```
> 
> Outside of that, the system.json file that @tsachiherman is referring to is found [here](https://github.com/algorand/go-algorand/blob/master/installer/system.json). This gets installed by apt/yum installs by default, but it looks the systemd-setup script should be creating that file too. Sorry for the inconvenience. Here are docs with more details and how to use that system.json file
> 
> https://developer.algorand.org/docs/run-a-node/operations/switch_networks/#debian-or-rpm-installs

Hi @bricerisingalgorand below your response 
```bash
pi@raspberrypi:~/node $ sudo systemctl status algorand@$(systemd-escape `pwd`/data)
● algorand@-home-pi-node-data.service - Algorand daemon under /home/pi/node/data
   Loaded: loaded (/lib/systemd/system/algorand@.service; enabled; vendor preset: enabled)
   Active: active (running) since Sun 2021-08-22 16:36:10 BST; 8min ago
 Main PID: 9409 (algod)
    Tasks: 10 (limit: 4915)
   CGroup: /system.slice/system-algorand.slice/algorand@-home-pi-node-data.service
           └─9409 /home/pi/node/algod -d /home/pi/node/data

Aug 22 16:36:10 raspberrypi systemd[1]: Started Algorand daemon under /home/pi/node/data.
Aug 22 16:36:10 raspberrypi algod[9409]: Telemetry configured from '/home/pi/node/data/logging.config'
Aug 22 16:36:10 raspberrypi algod[9409]: Logging to:  /home/pi/node/data/node.log
Aug 22 16:36:10 raspberrypi algod[9409]: Deadlock detection is set to: disabled (Default state is 'disable')
Aug 22 16:36:10 raspberrypi algod[9409]: Initializing the Algorand node... Success!
Aug 22 16:36:10 raspberrypi algod[9409]: ⇨ http server started on 127.0.0.1:8080
Aug 22 16:36:10 raspberrypi algod[9409]: Node running and accepting RPC requests over HTTP on port 127.0.0.1:8080. Press Ctrl-C to exit
pi@raspberrypi:~/node $
```

**Comment by alemens** [comment]
Hi @onetechnical why you closed the issue if still not resolved?
