### ISSUE TITLE
Update tealdbg for TEAL 4

### ISSUE THREAD

**Issue by jasonpaulos** [algorand/go-algorand#2289]
## Summary
TEAL v4 now allows looping, function calls, and has some additional opcodes. We need to make sure the debugger is able to understand these new changes.

## Scope/Requirements
Test that the debugger can handle the new feature from TEAL 4. I suspect the following may require debugger changes:
* Changes to foreign app/asset/account indexing
* Function calls & backward branches

If any changes are required, make them.

## Urgency/Relative Priority
Required to ensure TEAL 4 programs can be debugged properly.

**Comment by onetechnical** [comment]
As you're stepping it should tell how much cost you've used.
