### ISSUE TITLE
Impossible to compile with multiple `GOPATH`

### ISSUE THREAD

**Issue by fabrice102** [algorand/go-algorand#230]
**Is your feature request related to a problem? Please describe.**

The environment variable `$GOPATH` may contain multiple paths (see https://golang.org/cmd/go/#hdr-GOPATH_environment_variable).
This is not supported by the compilation system: compilation will failed in that setting.

**Describe the solution you'd like**

The assumption that `$GOPATH` is a single folder is used extensively in the source code and it is not clear that there is a simple solution to fix it.
Maybe the simplest solution is to add a comment in the README explaining that `$GOPATH` must be a single folder.

**Comment by zeldovich** [comment]
Thanks for pointing that out.  I had not realized that Go tools support a `$GOPATH` containing multiple paths, colon-separated.  The assumption that `$GOPATH` has just a single element is indeed fairly widespread in our code and scripts, though it shows up a bit less now that we've added support for Go modules.

https://github.com/algorand/go-algorand/pull/231 should be enough to at least get `make` to run fine with a multi-component `$GOPATH`.

**Comment by onetechnical** [comment]
The fix in #231 just presumes the first path in GOPATH is correct for installing binaries. This may or may not be true, so we should just update the README to indicate the same for now.

**Comment by ian-algorand** [comment]
Blocked on 1.14 upgrade, this will be resolved at that point.

**Comment by bbroder-algo** [comment]
dead or worked around by now
