### ISSUE TITLE
Block does not get fully filled up when block size is set to large

### ISSUE THREAD

**Issue by yangl1996** [algorand/go-algorand#232]
### Subject of the issue
Block is not able to be filled when block size is set to large in `config/config.go`

### Your environment
* Software version: `4295011400, 1.0.44104.dev [master] (commit #bbcffcbb+)`
* Operating System: Ubuntu 18.04 on AWS EC2 c5d.4xlarge

### Steps to reproduce
Modify line 224 of `config/config.go` to make the block 100 times larger (100MB) and rebuild. Create a private test network of 20 nodes, and generate transactions at 40 txn/s on each node.  Wait a bit until backlog builds up in the memory pool Measure the size of the produced blocks now.

### Expected behaviour
Blocks should contain 100x more transactions.  

### Actual behaviour
Blocks contain roughly the same number of transactions as without modifying the block size.

**Comment by Karmastic** [comment]
This is actually by design.  There is an additional deadline specified when assembling blocks to ensure we do not spend too much time assembling blocks.  If too much time is spent assembling blocks, this can affect the health of the protocol (blocks need to be propagated for voters to approve them).  Refer to data/ledger.go: AssemblePayset(), and the source for that deadline in agreement/pseudonode.go: AssemblyTime (constant = 250ms).

**Comment by yangl1996** [comment]
Indeed! I tried increasing both block size and assembly deadline, and was able to get the system produce larger blocks. Thanks!

**Comment by yangl1996** [comment]
Hi @Karmastic , quick follow-up: I successfully increased the size of blocks being generated. However, I found that after the block gets larger than a certain threshold, rounds won't conclude. Specifically when the block gets larger (the biggest size that works fine is 4MB), `carpenter` gets stuck after `algod` receives the first vote for step 2, for example:

```
12.0.2:           VoteAccepted(14/14) PL673- 12.0.2|
```

The next event one gets would be `StepTimeout` follows, after the timer for step 2 has expired. This prevents the system from progressing. Any idea how this could be fixed?

Thanks!

**Comment by Vervious** [comment]
What small and big lambdas are you using? Do you see a `ThresholdReached` event for step 1?

**Comment by zeldovich** [comment]
My guess is that you're hitting a 4MB max network message size: `maxMessageLength` in `network/wsPeer.go`

**Comment by yangl1996** [comment]
> My guess is that you're hitting a 4MB max network message size: `maxMessageLength` in `network/wsPeer.go`

Indeed. I modified that value and was able to get the system progressing. Thank you so much Nickolai!
