### ISSUE TITLE
How to get txid in /v2/blocks/{round}

### ISSUE THREAD

**Issue by anhcao142** [algorand/go-algorand#2338]
## Summary
Transactions in `/v2/blocks/{round}` don't include `txid`. How can I get txid using `/v2/blocks/{round}`?

**Comment by winder** [comment]
You would have to do something like using `format=msgpack`. From there you can either compute the `txid` manually from the encoded objects, or re-encode them into the SDK Transaction objects and use the existing helper functions.

Alternatively you can use Indexer which already does something similar to include the `txid` in its version of `/v2/blocks/{round}`.

**Comment by anhcao142** [comment]
Thank you, I overlooked the indexer since I thought the response would be the same as v2. I will close this now.
