### ISSUE TITLE
ABI - AVM Support - selector and dig/bury

### ISSUE THREAD

**Issue by chaihoang** [algorand/go-algorand#2346]
- [x]  Have a pseudo opp similar to ADDR to calculate method selector
- [ ] Revisit dig/bury for easier stack manipulation

**Comment by jannotti** [comment]
Here are proposed ops to give us better stack manipulation
```
cover n : remove TOS, and place it down the stack such that n elements are above it
uncover n: inverse of cover (this is also like dig, but removes the deep element)
```

**Comment by jannotti** [comment]
Trying to reopen, since it was auto closed by a linked PR.
