### ISSUE TITLE
Add ABI encoding support to goal

### ISSUE THREAD

**Issue by chaihoang** [algorand/go-algorand#2348]
## Summary
Add support for encoding and decoding ABI values, as described in https://github.com/algorandfoundation/ARCs/pull/7

## Scope
Add ability to:
* Parse and serialize ABI type strings, e.g. `(uint64, byte[], address)`
* Encode and decode ABI values, using type information

## Dependencies
This has follow-up issues:
* https://github.com/algorand/go-algorand/issues/2803
* https://github.com/algorand/go-algorand-sdk/issues/236
* https://github.com/algorand/js-algorand-sdk/issues/425
* https://github.com/algorand/py-algorand-sdk/issues/228
* https://github.com/algorand/java-algorand-sdk/issues/244

**Comment by jannotti** [comment]
--app-arg should also accept an argument like "selector:add(uint64,uint64):uint128" and place the ABI defined selector in the argument (4 bytes of sha512_256).
