### ISSUE TITLE
ABI: Design - multi transaction groups 

### ISSUE THREAD

**Issue by chaihoang** [algorand/go-algorand#2351]
## Summary
The Algorand ABI (tracked by https://github.com/algorandfoundation/ARCs/pull/7) introduces a standard way of invoking methods on an application. Each method occupies an entire application call transaction, however some applications may require additional transactions to be present in the same atomic group in order for them to operate successfully.

For example, an application implementing an exchange between Algos and an ASA may require two additional transactions to be present in the same atomic group as its method invocation: a payment transaction from the caller into an escrow account, and an asset transfer transaction from the escrow account to the caller.

The goal of this issue is to design a standard way of declaring and expressing dependencies that methods may have on additional transactions in such a way that method callers can easily construct atomic groups to properly invoke a method.

## Scope
* Extend the ABI to allow declaring dependencies on additional transactions
  * @jannotti has suggested creating more argument types, such as `payment` or `transaction<pay>`, which can be used as method arguments to indicate dependencies on other transactions. These might be encoded as a `uint8` to represent the index of the transaction.
* Based on the above, provide guidelines for how the method caller can construct an atomic groups that will properly invoke a method. A requirement is that it should be possible to invoke multiple methods in the same atomic group (provided the total txn count is 16 or less).
* Additionally, consider how to prevent a method caller from tricking a method into believing more transactions are present than actually are. E.g. what if a method requires the caller to pay a certain addresses, but the caller invokes the method twice in the same group with only one payment transaction?
  * A solution might be to provide a way to "mark" transactions as being used, and a method should fail if an input transaction is already marked.

Previous information to revisit (this may not be relevant anymore): https://docs.google.com/document/d/1blmAJBMmB4Ki4p4YxP1IVEbvzFSHtHp0VxSRyV7Gj1g/edit

**Comment by algorandskiy** [comment]
The design proposal: https://docs.google.com/document/d/1RGxzYq3QwXgmxVmKcqUnPymJ7YTaLIT970e1YwJ--HE

Took couple iterations and looks good for stakeholders.
