### ISSUE TITLE
Static Host ID

### ISSUE THREAD

**Issue by AlgoStephenAkiki** [algorand/go-algorand#2355]
## Summary
The `HostName` being provided in the telemetry `PeerConnection` event is empty in case the telemetry is not enabled on the local machine. We want to make sure that the provided value is static so that we can count the number of hosts on the network.

## Scope / Requirement

Convert existing dynamic host ID into a static host ID while allowing the user to use dynamic host ID if they chose to.

**Comment by yaovi-a** [comment]
closes #1101
