### ISSUE TITLE
Flaky test: TestAsyncTelemetryHook_QueueDepth

### ISSUE THREAD

**Issue by yaovi-a** [algorand/go-algorand#2394]
## Description
Travis Test Errors Reference Spreadsheet for details on cases where this test has failed: https://docs.google.com/spreadsheets/d/1apjaNvZodnTSIdZaQlpMaqf0nzbKgSYdIWHqvmINHS8/edit#gid=0

### Example Failure
Time: Mon 7/19/2021
Build: https://app.travis-ci.com/algorand/go-algorand/builds/233054279?utm_source=slack&utm_medium=notification
Travis Test: External ARM64 Build, MacOS AMD64 Build
Package: logging
Test: TestAsyncTelemetryHook_QueueDepth 

```
=== FAIL: logging TestAsyncTelemetryHook_QueueDepth (0.03s)
telemetryhook_test.go:220:
Error Trace:	telemetryhook_test.go:220
Error:      	Not equal:
expected: 10
actual  : 11
Test:       	TestAsyncTelemetryHook_QueueDepth
DONE 5471 tests, 23 skipped, 1 failure in 3558.591s
Makefile:241: recipe for target 'fulltest' failed
make: *** [fulltest] Error 1
The command "/home/ubuntu/go/src/github.com/[secure]/go-[secure]/scripts/travis/test.sh" failed. Retrying, 2 of 3.
```

**Comment by yaovi-a** [comment]
This test was removed with #2299

**Comment by algobarb** [comment]
I'm not sure, but I don't think this test was properly removed given the Travis FAIL on a false positive External ARM64 Build last Monday.

**Comment by yaovi-a** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Algorand-Main-Workspace-5ea71fda6d554d53dda36f16/issues/algorand/go-algorand/2394?planning-poker) with ZenHub @algobolson @algonautshant @AlgoStephenAkiki @nicholasguoalgorand @tolikzinovyev @tsachizehub @winder
