### ISSUE TITLE
ExtraProgramPages not usable after Creation

### ISSUE THREAD

**Issue by jeapostrophe** [algorand/go-algorand#2431]
You can set `ExtraProgramPages` to something greater than 0 at creation time, but you can't update an application and use extra space you allocated

If you look at this code:

https://github.com/algorand/go-algorand/blob/c7b017a7d38317aa7484fd0c95a417418a4386e4/data/transactions/transaction.go#L353-L408

You can see that
- L348 - is true when you are updating
- L353 - guarantees that `tx.ExtraProgramPages` is 0
- L399 - is 0 because of above
- L406 - is going to be true (i.e. error) because of that

I believe that this is not a problem when you are not updating (i.e. when you are calling) because `tx.ApprovalProgram` and `tx.ClearProgram` are expected to be 0 since they aren't being updated.

I believe that the fix is to look up the actual application `ExtraProgramPages` when you aren't updating and use the stored value

**Comment by jeapostrophe** [comment]
I'll work on a patch and get back to you about my proposed fixed, but I figured learning about the problem fast is good :)

**Comment by jeapostrophe** [comment]
@shiqizng

**Comment by jannotti** [comment]
> I believe that the fix is to look up the actual application `ExtraProgramPages` when you aren't updating and use the stored value

That sounds right to me.

**Comment by jeapostrophe** [comment]
I spent some time working on a patch for this and I now think that `WellFormed` should not be checking the program lengths on update like this. Basically `WellFormed` says `// WellFormed checks that the transaction looks reasonable on its own (but not necessarily valid against the actual ledger). It does not check signatures.` The only way to do this check is to look at the current ledger, which is not available to this function. So instead, it should make sure the program is not more than is possible and then `updateApplication` in `application.go` should check to make sure the new programs are valid

**Comment by jeapostrophe** [comment]
This is the patch I'm using and it is working well --- https://gist.github.com/94149c776903646a9d8e0120811b5e02

**Comment by shiqizng** [comment]
the fix looks good to me.
