### ISSUE TITLE
Design: automating indexer release pipeline

### ISSUE THREAD

**Issue by yaovi-a** [algorand/go-algorand#2440]
## Description: 
Build and publish indexer binaries.
https://algorand.atlassian.net/wiki/spaces/DEVOPS/pages/1246691329/Indexer+Release+Process

(Removed test from scope - this requires more thinking.)

## Acceptance/criteria: 

- Design output for indexer release on confluence 
- A complete list of stories required to deliver on indexer release pipeline.

**Comment by bricerisingalgorand** [comment]
![Image from iOS](https://user-images.githubusercontent.com/60147418/126203724-2df1fead-261f-4ebd-a1e5-6b83629a8bd1.jpg)

**Comment by egieseke** [comment]
Use Jenkins to automate the Indexer Release process defined here: https://algorand.atlassian.net/wiki/spaces/DEVOPS/pages/1246691329/Indexer+Release+Process

**Comment by egieseke** [comment]
Include the checklist as part of this ticket.  Update the spread sheet with release checklist to include.

**Comment by algobarb** [comment]
Can you create issues/stories on steps we can automate for the [Create pipeline for indexer release](https://app.zenhub.com/workspace/o/algorand/go-algorand/issues/2439) epic? 

I think it will be similar to the Automate [Go-Algorand Release Processs](https://app.zenhub.com/workspaces/algorand-main-workspace-5ea71fda6d554d53dda36f16/issues/algorand/go-algorand-internal/1037) epic.

**Comment by egieseke** [comment]
> Can you create issues/stories on steps we can automate for the [Create pipeline for indexer release](https://app.zenhub.com/workspace/o/algorand/go-algorand/issues/2439) epic?
> 
> I think it will be similar to the Automate [Go-Algorand Release Processs](https://app.zenhub.com/workspaces/algorand-main-workspace-5ea71fda6d554d53dda36f16/issues/algorand/go-algorand-internal/1037) epic.

Created this Implementation ticket: https://github.com/algorand/go-algorand-internal/issues/1457

**Comment by algobarb** [comment]
I think we should split out the implementation ticket into separate issues so that they're smaller and easier for us to pick up, groom, and estimate points for. I would name the titles to be something like: "Automate GitFlow branch creation" and link the design doc and the indexer release documentaion.

**Comment by egieseke** [comment]
Created separate tickets.
