### ISSUE TITLE
Design and doc architecture - EBS snapshot of Archival Nodes

### ISSUE THREAD

**Issue by yaovi-a** [algorand/go-algorand#2442]
## Problem

- Developers don’t have an easy way to spin an archival or indexer node without it taking a significant amount of time
- There’s a way to spin up indexer environment but requires TerraForm 
- Allocating resource is time consuming
- Even after allocating resources, one has to confirm the functionality of their nodes and indexers
- For internal developer only 

## Solution

**Pre-existing volume (<1 hour)**
1. Snapshot EBS of archival node
2. Spin up new EC2 instance, with EBS volume attached built from snapshot of EBS
3. Sanitize EBS volume, configure algod
4. Start algod and catch up

## Acceptance criteria: 
**Design for the followings:** 
- Tech for taking snapshot & snapshot cost 
- Confirm how we can create snapshot (process)
- How we're access different tech that are being leveraged securely 
- Create follow up stories 
- Document outlining design and intention behind follow up stories  -- To be reviewed in design review meeting

**Comment by egieseke** [comment]
Held brainstorming session:
Created and reviewed design doc
https://docs.google.com/document/d/1UVhzynYNHQa28OvKhqvEM9iS75lhxbTh3_-bhzGnv9c/edit?usp=sharing

Created associated Github issues for implementation: 
https://github.com/algorand/go-algorand-internal/issues/1547
https://github.com/algorand/go-algorand-internal/issues/1548

**Comment by Blackglade** [comment]
Just saw the issue come across. As an external developer building on Algorand, I've been dealing with a similar problem. This is sort of a hacky solution, but it's what I ended up coming up with for the time being: https://github.com/WaferFinance/AlgoNode-AWS.
