### ISSUE TITLE
Update release build process (and nightly) to generate docker images too

### ISSUE THREAD

**Issue by ian-algorand** [algorand/go-algorand#246]
We should generate and upload official docker images tagged for the build # and a 'latest', for nightly and stable channels.

Low priority unless we hear people asking for it.

Remaining trickiness is in dealing with Docker Hub credentials if we fully automate this.

~~Probably want to upload on build to private repository. (This may be fully automated? We push the docker images to S3.)~~

Release process should upload to Docker Hub.

**Comment by algobolson** [comment]
There's a docker package built and signed, but not pushed to dockerhub
https://releases.algorand.com/

**Comment by btoll** [comment]
We are already doing this for stable releases.

See my comment here: https://github.com/algorand/go-algorand/issues/558
That ticket is very similar to this one.   Possible duplicate?

**Comment by onetechnical** [comment]
Considering this a duplicate
