### ISSUE TITLE
Txn sync: 1 relay 2 node txn sync test

### ISSUE THREAD

**Issue by yaovi-a** [algorand/go-algorand#2466]
## Problem

As part of transaction sync readiness, we need to run some e2e test to surface any potential issues with the implementation 

## Solution

Test transaction performance with 1 relay 2 nodes. 

## Acceptance criteria
Txns should be received by relay 
Txns should reach destination within reasonable amount of time (???)
Confirm that there are no regression between operation w/o txn sync and w/ txn sync

**Comment by brianolson** [comment]
Use an SDK to send a txn to node A, check its pending status on node B to see that it moved across. txn should propagate within ~2 seconds or some better bound.
