### ISSUE TITLE
Indexer should make it convenient to find the create transaction for an ASA

### ISSUE THREAD

**Issue by jannotti** [algorand/go-algorand#2528]
[ARC3](https://github.com/algorandfoundation/ARCs/blob/main/ARCs/arc-0003.md) will likely propose that NFT metadata can be optionally stored in the note field of the create transaction for an ASA that is an NFT.  It should be possible to find that transaction easily with an indexer query.

Some possibilities
1. Add the ability to query by TXSeqNo, which an ASA ID actually is.  So you could find the create this way.
2. Add an explicit query to find the first acfg for an ASA. (This only works if we are doing the work to make sure queries of create acfgs are findable under the ASA's newly created id - recall that the txn itself will have a 0 in the axid field)

**Comment by winder** [comment]
To get the create transaction you can use `/v2/transactions?assetid=<id>&type=acfg&limit=1` or `/v2/assets/<id>/transactions?type=acfg&limit=1`

**Comment by brianolson** [comment]
Default Indexer isn't necessarily configured with the indexes to make that query fast. Adding an index on txn by assetid would make it fast.

**Comment by winder** [comment]
You could lookup by the creator also, but then you'd need the final asset config transaction instead of the first.

**Comment by jannotti** [comment]
Do we actually do the "extra" work to make that work? That is, the txn does
not have the asset I'd, since it's the creation transaction. Do we get it
and put it in before ingesting it?

**Comment by winder** [comment]
@jannotti yes, we compute the asset ID and include it with the initial asset config transaction. When fetching the transaction, there is a special field used to indicate that something was created:
```
{
  "current-round": 19,
  "next-token": "EwAAAAAAAAAAAAAA",
  "transactions": [
    {
      "asset-config-transaction": {
        "asset-id": 0,
        "params": {
          "clawback": "HYR2RKYMTNOSAFHTQ2RGB6YLJNEEGAPYSIQ4PQ4J3AOSZJAIU4X2ASJ7ME",
          "creator": "HYR2RKYMTNOSAFHTQ2RGB6YLJNEEGAPYSIQ4PQ4J3AOSZJAIU4X2ASJ7ME",
          "decimals": 0,
          "default-frozen": false,
          "freeze": "HYR2RKYMTNOSAFHTQ2RGB6YLJNEEGAPYSIQ4PQ4J3AOSZJAIU4X2ASJ7ME",
          "manager": "HYR2RKYMTNOSAFHTQ2RGB6YLJNEEGAPYSIQ4PQ4J3AOSZJAIU4X2ASJ7ME",
          "name": "hellocoin",
          "reserve": "HYR2RKYMTNOSAFHTQ2RGB6YLJNEEGAPYSIQ4PQ4J3AOSZJAIU4X2ASJ7ME",
          "total": 1000
        }
      },
      "close-rewards": 0,
      "closing-amount": 0,
      "confirmed-round": 19,
      "created-asset-index": 1, // there is also a 'created-application-index' field.
      "fee": 1000,
      "first-valid": 18,
      "genesis-hash": "IhPtd7u2NHTSKE2zTde17YCjrdZcM+EqdFgWl4FhAhg=",
      "id": "KOBDQ3GEYHXDHAXM3IRPHC466CHHSMWGCOEHCS6DZD7Z4OVQCD6A",
      "intra-round-offset": 0,
      "last-valid": 1018,
      "note": "Ljqpaao+ORw=",
      "receiver-rewards": 0,
      "round-time": 1626439650,
      "sender": "HYR2RKYMTNOSAFHTQ2RGB6YLJNEEGAPYSIQ4PQ4J3AOSZJAIU4X2ASJ7ME",
      "sender-rewards": 0,
      "signature": {
        "sig": "3ohPsOSjGfx+guSYlMpDlIK3AohaymevlKefKqL6SX4SPIVXR2blm7I+WHWkugXw/dgx7lBGOBHFbZU6czntAw=="
      },
      "tx-type": "acfg"
    }
  ]
}
```

**Comment by jannotti** [comment]
Great, thanks. I think I will close this. It's possible we will need an index to make this fast if this practice becomes common, but I'd say we're good for now.
