### ISSUE TITLE
Design: Source map support for `tealdbg`

### ISSUE THREAD

**Issue by jasonpaulos** [algorand/go-algorand#2538]
## Summary
Currently the TEAL debugger only shows the disassembled TEAL program during a debugging session. This works fine for developers who are familiar with TEAL opcodes, but to better support developing in a higher level language like PyTeal or Reach, it would be beneficial for the debugger to support source maps to these languages.

## Scope/Requirements
Source maps should be able to map from TEAL program counter values (i.e. each TEAL op) to the higher-level source code which generated it. The higher level language which produced the TEAL program will be responsible for generating a source map as well.

The debugger should be able to load a source map, load the files it references, and display these files during a debugging session instead of/in addition to the disassembled TEAL.

## Urgency/Relative Priority
Nice to have to enable debugging from higher level languages.

**Comment by algochoi** [comment]
Closed by #3475
