### ISSUE TITLE
investigate: Add support in Apple M1 machines

### ISSUE THREAD

**Issue by rotemh** [algorand/go-algorand#2553]
## Is your feature request related to a problem? Please describe.

Currently, the only way to run a node on an M1 Machine is by using Rosseta. The compilation process fails and there no pre-built binaries for M1. 

## Describe the solution you'd like.

Pre-built binaries and support for building from source. 

## Additional context.

Apple's new processor becoming more popular over time and Apple will drop support in intel-based machines by the end of next year.

**Comment by grakshith** [comment]
This PR already fixes this issue. https://github.com/algorand/go-algorand/pull/2290
Pre-built binaries aren't there yet but building from source on M1 machines should work and algod should run the native `arm64` binary.
Let me know what stage of the compilation process fails and I can take a look.

**Comment by tsachizehub** [comment]
Need to make sure the binomial dist works the same on that platform.
