### ISSUE TITLE
Update nightly build to generate deb and rpm packages

### ISSUE THREAD

**Issue by ian-algorand** [algorand/go-algorand#256]
(originally reported by @Karmastic)

Need to generate nightly-channel packages so we can test them - should still sign (maybe disposable key) and publish at a different package endpoint so we can choose whether to install nightly or stable (currently can't support SxS)

Questions:
- How far back would we want to store these packages?
- Who would use this?

**Comment by onetechnical** [comment]
Considering this a dupe of #1047
