### ISSUE TITLE
Update indexer release pipeline documentation

### ISSUE THREAD

**Issue by yaovi-a** [algorand/go-algorand#2583]
## Problem

We currently need to update the release documentation for indexer pipeline. (do not include Travis test (integration test) upgrade binary test, migration testing, data validation, and catchup from scratch, Canonical query list for validation) 
https://algorand.atlassian.net/wiki/spaces/DEVOPS/pages/1246691329/Indexer+Release+Process

Potential issues with gitflow cli access/approval: please document the gitflow cli process

## Solution

Update the indexer release documentation. 

## Acceptance criteria: 

Documentation of updated indexer release (included gitflow cli process) 
Indexer release checklist

**Comment by onetechnical** [comment]
The documentation part of this is done, so just the checklist is needed.

**Comment by algobarb** [comment]
I think @onetechnical recently updated it, so I think we just need to validate it? Kinda related to #2440 I think @egieseke
