### ISSUE TITLE
REST API "/v1/status" should include the genesisID to identify the network it's on

### ISSUE THREAD

**Issue by ian-algorand** [algorand/go-algorand#259]
(originally reported @Karmastic)

**Comment by ian-algorand** [comment]
@Karmastic who was originally asking for this? We have some concerns around the fact that we would be returning the constant genesisID ever time we call this (which would be a waste).

**Comment by Karmastic** [comment]
Me - I was asking for it.  We're already returning the genesis hash, but
that's not a readable string that is easily identifiable as 'testnet' or
'mainnet'.  When given the REST endpoint for an arbitrary node, we can't
easily tell what network it's serving.  I'm fine adding another API method
if that makes it easier to swallow.

**Comment by rotemh** [comment]
I believe that expending the current ‘/status’ end point is the right solution.
