### ISSUE TITLE
Release work: go-algorand v2.8.0 stable 

### ISSUE THREAD

**Issue by yaovi-a** [algorand/go-algorand#2606]
Release Checklist to follow for Stable:
https://docs.google.com/spreadsheets/d/1nSl-QSmGU5hTRePFa_porqLBKCiatzqynd9B-yGp4RA/edit#gid=350212538

Documentation:
https://algorand.atlassian.net/wiki/spaces/DEVOPS/pages/1949663249/go-algorand+Stable+Release+Process

**Comment by egieseke** [comment]
Completed release on Wednesday 7/28 at 2:30 PM.

**Comment by algobarb** [comment]
Looks good
