### ISSUE TITLE
Expose testing helper functions from logic package

### ISSUE THREAD

**Issue by fergalwalsh** [algorand/go-algorand#2624]
## Problem

Testing Teal code is hard. I have tried multiple methods including using sdk transactions with the sandbox and using the dryrun endpoint. These are both slow and error prone and are end-to-end integration tests instead of unit tests.

This repository contains a framework for testing Teal programs which turns out to be a very useful way of writing unit tests for both stateful apps and logicsig programs. Unfortunately the members are all private to the `logic` package so the only way I have found to use them is to copy large sections of the code. This works fine but it's a risky problem when new releases are made.

## Solution

Expose some of the functions and types from `eval_test.go` & `evalStateful_test.go` such as:
[makeTestLedger](https://github.com/algorand/go-algorand/blob/58fd804cbc8094bdce0a80b2f8ae2badc3784fb0/data/transactions/logic/evalStateful_test.go#L98)

[defaultEvalParams](https://github.com/algorand/go-algorand/blob/58fd804cbc8094bdce0a80b2f8ae2badc3784fb0/data/transactions/logic/eval_test.go#L73)

[testApp](https://github.com/algorand/go-algorand/blob/58fd804cbc8094bdce0a80b2f8ae2badc3784fb0/data/transactions/logic/evalStateful_test.go#L762)

This is not an exhaustive list, just some examples. These particular members would not necessarily need to be made public, it would be sufficient to have public wrappers for them. 

Would this be possible? Is there any reason not to make this functionality public?

**Comment by chaihoang** [comment]
Can you provide more information about your particular use case?  If these were exposed, how would it assist in what you're trying to achieve?

**Comment by fergalwalsh** [comment]
Here is an example of a test I have written. It tests an app call within a transaction group with a specific initial ledger state and asserts that the app program passes and that the local state deltas are as expected.

```
func TestValidatorBootstrap(t *testing.T) {
	t.Parallel()

	source := getValidatorAppSource()

	txgroup := makeBootstrapTxnGroup()
	var txn = &txgroup[1]

	sender := txgroup[0].Txn.Sender

	ep := defaultEvalParams(nil, nil)
	ep.Txn = txn
	ep.Txn.Txn.ApplicationID = appId
	ep.TxnGroup = txgroup

	ledger := makeTestLedger(
		map[basics.Address]uint64{
			sender: 1000000,
		},
	)
	ledger.newApp(txn.Txn.Sender, appId, makeSchemas(0, 0, 0, 0))

	params := basics.AssetParams{
		Total:         1000000000000,
		Decimals:      6,
		DefaultFrozen: false,
		UnitName:      "EURO",
		AssetName:     "Euro ASA",
		URL:           "",
		Manager:       sender,
		Reserve:       sender,
		Freeze:        sender,
		Clawback:      sender,
	}
	ledger.newAsset(txn.Txn.Sender, asset2, params)

	params = basics.AssetParams{
		Total:         1000000000000,
		Decimals:      6,
		DefaultFrozen: false,
		UnitName:      "USDC",
		AssetName:     "USDC ASA",
		URL:           "",
		Manager:       sender,
		Reserve:       sender,
		Freeze:        sender,
		Clawback:      sender,
	}
	ledger.newAsset(txn.Txn.Sender, asset1, params)
	ep.Ledger = ledger

	delta := testApp(t, source, ep)
	require.Empty(t, delta.GlobalDelta)

	d := delta.LocalDeltas[0]["a1"]
	require.Equal(t, basics.SetUintAction, d.Action)
	require.Equal(t, uint64(asset1), d.Uint)

	d = delta.LocalDeltas[0]["a2"]
	require.Equal(t, basics.SetUintAction, d.Action)
	require.Equal(t, uint64(asset2), d.Uint)
}
```


In other tests I am setting initial asset holdings and local state in the ledger at the beginning of the test to test a particular scenario:

```
ledger.newApp(creator, appId, makeSchemas(16, 0, 0, 0))
ledger.appOptIn(pool, appId)
ledger.appOptIn(pooler, appId)

ledger.setHolding(pool, asset1, asset_1_reserves, false)                                                 
ledger.setHolding(pool, asset2, asset_2_reserves, false)                                                
ledger.setHolding(pool, liquidityAsset, uint64(0xffffffffffffffff)-(issued_liquidity_asset-1000), false) 

ledger.balances[pool].locals[appId]["a1"] = basics.TealValue{Type: basics.TealUintType, Uint: asset1}
ledger.balances[pool].locals[appId]["a2"] = basics.TealValue{Type: basics.TealUintType, Uint: asset2}
ledger.balances[pool].locals[appId]["lt"] = basics.TealValue{Type: basics.TealUintType, Uint: liquidityAsset}
ledger.balances[pool].locals[appId][makeOutstandingKey(liquidityAsset)] = basics.TealValue{Type: basics.TealUintType, Uint: 1000}
ledger.balances[pool].locals[appId][makeOutstandingKey(asset2)] = basics.TealValue{Type: basics.TealUintType, Uint: outstanding_asset_2_amount}

ledger.balances[pooler].locals[appId][makeExcessKey(asset2, pool)] = basics.TealValue{Type: basics.TealUintType, Uint: tc.excess_amount}
```

Note: I added the `appOptIn` method to the ledger to initialize the `locals` array in the balance record.

**Comment by tmc** [comment]
It may be more appropriate to factor these out to a tealtest package as to not pollute the logic package’s namespace.

**Comment by jannotti** [comment]
I have been making some of these changes by introducing a logictest package as a sibling of logic.  I'll link my in progress PR here soon.  It's part of the work to introduce something like transactions to AVM/Teal.  It moves the entire testledger from evalStateful_test.go into logictest/ledger.go.  Unfortunately, it's going to take some merge/rebase effort because I started my fork a while back.

**Comment by fergalwalsh** [comment]
Thanks for the update @jannotti, that sounds great! As I say I do have a working solution for now for the current project but it would be good to see this in a new package for future/broader use.

Good points re the mocked ledger. The way I see it it is fine for providing context for testing TEAL but it doesn't do the real ledgering. For the moment I'm fine with testing those aspects of transactions/groups as integration tests through the full node but exporting a better ledger for testing in the future does sound ideal. Will look forward to that.

**Comment by algoanne** [comment]
> Would this be possible? Is there any reason not to make this functionality public?
Yes, but we're reluctant to commit to public interfaces for tests, especially as things are changing a lot.
