### ISSUE TITLE
Investigate: goal support for signing LogicSig/Multisig transactions from different addresses

### ISSUE THREAD

**Issue by jasonpaulos** [algorand/go-algorand#2642]
## Summary
Investigate whether goal allows LogicSig and Multisig accounts to sign transactions if the sender of the transaction does not match the LogicSig/Multisig account address. If this is not currently possible, it should be fixed, since it is possible to rekey other accounts to LogicSig/Multisig accounts.

## Scope

If a fix is needed, the SDK PRs below can be used as a starting point:
* https://github.com/algorand/go-algorand-sdk/pull/230
* https://github.com/algorand/js-algorand-sdk/pull/408
* https://github.com/algorand/py-algorand-sdk/pull/216
* https://github.com/algorand/java-algorand-sdk/issues/240 (has not yet been fixed in Java)

**Comment by algoanne** [comment]
this was resolved by https://github.com/algorand/go-algorand/pull/3773
