### ISSUE TITLE
faster pingpong

### ISSUE THREAD

**Issue by brianolson** [algorand/go-algorand#2644]
## Problem

pingpong may currently be limited by the speed of doing API requests to kmd and/or this API connection within machine is inefficient and causes excess CPU load in testing.

## Solution

Improve pingpong to create key pairs internally and do signing within process. ( i.e. instead of using the kmd )

Keep key pairs as msgpack blob in current directory (or location based on flag) so that accounts can be re-used on a subsequent pingpong session.

## Urgency

This will improve testing of the system beyond 1000 TPS

**Comment by winder** [comment]
Having it in go-algorand is convenient for packaging and distribution, but I've always thought pingpong should be a standalone program built with an SDK.
