### ISSUE TITLE
Dev mode broadcast queue full

### ISSUE THREAD

**Issue by barnjamin** [algorand/go-algorand#2674]
### Subject of the issue

From the discord, nullun was testing the new dev-mode and found that if 100txns were sent he'd get a buffer queue full message:

> Just updated my sandbox, added DevMode to the template file, and tested it out. Sure enough made 50 transactions (50 blocks) and it took ~7 seconds. However trying to push it up to 100 transactions lead me to hitting 100 transactions and then getting the error algosdk.error.AlgodHTTPError: {"message":"broadcast queue full"}

https://discord.com/channels/491256308461207573/813198189334888469/870668018315833355

It looks like that message comes from not being able to pass  into this channel which is buffered to 100:
https://github.com/algorand/go-algorand/blob/66fbd60d63aa47227f3f5b567f07c3a772e85834/network/wsNetwork.go#L695

This may not be a bug and I didn't follow up to ask if it was a temporary condition

### Expected behaviour
No broadcast queue full

### Actual behaviour
broadcast queue full

**Comment by onetechnical** [comment]
Re-assigning to Carbon-11; adjustments to the broadcast queue could have wide implications.

**Comment by StylishTriangles** [comment]
I'm encountering the same issue, sometimes I am able to send more transactions, but this happens very often.
