### ISSUE TITLE
Metadata field for Asset

### ISSUE THREAD

**Issue by runvnc** [algorand/go-algorand#2714]
## Problem
https://github.com/algorandfoundation/ARCs/issues/3

## Solution

My understanding is the plan is to make massive changes to capabilities in the next few months such as having transactions generate other transactions and increasing the processing speed by a factor of 10.  If all of that is possible, maybe we can consider just adding a metadata field to Assets.  Not metadata hash, but metadata JSON.

**Comment by ChrisAntaki** [comment]
This would be incredibly useful!

**Comment by runvnc** [comment]
Right, I mean it seemed like a major change to me.. and I would not have
proposed it except for what seemed like a lot of other major changes going
on and the fact that there was always 1000 available for the transaction
notes.. which people seemed to be using to store the metadata.  Indicating
in my mind that people were going to try hard to store it on-chain
regardless of whether it was accommodated smoothly or not.. So I thought I
would just throw it out there to be considered in public on the off chance
you guys thought it could work.

**Comment by fabrice102** [comment]
There is a big difference between the note field and the ASA metadata field.
Only the note fields in the transactions in the last 1000 blocks are stored by non-archival nodes.
Access to all the note fields require an archival node (and an indexer for convenient).

In comparison, ASA fields are stored by all nodes, whether archival or not.

**Comment by runvnc** [comment]
I understand. Again just wanted the idea to be out there. Maybe if it were going to be possible it would need to have a significant cost tied to the size of the data stored there.  And most people would not need a ton of storage. Nothing like 1000.

**Comment by runvnc** [comment]
If the Metadatahash field were slightly longer, that could point to an IPFS CID for metadata, the URL could still link directly to the media, and then even having one small additional field like 4-8 bytes could allow for critical information (like MIME type as a binary ID for example) to be accessed directly with the asset.

**Comment by emg110** [comment]
Try [ipfs2bytes32](https://github.com/emg110/ipfs2bytes32 ), if IPFS default sha2-256 is used like 70% of IPFS network, then this can do the job.

**Comment by algoanne** [comment]
closing this old issue, which is mostly stale at this point - [arc 19](https://github.com/algorandfoundation/ARCs/blob/main/ARCs/arc-0019.md) is a standard solve, and there are other creative solutions out there.
