### ISSUE TITLE
waitForBlock is incorrect

### ISSUE THREAD

**Issue by jeapostrophe** [algorand/go-algorand#2716]
`waitForBlock` does not wait for the given block, but waits for the next block:

https://github.com/algorand/go-algorand/blob/master/daemon/algod/api/server/v2/handlers.go#L328
https://github.com/algorand/go-algorand/blob/master/daemon/algod/api/server/v1/handlers/handlers.go#L629

Even though the end-point is named "wait-for-block-after", the docs say --- https://developer.algorand.org/docs/reference/rest-apis/algod/v2/#get-v2statuswait-for-block-afterround --- "Gets the node status after waiting for the given round." meaning "/v2/status/wait-for-block/after/5" means "Gets the node status after waiting for round 5" (and that's the way the Indexer uses it)

This is easy to fix, just remove the `+ 1` on those two lines.

**Comment by jeapostrophe** [comment]
Discovered with devMode --- https://github.com/algorand/go-algorand/pull/2334#issuecomment-873033723

**Comment by brianolson** [comment]
There's existing software relying on the current behavior, so the fix will probably be to the documentation.

**Comment by jeapostrophe** [comment]
The incorrect behavior breaks the Indexer on the DevMode

**Comment by jeapostrophe** [comment]
(By breaks, I mean that it makes it so the "fast" DevMode is actually slower because every round takes 1 minute.)

**Comment by brianolson** [comment]
Ah, you mean that 'wait-for-block on devmode is different than wait for block in normal algod operation' ? Wait-for-block in regular mode has been a little confusing sometimes, sorry if I jumped to the wrong interpretation.

**Comment by jeapostrophe** [comment]
No, it's not different. It's just that on devMode, the next round isn't going to come, so the indexer will ALWAYS wait 1 minute between updates. So if you have an app that does "post txn, look for it on the indexer" then it will take 1 minute per loop, because the indexer uses waitForBlock to get the next one.

**Comment by gmalouf** [comment]
Fixed in #4910
