### ISSUE TITLE
Lacework Jenkins Job

### ISSUE THREAD

**Issue by algojack** [algorand/go-algorand#2724]
**Lacework**
This will be a part of a bigger Jenkins job (or can be a Jenkins job on it's own for now).
We already have a network report Jenkins integration with slack which we can re-use/use as an example for this one.
We discussed two ways of getting the info we need:
1. using official Lacework api
2. using slack api

**Acceptance criteria**
Start with Lacework APIs 

**Deliverables**
- Should return a well structured(json?) result about Lacework report.
- (stretch goal) Pagerduty critical alerts in another ticket

**Comment by onetechnical** [comment]
We have Lacework notifications, which is probably sufficient.
