### ISSUE TITLE
CI/CD CircleCI Jenkins Job

### ISSUE THREAD

**Issue by algojack** [algorand/go-algorand#2725]
**CircleCI**
This will be a part of a bigger Jenkins job (or can be a Jenkins job on it's own for now).
We already have a network report Jenkins integration with slack which we can re-use/use as an example for this one.
We discussed two ways of getting the info we need:
1. using official CircleCI api
2. using slack api

**Deliverables**
- Should return a well structured(json?) result about rel/nightly.
- (stretch goal) use test insights to get exact test failures (possible?)

**Comment by onetechnical** [comment]
I don't think this is a thing?
