### ISSUE TITLE
EvanBot: Network Report Jenkins Job

### ISSUE THREAD

**Issue by algojack** [algorand/go-algorand#2727]
**Network Report**
This will be a part of a bigger Jenkins job (or can be a Jenkins job on it's own for now).
We already have a network report Jenkins integration with slack which we can re-use/use as an example for this one.
We discussed two ways of getting the info we need:
1. using official Datadog api
2. using slack api

**Deliverables**
- Should return a well structured(json?) result about Network Report.
- disable current report that's going to #dev when there are no errors (only display on summarized report)
- Make an automated nightly test to see if it works (so we know when it doesn't)
- Number of hosts that have the error
- Feature: Add number of hosts effected/Organize it by host/Summarize it "better"

**Comment by algojack** [comment]
**Network Report slack bot**

- hide/don't display/send when there are no errors (only display on report)
- Make an automated nightly test to see if it works (so we know when it doesn't)
- Bot scans #devops-alerts and adds
- Number of hosts that have the error
- Feature: Add number of hosts effected/Organize it by host/Summarize it "better"

Needs to be able to be triggered by another slack bot, and return a well structured result to it.

**Comment by onetechnical** [comment]
Can be better, but is functional.
