### ISSUE TITLE
Fully specify rewards logic

### ISSUE THREAD

**Issue by algoradam** [algorand/go-algorand#276]
Some parts of our rewards logic are not fully described in the spec (or are described in a way that is impossible to understand). We should try to better specify rewards, in particular the logic around lazy evaluation and calculating rewards rates

**Comment by pzbitskiy** [comment]
Some info: https://www.algorand.com/resources/blog/rewards-technical-overview

**Comment by ian-algorand** [comment]
Will reopen if we hear specific complaints about this
