### ISSUE TITLE
Use ABI encoding support in goal

### ISSUE THREAD

**Issue by jasonpaulos** [algorand/go-algorand#2803]
## Summary
Add support in goal for sending app calls with encoded ABI arguments, and for viewing ABI encoded return values from app calls.

## Scope
Specifically:
* Add support for passing and encoding ABI method selectors and values into `goal app` calls, similar to the existing `--app-arg` support for encoding strings, integers, and other values ([see the implementation](https://github.com/algorand/go-algorand/blob/734e727e677c2c574410d096962d3c86830f1899/cmd/goal/application.go#L198-L236) for a complete set).
  * Proposal: support a new encoding type for ABI values: `abi:<abi-type-string>:<abi-value-as-json>`
    * `<abi-type-string>` would be the serialized ABI type string, e.g. `(bool,byte[],uint64)`
    * `<abi-value-as-json>` would be a JSON string that represents an ABI value. Together with the type string, an ABI value can be properly formed. The mapping from schema type to acceptable JSON values would be:
      * ABI uint/byte: accepts JSON integers, throws error if number is outside acceptable range.
      * ABI ufixed: accepts JOSN decimal numbers, throws error if number is outside acceptable range. For example, a `ufixed64x2` should accept a decimal with up to 2 digits after the decimal, e.g. `1.99`.
      * ABI bool: accepts JSON boolean values
      * ABI string: accepts a JSON string, or a JSON array containing the raw bytes this string should contain. This allows non UTF-8 characters to be encoded
      * ABI address: accepts a JSON string containing a base32 Algorand address with checksum, throws error if address is invalid
      * ABI tuple: accepts a JSON array
      * ABI static/dynamic arrays: accepts a JSON array, or **if this is an array of bytes**, additionally accept a JSON base64 encoded string, since this is the de facto format for embedding binary data in JSON
    * For example, the JSON  string `[true, [0, 1, 2], 17]` is a valid encoding of the type `(bool,byte[],uint64)`. An equivalent encoding using base64 for the contained byte array would be `[true, "AAEC", 17]`. Both should be accepted.
    * The reason behind using JSON for this is because it's already a well-known format by developers, and we won't have to implement a complex parser just to make this work.
  * Complete example: we should be able to pass `--app-arg "abi:(bool,byte[],uint64):[true, [0, 1, 2], 17]"` as a flag to goal app calls
* Add a way to view the return value of an app call. We are using `log` for this, but this may require an ABI spec change to explicitly specify the format of the return value.

**Comment by algoanne** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Algorand-Main-Workspace-5ea71fda6d554d53dda36f16/issues/algorand/go-algorand/2803?planning-poker) with ZenHub @ahangsu @algochoi @algorandskiy @jannotti @jasonpaulos @shiqizng

**Comment by jannotti** [comment]
We probably need one more: `--app-arg "abi-method:add(uint,uint):uint" which would put the method selector for the given method signature in the app-arg.

Should we support `--app-args` (note the plural) that is used something like: `--app-args "abi:add(uint,uint):3,4" where we pack all of the app args according to abi rules? [0] becomes the selector, [1] is 3, [2] gets 4

**Comment by jasonpaulos** [comment]
Good point about support method selectors and proper placement into args. I wonder if at this point we want a new subcommand dedicated to this, something like:
* `goal app method --method "add(uint64,uint64)uint64" --arg 3 --arg 4`

**Comment by ahangsu** [comment]
One question pops up: Previously `--app-arg` was parsed with `StringSliceVar`, which will let split the string by commas. This contradicts with our design (consider example input `--app-arg "abi:(uint32,uint32):[1,1]"`.

I have a workaround in my head now: If we enforce to wrap the `<abi-type-str>:<abi-value-as-json>` with quote characters like following: `--app-arg "abi:\'(uint32,uint32):[1,1]\'"`, then by https://github.com/spf13/pflag/pull/59, this should be resolved.

Please let me know your suggestions and thoughts, thanks!
