### ISSUE TITLE
Modify release PR creator to auto-tag reviewers

### ISSUE THREAD

**Issue by onetechnical** [algorand/go-algorand#2814]
## Problem

We have a job to create the release PR, but it currently requires some manual work to set reviewers. We should go ahead and automatically assign reviewers.

go-algorand PR Jenkinsfile that needs to be modified: https://github.com/algorand/go-algorand-ci/blob/master/jenkins-tasks/automated-release/Jenkinsfile

## Solution

Since we're already using the github API to generate this, just modify it to also assign reviewers. We can query for members from the devops team, strip the service account, and assign reviewers.

## Dependencies

Github API access (should already be present in the job).

## Urgency

Low; it's just an additional step in the process.

**Comment by bricerisingalgorand** [comment]
Didn't we try to do this before in go-algorand-ci?

**Comment by onetechnical** [comment]
> Didn't we try to do this before in go-algorand-ci?

We did try this with CODEOWNERS, but I don't think it worked. That would also go across all go-algorand PRs, which we don't want to do.
