### ISSUE TITLE
Missing Fedora Dependencies when Installing from Source

### ISSUE THREAD

**Issue by leb4r** [algorand/go-algorand#2815]
### Subject of the issue

While [building this project from source](https://github.com/algorand/go-algorand#linux--osx) in a Fedora 34 toolbox container, I was running into the issue described in https://stackoverflow.com/questions/56547970/go-pkg-tool-linux-amd64-link-running-gcc-failed-exit-status-1-usr-bin-ld-can.

The [second answer](https://stackoverflow.com/a/67430511/7415549) outlining the existence of the `glibc-static` package, solved the issue. I had to install `glibc-static` and `libstdc++-static` before being able to install from source. 

The image is hosted at `registry.fedoraproject.org/fedora-toolbox:34` .

**Comment by algolucky** [comment]
Looking into this more, I wonder how relevant is this now that there is RPM repository and is now the preferred method of installation? When I previously opened this, I was building Algorand from source. 

I've searched through a few repos, and I only see one place where `install_linux_deps.sh` is being used: 
https://github.com/algorand/go-algorand/blob/91095fa6bdccb11ec133c38da68fdd92fa611b6c/scripts/configure_dev.sh#L72

**Comment by algolucky** [comment]
Testing against Fedora 36 using the following Dockerfile:

```dockerfile
FROM registry.fedoraproject.org/fedora-toolbox:36

ENV GOPATH="/go"

ENV PATH="${GOPATH}/bin:${PATH}"

RUN sudo dnf install -y git go make && \
    git clone https://github.com/algorand/go-algorand.git && \
    bash go-algorand/scripts/install_linux_deps.sh && \
    make -C go-algorand install
```

There is a new errror: 

```
#5 112.2 libtool is required, but wasn't found on this system
```

go-algorand will no longer build natively on Fedora 34 or 35 because of the Go version requirement. 36 has an appropriate version available.

**Comment by jsgranados** [comment]
Closing as ticket seems outdated.
