### ISSUE TITLE
Better Handling for Repetitive Errors

### ISSUE THREAD

**Issue by winder** [algorand/go-algorand#287]
It's hard to evaluate network health because there are too many repetitive error messages / false positives. For example on the following networks today:

**mainnet**
Over 100,000 errors, they all seem to follow this pattern:
> node.GetPendingTransaction: cannot get consensus params for latest round <round>

**testnet**
Over 3.5 million errors. A big fraction of that is legitimately related to the recent stall, but there are also many hundreds like this:
> failed fetching block <round>, trying again in 0.5 seconds

**Comment by tsachiherman** [comment]
The `failed fetching block , trying again in 0.5 seconds` error is originated in the indexer and is a minor issue. We might consider lowing that into a warning instead of an error.

**Comment by rotemh** [comment]
It's actually more concerning than that. This error should, in theory, never be raised. see PR #288 for more details.

**Comment by rotemh** [comment]
dup of #203
