### ISSUE TITLE
Update terraform-inventory to support terraform 0.12 

### ISSUE THREAD

**Issue by tsachiherman** [algorand/go-algorand#289]
Our existing private network deployment is using terraform-inventory which doesn't supports terraform 0.12; we need to either:
- fix terraform-inventory
- find an alternative solution that would not require us to use it

**Comment by pzbitskiy** [comment]
terraform-inventory 0.9 works just fine with terraform 0.12. @derbear updated installation script for Ubuntu, no additional works needed.
