### ISSUE TITLE
Add some kind of rate limiting to dispensers

### ISSUE THREAD

**Issue by onetechnical** [algorand/go-algorand#2892]
## Problem

We've had to refill the dispenser with 40,000 algos over the past few days. The danger is of if there is abuse of the dispenser. Burning a million algos a month would be problematic. This use case might be temporary, but does highlight a need to institute some kind of rate limiting.

## Solution

??? Many ways to handle this; have to decide how we want to do it.

**Options:** 
1. Ethereum's method: https://faucet.rinkeby.io/
2. Can limit by IP. (Size: Small) 
3. Can track account sent to and limit total sent. (easier for the new dispenser, harder for the legacy one.)

4. Can swap captchas in case it's easier, or step up the difficulty (we've already attempted this) 

Can be app side, or it can be in CloudFlare traffic limiting.

## Acceptance criteria
Limit dispensing by IP for TestNet and BetaNet
Document and review solution with team 

## Dependencies

Tooling (CloudFlare, other uses)

## Urgency

Medium-High. People who want to develop on this need (testnet) Algos!

**Comment by yaovi-a** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Algorand-Main-Workspace-5ea71fda6d554d53dda36f16/issues/algorand/go-algorand/2892?planning-poker) with ZenHub @algobarb @algojack @bricerisingalgorand @egieseke @onetechnical

**Comment by algojack** [comment]
i definitely think we should decide on the way we do this before voting on implementing that way. Also are we sure this is team hyper flow or is this better done by another team?

In either case I would suggest that we don't maintain two dispensers unless there's a good reason.

i personally like the social media public post idea, with premade example posts, but as long as they contain the word algorand and wallet address, it seems ok for me.

As far as rate: even if we just give 1 algo, that's 1000 of transactions. Let's say we need non-zero transactions for testing, that's still 500. So 1 algo per day might be enough? make it 10 and that's for sure should be enough per day in my opinion.

**Comment by onetechnical** [comment]
> i definitely think we should decide on the way we do this before voting on implementing that way. Also are we sure this is team hyper flow or is this better done by another team?

Depends on the solution, but if it's an infrastructure solution, I'd say it's the Hyper Flow team. If it's the new dispenser as well. If it's the old dispenser it's a toss up.

> In either case I would suggest that we don't maintain two dispensers unless there's a good reason.

Trickiness: new dispenser is written in Python, while the old is in golang. The old may be used by people running custom networks or maintaining legacy dispensers. If we generalize the Python one, we will need to have configurable handling to disable and not display USDC support, unless it's on TestNet.

> i personally like the social media public post idea, with premade example posts, but as long as they contain the word algorand and wallet address, it seems ok for me.

We have to be careful about being too spammy, but if it works for Ethereum, it's probably generally acceptable.

> As far as rate: even if we just give 1 algo, that's 1000 of transactions. Let's say we need non-zero transactions for testing, that's still 500. So 1 algo per day might be enough? make it 10 and that's for sure should be enough per day in my opinion.

Our current default is to provide 10 algos a turn.

**Comment by jannotti** [comment]
Keep in mind that it's not just txn fees that you need algos for. Accounts
have 0.1 Algo min balance requirement. Each asset is another 0.1. Apps can
be as much as a few algos to create, I think.

**Comment by yaovi-a** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Algorand-Main-Workspace-5ea71fda6d554d53dda36f16/issues/algorand/go-algorand/2892?planning-poker) with ZenHub @onetechnical
