### ISSUE TITLE
Test Network Performance with 2.5 secs block latency

### ISSUE THREAD

**Issue by yaovi-a** [algorand/go-algorand#2915]
## Problem

To make the appropriate adjustments for 2.5 secs block latency, we need understand how the network will perform under 2.5 seconds block latency. 

## Solution

Adjust the block latency to 2.5 seconds and measure the network performance. 
Metrics that define optimal network performance will need to be defined to run gauge the impact of 2.5 seconds block latency.

**Comment by algobolson** [comment]
TODO: define this task; what do we want to measure?
