### ISSUE TITLE
goal fails to install/list participation keys

### ISSUE THREAD

**Issue by tsachiherman** [algorand/go-algorand#294]
### Subject of the issue
Using goal would fail to install or list participation keys when installed using Debian package.
The algod is running as user `algorand` and creating the `mainnet-v1.0` directory with 0700. When the user invokes goal, it tries to access the directory directly and fails.

### Steps to reproduce
Install debian package.
Use a non-root account to install/list existing participation keys.

### Expected behaviour
All good

### Actual behaviour
Fail to access `mainnet-v1.0` directory due to permission constrain.

### Potential fix paths
1. Update the documentation to instruct end users to modify the mainnet-v1.0 directory mode.
2. Have a code workaround that would change the directory mode.
3. Add new API entry point so that goal would be able to access the same functionality via the http endpoint. (maybe by using a one-shot ephermal token ? )

**Comment by ian-algorand** [comment]
Tsachi is going to list out some possible solutions and we can decide what we want to do there.
