### ISSUE TITLE
Add version field to --msig-parms flag of goal clerk send command

### ISSUE THREAD

**Issue by ryanRfox** [algorand/go-algorand#2951]
## Problem

Currently, the `goal clerk send` command has a flag to add the multisig parameters formatted "[threshold] [Address 1] [Address 2] ..." but is does not include the value "version". Currently, the flag constructs the multisig using a hardcoded value of 1 (the only valid version). In the future, the introduction of a new multisig version would require refactoring this flag. 

## Solution

Modify the string to be "T=[threshold] V=[version] [Address1] [Address2] ..."

## Dependencies

Proposed solution is a breaking change for the existing `--msig-parms` flag, so documentation must be updated.

## Urgency

Low - Currently only version=1 multisig is supported. This is a forward looking fix.

**Comment by winder** [comment]
I think we would add this if a second version is ever created.
