### ISSUE TITLE
New opcode: json_ref

### ISSUE THREAD

**Issue by algoanne** [algorand/go-algorand#2960]
Create the new opcode `json_ref` that takes in a json string and a key name, and yields the value of that key in the json string. Has one immediate argument that can be either Uint or String for the opcode.

**Comment by jannotti** [comment]
Some design choices to consider:  Should we have two opcodes? json_ref_string and json_ref_int, so we can be more precise about the stack after executing?  Might we even need json_ref_int to return two numbers, a sign and an int, so we can handle negative numbers?  Do we panic if a field is a float?

**Comment by barnjamin** [comment]
would this handle ARC2 note fields directly or will you need to lop off the !json bits first?

**Comment by jannotti** [comment]
I wouldn't know another about them, so you'd have to trim it down to just
json first.

**Comment by jannotti** [comment]
We need to be thoughtful about spec'ing our parsing exactly. Read this first. https://seriot.ch/projects/parsing_json.html
