### ISSUE TITLE
Make goal easier to use

### ISSUE THREAD

**Issue by algoanne** [algorand/go-algorand#2980]
## Problem

As a beginner to Algorand, running `goal` commands is the easiest way to start interacting with the blockchain. However, there currently exist several barriers that make it more difficult than it could be. 

This problem was initially brought up in #2904. 

## Solution

Multiple things we can do to make `goal` easier to use: 
- make it easier to point to remote algod’s
- migrate use of v1 APIs to v2 (`goal` should be using v2 anyway)
- offer ways to sign transactions besides kmd
- (maybe) take `goal` out of go-algorand 

## Urgency

Medium. Would make Algorand much more accessible to beginners, removing a barrier to entry for interested devs. Would also make using `goal` less annoying for everyone who doesn't want to be running a node all the time, catching up every time they start it again.

**Comment by barnjamin** [comment]
Should I close the issues I filed for this?

**Comment by algoanne** [comment]
@barnjamin no; I added them under this epic - and thanks for contributing them!

**Comment by algoanne** [comment]
need to think about this in the context of the beginning of a dev's journey in Algorand - when should they be pointed to use sandbox instead of starting up a node?
