### ISSUE TITLE
Add "address" to "ApplicationParams" of algod API schema

### ISSUE THREAD

**Issue by ryanRfox** [algorand/go-algorand#2989]
## Problem

The algod API for `/v2/applications/{application-id}` does not return the address for the application-id. This field is returned by `goal app info` (although it's named [account](https://github.com/algorand/go-algorand/blob/master/cmd/goal/application.go#L978)).

## Solution

- Add "address" to [#/components/schemas/ApplicationParams](https://github.com/algorand/go-algorand/blob/master/daemon/algod/api/algod.oas3.yml#L780)

## Dependencies

None

## Urgency

Higher than _nice to have_; this feels like an oversight. Workaround within the SDKs: calculate the address based on the appID. Sample code in Python:
```
def getAppAddress(appID: int) -> str:
    toHash = b"appID" + appID.to_bytes(8, "big")
    return encoding.encode_address(encoding.checksum(toHash))
```

**Comment by jannotti** [comment]
This should appear as a local function to call, similar to getting logicsig
address from code, not from api.

**Comment by tzaffi** [comment]
I agree with @ryanRfox . Maintaining parity with [goal functionality](https://github.com/tzaffi/go-algorand/blob/master/cmd/goal/application.go#L1036) is nice to have. Though each API can calculate the hash independently, it seems like an application's address is so fundamental that it should be provided by `algod`.

**Comment by jannotti** [comment]
I disagree. a) you don't need that code. The SDKs all already have the function. b) goal isn't the thing that the api should try to emulate. goal is _using_ the api to get the app id and then calculating the address with an internal function. This makes it convenient for use by humans and shell scripts, neither of which can calculate hashes well. But all api consumers can.

**Comment by winder** [comment]
I believe the APIs are now consistent because the creator was removed from the goal API.
