### ISSUE TITLE
Memory leak in unused metric label feature

### ISSUE THREAD

**Issue by winder** [algorand/go-algorand#3040]
### Subject of the issue

There is a dynamic "label" feature in `Gauge` and `StringGauge`. The label is a string argument when collecting metrics used as a key into the gauge dataset. If we ever use the feature for something unbound like round, address or session ID. At that point memory would grow unbounded until a crash.

A couple of possible solutions (we would need to do this for both gauges):
1) Remove the `labels` feature (it seems to only be used by `segment.go:EnterSegment` and that function is not called anywhere).
2) Return from this function immediately when `len(valueIndices) <= 1`
3) Set `maxMetricRetensionDuration` to something very large in `config.json`

Earlier discussion here: https://github.com/algorand/go-algorand/pull/2508#discussion_r667961227

### Acceptance criteria 
Remove `labels` that can be associated with metrics. 
Why: using the `labels` may lead to memory issues that lead to the node crashing. 

### Priority 
Low / Tech debt

**Comment by iansuvak** [comment]
Started working on this with approach #1 and noticed that `Counter`s also support labels and that unlike `Gauge`s they do use the labels for `networkConnectionsDroppedTotal` in `wsNetwork.go` so if the same memory leak concern applies there as well the simple solution of removing labels functionality won't work. 

Should we deal with both of them at the same time or limit this issue to just `Gauge` struct which would further decrease parity between the two?
