### ISSUE TITLE
Add forward secrecy to State Proofs 

### ISSUE THREAD

**Issue by rotemh** [algorand/go-algorand#3061]
## Context
In order to achieve forward security Stateproof's ephemeral keys must be deleted from the Database after use.

## Acceptance criteria
The node removes the ephemeral private keys after signing a statproof.

**Comment by algonoah** [comment]
Closed as duplicate of https://app.zenhub.com/workspaces/algorand-main-workspace-5ea71fda6d554d53dda36f16/issues/algorand/go-algorand/3622
