### ISSUE TITLE
SDK - Update API Client to support Get Transaction Merkle Proof endpoint

### ISSUE THREAD

**Issue by rotemh** [algorand/go-algorand#3117]
## Context:
currently, algod supports a REST endpoint that returns proof of a specific transaction inside a block.
The new statproofs keys introduce merkle tree changes that imply changes on the proof that is being returned.
Thus, the REST endpoint is going to change

## Acceptance Criteria:
the SDKs should support these API changes.

**Comment by algoidan** [comment]
Context:
currently, algod supports a REST endpoint that returns proof of a specific transaction inside a block.
The new statproofs keys introduce merkle tree changes that imply changes on the proof that is being returned.
Thus, the REST endpoint is going to change

Acceptance Criteria :
the SDKs should support these API changes.
