### ISSUE TITLE
gload with both parameters from stack

### ISSUE THREAD

**Issue by hernandp** [algorand/go-algorand#3121]
Hello guys, 

Considering that in TEAL5 you can execute loops, and that stateless contracts have access to global scratch space from a transaction in a group,  I would like to iterate over Slots 0...N of a TX#0 where I store an array of values for stateless checks. 

Unfortunately, the `gloads` opcode allows to dynamically set the transaction index from stack, but not the scratch slot, so If i want to traverse through slots I would need to synthesize TEAL code when the transaction group is generated.

Any possibility to include a flexible `gload` opcode for a case like this?

**Comment by jannotti** [comment]
This is going into the AVM 1.1 feature branch very soon.
