### ISSUE TITLE
Java SDK 1.11.0-beta-1 Release 

### ISSUE THREAD

**Issue by yaovi-a** [algorand/go-algorand#3193]
Java SDK release for ABI support

**This is a beta release.**

https://algorand.atlassian.net/wiki/spaces/DEVOPS/pages/1858174977/Java+SDK+Release+Process

Primary differences:

Use version 1.11.0-beta-1
When publishing the github release, mark it as a pre-release

**Comment by egieseke** [comment]
Completed Release https://github.com/algorand/java-algorand-sdk/releases/tag/1.11.0-beta-1
