### ISSUE TITLE
Creating Fungible Asset Scarcity

### ISSUE THREAD

**Issue by ObiajuluM** [algorand/go-algorand#3197]
## Problem

Creating Fungible Asset Scarcity. 
## Solution

ASA transactions by default have transaction fees settled in Algos a brilliant choice. I suggest that there should be an option specified upon asset creation aptly named `asset_fee` its value can't be modified after asset creation and its value will be calculated in percentages for example if set as 10, any time the asset is being transacted with 10% of the asset will be deducted and sent to the reserve address or any other address if specified or better still a **universal burn address**.

A universal burn address is an address created by the blockchain that no one has access to, the address will be able to hold all assets created.

Now, this doesn't mean that asset transaction fees will stop being paid in Algos it just means that for each asset transaction a specified percentage of the asset will be deducted.

## Dependencies

**PROS**
1. Assets with this option enabled will be deflationary and have increased value over time.
2. Central bank digital currency anchors can receive the fee as compensation.

**CONS**
1. This will require a complete overhaul of the network which is no easy feat.
    * `params` will have a new variable `params.UBA` which can be used below
    * There will be a new optional field called 'fee_address'  specified upon asset creation which can be changed later on by the manager address.
    * The blockchain will be forked or updated to add a new global address, `universal burn address` or we will use anyone that has been there, I don't know.
    * The limit of 1000 assets per account will be set to limitless for the `UBA` 
    * The indexer and algod clients functions will return more parameters in their JSON response such as  `asset_fee`, `fee_address`.
2. Bad actors can set fees extremely high and set the `fee_address` as their own personal account.

## Urgency

There is no urgency, it's just a suggestion.

PS: I work with Algorand python SDK, I'm sorry if you don't understand the lingo used here

**Comment by ObiajuluM** [comment]
I'm available to answer any questions.

**Comment by barnjamin** [comment]
This sounds like something that would be good for an ARC spec rather than embedded in the protocol

https://github.com/algorandfoundation/ARCs/tree/main/ARCs

**Comment by algoanne** [comment]
closing this issue in favor of the ARC spec. Thanks for contributing!
