### ISSUE TITLE
Investigate Catchup Scripts

### ISSUE THREAD

**Issue by AlgoStephenAkiki** [algorand/go-algorand#3206]
Investigate the catchup scripts located in the algonet repository and determine how to apply them to a jenkins job.  The result of this should be that a jenkins job automatically runs the catchup test scripts to determine if they are broken or not.

Acceptance Criteria:

Jenkins Job that runs and automatically reports the success or failure of the catchup tests.

**Comment by yaovi-a** [comment]
@AlgoStephenAkiki what are we trying to achieve here?
