### ISSUE TITLE
transactions accepted by node but not broadcasted

### ISSUE THREAD

**Issue by nining** [algorand/go-algorand#3254]
### Subject of the issue

Recently I have too many transactions  accepted by node but not broadcasted.

### Your environment

$ algod -v
12884901889
3.0.1.stable [rel/stable] (commit #b619b940)
go-algorand is licensed with AGPLv3.0
source code available at https://github.com/algorand/go-algorand

$ cat /etc/issue
Ubuntu 20.04.3 LTS \n \l

### Steps to reproduce

First I use node RPC to send transaction and got successful response.  When I query the transaction, the node said it could not find such transactions.

These happened very often in these days.

**Comment by winder** [comment]
Is this still an issue?

Could you describe what you're doing and how you've determined that the issue is related to the node broadcasting transactions?
