### ISSUE TITLE
crypto parameters and dependence on config params

### ISSUE THREAD

**Issue by algonautshant** [algorand/go-algorand#3257]
In an effort to separate cryto package from config, the dependance of crypto on the consensus parameters is broken. 
However, some dependance remains for testing purposes. 
The task here is to move any tests that depend on the consensus params outside of the crypto package. 
e.g. crypto/compactcert/builder_test.go

Moreover, hard-coded values in the crypto tests need to be replaced by the appropriate variables, whenever applicable. 
 e.g. TestConsensusCompactCertParams (see comments in https://github.com/algorand/go-algorand/pull/3181)

**Comment by algoidan** [comment]
once https://github.com/algorand/go-algorand/pull/3991 will get merged into the feature branch. crypto package will no longer reference the config package.
