### ISSUE TITLE
Look at upgrading dependent repositories to use golang 1.17

### ISSUE THREAD

**Issue by onetechnical** [algorand/go-algorand#3293]
We have a few golang repositories we incorporate, that should be updated to golang 1.16. Once we do so, we will need to update our go.mod/sum to incorporate the new hash.

```
        github.com/algorand/go-codec/codec v0.0.0-20190507210007-269d70b6135d
        github.com/algorand/go-deadlock v0.2.1
        github.com/algorand/graphtrace v0.0.0-20201117160756-e524ed1a6f64
        github.com/algorand/oapi-codegen v1.3.5-algorand5
        github.com/algorand/websocket v1.4.4
        github.com/algorand/xorfilter v0.2.0
```
The following was already done:
~~github.com/algorand/msgp v1.1.48~~

This ticket is to track these dependencies, as well as the needed change to this repository, once the modules are updated.

Try to update the submodules, then update go-algorand, do a build and run tests.

**Comment by onetechnical** [comment]
Some of these may already be done (like mgsp).

**Comment by jsgranados** [comment]
Closing. We have transitioned over to golang 1.20
