### ISSUE TITLE
Sync Time increasing despite being fully synced

### ISSUE THREAD

**Issue by nullun** [algorand/go-algorand#3295]
### Subject of the issue

Since the latest stable release (3.2.1) users have reported in the Discord channel that the Sync Time continues to increase despite the node being fully synced with the network. I have recompiled and found the same result using rel/stable (commit #b6cbbf34)

### Your environment

12885032961
3.2.1.dev [rel/stable] (commit #b6cbbf34)
go-algorand is licensed with AGPLv3.0
source code available at https://github.com/algorand/go-algorand

Last committed block: 17917527
Time since last block: 3.4s
Sync Time: 592.5s
Last consensus protocol: https://github.com/algorandfoundation/specs/tree/bc36005dbd776e6d1eaf0c560619bb183215645c
Next consensus protocol: https://github.com/algorandfoundation/specs/tree/bc36005dbd776e6d1eaf0c560619bb183215645c
Round for next consensus protocol: 17917528
Next consensus protocol supported: true
Last Catchpoint: 
Genesis ID: mainnet-v1.0
Genesis hash: wGHE2Pwdvd7S12BL5FaOP20EGYesN73ktiC1qzkkit8=

Linux Mint 20.2 Cinnamon | kernel 5.4.0-90-generic

### Steps to reproduce

1. Compile latest stable branch and start the node.
2. Type `goal node status` to view Sync Time increasing.

### Expected behaviour

Sync Time should reset to 0.0 once up-to-date and synced with the network.

### Actual behaviour

Sync Time continues to go up.

**Comment by Vytek** [comment]
Same issue on:  4.19.0-18-amd64 #1 SMP Debian 4.19.208-1 (2021-09-29) x86_64 GNU/Linux

Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster

**Comment by vipeeerr** [comment]
Same here in Ubuntu. Two different machines with the same issue. The sync time is going up indefinitely after the fast catchup.

**Comment by winder** [comment]
Resolved by #3299
