### ISSUE TITLE
Cucumber tests for `min-balance`

### ISSUE THREAD

**Issue by tzaffi** [algorand/go-algorand#3316]
# Introduction

https://github.com/algorand/go-algorand/pull/3287 has introduced `min-balance` to the response of `algod`'s `/v2/accounts/{{ACCOUNT}}` as well as to the `goal account info`.  "For free", it is also introduced into the Python SDK's `account_info()` method. We'll need to implement this functionality in all our other SDK's. To ensure that the SDK's behave as expected, we should adhere to a spec that is defined in a cucumber test.

# Output

Cucumber test that describes what the `min-balance` field should look like when calling `account_info()`

**Comment by ahangsu** [comment]
If I am understanding it correctly, I suppose it should sit in https://github.com/algorand/algorand-sdk-testing?

**Comment by tzaffi** [comment]
Closing in favor of https://github.com/algorand/algorand-sdk-testing/issues/155
