### ISSUE TITLE
Design: Parallelizing performance tests

### ISSUE THREAD

**Issue by yaovi-a** [algorand/go-algorand#3426]
## Context
Network performance tests are run serially, and this can be time consuming. Waiting for tests to finish so that we can run the next test is not productive. 

## Objective 
The goal here is to produce a design document detailing how we can run more tests in less time or parallelizing testing.

## Value Add 
Reduce time to test multiple scenarios. 

## Design notes 
Consider how we can shorten DNS 
Come up with a new naming structure for the tf state file name
Consider running the job on a separate jenkins agent 

https://docs.google.com/document/d/1eZdl8ce84SfcDkNU1WIXgRav4Q9rlkl0OQeK9qauVwE/edit#

## Success criteria 
- Produce design document to run multiple test scenarios simultaneously 
- Review design document with Performance team 
- Create a follow up story for implementation

**Comment by algobarb** [comment]
Working on the Parallel Performance Tests Design using the design template: https://docs.google.com/document/d/1ahDnW2Jl9x47M4rqt78xi7UhwHOShTJadideA4HdGOU/edit#

**Comment by algobarb** [comment]
Reviewed Design with the Hyper-Flow team and will organize the new ideas on the design doc and create stories out of them.

**Comment by algobarb** [comment]
Epic - Implement Parallel Performance Tests
https://app.zenhub.com/workspaces/algorand-main-workspace-5ea71fda6d554d53dda36f16/issues/algorand/go-algorand-internal/1888
