### ISSUE TITLE
Support 320 rounds: Implement online accounts db manipulation 

### ISSUE THREAD

**Issue by yaovi-a** [algorand/go-algorand#3430]
### Context
This is part of a larger effort for the ledger refactoring project to support 320 rounds. 

### Objective

* Store online account history: balance, voting data
* Online accounts tracker: commit + lookup
* Lookup online account data for found N
* Lookup top N accounts for compact cert

### Success criteria

Unit tests added for insertion and lookup.

**Comment by algorandskiy** [comment]
fixed in algorand/go-algorand#3814
