### ISSUE TITLE
Feature Network: Access documentation

### ISSUE THREAD

**Issue by yaovi-a** [algorand/go-algorand#3444]
## Context
Once we are ready to launch the feature network to third party users and developer, we need to document how they can access the network. 

## Objective 
Work with DevRel to capture a detailed description of how anyone can access a feature network. 

## Value Add 
Without the this documentation, external community members and third party wouldn't be able to access the feature network. 

## Success criteria 
Detailed documentation capturing how to access the feature network posted on the Algorand developer portal.

**Comment by algojack** [comment]
this issue was not done, not sure why it's closed. @yaovi-a
