### ISSUE TITLE
Test plan for 320 rounds lookback

### ISSUE THREAD

**Issue by yaovi-a** [algorand/go-algorand#3471]
Tests

https://docs.google.com/document/d/1jEYSdVBdB39bH2LeLUASVfopHWWVZrReVFE7asHxlNw/edit

**Comment by algorandskiy** [comment]
The test plan prepared: https://docs.google.com/document/d/1jEYSdVBdB39bH2LeLUASVfopHWWVZrReVFE7asHxlNw

Need to create tickets and assign
