### ISSUE TITLE
Provide mappings between layers (PyTeal, TEAL, PC) 

### ISSUE THREAD

**Issue by algoanne** [algorand/go-algorand#3474]
**Context**
PyTeal is a language that generates TEAL, intended to be easier for a human to write than TEAL. The TEAL can then be compiled, executed, debugged using the debugger. However, if an error is found on a certain line of TEAL, there is no way for the developer to know which line of PyTeal caused the error. 

Separately, when writing tests of TEAL programs, it can currently be difficult to get useful outputs from the tests - when the test fails, there's no easy way to know which line of TEAL the test failed on. 

The above two problems are grouped together in this epic because they both involve easier debugging and mappings, and can hopefully be solved thoughtfully and with minimal redundancy in the solutions. 

**What are you looking for?**
A source map from TEAL to PyTeal mapping lines of the one to the other. 
A mapping from the Program Counter to TEAL.

**Comment by MetaB0y** [comment]
FWIW: somebody from PyTEAL already works on source mapping and there is decent progress: https://github.com/algorand/pyteal/pull/157
