### ISSUE TITLE
Revert Go lang v1.16 support to v1.14

### ISSUE THREAD

**Issue by yaovi-a** [algorand/go-algorand#3501]
## Context
We discovered a runtime issues on go lang v1.16.11 that leads to a performance regression on go-algorand v3.3.0 release. Consequently, we need kill the upcoming stable release and push a new release with the former go lang version (v1.14.7) 

## Objective 
There was a lot of changes that went into support go lang v1.16 and those changes need to be reverted for the next go-algorand release. 

Figure out what changes were made that need to be reverted for go lang v1.14

- [x] go-aglorand changes
- [x] go-aglorand-ci changes 
- [x] Indexer changes 
- [x] Algonet 
- [x] Sandbox

## Value Add 
Support reverting changes that are currently leading TPS performance regression in v1.16

## Success criteria 
All changes have been, and we can safely return to go lang v1.14

**Comment by algojack** [comment]
parsed through our repos for backing out 1.16. Here are the results that need to be backed out (at least partially):
go-algorand
https://github.com/algorand/go-algorand/pull/2825 - Changing golang version to 1.16.11 in go-algorand
(also has partition linter on 1.16, but i don’t think we need to back it out)
go-algorand-ci
https://github.com/algorand/go-algorand-ci/pull/237 - update CICD pipeline to golang version 1.16.11
https://github.com/algorand/go-algorand-ci/pull/203 - Network Monitor
indexer
https://github.com/algorand/indexer/pull/806/files - Upgrade golang to 1.16
https://github.com/algorand/indexer/pull/798 - Add libboost-math-dev to mule’s Dockerfile
algonet and sandbox had nothing on 1.16

**Comment by algojack** [comment]
Created PRs to revert:
https://github.com/algorand/go-algorand-ci/pull/264
https://github.com/algorand/go-algorand/pull/3506
https://github.com/algorand/indexer/pull/841
