### ISSUE TITLE
Remove MaxMinBalance

### ISSUE THREAD

**Issue by yaovi-a** [algorand/go-algorand#3503]
## Context
In the go-algorand code, there's variable, MaxMinBalance, that sets a limit on the maximum minimum balance that accounts reach. The MaxMinBalance essential caps the minimum balance but it isn't clear why the MaxMinBalance exist. 

There's a few theories for the existence of this ceiling, but the ceiling is currently preventing us from implementing unlimited assets/apps. As an accounts' assets or apps grow, so will the minimum balance. 

## Objective 
We need to the following: 

- [ ] What was the original purpose behind the MinMaxBalance?

- [ ] Delete the MinMaxBalance

## Value Add 
This will unblock an accounts' ability to support a higher number of assets/apps

**Comment by tsachizehub** [comment]
already handled in https://app.zenhub.com/workspaces/algorand-main-workspace-5ea71fda6d554d53dda36f16/issues/algorand/go-algorand/3460
