### ISSUE TITLE
Automate PR title checking with Github actions

### ISSUE THREAD

**Issue by yaovi-a** [algorand/go-algorand#3521]
## Context
When automating release notes, a critical part of this is making sure that PRs are labeled with 'New Feature', 'Enhancement', or 'Bug Fix'. 

## Objective 
This story will check that one proper label ('New Feature', 'Enhancement', or 'Bug Fix'. ) is included on the PR when the PR is created against master.

## Value Add 
Enforces automated release notes

## Design notes 
Utilize github actions to enforce labels on PRs 

When one of the 3 lables is not created, report: "Please include exactly one of the following labels: New Feature, Enhancement, Bug Fix" 

## Success criteria 
When PRs are not created with one of the following labels ('New Feature', 'Enhancement', or 'Bug Fix'. ), a message should be displayed during creation.

**Comment by fionnachan** [comment]
Dropping by....

GitHub doesn't allow non-collaborator contributors to add labels to PRs

For issues non-collaborator contributors can use issue templates to create issues with pre-determined labels but nothing similar is there for PRs 👀

https://docs.github.com/en/organizations/managing-access-to-your-organizations-repositories/repository-roles-for-an-organization#permissions-for-each-role

**Comment by algojack** [comment]
I think it's ok if we have one of the collaborators add the labels. (in other words we don't need outside contributors adding labels). Unless I'm missing something.

**Comment by algobarb** [comment]
As raised by Tsachi, @algojack can we limit this check to just the "master" branch?

**Comment by algojack** [comment]
> Dropping by....
> 
> GitHub doesn't allow non-collaborator contributors to add labels to PRs
> 
> For issues non-collaborator contributors can use issue templates to create issues with pre-determined labels but nothing similar is there for PRs 👀
> 
> https://docs.github.com/en/organizations/managing-access-to-your-organizations-repositories/repository-roles-for-an-organization#permissions-for-each-role

thank you for noting that. I believe we can add the labels when reviewing/merging PRs.
