### ISSUE TITLE
Suggest params returns fee (per byte) of 0

### ISSUE THREAD

**Issue by plasmatech8** [algorand/go-algorand#3534]
### Subject of the issue

The documentation for [/v2/transactions/prams](https://developer.algorand.org/docs/rest-apis/algod/v2/#get-v2transactionsparams) states that it returns a parameter called `fee` (the fee-per-byte "Fee is in units of micro-Algos per byte").

However, the response always falls back to fee=0.

As discussed in my [post](https://forum.algorand.org/t/cannot-calculate-suggested-fees-for-inner-transactions/5826/2) to the Algorand forum, I wanted to use fee-per-byte because I believe it is easier for development and allows your application to adapt to future fee changes/fluctuations. 

Since fee-per-byte is not available, currently the only way to calculate the fee is to use the minimum fee. However, if you use `min_fee * num_transactions` then you need to make sure that you know:
* How many inner transactions your application call will create
* If any of your transactions will write too many bytes causing the total fee to exceed the min_fee 
* That the current network fees have not increased causing the total fee to exceed the min_fee 

However, if the fee-per-byte was available via API, there is no work required. In py-algosdk, I can simply use the suggested params (including `fee` per byte) without any additional logic.

### Your environment

For Sandbox Release net:
```
./sandbox goal node status
Last committed block: 10
Time since last block: 0.2s
Sync Time: 0.0s
Last consensus protocol: https://github.com/algorandfoundation/specs/tree/bc36005dbd776e6d1eaf0c560619bb183215645c
Next consensus protocol: https://github.com/algorandfoundation/specs/tree/bc36005dbd776e6d1eaf0c560619bb183215645c
Round for next consensus protocol: 11
Next consensus protocol supported: true
Last Catchpoint: 
Genesis ID: sandnet-v1
Genesis hash: ACW86Mj8v1YALH5OuUVV6pcVGH8P7AX+4AfNJuEC9d8=
```

### Steps to reproduce

1. Start Algorand sandbox
```
git pull
./sandbox up release
```
2. Call the /v2/transactions/params endpoint using curl
```bash
curl localhost:4001/v2/transactions/params -H "X-Algo-API-Token:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
```
Response:
```json
{
    "consensus-version": "https://github.com/algorandfoundation/specs/tree/bc36005dbd776e6d1eaf0c560619bb183215645c",
    "fee": 0,
    "genesis-hash": "4vq5MLviei4rVXczEOpRXCsz2Gz/57nFz7cV9e8xZYg=",
    "genesis-id": "sandnet-v1",
    "last-round": 4873,
    "min-fee": 1000
}
```

I have also tested using:
* Sandbox Dev
* Sandbox DevNet
* PureStake MainNet 
* PureStake Testnet

They all return fee=0.

### Expected behaviour

JSON response should return the field: `"fee": <SOME-NUMBER>`

e.g. `"fee": 10`

### Actual behaviour

JSON response returns `"fee":0` as shown above.

**Comment by petitnau** [comment]
I'm pretty sure this is [intended](https://developer.algorand.org/docs/rest-apis/algod/v2/#get-v2transactionsparams): 
"Fee may fall to zero but transactions must still have a fee of at least MinTxnFee for the current network protocol."

From what I know this amount only goes up in case of network congestion, but right now we're pretty far from that so it remains zero.

**Comment by plasmatech8** [comment]
@petitnau Yeah I saw that.

Is the fee-per-byte actually currently zero? 

Based on the transactions I have run in sandbox, it seemed that the fee-per-bye is not actually zero: My Application Call Transactions that contain Inner Transactions (with fee paid by the user) fail unless the fee is non-zero. (fee-per-byte of at least 10)

If the fee-per-byte is indeed zero, then I am starting to wonder if this is a problem with Inner Transactions instead of the API.

If the fee-per-byte is actually non-zero, then I do not know the rationale for not seeing it.

**Comment by petitnau** [comment]
This is how I understood this:

You have to pay the inner transactions in the same way as you do with other transactions (thus currently 0.001 ALGO per inner transaction). So if you had an application call with 3 inner transactions, you would need a fee of at least 0.004.

**Comment by barnjamin** [comment]
That's correct each txn is charged based on the fee schedule here https://developer.algorand.org/docs/get-details/transactions/?from_query=fees#fees

You may pool fees by overpaying on some txns to cover others. 

Fee per byte is 0 until congestion so min fee of 0.001A per txn is used

**Comment by plasmatech8** [comment]
Ah okay awesome. Thanks a lot.

So the fee-per-byte returned by the API is correct, and this is an issue with something else.

This has resolved some of my confusions and I think I may have figured out what my problem was. I think this is a problem with neither algod, nor inner transactions, but rather may be one small issue with how py-algosdk fee calc works.
