### ISSUE TITLE
Dryrun endpoint does not accept app index 0 for app in apps array, even for an app create transaction

### ISSUE THREAD

**Issue by fionnachan** [algorand/go-algorand#3536]
### Subject of the issue
1. The dryrun endpoint does not dryrun an app create transaction without an apps array (see #2307). As a workaround, the app has to be passed into the apps array in addition to the transaction. For the app create transaction, naturally the app index `0` should be used, which brings us to the issue:
2. The dryrun endpoint does not allow the app index of an app in the apps array to be `0`. The request fails with the error `['ApprovalProgram', 'REJECT', 'cannot make logic ledger for app index 0']`.

https://github.com/algorand/go-algorand/blob/93a372d085dfa6305e6d3dba95df5279980a545e/ledger/internal/applications.go#L52-L55

### Your environment
sandnet in sandbox

### Steps to reproduce
1. Run algod with `"EnableDeveloperAPI": true`
2. Send an app create transaction with the app of app index 0 in the apps array

If `0` is changed to `1` or any other positive number, the dryrun request will work.

**Example in JS**
```typescript
const constructAppTxForDryrun = (
  tx: TransactionResponse,
  appArgs: Uint8Array[],
  forClearState: boolean = false
) => {
  const appInfo = tx["application-transaction"];
  const approvalProgram = Uint8Array.from(Buffer.from(appInfo["approval-program"]!, "base64"));
  const clearProgram = Uint8Array.from(Buffer.from(appInfo["clear-state-program"]!, "base64"));
  let txObj = {
    from: tx.sender,
    onComplete: forClearState ? OnApplicationComplete.ClearStateOC : OnApplicationComplete.NoOpOC,
    approvalProgram,
    clearProgram,
    appArgs,
    numLocalInts: appInfo["local-state-schema"]!["num-uint"],
    numLocalByteSlices: appInfo["local-state-schema"]!["num-byte-slice"],
    numGlobalInts: appInfo["global-state-schema"]!["num-uint"],
    numGlobalByteSlices: appInfo["global-state-schema"]!["num-byte-slice"],
    suggestedParams: {
      fee: tx.fee,
      firstRound: tx["first-valid"],
      lastRound: tx["last-valid"],
      genesisHash: tx["genesis-hash"],
      genesisID: tx["genesis-id"],
    },
  };
  if (appInfo["foreign-apps"] && appInfo["foreign-apps"].length > 0) {
    txObj = Object.assign(txObj, {
      foreignApps: appInfo["foreign-apps"],
    });
  }
  if (appInfo["foreign-assets"] && appInfo["foreign-assets"].length > 0) {
    txObj = Object.assign(txObj, {
      foreignAssets: appInfo["foreign-assets"],
    });
  }

  return algosdk.makeApplicationCreateTxnFromObject(txObj);
};

const constructAppForDryrun = (tx: TransactionResponse) => {
  const appInfo = tx["application-transaction"];
  const approvalProgram = Uint8Array.from(Buffer.from(appInfo["approval-program"]!, "base64"));
  const clearProgram = Uint8Array.from(Buffer.from(appInfo["clear-state-program"]!, "base64"));
  return new Application(
    0,
    new ApplicationParams({
      approvalProgram,
      clearStateProgram: clearProgram,
      creator: tx.sender,
      localStateSchema: new ApplicationStateSchema(
        appInfo["local-state-schema"]!["num-uint"],
        appInfo["local-state-schema"]!["num-byte-slice"]
      ),
      globalStateSchema: new ApplicationStateSchema(
        appInfo["global-state-schema"]!["num-uint"],
        appInfo["global-state-schema"]!["num-byte-slice"]
      ),
    })
  );
};

export const getAppTEAL = async (tx: TransactionResponse) => {
  const appInfo = tx["application-transaction"];
  if (
    !appInfo["approval-program"] ||
    !appInfo["clear-state-program"] ||
    !tx["created-application-index"] ||
    !appInfo["application-args"] ||
    !appInfo["local-state-schema"] ||
    !appInfo["global-state-schema"]
  ) {
    return;
  }
  const appArgs = appInfo["application-args"].map((arg) => Uint8Array.from(Buffer.from(arg, "base64")));
  const app = constructAppForDryrun(tx);
  const appTx = constructAppTxForDryrun(tx, appArgs);

  // @ts-ignore
  const dr = new algosdk.modelsv2.DryrunRequest({
    apps: [app],
    txns: [{ txn: appTx.get_obj_for_encoding() }],
  });
  const dryrunResponse = await algod.dryrun(dr).do();
  return dryrunResponse;
};
```

### Expected behaviour
App index 0 should be accepted for a dryrun request.
Even better would be actually fixing #2307 to allow dryrun request of app create transaction without the need of passing an apps array.

### Actual behaviour
The dryrun request throws the error `['ApprovalProgram', 'REJECT', 'cannot make logic ledger for app index 0']`.

**Comment by algorandskiy** [comment]
Hello @fionnachan, thank you for the report.

This is well-know limitation on how dryrun works. Here is a relevant code: https://github.com/algorand/go-algorand/blob/master/daemon/algod/api/server/v2/dryrun.go#L416-L423
In other words, it expects to have the app being created to be at `apps[0]` position with non-zero appIdx.

I can explain the root cause. Dryrun is a pure function in terms it does not look into actual blockchain state, instead, the state have to be provided to it in `apps` or `accounts` fields in Dryrun input. Going from there, there are two options on how to handle application creation transaction:
1. If Dryrun sees zero value it might use some hardcoded value.
2. Let a user to provide such input data and control the appIdx being used. This option is actually implemented.

Now suppose one want to dryrun a real transaction group of two txns that happened at some block in past: app A creation, app A opt-in. In this case it is sufficient to extract the txn group from the blockchain (from a block or ask the indexer), get app params for A from the blockchain and call Dryrun. And this will work without any modifications if the params are in `apps[0]`.

**Comment by fionnachan** [comment]
Thanks for the clarification @algorandskiy. It's understandable if this is the behaviour by design. Would really appreciate if there are some documentation for it.

It'd also help if the docs mention that the app has to be passed in `apps` explicitly in complement to an app creation tx for dryrun since the approval program and the clear program passed into the tx didn't seem to have any effect.

**Comment by algorandskiy** [comment]
Hi @fionnachan, we have the documenting for dryrun endpoint here: https://github.com/algorand/docs/blob/staging/docs/get-details/dapps/smart-contracts/debugging.md#dryrun-rest-endpoint
Please feel free to add missed pieces.
