### ISSUE TITLE
Unlimited opt-ins: Update libgoal with new API spec

### ISSUE THREAD

**Issue by yaovi-a** [algorand/go-algorand#3555]
## Context 
Due to increased number of opt-ins, the algod REST API endpoints will need to be updated to reflect new functionality. Libgoal currently import the algod REST API, we'll need to update support for the new API spec 

## Objective 
Update libgoal algod REST API support

- [ ] Update lib goal 
- needs to follow the new endpoints: 
GET /v2/accounts/{address}/assets/{asset-id}
GET /v2/accounts/{address}/applications/{application-id}

## Value Add 
**UX** 
- Required to ensure functionality of the updated goal commands

## Design notes 
Reference doc: https://docs.google.com/document/d/11Hm21Dd1MKi7_DVNdrCo1IdfkffCx1_WojYyjByubjA/edit#

## Acceptance criteria
Libgoal should continue supporting the API endpoints and reflect expected functionality.

Conduct e2e test for libgoal

- Confirm that the new endpoints are being properly accessed
- Check that tests results are as expected

## Priority
Blocking unlimited assets/apps release

**Comment by cce** [comment]
I think this should be combined with updating the goal commands, to make sure the new methods fit their intended as supporting the goal commands.
