### ISSUE TITLE
Indexer 2.9.0-rc2 data validation test

### ISSUE THREAD

**Issue by yaovi-a** [algorand/go-algorand#3568]
## Objective
Run Indexer v2.9.0 data validation for all networks.

- [x] Betanet
- [x] Testnet
- [ ] Mainnet

**Comment by onetechnical** [comment]
This is using go-algorand v3.4.1-beta + indexer 2.9.0-rc2.

**Comment by onetechnical** [comment]
Barbara took a 2.8.4 indexer and upgraded it to 2.9.0-rc3, then ran validation on it which came back clean. I have been catching up a mainnet indexer from scratch on various iterations of 2.9.0-rcs, upgrading up to 2.9.0 final. However, it is only at round 15115263 after two weeks.
