### ISSUE TITLE
Support Mac builds for Apple Silicon

### ISSUE THREAD

**Issue by gmalouf** [algorand/go-algorand#3572]
## Problem
Apple continues their move towards releasing computers primarily using [Apple Silicon processors](https://en.wikipedia.org/wiki/Apple_silicon). 

## Solution
Work through platform-specific challenges to add an Apple Silicon-specific build to our pipeline.

## Dependencies
Depends on completion of the [Go 1.16 upgrade](https://github.com/algorand/go-algorand/issues/3570).

## Urgency
We are approaching a point where the Macs with Intel processors will no longer be sold, leading the developer ecosystem to bias towards Apple Silicon-based machines.

**Comment by winder** [comment]
Done.
