### ISSUE TITLE
send Transaction

### ISSUE THREAD

**Issue by abyssal0** [algorand/go-algorand#364]
🚨 The issue tracker is not for questions. 🚨

A small portion of the balance for each address cannot be transferred out.Bad Request error.why?
The balance just received cannot be transferred for a long time.Bad Request error.why?
What it means:'First round' and 'Last round' in this transaction???

**Comment by algoradam** [comment]
This issue tracker is not for questions, please ask on https://forum.algorand.org/ next time.
Accounts have a minimum nonzero balance (currently 0.1 algo) to prevent an attacker from spamming the system with almost-empty accounts that everyone has to store. To completely empty an account, including the 0.1 algo, set the "CloseTo" field to an address to spend all remaining funds from the account into.
First round and last round give the range of rounds for during which the transaction is allowed to go into a block. If the transaction hasn't made it into a block by LastValid, it's never going in.
Again, this issue tracker is not for questions; please use https://forum.algorand.org instead.
