### ISSUE TITLE
Iterate on go-algorand release notes automation

### ISSUE THREAD

**Issue by yaovi-a** [algorand/go-algorand#3641]
## Context
We've already made some progress on automating go-algorand releases (#3520). However, some iteration is required to address some missed opportunities with the release notes template and the PR title structure. 

## Objective

- [x] - Ensure that only one PR link is being shown in the release notes
- [x] - Cleanup labels 
- [x] - Extend script across go-algorand branches: report Add the script generation to support comparing any two branc

hes

## Notes
Labels: 
- remove: "New-Feature", "new-bug"
- keep: "New Feature"

Support for other repos (support fro go-algorand) 
- Compare any two branches within go-algorand repo

## Acceptance criteria
- Ensure the produced go-algorand release notes is the representation of the template below
- Generate release notes using the updated solution. Share the generated release notes with Product and team. 

- Create a story to extend release notes generation across other repos (indexer, SDKs)
---------------
### **Overview**
< A sentence or two capturing the release and any noteworthy details that anyone taking the release should be aware of > 

### **What’s New**

- < New feature highlight 1> 
- < New feature highlight 2 > 
- < New feature highlight 3 >

### **Changelog**
**New Features** 
- Category: PR title (link to PR)
- Category: PR title  (link to PR)

**Enhancements** 
- Category: PR title (link to PR)
- Category: PR title (link to PR)
 
**BugFixes** 
- Category: PR title (link to PR)
- Category: PR title (link to PR)
---------------

**Comment by algojack** [comment]
Sample run:
`./gen_release_notes.py -v 99.98.97 -s master -t rel/stable -w ../../go-algorand                                1 ↵ jack@MacBook-Pro
processing files in directory: ../../go-algorand
Current working directory: /Users/jack/projects/go-algorand
Current working directory: /Users/jack/projects/go-algorand-ci/release-note-gen
processing pull request: 3718
processing pull request: 3715
processing pull request: 3716
processing pull request: 3708
processing pull request: 3712
processing pull request: 3710
processing pull request: 3711
processing pull request: 3703
processing pull request: 3705
processing pull request: 3707
processing pull request: 3647
processing pull request: 3652
processing pull request: 3706
processing pull request: 3704
Filtering Re-merge PR Remerge (#3706)
writing release notes to file: release_notes_99.98.97.md

![GitHub Logo](https://raw.githubusercontent.com/algorand/go-algorand/master/release/release-banner.jpg)

# Overview


# What's New
* 
* 
* 

# Changelog
## Bugfix
* Agreement: Fix fuzzer test networkfacade clock implementation [3716](https://github.com/algorand/go-algorand/pull/3716)
* Fast catchup: Retry peers fetching [3711](https://github.com/algorand/go-algorand/pull/3711)
* Rest api: Fix check for record.appparams in accountapplicationinformation [3707](https://github.com/algorand/go-algorand/pull/3707)
* Telemetry: Fix version configuration [3718](https://github.com/algorand/go-algorand/pull/3718)
* Testing: Fix testassetconfig test to support unlimited assets [3710](https://github.com/algorand/go-algorand/pull/3710)
## Enhancement
* Agreement: Add messageshandled/dropped tagcounters [3712](https://github.com/algorand/go-algorand/pull/3712)
* Agreement: Add validatedat to proposal type and blockacceptedeventdetails message [3703](https://github.com/algorand/go-algorand/pull/3703)
* Agreement: Configurable incoming message buffer sizes [3705](https://github.com/algorand/go-algorand/pull/3705)
* Algod: Refactor registry operations [3647](https://github.com/algorand/go-algorand/pull/3647)
* Enhancement: Document instructions for updating indexer e2e test input [3704](https://github.com/algorand/go-algorand/pull/3704)
* Ledger: Replace ledger.lookupresource with lookup{application,asset} [3708](https://github.com/algorand/go-algorand/pull/3708)
* Telemetry: Replace the uuid package dependency [3715](https://github.com/algorand/go-algorand/pull/3715)
## Feature Request
* Algod: Merge unlimited assets to master [3652](https://github.com/algorand/go-algorand/pull/3652)
## Protocol Upgrade
This release does not contain a protocol upgrade.

## Additional Resources
* [Algorand Forum](https://forum.algorand.org)
* [Developer Documentation](https://developer.algorand.org)`

**Comment by algojack** [comment]
instead of creating a story, i believe it now works on any given repo

**Comment by algobarb** [comment]
Remember to check off the objectives before closing the ticket. I believe this ticket is still missing label clean up
