### ISSUE TITLE
Outdated swagger

### ISSUE THREAD

**Issue by mxmauro** [algorand/go-algorand#3698]
### Subject of the issue

Call `/swagger.json` endpoint

### Expected behaviour

Ideally - Get API details for each available API version (v1 and v2).

After a round of group discussion, we identified these ranked options.  Assumes the story owner will vet further upon picking up the effort.
1. Top-level swagger.json that merges v1 and v2.  
    * Assumption:  Merge is clean and _easy_ to setup in build. 
    * Example tooling:  https://github.com/WindomZ/swagger-merger
2. Top-level swagger.json describes common and v2 endpoints, but omits v1 endpoints.  
    * Rationale:  If the preferred choice doesn't work out, we'll omit v1 because it's subject to removal and there's no new API version on the horizon.

Not ranked - These options were discussed, but we assume they won't be needed.
* Top-level swagger.json for just the common endpoints and then v1 and v2 specific swaggers.
* No top-level swagger and the v1 and v2 specific swaggers also capture common endpoints.

### Actual behaviour

It only returns details about the deprecated `/v1` endpoints.

**Comment by algochoi** [comment]
Need to update `swagger.json` regeneration as well: https://github.com/algorand/go-algorand/blob/7666348a508b664f6ee2f4ae757fa71c0038e94b/Makefile#L151
