### ISSUE TITLE
Does the protocol upgrade have an upgrade date?

### ISSUE THREAD

**Issue by vae520283995** [algorand/go-algorand#3709]
Algorand 3.4.2 is released, which includes protocol upgrades, so as a node provider, when should we upgrade?

**Comment by vae520283995** [comment]
@yaovi-a please help

**Comment by onetechnical** [comment]
@vae520283995 Yes - we strongly recommend applying this upgrade as soon as possible. The network has not yet approved the upgrade yet, but once it is approved, you will have 140,000 rounds (roughly one week) to upgrade.

**Comment by vae520283995** [comment]
> @vae520283995 Yes - we strongly recommend applying this upgrade as soon as possible. The network has not yet approved the upgrade yet, but once it is approved, you will have 140,000 rounds (roughly one week) to upgrade.

okay, thank you
