### ISSUE TITLE
Fail fast in network upgrades

### ISSUE THREAD

**Issue by rotemh** [algorand/go-algorand#3720]
## Problem

Currently, when a new upgrade is proposed, there is usually a 10,000 blocks period for the network to accept the upgrade. Each block contains a "Yes" or "No" and the threshold for acceptance is 90%, I.e. 9000 blocks with a "yes" vote. Right now, the network waits for the entire period to pass before it makes a decision even though once there are >1000 "no" votes, the decision is already practically made. 

## Solution

Reject the upgrade once one of the thresholds (10% "no") is met. 

## Dependencies

No

## Urgency

Not urgent but a very convenient optimization.

**Comment by algorandskiy** [comment]
This would make consensus target estimations impossible.
