### ISSUE TITLE
Smart contracts should be given access to accounts for apps specified in the foreign apps array

### ISSUE THREAD

**Issue by algoanne** [algorand/go-algorand#3723]
## Problem

Currently, I have to separately specify the account for an application if I want to use it in my smart contract, even if I already specified that I will need access to the application itself. 

## Solution

Make it so the smart contract automatically has access to the app's address if it specifies the app in its foreign apps array.

**Comment by TeamCyberCrypto** [comment]
Same issue resolved

**Comment by algoanne** [comment]
actually, probably want a stronger statement: you should have access to any app account for any app that is available to you. i.e. if it was created earlier in the transaction group. 

Note that this story excludes writing to these app accounts that you get access to now implicitly - if you want to write to it, you still have to reference it in your foreign accounts array. (but you can still pay to it and read from it)
