### ISSUE TITLE
CatchpointInterval doesn't prune older catchpoints

### ISSUE THREAD

**Issue by Blackglade** [algorand/go-algorand#3731]
### Subject of the issue

Just creating this issue for visibility. The `CatchpointInterval` config doesn't seem to work properly anymore. Older catchpoints are not pruned.

### Your environment

`algod -v`

```
12885164034
3.4.2.stable [rel/stable] (commit #54c3c397)
go-algorand is licensed with AGPLv3.0
source code available at https://github.com/algorand/go-algorand
```

**Comment by algorandskiy** [comment]
`CatchpointFileHistoryLength` controls older catchpoint files deletion, `CatchpointInterval` sets catchpoint generation frequency.
