### ISSUE TITLE
Adjust Catchpoint Defaults

### ISSUE THREAD

**Issue by Blackglade** [algorand/go-algorand#3732]
## Problem

Adjust the default config settings for catchpoints to appeal to the majority use case. Most users running a go-algorand node will likely be running a participation node. Very few users (I'd argue < 1%) actually run archival or relay nodes. It does not make sense for catchpoints to be enabled for participation nodes. 

## Solution

The following value configs should be default:

```
CatchpointFileHistoryLength: 0 // instead of 365
CatchpointInterval: 0 // instead of 10000
CatchpointTracking: 0 // instead of 1
```

## Urgency

Low

**Comment by algorandskiy** [comment]
`CatchpointTracking` has 0 default value that efficiently disables catchpoints.
