### ISSUE TITLE
BetaNet Transaction sync test infrastructure 

### ISSUE THREAD

**Issue by yaovi-a** [algorand/go-algorand#3757]
## Context 
Upcoming transaction release will require testing that is currently missing infrastructure. Though carbon-11 will be executing the tests, we need to lay the ground work to get this work done.

## Requirement 
Set up instances on Betanet where nodes on the network are enabled with transaction sync and others are not enabled. This will provide comparison across nodes with txn sync and nodes without.

**Comment by TeamCyberCrypto** [comment]
We will assess sync functionality, both with & without.

**Comment by onetechnical** [comment]
This is almost done - just need to:

- Add cron job to auto-update
- Add relays r6 - r9 to betanet DNS bootstrap

**Comment by onetechnical** [comment]
Eric added cron job.

Relays added to DNS bootstrap.

All binaries "downgraded" to v3.5.1-beta.
