### ISSUE TITLE
Catchpoints Disabled, but still being generated.

### ISSUE THREAD

**Issue by Blackglade** [algorand/go-algorand#3785]
### Subject of the issue

I have the following set in my config.json of my archival nodes:

```
{
    "Archival": true,
    "OptimizeAccountsDatabaseOnStartup": true,
    "CatchpointInterval": 0,
    "CatchpointFileHistoryLength": 0,
    "CatchpointInterval": 0
}
```

Yet I still seem to be generating catchpoints. I delete them and they keep getting created.

### Your environment

```
12885164034
3.4.2.stable [rel/stable] (commit #54c3c397)
go-algorand is licensed with AGPLv3.0
source code available at https://github.com/algorand/go-algorand
```

### Steps to reproduce

1. Create a fully synced archival node
2. Change the config.json to disable catchpoints
3. Restart node.

### Expected behaviour

Catchpoints are supposed to not be generated at all.

**Comment by onetechnical** [comment]
If this works, there is still a bug since based on the above, a CatchpointInterval of 0 should disable it as well. However, this may solve it for your particular use case in the mean time.

**Comment by Blackglade** [comment]
Yep this works. Setting CatchpointTracking to -1 disabled it.
