### ISSUE TITLE
ARM32 Node Fails with Mismatching Genesis Hash

### ISSUE THREAD

**Issue by riceke** [algorand/go-algorand#3787]
### Subject of the issue

Since the 3.4.2 stable release, my ARM32-based node refuses to start and always fails with an error stating:

couldn't initialize the node: latest block 19845662 genesis hash YBQ4JWH4DW655UWXMBF6IVUOH5WQIGMHVQ333ZFWEC22WOJERLPQ does not match expected genesis hash GLWB5VVYCCV33B5SJ4KE3ECJWN4GJNVU6TW3DYIBNT7J4IGN3XNQ

I have double-checked that my genesis configuration still refers to mainnet (as it always did) and I get the error regardless of if I build the node from source code or if I use the pre-built ARM32 package.

I have also retried with a fresh catchup and the result is the same. I had to actually perform the catchup on an AMD64 machine, as the catchup kept restarting the account verification on the ARM32 (so the catchup does not seem to work on ARM32 any more either), and then copy over the 'mainnet-1.0' directory from the AMD64 machine to the ARM32 machine (I have done this many times in the past, for various reasons, and it always worked OK).

### Your environment
* ASUS Tinkerboard - ARM32 - 5.15.25-rockchip #22.02.1 SMP PREEMPT Sun Feb 27 09:23:03 UTC 2022 armv7l armv7l armv7l GNU/Linux
* Software version: 3.4.2.stable [rel/stable] (commit #54c3c397)
* Node status if applicable: Not started
* Operating System: Ubuntu 20.04.4 LTS

### Steps to reproduce
1. Try to start the node in an ARM32 environment.
2. Node fails immediately.

### Expected behaviour
Node should start.

### Actual behaviour
Node stops immediately after start with previously described error.

**Comment by nullun** [comment]
I had this issue the other day, turns out my genesis.json file appeared to be missing the timestamp field, which I blamed on myself but if you have the same issue it must have come from somewhere.

```
user@computer:~/go-algorand$ diff installer/genesis/mainnet/genesis.json ~/.algorand/genesis.json
944,946c944,945
<   "rwd": "737777777777777777777777777777777777777777777777777UFEJ2CI",
<   "timestamp": 1560211200
< }
\ No newline at end of file
---
>   "rwd": "737777777777777777777777777777777777777777777777777UFEJ2CI"
> }
```

Try copying it over and starting your node again, hope this resolves your issue.

**Comment by riceke** [comment]
Oh my god, that is seriously embarrassing on my behalf!

I must have somehow managed to copy the genesis file from another location than the 'installer' location (or perhaps it used to work without a timestamp before?).

Thank you *VERY* much for this, nullun!

All now seems well, so this ticket can be closed.

Thanks!

**Comment by onetechnical** [comment]
Ah - never mind, I think I know what happened. If you used the mainnet genesis created from `make gen` it will be missing a timestamp. Please use official sources. See this comment from the Makefile:

```
# The mainnet genesis.json file generated by this target does not have timestamp value so the hash is different from the deployed mainnet,
# use a real genesis.json file from installer/genesis/mainnet/genesis.json if needed.
# This target is preserved as part of the history on how mainnet genesis.json was generated from the CSV file.
```
