### ISSUE TITLE
Enhance Goal to work with non local node (remote access) and provide robust status. 

### ISSUE THREAD

**Issue by rfustino** [algorand/go-algorand#379]
Problem 1:  

Goal only works with a local node. We now have standup instances and Purestake instances and Goal can not be used with these scenarios. Right now, to determine this, we must use code and the SDKs or contact someone that has access to that instance.

Example use case: I am using a standup hackathon instance, or Purestake perhaps, at a hackathon event. A user comes up to the Algorand team and transactions are not working. It would be extremely handy to ping the standup instance with Goal to see if it is caught up and synced. 

related Problem 2:

Enhance the Goal node status option/command, that is "full", showing all of the options currently in effect. This would be for local (or remote in #1 above). We can use this to occasionally check the standup instances we have for devrel and hackathon and Purestake perhaps. These nodes are located on machines that we do not have direct access too. Example, we had a question recently if archive was turned on and we had to ask Will and Eric that created the machines. 

Example use case:
We are at a hackathon or presentation by devrel or ambassadors, and something is going wrong, such as the chess example which requires Archive and Indexing to be turned on.  It would be nice to simply run this expanded status command to determine if the settlings are the way they are supposed to be without having to contact someone at 3AM to indeed verify that the Indexer and archive settings are correct.

Implementation suggestions: Add a parameter to the Goal command for remote node, with properties for token, url, and port. Or read from a Json file with these name value pairs.

Benefits: Developers that are used to developing on other Blockchains, currently see this as an implementation constraint on Algorand, as they do not need to install a local node to use something equivalent for command line tools. This facilitates quicker ramp-up and ease of use. 

Other considerations: Need a Goal only install that is not dependent on installing a local node. Probably would need a flag to require start and stop w a password perhaps?  If easier to implement remote access for Algod only, this is fine as the standup instances and Purestake do  not facilitate kmd.

**Comment by rfustino** [comment]
Actually Eric's CLI can do this. When will we publish that?[ https://github.com/algorand/algocli/ ]( https://github.com/algorand/algocli/ )

**Comment by brianolson** [comment]
I feel like adding --algod-net and --algod-token options, or environment variables, to `goal` should be easy-ish.

**Comment by ashleydavis** [comment]
> Actually Eric's CLI can do this. When will we publish that?[ https://github.com/algorand/algocli/ ](https://github.com/algorand/algocli/)

That link gives a 404 error now.

**Comment by barnjamin** [comment]
@ashleydavis I think its a private repo and hasn't been worked on in some time.  I filed another issue for goal remote in #2904 with some details on how you might be able to make it work but some of the internal methods still use the V1 API which is unsupported on services like algoexplorer.  I'm going to close this one as stale but if its something you'd like please let the team know in the newer PR.

**Comment by ashleydavis** [comment]
Thanks @barnjamin, I've put my vote on that other issue.
