### ISSUE TITLE
M1 Support: go SDK

### ISSUE THREAD

**Issue by winder** [algorand/go-algorand#3811]
We don't anticipate any issues with the go SDK, but should run the unit and integrations tests anyway to verify.

**Comment by tolikzinovyev** [comment]
should probably be moved to go-algorand-internal

**Comment by winder** [comment]
@tolikzinovyev I'm pretty sure epics are not allowed to span across multiple repos. Given the choice of hiding effort, and creating issues in the wrong repository, I opetd to create them in the wrong repository.
