### ISSUE TITLE
Return 404 when a block is not found.

### ISSUE THREAD

**Issue by winder** [algorand/go-algorand#3835]
### Subject of the issue

This change was already implemented in indexer: https://github.com/algorand/indexer/pull/719

We should change it for algod as well.

Return a 404 instead of 500 when /v2/blocks/:round fails due to a missing block.

**Comment by mxmauro** [comment]
I support this request.

**Comment by barnjamin** [comment]
It turns out 500s make load balancers penalize the node the 500 err came from, so this would be a very good change to make. 

cc @urtho
