### ISSUE TITLE
goal conflict between multisig sender and -o flag

### ISSUE THREAD

**Issue by CiottiGiorgio** [algorand/go-algorand#3839]
### Subject of the issue

When attempting to build a group transaction, one needs to have unsigned transaction, group them, split, sign and concatenate.
Usually the transaction creation is accomplished by using the `-o` flag. However, when the sender is a msig account, the transaction comes out already signed. This makes it impossible to compose it into a group.
This has been observed while attempting to create an app call with msig as sender.

### Your environment

* Software version: `algod -v`
`12885229569
3.5.1.dev [rel/stable] (commit #aa2fb0ee)
go-algorand is licensed with AGPLv3.0`

### Steps to reproduce

1. Create a multisig account
2. Create an app call from that msig with `-o` flag set to a file
3. Create any other transaction with `-o` flag set to a different file
4. Attempt creating a group transaction in the usual way

### Expected behaviour
Group is created as expected and can be used to split, sign, concatenate and rawsend

### Actual behaviour
The transaction from msig will already be signed and creating a group will be impossible.

**Comment by CiottiGiorgio** [comment]
To add to this: the only way that I could compose a group with msic transactions is to have an empty wallet which I use to create the txn file (`-w walletName` since it doesnt have any accounts in it, the transaction comes out not signed). Then group it as usual and then sign it with the wallet that contains the msig.

**Comment by winder** [comment]
There is some documentation about using goal to create multisignature transactions here: https://developer.algorand.org/docs/get-details/transactions/signatures/?from_query=multisignature#multisignatures

**Comment by CiottiGiorgio** [comment]
The problem was really that transaction saved to disk came out as already signed. Not sure if that's the case anymore but the problem was never _creating_ a multisig transaction.
