### ISSUE TITLE
Algod timestamp lags behind real time when in devmode

### ISSUE THREAD

**Issue by ashleydavis** [algorand/go-algorand#3858]
### Algod timestamp lags behind real time when in devmode

When running Algod in devmode the current system time is frozen and appears to be advanced  by 25 seconds for each transaction.

This causes it to lag behind the system time which makes it very difficult to test contracts that depend on the block stamp.

I believe it is due to the the "frozen clock" that is enabled in dev mode here:

https://github.com/algorand/go-algorand/blob/35be745f200e26b0a9d2bee713f1034148860c32/node/node.go#L251

Then the initial time is captured when Algod is started.

Subsequently for each new transaction 25 seconds is added here:

https://github.com/algorand/go-algorand/blob/9d9d7597043169413f393c5f2138985c66c5b317/data/bookkeeping/block.go#L483

Could someone please add an option to control the clock independently of dev mode.

**Comment by barnjamin** [comment]
Related to https://github.com/algorand/go-algorand/issues/3192

**Comment by winder** [comment]
I believe this is the expected behavior. There should be a reference to it in the whitepaper, but I'm not sure where it would be. Essentially there is a maximum time delta between rounds, so when there is a "stall", the time would have to gradually catchup.

It might be to prevent people from proposing rounds in the future.

**Comment by barnjamin** [comment]
@winder to expand on the issue further, this is specific to dev-mode and the frozen clock it uses. It is quite difficult to do any time based testing in dev mode currently
