### ISSUE TITLE
AVM needs access to larger programs

### ISSUE THREAD

**Issue by jannotti** [algorand/go-algorand#3864]
## Problem

AVM values are limited in length to 4k. However, programs can be up to 8k, and perhaps they will be allowed even longer in the future.  Therefore, access to large programs, using `txn ApprovalProgram` or `app_params_get AppApprovalProgram` (or the clearstate versions of those) causes an AVM program to fail.

## Solution

Introduce a few "virtual fields" to access programs:
`txn ApprovalProgramPages`
`txna ApprovalProgramPage n`
would allow safe access by returning chunks of the program.

(similar fields would be need for ClearState programs, and for `app_params_get`

## Urgency

Users want to hash incoming program updates to confirm they are as expected.

Users want to inspect the last bit of programs, as specified in ARC-23

Users _might_ want to inspect app for certain prologues, to ensure they don't allow updates or some such.

**Comment by jeapostrophe** [comment]
A similar thing, but could potentially be done sooner, would be to support `itxn_field ApprovalProgram` being run multiple times for each of the pages...

```
bytes 4k
itxn_field ApprovalProgram
bytes 4k
itxn_field ApprovalProgram
```

This is like how when you do `itxn_field ApplicationArgs` multiple times it pushes onto the array.

**Comment by jannotti** [comment]
Unfortunately, that would change the existing declared semantics, that
multiple uses of `itxn_field` replace the value. I think new field names
are required.

**Comment by jeapostrophe** [comment]
New names are fine. I just mean that when you do this, make sure `itxn_field` works too

**Comment by jannotti** [comment]
Agreed, your example should work, tweaked to:
```
bytes 4k
itxn_field ApprovalProgramPages
bytes 4k
itxn_field ApprovalProgramPages
```
since `ApprovalProgramPages` will be an array field.

**Comment by jannotti** [comment]
I'm realizing this is much easier for the `txn` family of opcodes that it is for `app_params_get` since `app_params_get` does not currently have an "array flavor".  This would let programs inspect incoming programs, and create big programs, but not inspect a program that has already been placed on chain.  Is that a useful intermediate step? I *think* it might actually be all either of you care about.

**Comment by jumpsiegel** [comment]
Something like .. pseudo code.. (yes, not correct)                                                                                           
                                                                                                                                             
    def getOnUpdate():                                                                                                                       
            return Seq( [                                                                                                                    
                Assert(Sha512_256(Concat(Bytes("Program"), Txn.approval_program())) == App.globalGet(Bytes("validUpdateApproveHash"))),      
                Return(Int(1))                                                                                                               
            ] )                                                                                                                              
                                                                                                                                             
    would get converted into                                                                                                                 
                                                                                                                                             
      idx.store(Int(0)),                                                                                                                     
      buf.store(Bytes("")),                                                                                                                  
      while (idx <= Txn.ExtraProgramPages).Do(Seq([                                                                                          
          buf.store(concat(buf.load(), Sha512_256(Txn.ExtraProgramPages(idx)))),                                                             
      ]),                                                                                                                                    
      Assert(Sha512_256(buf.load()) == App.globalGet(Bytes("validUpdateApproveHash"))),

**Comment by jannotti** [comment]
Yes, that would be possible with just the `txn` opcode that I think we can do quickly.  You're only inspecting the program that appears in a txn, not trying to inspect the program that is already installed in an app.

**Comment by jeapostrophe** [comment]
I care far more about creating big programs than I do about inspecting existing programs :) So, yes, I want this intermediate step :P
