### ISSUE TITLE
An error in TEAL code should report the line number in the TEAL file, not just the program counter

### ISSUE THREAD

**Issue by ashleydavis** [algorand/go-algorand#3868]
When getting an error or assertion failure from running TEAL code it would be very useful if we could get a line number in the TEAL file where the problem occurred.

The actual error message only includes the program counter: 

```
Error: Network request error. Received status 400: TransactionPool.Remember: transaction XXX: logic eval error: assert failed pc=191. Details: pc=191
```

This kind of leaves me guessing as to where the problem actually occurred.

Something like this would help pinpoint the error in the code immediately and save wasted time:

```
Error: Network request error. Received status 400: TransactionPool.Remember: transaction XXX: logic eval error: assert failed pc=191. Details: line=200, pc=191
```

**Comment by jannotti** [comment]
No line number information is sent to algod, so this isn't directly possible. But there is an effort to produce source maps during assembly, so that the line can be determined on the client side from the pc report. 

https://github.com/algorand/go-algorand/issues/3725

**Comment by ashleydavis** [comment]
@jannotti isn't the TEAL program sent to algod and compiled within algod?

**Comment by jannotti** [comment]
Not usually, no. algod does offer an assembly endpoint, which returns the
bytecode, but then the client creates a transaction with the bytecode
inside, not the source code. Or, more commonly, it compiles the bytecode
with `goal clerk compile`, so algod never sees the source code at all.

So, yes, algod sometimes performs the compilation, but even when it does,
it's in a separate step, son the transaction submission does not have the
source.

**Comment by ashleydavis** [comment]
I'm using the algosdk in JavaScript. 

In that case does it compile the code in JavaScript and then send the byte code to algod?

**Comment by barnjamin** [comment]
The `compile` endpoint now supports the `sourcemap` boolean flag. The result can be parsed into a SourceMap object and consulted for the corresponding TEAL line number when an exception occurs.

Here are a couple links for both ts/py to take an error message and a sourcemap and return a little stack trace with the offending line flagged
https://github.com/algorand-devrel/beaker-ts/blob/master/src/application_client/logic_error.ts
https://github.com/algorand-devrel/beaker/blob/master/beaker/client/logic_error.py
