### ISSUE TITLE
Ensuring that the participation keys related commands are run with the correct user

### ISSUE THREAD

**Issue by fabrice102** [algorand/go-algorand#3879]
## Problem

If `goal account installpartkey` or `goal account addpartkey` are not run the user running `algod` then `algod` will not be able to use those participation keys. This may create hard-to-debug issues.

There may be other commands in this case.

## Solution

* Have these commands check that they are run with the proper user.
* Update the documentation of these command to 

## Dependencies

N/A

## Urgency

Nice to have.

**Comment by winder** [comment]
This is issue is going to be obsolete soon, goal is updated to use a REST API instead of copying files with #2594.
