### ISSUE TITLE
Design: Confirm FeatureNet functionality

### ISSUE THREAD

**Issue by yaovi-a** [algorand/go-algorand#3880]
## Context
A FeatureNet with available binaries was built but was never functional. Before continuing to build on top of the existing work, we need to confirm that we can build binaries from branches and that they work. 

## Objective 
Confirm that the following happen: 

1 - Anyone (internal eng) can create binaries by pointing at a commit or branch
Note - Network should be created after the binary is created. 

2 - Confirm that the network is created and operational: Run network status check and make sure rounds are advancing. 

**Outputs:** 
1. Binaries (package genesis.json into the binary, potentially) 
2. genesis.json gets created after the network (after the binaries are created) is created so we need to understand how we want to package it
- we should send genesis.json to s3
3. Config.json (dependent on what kind of FeatureNet exist) 

What's not included in this story: 

## Value Add 
This first thing that we need to do for FeatureNet creation 

## Notes 
Document any findings but the following needs to be included in design doc: 
- If you run into any issues going through the binary and network creation, document the failure and create a follow up story. 
- Include potential paths for resolving how we provide one package that includes binary, genesis, config.json to the user. 
- Explore how we create config.json files that are custom to FeatureNet

## Success criteria 
Create follow up stories that are blocking featurenet creation and functionality, packaging mechanism and custom config.json file approach.

**Comment by algojack** [comment]
So, for feature network testing, here’s what I did so far. Connected to network and rounds are catching up. Network is moving.
- build jenkins job with custom network name and branch
- look at the jenkins job log when finished to download files
	- aws s3 cp s3://algorand-releases/channel/jackstest/node_jackstest_linux-amd64_3.5.123.tar.gz .
	- aws s3 cp s3://algorand-releases/channel/jackstest/tools_jackstest_linux-amd64_3.5.123.tar.gz .
	- aws s3 cp s3://algorand-releases/channel/jackstest/install_jackstest_linux-amd64_3.5.123.tar.gz .
- spin up docker with file directory mounted
	- docker run -it -v `pwd`:`pwd` -w `pwd` alpine
- untar the node file
	- tar -xvf node_jackstest_linux-amd64_3.5.123.tar.gz
- cp genesis/genesis.json data/
- copy and edit config.json.example to config.json
	- change DNSBootstrapID from <network>.algorand.network to <network>.algodev.network
- (optional) ./bin/algod -v
- ./bin/goal node start -d data
- (optional) ./bin/goal node status -d data

**Comment by algojack** [comment]
also installed and ran the node on ec2 using updater instructions here:
https://developer.algorand.org/docs/run-a-node/setup/install/#installation-with-the-updater-script
modified channel to my network name jackstest and had to still rename and edit config.json dns, but other than that worked as expected.

**Comment by algojack** [comment]
tested upgrade and everything went smoothly except jenkins generates a new genesis file, which is a bug, and will file a separate ticket for it.
