### ISSUE TITLE
EvalDelta in json schema should be TealValue

### ISSUE THREAD

**Issue by barnjamin** [algorand/go-algorand#3886]
The schema defines EvalDelta as
https://github.com/algorand/go-algorand/blob/master/daemon/algod/api/algod.oas2.json#L2027-L2064

I believe the EvalDelta in the JSON schema should be named as TealValue
https://github.com/algorand/go-algorand/blob/b0c551a7137e3860d81a854aa7cc0681c378bac4/daemon/algod/api/server/v2/generated/types.go#L441-L462

The transactions package defines EvalDelta as
https://github.com/algorand/go-algorand/blob/master/data/transactions/teal.go#L29

**Comment by barnjamin** [comment]
🤷‍♂️ 

If it is a breaking change we should start a label for V3 API changes and tag this one

**Comment by jasonpaulos** [comment]
`EvalDelta` is modeled after `basics.ValueDelta`, not `basics.TealValue`. While the two are very similar, `ValueDelta.Action` is more informative than just the TEAL type of the value. Closing as there are no immediate plans to change the definition in the REST API
