### ISSUE TITLE
Design - Decide how to handle node exporter upgrading and fix disk stats issue

### ISSUE THREAD

**Issue by onetechnical** [algorand/go-algorand#3902]
### Subject of the issue

This is a little bit of a rabbit hole, but there are issues with exporting prometheus disk stat metrics with node exporter. You may get errors like the following when hitting the node exporter /metrics endpoint:

```
time="2022-04-20T20:51:34Z" level=error msg="ERROR: diskstats collector failed after 0.000381s: invalid line for /proc/diskstats for nvme0n1" source="collector.go:135"
time="2022-04-20T20:51:35Z" level=error msg="ERROR: diskstats collector failed after 0.000620s: invalid line for /proc/diskstats for nvme0n1" source="collector.go:135"
time="2022-04-20T20:51:36Z" level=error msg="ERROR: diskstats collector failed after 0.000375s: invalid line for /proc/diskstats for nvme0n1" source="collector.go:135"
time="2022-04-20T20:51:37Z" level=error msg="ERROR: diskstats collector failed after 0.000151s: invalid line for /proc/diskstats for nvme0n1" source="collector.go:135"
time="2022-04-20T20:51:38Z" level=error msg="ERROR: diskstats collector failed after 0.000809s: invalid line for /proc/diskstats for nvme0n1" source="collector.go:135"
```

This is likely due to a change in /proc/diskstats: 

https://www.kernel.org/doc/Documentation/ABI/testing/procfs-diskstats

Relevant line:

`259       0 nvme0n1 184387291 1330415 6620722234 172791015 686467566 371735953 159325905144 1906308536 0 310220504 727347624 0 0 0 0`

Because there are now more fields, this line will fail:

`		if len(stats) != len(c.descs) {`

This should probably be:

`		if len(stats) < len(c.descs) {`

The trickiness: this two character change should be done in this repo:

https://github.com/algorand/node_exporter

And then we need to build new tar.gz binaries, that _used_ to be built in travis. Since we no longer use travis, we need a separate mechanism to build these, either by porting to Github Actions, CircleCI, or other means to build clean binaries, then copy the tar.gz files to go-algorand:

https://github.com/algorand/go-algorand/tree/master/installer/external

### Your environment

* Software version: v3.5.1-stable
* Node status if applicable: N/A
* Operating System details: Ubuntu 18.04

### Steps to reproduce

1. Enable node exporter
2. Hit the node exporter port, /metrics endpoint, e.g. `curl localhost:9100/metrics`

### Expected behaviour

No errors

### Actual behaviour

Above error

**Comment by brianolson** [comment]
I would add one point while we're in there: maybe don't store binaries in git? The build flow for this can store results in S3; the packaging steps for `algod`&tools can pull from there.

**Comment by onetechnical** [comment]
> I would add one point while we're in there: maybe don't store binaries in git? The build flow for this can store results in S3; the packaging steps for `algod`&tools can pull from there.

I guess if it's public on S3, sure, I would just worry about third party compilers. They would also be implicitly trusting our S3 repository, which is an interesting proposition as well.

**Comment by cce** [comment]
upgrading our version of github.com/prometheus/procfs should fix this

**Comment by cce** [comment]
ohhh our version of node_exporter does not use that library. OK I see

**Comment by brianolson** [comment]
We can still ship binary node_exporter in our binary releases; I just see no need to store it in git. People who want to build `algod` from source shouldn't be too put off by also building `node_expotrer` if they want it?

**Comment by onetechnical** [comment]
Might need a larger discussion with software engineering on how we want to handle it.

**Comment by onetechnical** [comment]
This is a 5 because we have to verify effects of upgrading. We also want a good setup for building node exporter binaries.

**Comment by cce** [comment]
Our custom node_exporter fork implements a custom collector that adds an HTTP listener to capture metrics pushed by algod, so I don't know that we can get rid of it easily.

**Comment by onetechnical** [comment]
Chris updated this.
