### ISSUE TITLE
Add getBlock(blockHash) function to get block info based on the block hash

### ISSUE THREAD

**Issue by haardikk21** [algorand/go-algorand#395]
**Is your feature request related to a problem? Please describe.**

Bitcoin and Ethereum both have similar functions. Currently, the `getBlock()` function only supports looking up based on the `round`. This feature would be helpful for various use cases, e.g. for implementing the sidetree protocol on algorand.

**Describe the solution you'd like**

Write a function to query the database and get block info based on hash. Make an endpoint to correlate with it.

**Comment by haardikk21** [comment]
Taking a look at the codebase it seems like this is a bigger problem than what it seems to be. The block hash is not a column in the database. Instead, it is considered to be the hash of the decoded `blkdata` blob in the table. This means, as far as I know, a `SELECT ...` statement which queries based on the block hash won't be possible. 

The other solution is of course looping over the blocks and checking if the block hash is the same, but that seems to be very inefficient.

I still think we should add this, as other major public chains support this and it can be helpful for certain use cases. Also, you should be able to search on AlgoExplorer using block hash, which will be possible if this is done.

**Comment by derbear** [comment]
This is a great suggestion! I think the right place to place this query is in the indexer, which builds a second set of indexes on the block and account databases for exactly these kinds of queries (for storage scalability, non-archival nodes currently only store recent history). @rotemh , can you assess how feasible this is?

(Tagging @ian-algorand for purposes of tracking this issue.)

**Comment by EvanJRichard** [comment]
Heya, @haardikk21! I’m closing this issue because it isn’t going to be built in the near term, but it may be revisited in the future. For now, we feel that getting block by number from `algod` is sufficient, and more complex querying can be handled outside algod. Thanks for the great suggestion!
