### ISSUE TITLE
StateProofPK not in TransactionReference

### ISSUE THREAD

**Issue by jeapostrophe** [algorand/go-algorand#3959]
https://developer.algorand.org/docs/get-details/transactions/transactions/#key-registration-transaction

doesn't include StateProofPK

I found this because I tried to have AVM generate a keyreg and got this error:

```
Error: Network request error. Received status 400: TransactionPool.Remember: transaction MRMG2ITQISQYHJIJ72EPHXRMR3BZO3EGMLJU22Z4MZCSECEJ7WLQ: logic eval error: online keyreg transaction cannot have empty field StateProofPK. Details: pc=325, opcodes=btoi\n'
```

I searched in the repo for 'StateProofPK' and only found this commit:

https://github.com/algorand/go-algorand/commit/138811058860c9a79ef934726008ef90c1d5dd1e

This is all weird and should be fixed

**Comment by barnjamin** [comment]
Is this just a docs issue? If you include the field in the transaction does it work?

**Comment by jeapostrophe** [comment]
Yea, it's a docs issue
