### ISSUE TITLE
Algokey: print version information after generating keys

### ISSUE THREAD

**Issue by winder** [algorand/go-algorand#4009]
## Problem
Make it easier to isolate version problems by printing the version information when generating keys.

## Solution
Add a line to the end, something like this:

```
~$ algokey part generate --first 0 --last 1000 --keyfile test
Please stand by while generating keys. This might take a few minutes...
Participation key generation successful
Parent address:    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAY5HFKQ
VRF public key:    IaPVI/hb0stQnIPetFhpYp+6vVNSkWspR/1W/C1VnIw=
Voting public key: fv8YO026+4x1c+Xae9iLUYLXnnhms9diRu0M+fyTPww=
State proof key:   C/4y2hAFel9f8vtAwkxvGnvSBYvrnE/6y6B1jDLb1r+sJM2IiEGePfobKbe1YcK1YpG0WcOjPWULAV0RU9ywFg==
First round:       0
Last round:        1000
Key dilution:      32
First batch:       0
First offset:      0

Generated with algokey v3.2.5
```

**Comment by algonoah** [comment]
Looks good - can we add this to each of the key generation commands? I believe there are a few in goal as well

**Comment by winder** [comment]
@algonoah yes, please provide a list of places you would like to see this. For now we'll go ahead and plan to add it under `algokey part generate`

**Comment by algonoah** [comment]
1. algokey part generate (above)
2. goal account addpartkey (list goal version)
3. goal account renewpartkey (list goal version)
