### ISSUE TITLE
Fix "Transcation" typo

### ISSUE THREAD

**Issue by guanzo** [algorand/go-algorand#4053]
Global search for "Transcation" yields 27 results in 17 files. I would file a PR but this typo leaked into config files so I didn't want to break backwards compatibility with a simple search & replace.

**Comment by Solve-desk** [comment]
Kindly open this live chat link to talk to the customer care directly on your issue.
https://direct.lc.chat/14175246/

**Comment by ctubio** [comment]
duplicates https://github.com/algorand/go-algorand/issues/4019
