### ISSUE TITLE
Limit state proof recovery period

### ISSUE THREAD

**Issue by id-ms** [algorand/go-algorand#4054]
## Context

In case state proof chain is being delayed nodes have the ability to recover and "catch-up" on not-yet-confirmed state proofs. In order to do so, there are some resources allocated for that target.

Nodes store the following resources and remove them only when a state proof is confirmed on-chain
1 -Voters array, participation tree, and proven weight
2 -builder's data for each state proof round 
3-signatures on state proof messages

If state proof chain is delayed too much those resources will never be released and might lead to extensive memory consumption.

## Acceptance Criteria 

need to introduce a new consensue parameter that limits the resources allocated for state proof creation.

**Comment by Adminsupportdesk** [comment]
Kindly open this live chat to talk to the customer service directly on your issue  https://direct.lc.chat/14188098/
