### ISSUE TITLE
Unix sockets for API calls?

### ISSUE THREAD

**Issue by AaronColman** [algorand/go-algorand#4117]
Feature request: Support unix sockets for API calls.

**Comment by winder** [comment]
What sort of API calls are you wanting to make? We went with a REST API for most of the public interfaces, I haven't heard of using those with anything other than HTTP.

**Comment by AaronColman** [comment]
Yep. I'm familiar with the REST API and it works really well, but it's not
always the fastest. Even if I use raw sockets and fast open, it still takes
several hundred microseconds to connect to a local socket and recv the
data. There are cases - like submitting some kinds of trades or making
several calls at once where that level of speed starts to matter. I had the
idea after moving memcache to unix sockets and clocking the difference.
