### ISSUE TITLE
Box storage:  Vet performance via pingpong

### ISSUE THREAD

**Issue by michaeldiamant** [algorand/go-algorand#4157]
## Problem

To help improve confidence that Box storage does _not_ cause a performance regression, the story requests extending _pingpong_ to exercise Box storage.

By comparing transactions per block across pingpong test profiles, we _should_ be able to build confidence that box storage performs at least as well as existing transaction types.  Key metrics include:
* Transactions per block - Helps us glean how quickly transactions can be evaluated.  For equivalently sized blocks, smaller transaction counts than existing test profiles suggest box storage introduces a bottleneck.
* Block size - Helps us understand if/how much Box storage transactions add network overhead compared to existing transaction types.  For equivalent transactions per block, a larger block size implies additional network bandwidth requirements.

As part of writing tests, we'll need to gauge level of configurability required.  Here are dimensions that deserve consideration:
* Box-related consensus parameters
* App count + Boxes per App
* Box operations (create, update, delete)

## Solution

Idea from @cce (thanks!) to speed up test cycles:  Extract TEAL programs to be run in pingpong tests into new benchmarks in https://github.com/algorand/go-algorand/blob/master/ledger/ledger_perf_test.go.

**Comment by cce** [comment]
Besides writing programs for single-node benchmarks like the app tests in ledger_perf_test.go, here is what pingpong does with TEAL:

The simplest TEAL workloads are logic sigs run by pingpong with [`-teal` set to `light`, `normal`, or `heavy`](https://github.com/algorand/go-algorand/blob/master/cmd/pingpong/runCmd.go#L92) 
https://github.com/algorand/go-algorand/blob/master/cmd/pingpong/teal_programs.go

Here is a pingpong dynamic TEAL app generator ([genAppProgram](https://github.com/algorand/go-algorand/blob/master/shared/pingpong/accounts.go#L449-L582)) that takes parameters to put/get variable amounts of app local/global storage that are [controlled by pingpong CLI args](https://github.com/algorand/go-algorand/blob/master/cmd/pingpong/runCmd.go#L97-L101). You could imagine doing something similar with boxes and running different workloads via pingpong.
