### ISSUE TITLE
Include InnerTxns in output of DryRun

### ISSUE THREAD

**Issue by fergalwalsh** [algorand/go-algorand#4168]
## Problem

The DryRun response does not include Inner Txns for Application Call transactions. This makes DryRun quite limited. With this output included it could be effectively used for writing tests for application calls.

(I understand that Dryrun does not evaluate or apply changes from other txns in a group (#3953). This issue is independent of that problem.)

## Solution

Currently `DryrunTxnResult` includes `Logs`, `GlobalDelta`, `LocalDelta` from `EvalDelta` but for some reason it does not include `EvalDelta.InnerTxns`. Assuming that `InnerTxns` is easily serialisable the solution would be to return it too in DryrunTxnResult.

## Urgency

High. There is currently no reasonable contract testing solution for Algorand. Returning `InnerTxns` from DryRun would go someway towards enabling developers to build automated tests.

**Comment by algoanne** [comment]
Hi @fergalwalsh , we agree with you. This issue tracks our initial efforts in this area which will hopefully be what you need: https://github.com/algorand/go-algorand/issues/3953
