### ISSUE TITLE
Add opcode to retrieve the number of assets held by an account.

### ISSUE THREAD

**Issue by AlgoDoggo** [algorand/go-algorand#4206]
## Problem

I would like my contract to be able to retrieve the number of assets held by any account, including its own.

## Solution

Make logic for `acct_params_get AcctNumAssets`?

## Dependencies

none

## Urgency

Not urgent.

**Comment by algoanne** [comment]
Hi @AlgoDoggo what's your use case? What would the smart contract be using this information for?

**Comment by AlgoDoggo** [comment]
Originally, on contract bootstrap I was creating an asset and wanted to disallow bootstrapping the contract twice by looking if the contract address already held an asset. My workaround was simply to set the new asset ID in state and check for this at the top of my bootstrap branch. It works fine, it just cost one state value.

**Comment by algoanne** [comment]
Got it, that makes sense, thanks for explaining @AlgoDoggo. The way you're now doing it is probably ideal, rather than storing it for every contract, so I'mll close this suggestion.

**Comment by jannotti** [comment]
If merged, #4491  will do it.
