### ISSUE TITLE
New health endpoint should be added that only returns success if node is fully caught-up.

### ISSUE THREAD

**Issue by pbennett** [algorand/go-algorand#4223]
## Problem

The current /health endpoint returns success basically if algod is running 'at all.'
However, the node really isn't capable of accepting transactions, looking up blocks, or accounts or doing much of anything until its fully caught up.  
Thus a node in the middle of catch-up (fast catchup or otherwise), shouldn't be seen as being 'ready'

To run an Algorand node in a container (Kubernetes for instance), you typically set up http[s] liveness and readiness handlers.
The readiness handler determines if traffic can be sent to the container.  The existing /health is fine as a liveness handler, however there needs to be either a query-parameter alteration to /health, or a new endpoint to determine if the node is actually capable of accepting real requests/transactions.

Brainstormed topics to consider further:
* Should a readiness check modify behavior of `stat.Catchpoint != “”` guards in https://github.com/algorand/go-algorand/blob/master/daemon/algod/api/server/v2/handlers.go?
* What consideration (if any) should be given to readiness/liveness checks for algod going out of sync _after_ initial catch up?  

## Solution

I recommend a new endpoint of
/ready in addition the existing /health
it should return http status of 500 (there may be another code more appropriate, which is fine) if not ready, and 200 once ready.

Adding this prevents script hacks typically needed to work around this, including additional binaries in with the algorand node (like shells, programs that could be used as attack vector [curl, etc.].  Integrators can simply define their readiness handler as pointing to the /ready endpoint and it will just work.  Nodes can be configured to catch-up on startup, and no traffic will be sent to them until they're fully caught up.

**Comment by winder** [comment]
Could you ulse something like the `v2/status` endpoint and jq to check for `catchup-time` equals 0?

**Comment by pbennett** [comment]
See my comments on why I would never want to do this.   Things like curl, etc. - or even a shell - shouldn't be part of any production container.  They provide attack vectors whether via exfiltration or most importantly, ability to import foreign code trivially and execute it.

**Comment by WesleyMiller1998** [comment]
I have actually run into this issue as well. From my experience, cloud native load balancers (outside of k8s) check for readiness through a very simple system. You define an endpoint on the VM and the load balancers checks for either a 200 (ish) response or an error/no response. I would appreciate this addition as well!

**Comment by mxmauro** [comment]
What about a database schema change? They are very rare to happen but, when they do, the backend isn't up so one cannot be aware about the state.

It happened on the past, some machines took up to half an hour to complete the process and one doesn't know if the process is hung.

**Comment by pbennett** [comment]
Exactly. Same issue - catch-up or db upgrades. 👍

**Comment by mxmauro** [comment]
Excellent!! Thanks.

**Comment by ahangsu** [comment]
I am resuming the work on `/ready` endpoint. So just to be clear, the definition of your endpoint request is that, the node should be healthy and caught up? @pbennett

**Comment by pbennett** [comment]
Healthy, caught-up, and you should be able to successfully submit transactions successfully and fetch current state from that node.
IOW: That node should be able to receive any ALGOD REST API calls with some surety that they will succeed.

**Comment by mxmauro** [comment]
Once I proposed starting the API webserver (or create a secondary one for metrics and health check) before any other action so the health endpoint can return what is really happening inside. The rest of the endpoints can return 503 until fully up.
