### ISSUE TITLE
Eliminate bashisms from `/scripts`

### ISSUE THREAD

**Issue by piens1** [algorand/go-algorand#4242]
`checkbashisms`, a convenient tool for checking possible POSIX incompliances through so called 'bashisms' (`bash` shell specific syntax) outputs 600 lines when invoked in the `/scripts` directory. That means your scripts contain at least 300 non-standard commands and as such are incompatible with all *BSD systems and many Linux-based ones such as Alpine.Many users and system administrators also choose to replace bash with more frugal and secure shells. Consider converting your scripts to proper POSIX shell script syntax.

**Comment by onetechnical** [comment]
This is unlikely to be a high priority; bash is frequently used at large, and this would be a large effort.
