### ISSUE TITLE
add frame pointer opcodes

### ISSUE THREAD

**Issue by algoanne** [algorand/go-algorand#4304]
## Background 

Add frame pointers to the callstack of the AVM.

This would let us avoid the PyTeal convention of saving locals to scratch space. Compiling PyTeal subroutines, including arbitrary recursion, becomes trivial and never uses scratch vars. 

`callsub` should manage a stack of "frames" rather than a stack of bare return PCs. The frame would contain the return PC, the height of the stack when the subroutine was called, and some bookkeepping (see below)

`proto` would be a new opcode, used as the first instruction in a subroutine, to annotate the frame with the number of args the subroutines expects are on the stack, and the number of values the subroutine will put on top of them.

`retsub` would, if invoked by a subroutine that used `proto`, "cleanup" the call stack. It would restore the stack to the height it had when it was called, minus the arguments, plus the return values. The return values would be moved down from above the arguments.

`frame_get` and `frame_put` would be added that act something like `dig` but obtain the value from the stack at a point relative to the top frame's stored height, rather than being relative to the current height.

To call a function `f` that takes 3 arguments and returns 1 value, put each of the 3 arguments on the stack, and `callsub f`. Inside of f, the first instruction should be `proto 3 1`. Then, allocate space for the return value by pushing at least one value to the stack. If, say, 3 local vars are needed, push space for them too. (`pushn 4` would be a new, convenient way to do both in one step, but it may also be common to do so incrementally by calculating those values)

Now, access the return position and the three locals with `frame_get 0` through `frame_get 3`.  Use `frame_get -1` (and `-2` or `-3`) to read the arguments.  Use `frame_put` to change any of those stack slots.  Be sure to store the return value with `frame_put 0`, and then `retsub`.  `retsub` will remove the three arguments, sliding the return value down the stack, and trim the stack to just above the new position of the return value (effectively discarding the locals).

Maybe a version of proto should exist that pushes n stack slots if there are n return values.

Maybe `frame_get/put` should be `frame_load/store`.

Maybe there should be single byte opcodes for the most common slots, just as the is `intc0`, etc.

**Comment by jannotti** [comment]
A reasonable start:
https://github.com/algorand/go-algorand/pull/4319
