### ISSUE TITLE
install_buildtools.sh failed, macos m1

### ISSUE THREAD

**Issue by carson-yang** [algorand/go-algorand#4326]
macos Monterey
Version 12.1 (21C52)

go version
go version go1.18.4 darwin/arm64

commit 3eff2329690e134d1bcd9d5625413176cab0f250 (HEAD -> master, origin/master, origin/HEAD)
Author: cce <51567+cce@users.noreply.github.com>
Date:   Fri Jul 29 15:53:53 2022 -0400

    add AccountMnemonicList config option to loadgenerator (#4321)

+ [[ github.com/go-swagger/go-swagger/cmd/swagger != '' ]]
+ MODULE=github.com/go-swagger/go-swagger/cmd/swagger
++ get_go_version github.com/go-swagger/go-swagger
++ cd /Users/XXXXX/Documents/code/go-algorand/scripts/buildtools
+++ grep github.com/go-swagger/go-swagger
+++ awk -F ' ' '{print $2}'
++ VERSION=v0.25.0
++ echo v0.25.0
++ return
+ VERSION=v0.25.0
+ '[' -z v0.25.0 ']'
++ go install github.com/go-swagger/go-swagger/cmd/swagger@v0.25.0
+ OUTPUT='# golang.org/x/sys/unix
../../../../../go/pkg/mod/golang.org/x/sys@v0.0.0-20200625212154-ddb9806d33ae/unix/syscall_darwin.1_13.go:29:3: //go:linkname must refer to declared function or variable
../../../../../go/pkg/mod/golang.org/x/sys@v0.0.0-20200625212154-ddb9806d33ae/unix/zsyscall_darwin_arm64.1_13.go:27:3: //go:linkname must refer to declared function or variable
../../../../../go/pkg/mod/golang.org/x/sys@v0.0.0-20200625212154-ddb9806d33ae/unix/zsyscall_darwin_arm64.1_13.go:40:3: //go:linkname must refer to declared function or variable
../../../../../go/pkg/mod/golang.org/x/sys@v0.0.0-20200625212154-ddb9806d33ae/unix/zsyscall_darwin_arm64.go:28:3: //go:linkname must refer to declared function or variable
../../../../../go/pkg/mod/golang.org/x/sys@v0.0.0-20200625212154-ddb9806d33ae/unix/zsyscall_darwin_arm64.go:43:3: //go:linkname must refer to declared function or variable
../../../../../go/pkg/mod/golang.org/x/sys@v0.0.0-20200625212154-ddb9806d33ae/unix/zsyscall_darwin_arm64.go:59:3: //go:linkname must refer to declared function or variable
../../../../../go/pkg/mod/golang.org/x/sys@v0.0.0-20200625212154-ddb9806d33ae/unix/zsyscall_darwin_arm64.go:75:3: //go:linkname must refer to declared function or variable
../../../../../go/pkg/mod/golang.org/x/sys@v0.0.0-20200625212154-ddb9806d33ae/unix/zsyscall_darwin_arm64.go:90:3: //go:linkname must refer to declared function or variable
../../../../../go/pkg/mod/golang.org/x/sys@v0.0.0-20200625212154-ddb9806d33ae/unix/zsyscall_darwin_arm64.go:105:3: //go:linkname must refer to declared function or variable
../../../../../go/pkg/mod/golang.org/x/sys@v0.0.0-20200625212154-ddb9806d33ae/unix/zsyscall_darwin_arm64.go:121:3: //go:linkname must refer to declared function or variable
../../../../../go/pkg/mod/golang.org/x/sys@v0.0.0-20200625212154-ddb9806d33ae/unix/zsyscall_darwin_arm64.go:121:3: too many errors'

**Comment by winder** [comment]
@Eric-Warehime is this something you've seen?

**Comment by Eric-Warehime** [comment]
I think I did run into this. It's not an issue with go 1.17 if I recall.

Based on 
* https://github.com/golang/go/issues/51706
* https://stackoverflow.com/questions/71507321/go-1-18-build-error-on-mac-unix-syscall-darwin-1-13-go253-golinkname-mus
* https://github.com/golang/go/issues/49219
* https://go-review.googlesource.com/c/debug/+/359596/2/go.mod
The solution seems to be just bumping the golang.org/x/sys dependency.


I don't think we've gone through the exercise of fully upgrading go-algorand to 1.18 yet though.

**Comment by algolucky** [comment]
related to #4362

**Comment by onetechnical** [comment]
Compilation on arm-based macs has worked fine for some time now.
