### ISSUE TITLE
Extract data/abi into library for go-algorand-sdk

### ISSUE THREAD

**Issue by michaeldiamant** [algorand/go-algorand#4338]
## Problem

The story requests improving modularity by extracting `data/abi` into its own repository.  The desire is to downstream go-algorand usage without relying on the entire repo.

Success criteria:
* New repo called _avm-abi_ exists.  It exposes `data/abi`.
* go-algorand depends on _avm-abi_ + removes `data/abi`.
* go-algorand-sdk replaces its dependency on go-algorand with _avm-abi_.
* _avm-abi_ provides 1st class repo support by mirroring + enriching capabilities of existing repos (e.g. CI/build tooling).
  * Prefer trunk-based release model rather than gitflow. 
  * Prefer release model where development team can issue releases.

**Comment by jasonpaulos** [comment]
Related PRs:
* Populate avm-abi repo: https://github.com/algorand/avm-abi/pull/1
* * Use new repo in go-algorand: https://github.com/algorand/go-algorand/pull/4375
* Use new repo in go-algorand-sdk: https://github.com/algorand/go-algorand-sdk/pull/352
