### ISSUE TITLE
Increase CircleCI instance types

### ISSUE THREAD

**Issue by onetechnical** [algorand/go-algorand#4406]
We want to see if we can speed CI tests by increasing instance size (which we acknowledge will increase costs).

Experiment with increasing the sizes (e.g. medium to large or x-large) and parallelization (go from 4 to 8) to see how we can reduce sizes, and observe the effect on credit burn.

Credit burn per job can me monitored here (example for master branch):

https://app.circleci.com/insights/github/algorand/go-algorand/workflows/circleci_build_and_test/overview?branch=master

**Comment by algobarb** [comment]
| Before | After | Change %
-- | -- | -- | --
arm64_test | 32m 26s | 14.4 | -59%
$ annually | $17,971 | $115,891 | 545%

**Comment by algobarb** [comment]
Results from just increasing the machine from medium to large, no changes to parallelism
| Before | After | Change %
-- | -- | -- | --
arm64_test | 30m | 27m | -10%
arm64_integration | 28m | 18m | -35%
arm64_e2e_subs | 11m | 11m | 0%
arm64_e2e_expect | 24m | 23m | -4%
amd64_test | 17m | 15m | -11.8%
amd64_integration | 22m | 22m | 0%
amd64_e2e_subs | 11m | 11m | 0%
amd64_e2e_expect | 19m | 17m | -10.5%

Before times were the 95 percentile of the last 30 days. After were the average of 3 runs from this draft PR: https://github.com/algorand/go-algorand/pull/4467

**Comment by michaeldiamant** [comment]
For reader context:  The above results do _not_ include parallelism changes from https://github.com/algorand/go-algorand/pull/4448.  

We should assume the same experiment using #4448 is liable to produce materially different results.
