### ISSUE TITLE
SPIKE In DevMode no block seed is available

### ISSUE THREAD

**Issue by barnjamin** [algorand/go-algorand#4423]
Running the sandbox with DevMode flag set to `true` does not seem to produce a block seed which is useful for things like the new `vrf_verify` op and some folks use it for other reasons (see https://github.com/algorand/sandbox/issues/137)

Running off latest master but confirmed same issue on current beta release (3.9.1).

With `DevMode` as `false` it works as expected.

**Comment by jannotti** [comment]
There is no block seed to return in dev mode, but I think we might
reasonably just return the txnhash from the same block instead.

**Comment by gessic-apps** [comment]
Hi @jannotti Curious to know if this is going to be made available anytime soon?
