### ISSUE TITLE
Remove generate_*_config.sh scripts

### ISSUE THREAD

**Issue by algolucky** [algorand/go-algorand#4464]
## Problem

The following scripts are no-longer functioning and haven't been updated in 3 years:

- https://github.com/algorand/go-algorand/blob/master/scripts/generate_beta_config.sh
- https://github.com/algorand/go-algorand/blob/master/scripts/generate_devnet_config.sh
- https://github.com/algorand/go-algorand/blob/master/scripts/generate_testnet_config.sh

at this point, they are obsolete files in the scripts directory.

## Solution

remove `generate_beta_config.sh`, `generate_devnet_config.sh`, and `generate_testnet_config.sh`

## Dependencies

- doing a search, nothing in this repository is referencing these scripts
- external users are definitely not using them because they use internal infrastructure

**Comment by abebeos** [comment]
the files look unused:

* https://github.com/search?q=org%3Aalgorand+generate_beta_config.sh
* https://github.com/search?q=org%3Aalgorand+generate_devnet_config.sh&type=commits
* https://github.com/search?q=org%3Aalgorand+generate_testnet_config.sh

This does not look like a "good first issue", as a newcomer cannot have this knowledge.

Maybe ask the original author(s) if the files can be safely removed.

(As a sidenote: issues affecting obsolete files should not have "Low Priority")

**Comment by rafael-abuawad** [comment]
I will take a look a this

**Comment by rafael-abuawad** [comment]
This should be really straight forward, I will take a look at this and see how to remove this files safely.

**Comment by kehiy** [comment]
@algolucky you can review my change
