### ISSUE TITLE
Server's `ApplicationBoxes()` Should Return 404 Error when Querying Nonexistent Application Index

### ISSUE THREAD

**Issue by tzaffi** [algorand/go-algorand#4575]
### Your environment
C.I.

### Steps to reproduce

Run `TestBoxNameByAppId()` in `restClient_test.go` and observe that it passes. In particular:

### Expected behaviour

The assertion on [Line 1488](https://github.com/algorand/go-algorand/blob/0eb5dd04df196e074705b2a526a38f6fc3b6331e/test/e2e-go/restAPI/restClient_test.go#L1483-L1488) ought to **fail** because there is no app with index 1337.

### Actual behaviour
The assertion _does NOT fail_ because `err == nil`

## Additional Information
The corresponding indexer endpoint does return a 404 error [under similar circumstances](https://github.com/algorand/indexer/blob/35e87fa72773dc6503f8aa23012ab0876e3f5d27/api/test_resources/boxes.json#L606-L619)

**Comment by jannotti** [comment]
I don't think this correct. If an app is deleted while it has boxes, those
boxes live forever.

**Comment by tzaffi** [comment]
Ahhh right! There is no obvious way of telling the difference between:

* a never existing app whose boxes are being queried
  * a 404 might make sense in this case
* an old app that got deleted and whose boxes are being queried
  * a 404 would _not_ make sense
  
So being conservative and naively reporting the boxes found sounds like the correct approach. Am closing the ticket.

I'll also:
* modify #4576 to reflect this finding
* investigate if indexer's endpoint needs to be modified
