### ISSUE TITLE
Consider increasing maxTealSourceBytes in /v2/teal/compile

### ISSUE THREAD

**Issue by fergalwalsh** [algorand/go-algorand#4632]
## Problem

There is a limit on the byte size of a teal program that can be compiled with the `teal/compile` endpoint. I have run into that limit with a teal program that has a decent amount of comments. Normally I'd strip the comments before submitting to the compile endpoint but I'd like to take advantage of the source maps functionality that is now builtin.

https://github.com/algorand/go-algorand/blob/d3c10f41f2ac3e2bf84d8ddfd134c1cfba3d0908/daemon/algod/api/server/v2/handlers.go#L54

I am aware I can compile without this limit with `goal` but for some use cases compiling through a node is more convenient.

## Solution

If there is room for a higher safe value it would be nice to increase the limit to such a value. 

## Dependencies

None

## Urgency
There are other solutions so not particularly urgent at the moment.

**Comment by algoanne** [comment]
closing as I believe this was solved by #4633 .
