### ISSUE TITLE
Ability to change/disable network reward rate on sandnet

### ISSUE THREAD

**Issue by nullun** [algorand/go-algorand#4642]
Since approximately May 14th Mainnet has had the reward rate set to 0. I'm not aware of any intention of changing it in the future, but right now the default developer sandnet network in sandbox continues to give rewards. This can make testing in sandbox different to running on mainnet, as smart signatures and smart contracts will continue to have their Algo increase over time.

Is there an easy way we can change (to 0) the reward rate of a sandnet network?

**Comment by algoanne** [comment]
just a reminder that although the rewards program has ended, if anyone ever were to send money to the rewards pool then reward payouts would start again, following the protocol. So, Smart Contracts should be prepared for receiving sums like that (or from any other source randomly sending them money)

**Comment by pao-beep** [comment]
are the senders to that reward address limited to a few accounts?

**Comment by algoanne** [comment]
@pao-beep no, I don't believe so
