### ISSUE TITLE
Invalid path parameter for address/tx/pending  in swagger output

### ISSUE THREAD

**Issue by purestaketdb** [algorand/go-algorand#467]
### Subject of the issue
The generated swagger.json file from the Algorand betanet client provides an incorrect definition for the '/v1/account/{addr}/transactions/pending' endpoint. The path parameter should be {address} and will not work as defined.

### Your environment
* Software version: `algod -v` - 1.1.4.beta [rel/beta] (commit #0c64a3df)
* Operating System details.  - OS X 

### Steps to reproduce
curl  http://127.0.0.1:{port}/swagger.json  

### Expected behaviour
Address variable should be {address} 

### Actual behaviour
Address variable is {addr} 

`    "/v1/account/{addr}/transactions/pending": {
      "get": {
        "description": "Get the list of pending transactions by address, sorted by priority, in decreasing order, truncated at the end at MAX. If MAX = 0, returns all pending transactions.\n",
        "produces": [
          "application/json"
        ],
        "schemes": [
          "http"
        ],
        "summary": "Get a list of unconfirmed transactions currently in the transaction pool by address.",
        "operationId": "GetPendingTransactionsByAddress",
        "parameters": [
          {
            "pattern": "[A-Z0-9]{58}",
            "type": "string",
            "description": "An account public key",
            "name": "addr",
            "in": "path",
            "required": true
          },`

**Comment by rotemh** [comment]
Thanks for the feedback. Can you please elaborate more? Why should it be `address` and not `addr`?

**Comment by purestaketdb** [comment]
This was from awhile ago, so the details may be a bit blurry. We ran into it creating a new client from the swagger file. Generically, address is used everywhere else so it's odd to use addr for one endpoint - example:

    "/v1/account/{address}/transaction/{txid}": {
      "get": {
        "description": "Given a wallet address and a transaction id, it returns the confirmed transaction information. This call scans up to \u003cCurrentProtocol\u003e.MaxTxnLife blocks in the past.\n",
        "produces": [
          "application/json"
        ],
        "schemes": [
          "http"
        ],
        "summary": "Get a specific confirmed transaction.",
        "operationId": "TransactionInformation",
        "parameters": [
          {
            "pattern": "[A-Z0-9]{58}",
            "type": "string",
            "description": "An account public key",
            "name": "address",
            "in": "path",
            "required": true
          },
          {
            "pattern": "[A-Z0-9]+",
            "type": "string",
            "description": "A transaction id",
            "name": "txid",
            "in": "path",
            "required": true
          }

**Comment by rotemh** [comment]
I see. Besides the oddity, did it break anything?

**Comment by purestaketdb** [comment]
At the time there was an issue with it -  however I don't have the detail any longer.

**Comment by rotemh** [comment]
Ok, given the coming `v2` and the nature of this change, this will not be fixed.

**Comment by purestaketdb** [comment]
FYI this endpoint is inconsistently handled in the routes as well - it does not validate the structure of the address - 

`
	lib.Route{
		Name:        "pending-transaction-information-by-address",
		Method:      "GET",
		Path:        "/account/{addr}/transactions/pending",
		HandlerFunc: handlers.GetPendingTransactionsByAddress,`

vs. 

`	lib.Route{
		Name:        "transactions",
		Method:      "GET",
		Path:        "/account/{addr:[A-Z0-9]+}/transactions",
		HandlerFunc: handlers.Transactions,
	},`

Which results in an inconsistent error response of 400 instead of 405 

root@7ff87f1bb76a:/opt/algorand/node# curl -v -H "X-Algo-API-Token: $(cat ./data/algod.token)" http://127.0.0.1:4001/v1/account/foo/transactions/pending
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 4001 (#0)
> GET /v1/account/foo/transactions/pending HTTP/1.1
> Host: 127.0.0.1:4001
> User-Agent: curl/7.58.0
> Accept: */*
> X-Algo-API-Token: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
> 
< HTTP/1.1 400 Bad Request
< Access-Control-Allow-Headers: X-Algo-API-Token, Content-Type
< Access-Control-Allow-Methods: GET, POST, PUT, OPTIONS
< Access-Control-Allow-Origin: *
< Date: Tue, 17 Mar 2020 13:54:46 GMT
< Content-Length: 27
< Content-Type: text/plain; charset=utf-8
