### ISSUE TITLE
Dryrun panics if the eval method returns prior to setting debug state

### ISSUE THREAD

**Issue by barnjamin** [algorand/go-algorand#4698]
### Subject of the issue

During testing Joe was getting a nil pointer deref panic from the dryrun endpoint.

https://gist.github.com/joe-p/48982627e54364877662ae279a5001ce

The source of the issue seems to be [this](https://github.com/algorand/go-algorand/blob/15890d402c6a1d27b7ff9b80b42a78afcf8aff5a/data/transactions/logic/eval.go#L816) method call in a deferred function  combined with an early return from the eval method, likely [here ](https://github.com/algorand/go-algorand/blob/feature/avm-box/data/transactions/logic/eval.go#L834) from a teal version that is unsupported prior setting the debug state [here](https://github.com/algorand/go-algorand/blob/feature/avm-box/data/transactions/logic/eval.go#L847).

**Comment by joe-p** [comment]
Just confirming that I didn't have `"ConsensusProtocol": "future",` in my network template. Adding it fixed the issue as expected.

**Comment by jannotti** [comment]
This was fixed.
