### ISSUE TITLE
rest api:HTTP 500 Internal Server Error: indexer isn't running, this call is disabled

### ISSUE THREAD

**Issue by wx-shi** [algorand/go-algorand#47]
AlgodClient.TransactionByID(hash)->HTTP 500 Internal Server Error: indexer isn't running, this call is disabled
AlgodClient.Block(height)->HTTP 500 Internal Server Error: indexer isn't running, this call is disabled

**Comment by JasonWeathersby** [comment]
Did you enable the indexer on the node you are connecting to?
Read over this page.
https://developer.algorand.org/docs/algorand-node-types
