### ISSUE TITLE
test: Add running go:generate for stringer to codegen_verification.sh

### ISSUE THREAD

**Issue by iansuvak** [algorand/go-algorand#4727]
System build / correctness - Quick fix

Problem: we don't run stringer verification (go tool to convert variable names into strings).

`scripts/travis/codegen_verification.sh` currently checks that the autogenerated code committed to the repo matches that the autogen libraries produce themselves. This serves as a safeguard against people forgetting to run autogenerate when touching code that is affected by it. 

We are currently doing this for libraries like msgp but we aren't doing it for `stringer`

**Comment by jootd** [comment]
Hi, Is this still an issue ?

**Comment by iansuvak** [comment]
> Hi, is this still an issue ?

Just checked and it isn't. It looks like it was fixed in https://github.com/algorand/go-algorand/pull/4865/ Closing the issue and thanks for asking
