### ISSUE TITLE
Include consensus vote information in node status

### ISSUE THREAD

**Issue by winder** [algorand/go-algorand#4728]
When a consensus upgrade vote is in progress, we should include information about the voting progress.

Fields from the `UpgradeVote` blockheader struct:
* UpgradePropose
* UpgradeDelay
* UpgradeApprove

Consensus value:
* UpgradeThreshold

Computed value:
* The "no" votes. [For reference, the no votes are computed in node-ui.](https://github.com/algorand/node-ui/commit/b83cb12c204e8a6c5b3a5e203eae1bfbe4d32825#diff-e315ed0b493961808881f11e1a64ea256ce1ae92e6dfad586c013b78006eafbcR204)

Note: there is a special case between when a vote is scheduled and when the upgrade is applied where `UpgradeState` is non-zero but the vote has concluded. [node-ui had this bug.](https://github.com/algorand/node-ui/commit/58569622f4346fdfec73ad367bdf32de6b98b831)

# Acceptance Criteria
* `goal node status` includes 5 new rows when a consensus upgrade is being voted on.
* [Update the API node status response type.](https://github.com/algorand/go-algorand/blob/master/daemon/algod/api/algod.oas2.json#L3354).
* [And the API handler.](https://github.com/algorand/go-algorand/blob/master/daemon/algod/api/server/v2/handlers.go#L761)

**Comment by winder** [comment]
This is done.

**Comment by mciccarello** [comment]
You're welcome
