### ISSUE TITLE
Debugging:  Support catching up to a specific round

### ISSUE THREAD

**Issue by michaeldiamant** [algorand/go-algorand#4748]
## Problem

When diagnosing state differences across nodes, it feels beneficial to _freeze_ algod at a specific round.  For example, to compare _tracker_ database across nodes the flushed round must match.

The story requests providing a first-class way for algod operators to freeze algod at a specific round.  The following is up for discussion:
* How is the freeze round specified (e.g. cli arg, etc)?
* What is algod behavior upon reaching freeze (e.g. flushes + exits, interactively waits)?

**Comment by barnjamin** [comment]
If possible, this ability + the ability to change a local (caught up) node to be local only would help _greatly_ with being able to debug integrations with live apps

**Comment by jsgranados** [comment]
This is complete as this can be done with our follower node configuration.
