### ISSUE TITLE
Monitoring for dispensers / load generator / ping pong account balances

### ISSUE THREAD

**Issue by jsgranados** [algorand/go-algorand#4798]
## User Story

As a Dev Ops engineer, I would like to have a monitor that tracks account balances for our dispensers, our load generator tests, and ping pong tests so that I am able to know when my account balances are running low and can take immediate action

## Functional Information

- Ticket came out of a sprint retro: https://metroretro.io/board/LBBQSDFPHBPD
- Purpose for the ticket is for Dev Ops to be able to evaluate how we can monitor the account balances for our dispensers, and accounts that our load generator and ping pong tests use.
- Nice to have: It would be great to have a script that executes to rebalance the accounts and makes sure that our load generators, and ping-pong tests can correctly execute. In addition, it would be great to have a script that can collect "borrowed" funds when users use our dispensers. 
- Similar problem: we currently do not have a process around dispensing large amounts of Algo's on testnet to users. (i.e if someone needs a large amount of algo's who approves, how do we get the funds back, how do we ensure we never run out of funds) Because we want to ensure that we do not run out of funds, we should establish a process around recuperating the funds dispensed. This may be a separate ticket, but it is in the same light as the issue we are trying to solve -- having a clear way of looking at how much funds we are operating with on our different networks.

From #1788

## Summary
We need a task in our task framework that queries balances of our dispenser instances and lets us know when we need to give them more algos

## Scope/Requirements
We just need a script that can query account balances and inform us when they're below a certain amount. This will be put in a docker image and run using our task framework as a cronjob (Look into go-algorand-ci/tasks to add to k8s cluster as a cron task)

List of accounts that we need to check balances for and the network that they're on.

- mainnet
  - ~poker (private)~
  - ~poker (public)~
  - load generator
- testnet
  - dispenser
  - new dispenser w/ USDC support
  - load generator
- betanet
  - dispenser
  - load generator
- devnet
  - dispenser

## Acceptance criteria 
Monitor accounts balances for minimum balance and dispense algo to those accounts
Add alerts: datadog alert on minimum account balance 

## Urgency/Relative Priority
This is mildly urgent. Right now we have to remember to check these balances or get notified by users that they need more algos.

**Comment by onetechnical** [comment]
Third parties provide this gratis for managed networks
