### ISSUE TITLE
SPIKE: Investigation on why Package and Sign steps on go-algorand.muleci-full-pipeline run longer than expected

### ISSUE THREAD

**Issue by jsgranados** [algorand/go-algorand#4799]
## Problem

Currently, whenever the go-algorand.muleci-full pipeline runs, the Package and Sign stages take on average 52min and 26min, respectively. This is a behavior that is not expected as these are administrative stages rather than actual build stages.
Jenkins: https://jenkins.algodev.network/job/go-algorand.muleci-full-pipeline/

## Acceptance Criteria
- A root cause issue, or several is identified for each step
- Discuss with the team to develop a recommended fix/refactor
- A new ticket with a recommended fix
- STRETCH GOAL: Fix if it's not difficult

## Functional Information
- Issue was spoken about on the following slack thread: https://algorand-internal.slack.com/archives/GTFN0FJJK/p1668482649100659
- The time that it takes for these stages to complete is not normal. We should look to enhance or remove any outlying code that could be causing the delay in the completion of the stages. In fixing these steps, we can reduce the amount of time it takes for go-algorand.muleci-full-pipeline to complete by 50% (assuming that package stage reduces to 10 min, and sign stage reduces to 10 min) in term reducing our build time by 50%

**Comment by onetechnical** [comment]
The signing stage was optimized. The package stage has to deal with uploading and downloading large files, and is unlikely to be optimized in its current iteration.
