### ISSUE TITLE
Issue with install of 3.12.2

### ISSUE THREAD

**Issue by tom-gnade** [algorand/go-algorand#4851]
### Subject of the issue

Attempting to install version 3.12.2. Received the following output after $ sudo apt-get update:

W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://releases.algorand.com/deb stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 007CB592A5D131FE
W: Failed to fetch https://releases.algorand.com/deb/dists/stable/InRelease  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 007CB592A5D131FE
W: Some index files failed to download. They have been ignored, or old ones used instead.

### Steps to reproduce

1. $ sudo apt-get update
2. observe the error messages

### Expected behaviour
The public key should not be changed between releases, or it should automatically update, or it should be part of the install instructions.

### Actual behaviour
The public key signing the file has been updated since version 3.11.x. To resolve the issue, I repeated the following steps:

https://developer.algorand.org/docs/run-a-node/setup/install/

$ curl -O https://releases.algorand.com/key.pub
$ sudo apt-key add key.pub
$ sudo add-apt-repository "deb [arch=amd64] https://releases.algorand.com/deb/ stable main"
$ sudo apt-get update
$ sudo apt-get upgrade -y

If there is an update to the public key, then the release instructions should mention it.

**Comment by algoanne** [comment]
> If there is an update to the public key, then the release instructions should mention it.
yes, good point. We should be sure to include these sorts of changes in the release notes when they come up.
