### ISSUE TITLE
Error while installing Go-Algorand version 3.12.2

### ISSUE THREAD

**Issue by tom-gnade** [algorand/go-algorand#4852]
### Subject of the issue

I observed the following error while installing Go-Algorand version 3.12.2:

Setting up algorand (3.12.2) ...
Glob pattern passed to check, but globs are not supported for this.
Invalid unit name "algorand@*" escaped as "algorand@\x2a".
algorand@* is a disabled or a static unit not running, not starting it.

I believe I also observed this error during the 3.11.x install, so it has been around for a few releases. I observed the error on more than one relay, so it is not isolated to a specific node.

### Your environment

* Software version: `algod -v` 3.12.2
* Node status if applicable: `goal node status` Ok
* Operating System details. Ubuntu 20.04 LTS
* In many cases log files and cadaver files are also useful to include. Since these files may be large, an Algorand developer may request them later. These files may include public addresses that you're participating with. If that is a concern please be sure to scrub that data.

### Steps to reproduce

1. sudo apt-get update
2. sudo apt-get upgrade -y
3. observe the output to the command window

### Expected behaviour
An error should not be thrown.

### Actual behaviour
An error is thrown.

**Comment by algoanne** [comment]
Hi, is this still occurring? Looks like it may have been related to your service file, did you have any customizations there?

**Comment by tom-gnade** [comment]
Yes, the service file was customized. Our current config only has a few
overrides. The next time we upgrade, I will watch the logs for this error
and report it if I find it again.
