### ISSUE TITLE
Node.log should be properly formatted JSON, not a mixed file format.

### ISSUE THREAD

**Issue by tom-gnade** [algorand/go-algorand#4857]
### Subject of the issue

The node.log file displays information about the service restart without JSON formatting. The remainder of the file is properly JSON formatted. For example:

++++++++++++++++++++++++++++++++++++++++
Logging Starting
Telemetry Enabled: <telemetry-guid>:<server-name>
Session: <session-guid>
++++++++++++++++++++++++++++++++++++++++

when parsing the file, I often use jq from the shell to format and filter the file effectively, but this single element in the file causes a parsing error. For example, if the message above is part of the selection, the output will display:

$  tail -n 10 $ALGORAND_DATA/node.log | jq

parse error: Invalid numeric literal at line 17, column 0

instead of properly formatted JSON output.

### Steps to reproduce

1. Parse node.log and make sure the output includes a service restart message
2. Pipe the output to jq to display as formatted JSON instead of text, and observe the parse error

### Expected behaviour
The log should not include both formatted JSON and free text, it should be 100% formatted JSON. For example, the restart message could be enhanced to include more of the information from $ sudo systemctl status algorand, and wrapped in a JSON object:

{
  "event": "restart"
  "level": "info", # or "warning" so it would be included at a lower level of logging
  "telemetry-guid": "<GUID>",
  "server": "<SERVER-NAME>",
  "session-guid": "<GUID>",
  "msg": "\n++++++++++++++++++++++++++++++++++++++++\nLogging Starting\nTelemetry Enabled: <telemetry-guid>:<server-name>\nSession: <session-guid>\n++++++++++++++++++++++++++++++++++++++++\n
<add other interesting info here from $ sudo systemctl status algorand>",
  "time": "2022-12-03T04:18:01.647758+09:00"
}

I also suggest adding the element "event" to other log entries, and using the value "log" or "message" or something, so the results can be easily filtered by event type.

### Actual behaviour
The log is a hybrid of free text and formatted JSON.

**Comment by winder** [comment]
Resolved by issue #5000
