### ISSUE TITLE
asm: drive speculation by event and timer

### ISSUE THREAD

**Issue by algorandskiy** [algorand/go-algorand#4867]
## Summary

Current implementation is timer based instead of events. A new idea is to 
1. start speculating on a timer first
2. Ensure the speculation is right after seeing a soft votes

Events:
- validating a proposal
- 3.0s timer
- witness soft vote (at 3.4s)
- validating a new block at consensus

## Acceptance

Unit test demonstrating speculation kicks off as expected.

**Comment by brianolson** [comment]
in progress in https://github.com/algorand/go-algorand/pull/4861

**Comment by algorandskiy** [comment]
Fixed in #4861
