### ISSUE TITLE
asm: ensure speculative assembly cancelation handled well

### ISSUE THREAD

**Issue by algorandskiy** [algorand/go-algorand#4869]
# Summary

There is a suspicious speculative assembly cancelation b/c of better proposal is not handled.
If you speculate on the losing block, cancel speculation and either speculate on another block or fall back to the winning block (if the round has ended).

## Acceptance

Unit test showing cancellation b/c of better proposal is fired and handled, and next speculation starts.

**Comment by brianolson** [comment]
in progress in https://github.com/algorand/go-algorand/pull/4861

**Comment by algorandskiy** [comment]
Fixed in #4861
