### ISSUE TITLE
Min Balance Incorrectly Reported

### ISSUE THREAD

**Issue by Blackglade** [algorand/go-algorand#4873]
### Subject of the issue

There are a number addresses out there that interact with an app but don't hold any algos and are not present in the indexer. An address like this: `LLY22GANH43FA3A37IVH2TGJVE7VZLWVQETFKJNDZZ2FV2DFOXWPV67ELY`. The node lists this addresses's minimum balance as 0.1 ALGO when really it doesn't hold any Algos.

https://mainnet-api.algonode.cloud/v2/accounts/LLY22GANH43FA3A37IVH2TGJVE7VZLWVQETFKJNDZZ2FV2DFOXWPV67ELY

### Expected behaviour

I believe it's defaulting to 100000 microAlgos when it should default to 0?

**Comment by jannotti** [comment]
I don't think that's wrong, though I suppose it's endlessly debatable.  While it's true that the account has no algos in it (in fact, one might argue that the account simply doesn't exist yet), it is not legal to send that address 0.05 algos.  The account must never have less than 0.1 algos in it (if it has any at all).

At any rate, this is the way that's been defined for a long time, would be a big hassle to change (the `min_balance` opcode also works this way), and I don't think would be any _more_ correct than the correct value.
