### ISSUE TITLE
goal account balance does not show asset balances

### ISSUE THREAD

**Issue by algobolson** [algorand/go-algorand#488]
### Subject of the issue
`goal account list` shows asset balances but `goal account balance` does not

### Your environment
* Software version: master 0581f324814ab475c46e36e4a8dfcb66e08875dd

### Steps to reproduce
make a throw away private network
create an asset
run `goal account list`
run `goal account balance -a ...` on an account with an asset balance

### Expected behaviour
asset balance should be printed

### Actual behaviour
only the Algo balance was printed. tool hasn't been updated for assets.

**Comment by StylishTriangles** [comment]
Is there any way to check account balances with goal? I'm trying account list, but it just shows created assets and account balance only shows Algos.
