### ISSUE TITLE
Build pipeline builds algod docker image

### ISSUE THREAD

**Issue by jsgranados** [algorand/go-algorand#4894]
@algojack commented on [Fri Apr 15 2022](https://github.com/algorand/go-algorand-internal/issues/1992)

## Problem

As a third-party developer, I want to be able to pull and run an algod docker container image so that I can easily set up my algod node on available environments and test out my smart contract changes/developments

## Acceptance Criteria
- algod stable docker container image is built from our official binaries
- algod container image is published to dockerhub with proper tagging under the algorand account 
- keep release checklist and confluence page updated if there are changes to behavior
- Stretch: complete #3659

## Functional Information
- Instead of working around the pipeline that uses mule to build our packages, we should consider an alternative
- This should be single-arch AMD64 (to match what we have currently) 
- stretch: support multiarch builds (DockerBuildX ?)

---

@onetechnical commented on [Mon Aug 08 2022](https://github.com/algorand/go-algorand-internal/issues/1992#issuecomment-1208387922)

We want to look at the work coming out of Lamprey to provide more usable docker images, and then we want to integrate this multiarch build into the build process.

**Comment by onetechnical** [comment]
This is currently a separate pipeline / container, so I think this is done.
