### ISSUE TITLE
goal asset send should have --lastvalid

### ISSUE THREAD

**Issue by algobolson** [algorand/go-algorand#494]
**Is your feature request related to a problem? Please describe.**

*GOAL IS INCONSISTENT*
`goal clerk send --lastvalid` but `goal asset send --validrounds` !

Was trying to script some `goal` commands and wanted to specify `goal asset send --firstvalid A --lastvalid B` but it only has `--validrounds X` and it was slightly inconvenient to calculate validrounds

**Describe the solution you'd like**

Allow `goal asset send --lastvalid B`
This should work with `--firstvalid A` specified or not, if not specified it should ask algod for the current round and use that.

**Comment by pzbitskiy** [comment]
It is even worse, `account changeonlinestatus` has  `firstRound` and `validRounds` and also needs to be fixed.
