### ISSUE TITLE
Non-Archival Relay Nodes Support

### ISSUE THREAD

**Issue by gmalouf** [algorand/go-algorand#5063]
## Problem

We want to make it as straightforward as possible to support the Algorand network by running a "relay" node. **Cost** and **ability to find appropriate resources** (in this case, 4 TB disks) are two barriers that make it harder to run a relay. 

We'd like to introduce **non-archival relay nodes** as a supported configuration (in settings, documented on dev portal, etc).

## Solution

The logic that enforces 'relays' being archival nodes is [brief and self-contained](https://github.com/algorand/go-algorand/blob/master/config/config.go#L127). We will also want to disable catchpoint generation here (by setting `CatchpointTracking` to -1).

### Items We Need to Address Along the Way

**Formulating/running Test Scenarios Including**:

- bootstrap net new network with archival/non-archival relays both running
- Adding non-archival relays to existing network (with only archival ones)
- Update archive SRV record with known archival node(s), run 1 or more new archival nodes in a network with ALL non-archival relays - ensure archive node resolution works as expected for nodes spinning up to both full catchup and fast catchup.
   - Note that EnableCatchupFromArchiveServers will need to be updated to default to **true**, which tells nodes to prioritize catching up from archive servers over relays.
- In all of the above cases, observe state proofs being generated properly (on both archival and non-archival relays)
- **Research**: Exercise behavior when trying to retrieve a catchpoint from a relay that is non-archival - is this gracefully handled? (At time of writing, do not recall behavior)

**Comment by onetechnical** [comment]
This appears to be done with v3.23.1-stable.
