### ISSUE TITLE
Eliminate 'DataDir' related Duplicates within 'cmd/goal'

### ISSUE THREAD

**Issue by abebeos** [algorand/go-algorand#5068]
(Maintainers: I am missing an `Enhancement` template. This here is neither a `new-feature`, nor a `bug`)

## Problem

Code Duplication (`resolveDataDir` and possibly other DataDir related functions).

This came up within https://github.com/algorand/go-algorand/pull/5067#pullrequestreview-1272066636

## Solution

Usual strict refactoring, possibly a slight function signature change.

## Dependencies

> Does the solution have any team or design dependencies?

I do not understand this question.

## Urgency

Not super-urgent, but the kind of technical debt that needs to be 'payed' better sooner than later.

(I will take a look at this, as I'm still warm from #5067)

**Comment by winder** [comment]
Closed by #5073 5073
