### ISSUE TITLE
Improve pull test speed

### ISSUE THREAD

**Issue by algobolson** [algorand/go-algorand#508]
3 day timebox - may result in additional tickets

It takes over an hour for testing system to validate a pull request. I get distracted and check in an hour or two later and this slows down daily development.

Tests should run faster. Maybe some slow system tests that run networks and wait for rounds could run in parallel. Walk through the sets of tests called in `scripts/travis/integration_test.sh` and `scripts/travis/build_test.sh` and see what's slow and what can be optimized.

**Comment by pzbitskiy** [comment]
e2e_go_tests execution time improved by 10-12 minutes.
next stops are `expect` tests and `auction` tests.

**Comment by pzbitskiy** [comment]
Fixed stderr polling in expect tests, +2-5 minutes.
