### ISSUE TITLE
Error is shown during `goal account info` if an asset is deleted

### ISSUE THREAD

**Issue by nullun** [algorand/go-algorand#5154]
### Subject of the issue

If an account is stilled opted in to a deleted asset, when retrieving their account info using `goal` an error is displayed and two records are shown in their held assets.

```sh
$ goal account info -a ALICE7Y2JOFGG2VGUC64VINB75PI56O6M2XW233KG2I3AIYJFUD4QMYTJM
Error: Unable to retrieve asset information for asset 19 referred to by account ALICE7Y2JOFGG2VGUC64VINB75PI56O6M2XW233KG2I3AIYJFUD4QMYTJM: HTTP 404 Not Found: asset does not exist
Created Assets:
	<none>
Held Assets:
	ID 7, Demo Asset, balance 0.00 DA
	ID 19, error
	ID 19, <unnamed>, balance 0 units
Created Apps:
	ID 4, global state used 0/0 uints, 0/0 byte slices
Opted In Apps:
	<none>
Minimum Balance:	400000 microAlgos
```
### Your environment

```sh
$ goal -v
12885926471
3.15.172615.dev [master] (commit #a688c236)
go-algorand is licensed with AGPLv3.0
source code available at https://github.com/algorand/go-algorand
```

### Steps to reproduce

1. Create ASA
2. Opt in with another account
3. Destroy ASA
4. Get account info

### Expected behaviour

Gracefully display an unknown/deleted asset on a single line without errors.

**Comment by uday7981** [comment]
hey, I am interested on this issue. can you tell me the initialisation part for this issue.
