### ISSUE TITLE
Permissionless health endpoint for gossip service 

### ISSUE THREAD

**Issue by urtho** [algorand/go-algorand#5208]
## Problem

There is no easy way to get the state of a relay node when only the gossip service is enabled/exposed.
External monitoring of relay status is now possible only with exposed REST API port.
This can protected with token but this does not allow for public, permissionless monitoring. 

## Solution

Mount /v2/status API endpoint on the gossip service port as well. 

## Urgency

External public monitoring is needed for community run , decentralized relay networks.
Goracle network could easily monitor relay health by analyzing /v2/status output if exposed on gossip port.

**Comment by winder** [comment]
Completed with https://github.com/algorand/go-algorand/issues/4223

**Comment by scholtz** [comment]
I support this one.. the only way i can monitor healthiness of 4160 port from load balancer is monitoring / path with status code 404.. this is not very good approach, but without health endpoint it is the only option
