### ISSUE TITLE
Invalid Box reference error message encoding

### ISSUE THREAD

**Issue by barnjamin** [algorand/go-algorand#5229]
### Subject of the issue

Right now, an error message from the algod caused by an invalid box reference returns the raw byte slice in the the error message.
https://github.com/algorand/go-algorand/blob/master/data/transactions/logic/box.go#L40

For any bytes that don't fall in the ascii character range this makes for difficult debugging.

Here is the error message for a box named `0xFF4849`

```
algosdk.error.AlgodHTTPError: TransactionPool.Remember: transaction TE6PJUHXQ5QJ2CLFRLOFCLZVESRXYYKOTZ2XWKH3H6MKIHATNO3Q: logic eval error: invalid Box reference �HI. Details: pc=67, opcodes=pushbytes 0xff4849 // 0xff4849
pushint 1024
box_create
```

### Solution

Encode the name as hex or base64 prior to returning the error message so that it may be more easily decoded by the developer.

**Comment by bbroder-algo** [comment]
something like
https://go.dev/play/p/JrdNg5Ya_l2
?

**Comment by barnjamin** [comment]
@bbroder-algo easiest might just be to change `%v` to `%x` to spit out the whole thing as hex

**Comment by jannotti** [comment]
See also:

data/transactions/logic/box.go:153:		return fmt.Errorf("no such box %#v", name)
data/transactions/logic/box.go:181:		return fmt.Errorf("no such box %#v", name)
ledger/internal/applications.go:261:		return fmt.Errorf("box %s does not exist for %d", key, appIdx)

**Comment by ahangsu** [comment]
closing for #5325 merged
