### ISSUE TITLE
Unable to retrieve trie root hash

### ISSUE THREAD

**Issue by oggy95** [algorand/go-algorand#5232]
### Subject of the issue

Good day!
This night algorand node was stopped from insufficient space amount. After rescaling disk size and restarting service I got this error in logs.
Is it possible to recover state of the node or need to sync from scratch?
I'm trying to find command to reset node state, but didn't find. Is there are any solution to reset node state by goal command? Or just need to mode data lib folder and start over?

```
{"file":"node.go","function":"github.com/algorand/go-algorand/node.MakeFull","level":"error","line":218,"msg":"[Stack] goroutine 1 [running]:\nruntime/debug.Stack()\n\truntime/debug/stack.go:24 +0x65\ngithub.com/algorand/go-algorand/logging.logger.Errorf({0xc00009db90, 0xc000010078}, {0x1379c27, 0x21}, {0xc000040b20, 0x2, 0x2})\n\tgithub.com/algorand/go-algorand/logging/log.go:231 +0x69\ngithub.com/algorand/go-algorand/node.MakeFull({_, _}, {_, _}, {0x1b, 0x1, 0x4, {0x0, 0x0}, 0xdf8475800, ...}, ...)\n\tgithub.com/algorand/go-algorand/node/node.go:218 +0xb7d\ngithub.com/algorand/go-algorand/daemon/algod.(*Server).Initialize(_, {0x1b, 0x1, 0x4, {0x0, 0x0}, 0xdf8475800, {0x0, 0x0}, 0xf, ...}, ...)\n\tgithub.com/algorand/go-algorand/daemon/algod/server.go:223 +0x1253\nmain.run()\n\tgithub.com/algorand/go-algorand/cmd/algod/main.go:299 +0x1da5\nmain.main()\n\tgithub.com/algorand/go-algorand/cmd/algod/main.go:61 +0x5c\n","time":"2023-03-27T07:46:05.418600Z"}
{"file":"node.go","function":"github.com/algorand/go-algorand/node.MakeFull","level":"error","line":218,"msg":"Cannot initialize ledger (/var/lib/algorand/mainnet-v1.0/ledger): reloadLedger.loadFromDisk tracker *ledger.catchpointTracker failed to loadFromDisk : initializeHashes was unable to retrieve trie root hash: page 35703900 is missing","time":"2023-03-27T07:46:05.418754Z"}
{"file":"main.go","function":"main.run","level":"error","line":302,"msg":"[Stack] goroutine 1 [running]:\nruntime/debug.Stack()\n\truntime/debug/stack.go:24 +0x65\ngithub.com/algorand/go-algorand/logging.logger.Error({0xc00009db90, 0xc000010078}, {0xc00020f850, 0x1, 0x1})\n\tgithub.com/algorand/go-algorand/logging/log.go:221 +0x53\nmain.run()\n\tgithub.com/algorand/go-algorand/cmd/algod/main.go:302 +0x2186\nmain.main()\n\tgithub.com/algorand/go-algorand/cmd/algod/main.go:61 +0x5c\n","time":"2023-03-27T07:46:05.418827Z"}
{"file":"main.go","function":"main.run","level":"error","line":302,"msg":"couldn't initialize the node: reloadLedger.loadFromDisk tracker *ledger.catchpointTracker failed to loadFromDisk : initializeHashes was unable to retrieve trie root hash: page 35703900 is missing","time":"2023-03-27T07:46:05.418863Z"}

```
### Your environment
algod -v
12885884928
3.15.0.stable [rel/stable] (commit #814bc0bd)
go-algorand is licensed with AGPLv3.0
source code available at https://github.com/algorand/go-algorand

goal node status doesn't work

OS: Ubuntu 18.04

### Steps to reproduce

1. Algorand node is working
2. Stop to sync because insufficient amount of space
3. Rescale disk
4. Restart the node

### Expected behaviour
Node continues to sync or command to recheck bugged trie node.

### Actual behaviour
Stopped sync of the node

**Comment by winder** [comment]
There is no recover command. The node should try to recover on its own. Do you see this message every time you start the node? It's possible that the local database became corrupt when you ran out of disk space, in which case you'll need to re-initialize the data directory.

**Comment by oggy95** [comment]
Yes, service automatically restart when get this error.
Okay, how can I do it with saving kmd database?

**Comment by oggy95** [comment]
Figured out, created new data directory and moved kmd folder from old data directory to new one.
