### ISSUE TITLE
Fix "$0.33 USD" TX fee

### ISSUE THREAD

**Issue by abebeos** [algorand/go-algorand#5240]
(move this to any repo you want, just not to an Algorand Foundation repository, as the folks there does not grasp the concept of issue-tracking)

## Status

A Algorand Foundation publishes a link to this document on twitter:

https://www.algorand.foundation/news/jump-into-web3-with-algorand

Document contains:

>  The minimum fee for a transaction on Algorand is 0.001 Algo (currently $0.33 USD at the time of this writing).

Dysfunctional as the foundation is: no reaction to comments to fix the document.

Same with the CTO (John Wood), who's busy to win the challenge "who can post the most tasteless tweet to celebrate the introduction of the highly technical (and thus serious) tool Algokit". => no reactions to comments.

They just fire stuff on twitter, do not look at feedback

## Expected

* Such heavy documentation bugs are fix within 1 hour after a comments mentions them.
* Decentralization => Don't let the foundation publish stuff without peer-review 

## Solution

Don't know.

Fix it, use your "red phones" or whatever.

(Venting Frustration Sidenote: This is a "coherency tragedy". So nice platform, so nice new tools, but you loose it all in the details that are handled by detail-incompetent folks @ Algorand Foundation )

**Comment by bbroder-algo** [comment]
thanks, you're right, I'll try to find the red phone.
