### ISSUE TITLE
New Transaction Updates algod API Proposal

### ISSUE THREAD

**Issue by Eric-Warehime** [algorand/go-algorand#5272]
## Transaction Group Updates
Transaction group updates (or transaction group deltas) are the set of updates made to the ledger as a result of a single transaction group. These include changes made to apps, accounts, key value stores, etc., and are meant to be comprehensive for all data stored in the ledger across past and future protocol versions.

Note that we do not intend to provide separate APIs for transactions since transaction groups are meant to be atomic. Singular transactions can be thought of as groups with size 1.

## Background
Historically, the state of the ledger could be reconstructed from a combination of the set of transactions in the block and the `ApplyData` (`AD`) structure. Although it is not the `AD`’s primary purpose, `AD` helpfully contains information about the previously running rewards program, and also has many of the changes produced from evaluating application call transactions. The `AD` is calculated as part of each block evaluation, and is included in the block, i.e. it is committed to the Ledger as a result of consensus. By default, nodes store the last 1000 blocks, but archival nodes will store every block.

With the release of Boxes you can no longer use the `SignedTxnWithAD` (Signed Transaction With Apply Data) structure to implement a block follower without fully evaluating application calls. Boxes can be as big as 32KB which meant that including full Boxes (or even the set of changed bytes in a Box) had the potential to quickly inflate the size of a full archival Ledger–one which was storing the full history of committed blocks with their `AD`. For this reason Boxes were left out of `AD`.

## API Interfaces
We want to enable users to track the state of accounts, assets, apps, and resources between any two transaction groups and not just at the block boundary. For example, users of a dApp which makes multiple transactions in quick succession could have their interactions end up in a single block or separate blocks. It should be just as easy for that dApp to determine and display the changes in that user’s state regardless of whether the interactions landed in the same block or separate ones.

To accomplish this, we propose the following additions to the set of existing algod APIs. These are specifically meant to address the gaps in ApplyData mentioned above, and are intended to be a permanent resource for users looking for complete state changes happening as a result of groups of transactions.

## Ledger State Deltas
The data structure used to talk about ledger changes is currently called a State Delta, however “updates” is a more accurate term since the state delta objects do not include old state, just the set of new states for affected objects. We do intend to use the same basic data structure for the transaction group APIs, but are considering whether the existing name is misleading.

Here is the set of information currently included in the Delta/Update output between two rounds. 

```go
// LedgerStateDelta describes the updates between two time periods.
// Can be used either inter-round or inter-transaction-group.
type LedgerStateDelta struct {
	// modified new accounts
	Accts AccountDeltas

	// modified kv pairs (nil == delete)
	KvMods map[string]KvValueDelta

	// new Txids for the txtail and TxnCounter, mapped to txn.LastValid
	Txids map[Txid]IncludedTransactions

	// new txleases for the txtail mapped to expiration
	Txleases map[Txlease]Round

	// new creatables creator lookup table
	Creatables map[CreatableIndex]ModifiedCreatable
}
```

### `v2/deltas/{round}?txn-groups=true&next-token=id`
This is the existing follower node endpoint for per-round changes that returns the delta for an entire round. It will be modified with a query parameter so that the returned data will be per-transaction-group deltas for the entire round.

Here is a sample output.

```go
type TransactionGroupUpdates struct {
    // The Tx Group Id
    Id string

    // The changes associated with the transaction group
    Updates LedgerStateDelta

    // Pagination token
    Next string
}
```

### `v2/deltas/txn/group/{group}`
This endpoint is a dedicated endpoint to retrieve a single set of updates corresponding to an individual transaction group. Given the group ID as input, it will return the LedgerStateDelta object for the specified transaction group.

A couple of things to note here:  
* Because of the potential size of the output we may need to add pagination to this endpoint to limit the size returned per page. This would be the first algod endpoint to have pagination.
* We are looking into the best identifier to use for these APIs. Not every transaction is associated with a group ID, and it is sometimes non-trivial to surface the ID of a transaction or inner transaction.

## Caching And Storage
A final consideration is the availability of update information. The size of the cache, in terms of number of rounds, will be controlled by the existing configuration parameter `MaxAccountLookback` which defaults to 4. That means data for rounds more than 4 rounds earlier than the node’s latest round will be dropped. 

As part of the work done for Conduit we’ve created the “Follower Node” which can be turned on via the configuration parameter `EnableFollowMode`. This will enable the `/v2/ledger/sync` endpoints that enforce data availability constraints. Additionally, you can increase the cache size to widen the length of time data is kept around. Be aware that this may cause much higher memory usage, especially for rounds with high transaction counts.

More information on the Follower Mode, sync round APIs, and how Conduit uses them to keep necessary data cached can be found in the Conduit repository docs--the [Indexer Migration Guide](https://github.com/algorand/conduit/blob/master/docs/tutorials/IndexerMigration.md) has some background on those changes.

**Comment by algoanne** [comment]
A note that came up from discord discussion: we plan to add a new config option which will enable both the state delta and the group-updates APIs separately from follow mode so that they can be used independently of whether or not you're running a follower node.

**Comment by pbennett** [comment]
What is the impact to setting MaxAccountLookback equal to the non-archival node retention size of 1,000 rounds?

**Comment by pao-beep** [comment]
> What is the impact to setting MaxAccountLookback equal to the non-archival node retention size of 1,000 rounds?

Memory usage increases

**Comment by Eric-Warehime** [comment]
> > What is the impact to setting MaxAccountLookback equal to the non-archival node retention size of 1,000 rounds?
> 
> Memory usage increases

The amount of memory usage increase for the increased cache size of 1000 rounds of txn ledger deltas will depend on the content of those blocks. I'll try to get some data around average memory usage of this.

**Comment by fergalwalsh** [comment]
> Note that we do not intend to provide separate APIs for transactions since transaction groups are meant to be atomic. Singular transactions can be thought of as groups with size 1.

Would this be outer groups only or would you provide deltas for inner groups separately?

Will transaction level deltas be accessible in Go from external code? e.g. in a Conduit based indexer or similar?

**Comment by Eric-Warehime** [comment]
> Would this be outer groups only or would you provide deltas for inner groups separately?

That's a good question and I'm not sure I've worked enough in the TEAL evaluator to know the answer off the top of my head. #5234 adds the deltas to the Tracer interface if you're interested in taking a look. I'll try to run some app calls w/ inner txn groups to see what granularity we're at currently and make sure it aligns with the data we want to get out in the end.

My expectation though is that inner groups would be wrapped the same delta since they all originated from the outer app call. 

Is tracking the effects of inner txn groups something that's important to you for a certain use case?

> Will transaction level deltas be accessible in Go from external code? e.g. in a Conduit based indexer or similar?

It will be written as an [`EvalTracer`](https://github.com/algorand/go-algorand/blob/9875686a8ae2da17ad308dd2b52dc11cfcc7c10b/data/transactions/logic/tracer.go#L96) which collects data alongside block evaluation. 

The output will be the same [`LedgerStateDelta`](https://github.com/algorand/go-algorand-sdk/blob/develop/types/statedelta.go#L293) objects currently exposed via the deltas endpoint for full rounds.

And yes, we're thinking it will be useful to enable Conduit to stream these objects so that you can filter for exactly the ones you care about and export them to more permanent storage.

I'm not sure I fully grasped what you meant w/ that question though so let me know if I've not answered it.

**Comment by fergalwalsh** [comment]
Thanks for the details. It's nice to see it being implemented as a Tracer. It looks like it should be extendable by others even if the APIs offerred don't contain exactly what we want. For example I could hook into `AfterTxn` instead of `AferTxnGroup` and process the `deltas` there if I really want txn level deltas for something weird.

> is tracking the effects of inner txn groups something that's important to you for a certain use case?

My use case for this is theoretical right now but based on our current architecture for Tinyman. Currently we process each swap (txn group) separately and store the pool & user state changes in a DB. We apply the same processing whether it is an inner or outer group so we save each swap as an atomic unit. Sometimes there are many swaps in a group or in inner txns. Right now this is all based on local states so we just get this from ApplyData.

But, I can imagine a future version of Tinyman or a similar protocol that uses boxes for state instead of local state. In this case we'll be relying on this deltas interface (or a custom Conduit based thing) to fetch the deltas for processing. If we only have granularity for the outer group we wouldn't be able to process things per swap, but only per outer group which gives a lot less insight and limits the user level analytics features we can support. I'd like to be able to use this deltas interface for this rather than a custom conduit based thing if at all possible.

I hope that made sense.

**Comment by jannotti** [comment]
I think we recognized we'd needed something like this at the inner level for debugging, but had been expecting that outside consumers wouldn't care so much (Our claim was "Hey, the top-level group has transactional semantics, why would you want to know what the pieces did? Changes only take place on the group as a whole").  I think your use case makes sense though, so whatever we do to expose this stuff for debugging should probably also make it into the REST API that gets the changes (perhaps optionally, it'll be a lot bigger).
