### ISSUE TITLE
Move the "specs" Repository to "algorand"

### ISSUE THREAD

**Issue by abebeos** [algorand/go-algorand#5283]
## Status

The specification is under the https://github.com/algorandfoundation organization

* https://github.com/algorand/go-algorand/blob/master/agreement/README.md#specification
  * https://github.com/algorandfoundation/specs

## Expected

The specification source is under the https://github.com/algorand organization, together with the essential core-projects like `go-algorand`.

## Rationale

* The specs affect the "deep core code" and should be where the "core code" resides.

## Solution

Move repository over.

**Comment by winder** [comment]
The foundation is ultimately responsible for approving or denying changes to the spec, which is what led to the current approach. You could also imagine an alternate implementation, in which case it is nice that the spec resides in a neutral location.
