### ISSUE TITLE
Consider removal of copyright year

### ISSUE THREAD

**Issue by abebeos** [algorand/go-algorand#5287]
## Status

Copyright year is used

## Expected

Not copyright year is used.

This simplifies looking a code/code-history, and keeps the file histories clean.

## Solution

* verify industry standard within other high-profile projects 
  * (I think I detected a tendency to remove the copyright year)

**Comment by winder** [comment]
Thanks for the suggestion. In addition to leaving out the copyright year, it would be nice to leave out the entire copyright notice. Some of the permissive licenses I've looked into let the top level `COPYING` or `LICENSE` file serve for the entire project.

The AGPL license is different. There are detailed instructions for how to use it and part of those instructions are to mark each source file with the notice snippet and the year it was released. If you're curious the details are here: https://www.gnu.org/licenses/gpl-howto.html

**Comment by abebeos** [comment]
(@winder , why did you close this?)

> Thanks for the suggestion. In addition to leaving out the copyright year, it would be nice to leave out the entire copyright notice. Some of the permissive licenses I've looked into let the top level COPYING or LICENSE file serve for the entire project.

What I prefer personally is a license-footer. The file header should describe the most important this: a summary what this file is about technically.

> There are detailed instructions for how to use it and part of those instructions are to mark each source file with the notice snippet and the year it was released.

What the FSF suggests, and what high-profile project do (after legal validation, I guess) are two different things. The FSF suggestion is far too intrusive for my personal taste.

In any way, I you agree that stripping the actual year would be of benefit, just leave the issue open, so an interested party can take a look at this.

**Comment by winder** [comment]
Again, thanks for the suggestion, but our policy is to follow the document I linked. Leaving the issue open suggests that we're open to changing that policy. I don't want to mislead anyone.

**Comment by abebeos** [comment]
>  In addition to leaving out the copyright year, it would be nice to leave out the entire copyright notice.

My understanding is that you are positive about this change.

> our policy is to follow the document I linked.

Well, I thought that Algorand is a decentralized project.

But it seems that you don't even allow a 2nd opinion or a pointer to a legal assessment of 3rd parties.

I extract that you (one person alone) decide to stick to an ancient 'policy', without even considering to see what other high-profile projects do (e.g. the caliber of IBM, MS, SAP, Meta, NASA, ...).

Very well, resting my case here.
