### ISSUE TITLE
Split `ConsensusAccountData` from `AccountData`

### ISSUE THREAD

**Issue by winder** [algorand/go-algorand#5316]
## Problem

The `bookkeeping.Genesis` object contains a slice of `bookkeeping.GenesisAllocation` objects which contain a `basics.AccountData` object.

The problem here is that there are many fields in `basics.AccountData` which do not belong in the genesis file.

## Solution

Create a new type called `bookkeeping.ConsensusAccountData` for the types which may appear in the genesis file. Use  that  type to replace `State` in `bookkeeping.GenesisAllocation` and embed it in `basics.AccountData`.

```
// GenesisAccountData contains a subset of account information that is present in the genesis file.
type GenesisAccountData struct {
	_struct struct{} `codec:",omitempty,omitemptyarray"`

	Status          Status                          `codec:"onl"`
	MicroAlgos      MicroAlgos                      `codec:"algo"`
	VoteID          crypto.OneTimeSignatureVerifier `codec:"vote"`
	StateProofID    merklesignature.Commitment      `codec:"stprf"`
	SelectionID     crypto.VRFVerifier              `codec:"sel"`
	VoteFirstValid  Round                           `codec:"voteFst"` // this one could  technically be omitted, because the online genesis accounts vote on round 0.
	VoteLastValid   Round                           `codec:"voteLst"`
	VoteKeyDilution uint64                          `codec:"voteKD"`
}
```

**Comment by abebeos** [comment]
May I ask here for a clarification (mostly out of curiosity):

Why the https://github.com/algorand/go-algorand/labels/High%20Priority ?

The Algorand chains are live, so the genesis should not matter much (I would expect a lower priority).

**Comment by winder** [comment]
Sure. I use it to help with project management, in this case I'll filter issues tagged with https://github.com/algorand/go-algorand/labels/Team%20Lamprey and https://github.com/algorand/go-algorand/labels/High%20Priority.

One of my goals is to have automated checks for cross repository types, this types that was flagged as inconsistent between go-algorand and go-algorand-sdk. You're right that the Mainnet genesis file isn't going to change, but for a private network it does change from time to time. We also continue to develop dev tooling that uses the genesis file, so it would be good for the type system to prevent assigning invalid fields. There are other types which change more often, such as `bookkeeping.BlockHeader`.

**Comment by abebeos** [comment]
Makes sense, ty!

**Comment by algochoi** [comment]
https://github.com/algorand/go-algorand/pull/5463 addresses this issue
