### ISSUE TITLE
[agreement] Feedback "spec-notes" to the specs

### ISSUE THREAD

**Issue by abebeos** [algorand/go-algorand#5318]
## Status

The current implementation of the Algorand agreement protocol is described within the source-code's [agreement/README.md](../blob/master/agreement/README.md)

This document is a starting point for a work-in (to algorand technology, via the code-base), and should be as simple as possible (and as much as possibly in-synch with both - the specification and the code).

The README mentions 2 **Spec Notes** where the implementation is different from the [specification](https://github.com/algorandfoundation/specs/releases/download/82d70ad/abft.pdf)

* [Spec Notes: Reordering](../blob/master/agreement/README.md#spec-notes-reordering)
* [Spec Notes: Additional Events](../blob/master/agreement/README.md#spec-notes-additional-events)

## Expected / Solution

Instead of mentioning the differences between the Algorand agreement specification and implementation, **the specification should be updated** to reflect the alternative/additional constructs identified during implementation.

Once done, the two sections starting with "Spec Notes" (`Spec Notes: Additional Events` and `Spec Notes: Reordering` would become redundant and could be removed, resulting in a more compact implementation README.

## Dependencies

Specification Authors

## Urgency

low

**Comment by bbroder-algo** [comment]
Sorry what?

**Comment by abebeos** [comment]
> Sorry what?

I'll try to rephrase

**Comment by abebeos** [comment]
@bbroder-algo , rewrote it.

**Comment by bbroder-algo** [comment]
oh I see!
