### ISSUE TITLE
[agreement] Introduction of voteTrackerRound/voteTrackerPeriod files

### ISSUE THREAD

**Issue by abebeos** [algorand/go-algorand#5319]
## Status

`voteTrackerRound` and `voteTrackerPeriod` are currently within those files

* [voteAuxiliary.go](https://github.com/algorand/go-algorand/blob/master/agreement/voteAuxiliary.go)
* [voteAuxiliaryContract.go](https://github.com/algorand/go-algorand/blob/master/agreement/voteAuxiliaryContract.go)
* [voteAuxiliary_test.go](https://github.com/algorand/go-algorand/blob/master/agreement/voteAuxiliary_test.go)

This is not intuitive, and not consistent with the other classes (`voteAggregator`, `voteTracker` etc.), see [the agreement folder](https://github.com/algorand/go-algorand/tree/master/agreement).

## Expected

`voteTrackerRound`/`voteTrackerPeriod` are implemented in their own files.

## Solution

Refactoring

Alternative: rename `voteAuxiliary*` to `voteTrackerAux*`

Alternative2: provide a rationale why `voteAuxiliary*` is used (thus it can bed added to the documentation)

## Urgency

low

**Comment by bbroder-algo** [comment]
I agree.
