### ISSUE TITLE
[agreement] Document how to regenerate `msgp_gen.go`

### ISSUE THREAD

**Issue by abebeos** [algorand/go-algorand#5332]
## Status

it is not clear how to regenerate `/agreement/msgp_gen.go`

https://github.com/algorand/go-algorand/blob/master/agreement/msgp_gen.go

## Expected

Documentation should mention how to regenerate `/agreement/msgp_gen.go` (and other `msgp_gen.go` files in other locations)

(clarification: `make msgp` is not enough, it needs to clarify how to recreate especially when source-code structure was changed)

**Comment by winder** [comment]
There is documentation here: https://github.com/algorand/go-algorand/blob/master/docs/messagepack.md
