### ISSUE TITLE
[COMPLAINT] Abusive Behaviour of "John Jannotti", Collective Bullying

### ISSUE THREAD

**Issue by abebeos** [algorand/go-algorand#5338]
(this is a formal complaint agains an Algorand Inc. github organization team member)

[John Jannotti](https://github.com/jannotti) (@jannotti) has 

* closed a harassment complaint without comment and without having the authority to do so
  * https://github.com/algorand/go-algorand/issues/5330#event-9075399847
* refused to transparently state his role in this project
  * https://github.com/algorand/go-algorand/issues/5330#issuecomment-1519137698

### Bullying

Please realize one thing: **bullying** needs to be countered in its roots. I personally perceive this as **bullying**, not metphorically.

This is part of my individuality, and this is a right of mine.

What others calls "abuse of power" or "lack of transparency", I call bluntly (because it is my right): bullying

### Owners

Due to the lack of transparency, I cannot know who to address. Selection the Algorand Inc. Organization Members:

* https://github.com/orgs/algorand/people
  * @jasonpaulos 
  * @winder 

Please ensure that this stops now, and that I can continue my contributions here in peace, without beeing permanently bullied.

**Comment by Priegle** [comment]
@abebeos 

- while individuals from our org take actions on issues and PRs, our whole org communicates and collaborates on the feedback.   
- like any open source project we welcome feedback, issues, and prs from the community.  in addition, like any open source project, we are responsible for the curation, shepherding, and prioritization of those contributions. 
- you have filed both issues and PRs, some of which are helpful and some of which have small/questionable marginal benefit and are not going to be prioritized and may be closed by us.  
- you have also filed inflammatory issues and communicated in a way towards our team that is unacceptable and will not be tolerated going forward.
- we hope you can be a valuable member of the ecosystem going forward.

**Comment by abebeos** [comment]
@Priegle , your comments are irrelevant in context of a complaint that obviously addresses the (always silent) leadership.

(I'll neither read them fully, nor take them into account)

**Comment by abebeos** [comment]
(note to readers: @Priegle seems to be https://www.linkedin.com/in/paul-riegle, not in charge of "harrasment within project resources" and "lack of due process within project resources")

> * you have also filed inflammatory issues and communicated in a way towards our team that is unacceptable and will not be tolerated going forward.

Here? Or on another media? Get your stuff together, before making unfounded accusations, because this is bullying, too.

Are you a common bully?

Reopen the issues instead of communication within closed issues.

If you have any professional pride at all:

Reopen the (by harassment, intransparently) closed issues.

**Comment by abebeos** [comment]
(and do yourself a favor, Mr. @Priegle, to separate the media precisely. This here is not twitter. What I write "out there" (like e.g. this: https://twitter.com/abebeos/status/1651056165323669504) to overcome "trauma of harassment and bullying" is not of any relevance within this repository)
