### ISSUE TITLE
[Feature Request] Extract core code from algorand to make a general consortium blockchain

### ISSUE THREAD

**Issue by diyism** [algorand/go-algorand#5344]
We need a universal DAO tool, a consortium blockchain with one-person-one-vote system to vote on community affairs (doctrine revision, public property allocation, increase or decrease of members, etc.), 

For example, a community with more than 100,000 people.
When a vote passes to add a new member, one coin will be issued to this new member.
When a vote passes to kick out a member, this coin will be destroyed.
Each member will always have one coin. 
No incentive or gas fee is needed.

I found that only Algorand  consensus protocol is perfectly suited for such need, but there is no client program that can be used directly.

**Comment by bbroder-algo** [comment]
Hello, this is a great idea and could be implemented with an AVM smart contract on the Algorand blockchain with no worries about forking or finality delays.  There isn't a place specifically in the go-algorand for this work to be performed by the team, however I encourage you to join the Algorand discord and discuss your ideas with the builders and staff members who can help you get started.
