### ISSUE TITLE
Fix "Logging to" line when logs are being written to stdout.

### ISSUE THREAD

**Issue by winder** [algorand/go-algorand#5358]
### Subject of the issue

When logging to stdout by launching algod with the `-o` option, we incorrectly print the following log line to stdout:
```
Logging to:  /algod/data/node.log
```

### Steps to reproduce

Run the docker image, you'll see one of the first lines of output is this log message.

### Expected behaviour

Either omit this line, or say `Logging to: stdout`

### Actual behaviour

Incorrectly prints `Logging to:  /algod/data/node.log`

**Comment by piyushkrmaurya** [comment]
Fixed by #5359
