### ISSUE TITLE
Resolve TestVotersReloadFromDiskPassRecoveryPeriod, TestLedgerErrorValidate tests

### ISSUE THREAD

**Issue by jsgranados** [algorand/go-algorand#5432]
## Overview

Tests that need fixing:
- TestVotersReloadFromDiskPassRecoveryPeriod
- TestLedgerErrorValidate

## Origin of Issues

- TestVotersReloadFromDiskPassRecoveryPeriod
  - Failure is caused by non-determinism when committing
  - The test that we need is a deterministic commit facility

**Comment by algorandskiy** [comment]
The test was temporarily disabled at https://github.com/algorand/go-algorand/pull/5436

**Comment by algorandskiy** [comment]
```
=== FAIL: data TestLedgerErrorValidate (1.34s)
    ledger_test.go:632: 
        	Error Trace:	/opt/cibuild/project/data/ledger_test.go:632
        	Error:      	Should be empty, but was data.EnsureBlock: could not write block 771 to the ledger: round 770 before dbRound 774
        	Test:       	TestLedgerErrorValidate
        	Messages:   	data.EnsureBlock: could not write block 771 to the ledger: round 770 before dbRound 774
```

**Comment by algorandskiy** [comment]
TestLedgerErrorValidate fixed in https://github.com/algorand/go-algorand/pull/5487

**Comment by algorandskiy** [comment]
fixed in https://github.com/algorand/go-algorand/pull/5494

**Comment by algorandskiy** [comment]
Reopened to monitor `TestVotersReloadFromDiskPassRecoveryPeriod`. Not sure if a controlled flush in one place is enough to stabilize the test - it does two more flushes...

**Comment by algorandskiy** [comment]
TestVotersReloadFromDiskPassRecoveryPeriod wip is here https://github.com/algorand/go-algorand/pull/5496

**Comment by jsgranados** [comment]
Closing. Both Flaky tests have been addressed and fixed.
