### ISSUE TITLE
go-algorand binary package v3.16.x not available on Debian 10

### ISSUE THREAD

**Issue by gitmewai** [algorand/go-algorand#5475]
### Subject of the issue

No latest package to Install `go-algorand` `v3.16.2` via apt on Debian 10.13

### Your environment

* Software version: `algorand/stable,now 3.15.1 amd64 [installed]`
* Operating System details. 
```
Linux algorand-1 4.19.0-24-cloud-amd64 #1 SMP Debian 4.19.282-1 (2023-04-29) x86_64 GNU/Linux
```

### Steps to reproduce

```
apt update
apt list --upgradable   ### and no any v3.16.x package available
```

### Expected behaviour

`apt update && apt list --upgradable` should return the latest package of algorand

### Actual behaviour

No newer packages available for install

**Comment by jsgranados** [comment]
Since 3.16.2 has not yet been fully released and is in pre-release status, apt will not provide it. Once fully released and switched to `latest`, you'll be able to pull down the 3.16.2

**Comment by gitmewai** [comment]
Yes we have upgraded our testnet nodes. The issue is now closed. Thanks
