### ISSUE TITLE
Error in retrieving current block's BlkSeed

### ISSUE THREAD

**Issue by Sun-C0ffee** [algorand/go-algorand#5522]
Hello Algorand team,

I have encountered an issue related to the bytecode "block BlkSeed". According to the specification, this bytecode should allow retrieving the BlkSeed field of the current block. However, when attempting to fetch the BlkSeed of the current block, the operation is reverted in the txpool.

I suspect this could be because the current block has not yet been generated, resulting in the function `cx.SigLedger.BlockHdrCached(round)` in the file `eval.go` returning an error. This seems to contradict the specification. Obtaining the BlkSeed field of the current block should be a legal operation, the transaction should not be reverted.

**Comment by jannotti** [comment]
The specification for `block` says:
```
Fail unless A falls between txn.LastValid-1002 and txn.FirstValid (exclusive)
```
So it is invalid to request anything with the `block` opcode in the current round which, of course, must be at least txn.FirstValid.
