### ISSUE TITLE
Dnsaddr demo

### ISSUE THREAD

**Issue by algoanne** [algorand/go-algorand#5546]
## Demo

Once we have a set of test DNS records and some working code which resolves the dnsaddr records, provide a short demo showcasing how the node resolves peer information during bootstrapping.

**Comment by Eric-Warehime** [comment]
![algons-dnsaddr](https://user-images.githubusercontent.com/10753834/259163185-58513b4a-f849-4387-8e77-52bdb3cc8cdd.gif)
