### ISSUE TITLE
p2p bootstrapping: Integrate dnsaddr/peerstore with genesis files

### ISSUE THREAD

**Issue by algoanne** [algorand/go-algorand#5549]
## Problem

Once we have a peerstore implementation that can persist data about connected peers in the network, and a dnsaddr implementation from which we can bootstrap a peerstore, we want to be able to start a node with a genesis file and have it properly connect to a network.

For example, in [mainnet's genesis file](https://github.com/algorand/go-algorand/blob/master/installer/genesis/mainnet/genesis.json#L942) it provides "mainnet" and that is eventually turned into an SRV request for the record at `mainnet.algorand.network` (that might not be the exact domain, but something like that). 

## Outcome

WIth the proper config options enabled, algod will start up given a genesis file with a network name associated with it and make successful TXT requests for dnsaddr records at predictable domains.

**Comment by onetechnical** [comment]
Fetching TXT records from _dnsaddr registered DNS bootstraps works.
