### ISSUE TITLE
Support Multiple Disk Drives on Algorand Node

### ISSUE THREAD

**Issue by jsgranados** [algorand/go-algorand#5550]
## Overview

Wouldn’t it be nice if Algod supported multiple disk drives so that node runners could efficiently manage their hardware costs?

Our current storage hardware suggestions are the following:
- For part-node runners - we recommend a 100GB NVMe SSD or equivalent
- For relay-node runners - we recommend a 3TB NVMe SSD or equivalent

These suggested specifications combine the storage size requirements of catchpoints with the storage speed requirements of the ledger.

We should separate these requirements and allow for the storage of the node to be configured in a manner that allows for the separation of “hot data” (ledger state, recent blocks) from “cold data” (catchpoints, old blocks, logs, etc) without trading off node performance. 

## Benefits

- Node-runners have more control over the hardware they choose when running a node
- Decrease in hardware costs for Algod

## Risk

Configuring data paths could be cumbersome. There should be proper direction and documentation on sensitive artifacts that the node uses and where those artifacts belong.

## Implementation Proposal

Currently `algod` stores all artifacts in its data dir set by `-d` command line switch or by setting the `ALGORAND_DATA` env var.
The list of all known artifacts by components is the following:
1. agreement
    - crashdb
    - agreement.cdv + archive
2. ledger
    - blockdb
    - trackerdb
    - catchpoints dir (ledger snapshots)
3. node
    - node.log + archive
4. stateproof
    - builderdb

Two of the artifacts (blockdb and catchpoint dir) require lots of space for archival nodes. Subsequently, trackerdb is the most frequently read/write database with account data needed for blocks evaluation and its IO performance is important in high TPS /full blocks scenarios for all nodes. The log file `node.log` could generate lots of IO if configured with level=info on non-part nodes who accept transactions via REST API.

To address all these use cases algod should have a way to configure where to put its artifacts if the default data dir is not a good fit (not enough space or not fast enough). A logical approach would be allowing components to have their own path(s) in a format `component_name[.artifact_name]=path`.

### Example
To put trackerdb into NVME mounted `/data` dir, catchpoints into `/opt/catchpoints`, and all agreement files into `/opt/agreement` would require the following pairs to be set:
- `ledger.trackerdb=/data`
- `ledger.catchpointdir=/opt/catchpoints`
- `agreement=/opt/agreement`

All remaining files would stay in the default `-d /ALGORAND_DATA` location.

To instruct algod to use such custom path, a new command like switch `--datadirs`, a new `ALGORAND_DATADIRS` env var, and a new `DataDirs` config parameter could be used in the following form:
```sh
# cmd opts
algod -d /home/algod --datadirs ledger.trackerdb=/data --datadirs ledger.catchpointdir=/opt/catchpoints --datadirs agreement=/opt/agreement

# env vars
export ALGORAND_DATA=/home/algod
export ALGORAND_DATADIRS="ledger.trackerdb=/data:ledger.catchpointdir=/opt/catchpoints:agreement=/opt/agreement"

# config
jq -r .DataDirs config.json
ledger.trackerdb=/data:ledger.catchpointdir=/opt/catchpoints:agreement=/opt/agreement
```
 Note `:` in the env vars form - this is an OS-specific path separator.

### Update 2023-07-18

1. The component-level granularity might be too much for some users so we also introducing `hot` and `cold` data dir concepts: `cold` is an alias for `ledger.catchpointdir` and `ledger.blockdb`, and `hot` hot is everything else.
```sh
export ALGORAND_DATA=/home/algod
export ALGORAND_DATA_HOT=/data
export ALGORAND_DATA_COLD=/opt/blocks
```
Similarly a new `DataDirHot` and `DataDirCold` config options and command line switches are defined.

2. There is a hierarchical relation between the default `ALGORAND_DATA`, `ALGORAND_DATA_HOT/COLD` and `ALGORAND_DATADIRS`. For example, if one defined `ALGORAND_DATADIRS=ledger.trackerdb=/data` and `ALGORAND_DATA_HOT=/data2` then `ledger.trackerdb` does into `/data`, and everything else "hot" into `/data2`.

3. Note, at the moment there is no "Freezer" or "hot blocks cache" implementation. This functionality could be added later and the latest blocks could be part of "hot" storage.

### Update 2023-07-25

1. A WIP Implementation has been written to the spec above, which resolves provided paths in the preferred order: CLI, OS.Env, Config. Data directories are resolved via hierarchy, so resources can have individual paths, or may fallback to the most appropriate one.

2. The overhead of understanding how the various values will resolve, especially in situations where there are multiple/many data directories on a single machine, seems prohibitive

3. Therefore, extended data paths should be resolved *only* via settings in the `config.json` file. the `-d` dataDir will continue to be defined in the existing way(s), and won't be changed.

**Comment by AlgoAxel** [comment]
To pose an alternative, why not locate these path configurations in the node.config? When running `algod -d [root]`, the necessary runtime information is presumed to be in that folder, right? For that reason, this could live in our existing config file. Or, if we want it to have some fundamentally different behavior, it could have its own config file, but in either case, I'm wondering if expanding the launch options makes sense, if this path is not something that is changing between executions usually.

**Comment by algorandskiy** [comment]
Thanks for feedback, added `DataDirs` config parameter with the same syntax as `ALGORAND_DATADIRS`

**Comment by urtho** [comment]
Ideally the blockdb could have two tiers - last 1000 blocks (hot) and the archive (cold) 
with host->cold archive thread being an async job. 

For this to make sense the node would have to be able to recover from loss of the "hot" data (and or state) by fast catchup - without having to resync the cold storage.

**Comment by scholtz** [comment]
I believe first thing should be to split relay node feature from the archival node feature. I believe this is already in progress as i saw john saying on the next block this.

So I will comment on the archival node feature.

It would be great if the algorand node could be run in multiple instances in kubernetes with one persitant volume attached.

The drives can be setup in RAID mode, but it would be great if "old" data can be accessed by multiple instances at one time for HA purpose of the API.

Also it would be great if multiple drives can be used. At the moment i am using /data folder, data/mainnet folder and data/mainnet/catchpoints as different drives as it increases the IOPS available in the cloud.

If there is option to split the core data into multiple drives, it can increase significantly performance of algod node.

Also the "archival" node should not hold all data on super fast NVME drives as it is more expensive. I believe having last N blocks in fast drive and some job moving the data to slower disks might be good.

Next it would be great to make the sync much more efficient. If you want to to sync whole chain, it is quite inefficient to check every transaction and download it the current way. It is much more efficient right now to copy all raw data and start the node. The difference on very fast servers is ~2 days of sync vs 2 weeks of sync.

**I propose following**: Let's have in the configuration the partition number .. eg 10. Lets create file chunks of blockchain of 10k blocks for example. So each chunk will have its number, and we can store to /data/mainnet/blocks/[block number modulo partition]/[block number modulo 10k].db

Each of this file would have the hash, so if you want to sync this 10k chunks it would be much more efficient. Also i assume after the sync it would check the consistency with the network. 

Also please enable downloading these chuncks in parallel. Downloading of chunk 11 should not affect downloading of chunk 12 and if my network allows it, it would be great if i can download 10 chunks at one time.

These folders /data/mainnet/blocks/1..10 can be mapped to differend drives.

Also it would be great to have the health check in place to be run by node runner. If the hash of the file is not the same as data written there it would raise some error and it should show it to the user. Drive may fail.. I have seen the cases when data written to ssd were written successfully but loaded data were not the same.

For the record my company is relay node runner and we are running nodes in different hostings with multiple configurations (bare metal, cloud..), in k8s https://github.com/scholtz/AlgorandNodes
