### ISSUE TITLE
Simulate: report programs initial state

### ISSUE THREAD

**Issue by jasonpaulos** [algorand/go-algorand#5567]
## Summary

With the addition of execution trace information, the simulate endpoint is quickly becoming capable of powering an in-depth debugging experience for transactions and smart contracts. In order to offer a more complete debugging experience, it's necessary to also include the initial state of on-chain resources prior to the simulation.

This is especially important because it conveys the approval programs of apps that will run in simulate. More generally, this will allow debuggers to have a complete view of the environment prior to any evaluation.

## Completion Criteria

Include the following information the simulation response:
* programs of all accessible apps

Above, the use of "accessible" means that the transaction group being simulated can read and/or write to that program. In most cases that means the app is explicitly referenced somewhere in the group.

## Open Questions
Do we want to report this information in every response, or only under certain circumstances (e.g. if execution trace is enabled)?

How will this interact with #5366, since that PR allows txn groups to access resources that are normally inaccessible?
* Perhaps we need some additional logic to run every time a new resources is referenced to add it to our set of initial state.

**Comment by jannotti** [comment]
I think you're exactly write about the unnamed resource PR.  You'll be noting all of the touched resources, so I think you'll have to include them in initial state.

In fact, one might wonder if you should include a resource that is _available_ but is never actually read or written.  I think I'd say no. Especially when one considers locals and holdings, there might be things that are available that would never be interesting to the debugger.
