### ISSUE TITLE
Publish official Docker Image

### ISSUE THREAD

**Issue by egieseke** [algorand/go-algorand#558]
**Is your feature request related to a problem? Please describe.**

Streamline setting up an Algod node with a prebuilt Docker Image.  

**Describe the solution you'd like**

Include building docker image as part of release process:  

For Testnet and Betanet, incorporate the use of S3 snapshot service to allow quickly starting and synching a new node.  

**Additional context**

a docker/release
a docker/release/start_algod_docker.sh
a docker/release/README.md
a docker/release/algod_docker_init.sh
a docker/release/Dockerfile_algod_release
a docker/release/build_algod_docker.sh
a docker/release/deploy_README.md

**Comment by btoll** [comment]
We are currently building a docker image and pushing it to docker hub as part of the legacy build pipeline, and soon there will be a `mule` task as part of the deploy process.
https://github.com/algorand/go-algorand/blob/master/docker/releases/build_releases.sh

**Comment by onetechnical** [comment]
Between the official Docker image and the sandbox, we think we're covered here.
