### ISSUE TITLE
Enable nodes to supply a PeerID

### ISSUE THREAD

**Issue by Eric-Warehime** [algorand/go-algorand#5581]

**Comment by kehiy** [comment]
what is the ideal solution to this issue?
@winder @Eric-Warehime

**Comment by winder** [comment]
@kehiy it corresponds to this PR https://github.com/algorand/go-algorand/pull/5591

**Comment by kehiy** [comment]
> it corresponds to this PR #5591
uh, ok
I thought I can work on this
thank you
