### ISSUE TITLE
Clean-up code and comments for AccountData.VotingStake() 

### ISSUE THREAD

**Issue by ian-algorand** [algorand/go-algorand#56]
@zeldovich commented this earlier: On closer examination, not an actual problem (because we call VotingStake only after doing a Lookup, which does WithUpdatedRewards), just confusing code and comments that we should fix after v1.

Do we still want to do something about this issue? Maybe this is less of a bug and more of a clean-up task?

**Comment by zeldovich** [comment]
I did this in PR #115.
