### ISSUE TITLE
Add a way to discover node capabilities.

### ISSUE THREAD

**Issue by winder** [algorand/go-algorand#5610]
## Problem

It is difficult to detect various node capabilities:
* EnableFollowMode
* EnableDeveloperAPI
* EnableTxnEvalTracer
* MaxAcctLookback
* EnableRuntimeMetrics
* etc

The list above are things that directly influence behavior of REST APIs. You can figure out most of these features by probing the APIs and checking behavior. Other configurations related to networking and performance may be completely invisible.

## Solution

Two options:
1) Add `/v2/config` to the admin API to return the config.json file.
This is simple to implement and provides complete information about the node. It is limited to clients with the Admin API because there may be sensitive information in the configuration.

2) Add specific capabilities to the status endpoint.
The advantage here is that non-admin consumers of the API can find the relevant capabilities, but would have less granular detail. There would probably be some very specific flags that we add on demaand. It would require updating REST APIs and Goal. It also would make the status endpoint response (potentially much) larger. For example if the response included a new entry like `"Capabilities":"Follower|DeveloperAPI|EvalTracer"`, maybe it uses a bitmask or a nested JSON structure.

**Comment by algoanne** [comment]
We'll start with option (1). 

We could do (2) later as well if it seems useful. Could be to `status/capabilities` instead of the regular status endpoint.
