### ISSUE TITLE
Change Peerstore from datastore-backed to in-memory

### ISSUE THREAD

**Issue by shiqizng** [algorand/go-algorand#5650]
## Problem
libp2p is proposing to simplify [peerstore](https://github.com/libp2p/go-libp2p/issues/2355) interface and remove [database-backed](https://github.com/libp2p/go-libp2p/issues/2329) peerstore. 

## Solution 
Remove pstoreds dependency in Peerstore by switching to use the in-memory version.

**Comment by jsgranados** [comment]
- Start switching over to a in-memory peerstore
- Discuss information we want to keep in memory with the peerstore
