### ISSUE TITLE
Run fast catchup using peerstore instead of phonebook

### ISSUE THREAD

**Issue by winder** [algorand/go-algorand#5666]
* Initialize peerstore from SRV records / phonebook
* Replace usages of phonebook with peerstore (or an interface that uses the peerstore)
    * i.e. peerselector, maybe others.
* might require workarounds for peerIDs with no public key.

**Comment by algorandskiy** [comment]
I guess this included implementing rate limiting functionality like existing `phonebookImpl` has (used to rate limit outgoing HTTP queries).

**Comment by algorandskiy** [comment]
Eventually interfaces are back to `addrOrPeerID string` - see https://github.com/algorand/go-algorand/pull/5939/files#diff-9bb3f16d547ba0e9a7e4c4127d7e780f97c3bde15832d541342e9ae77caee737R132

**Comment by algorandskiy** [comment]
Although fast catchup still uses phonebook abstraction, clients (peers) returned are http capable so fast catchup runs HTTP on top of p2p streams.
