### ISSUE TITLE
node sync fail

### ISSUE THREAD

**Issue by OnfireMrHuang** [algorand/go-algorand#571]
file":"bootstrap.go","function":"github.com/algorand/go-algorand/tools/network.ReadFromSRV","level":"warning","line":33,"msg":"ReadFromBootstrap: DNS LookupSRV failed when using system resolver(lookup _algobootstrap._tcp.mainnet.algorand.network on 10.59.218.194:53: server misbehaving) as well as via 8.8.8.8 due to lookup _algobootstrap._tcp.mainnet.algorand.network on 10.59.218.194:53: read udp 10.104.138.171:47188-\u003e8.8.8.8:53: i/o timeout","time":"2019-11-25T19:13:58.870121+08:00

What is going on with this problem?

**Comment by tsachiherman** [comment]
The node on your computer seems to have difficulties retrieving the list of relays.
Could you please see what happen when you type:
```nslookup -q=srv _algobootstrap._tcp.mainnet.algorand.network```
and
```nslookup -q=srv _algobootstrap._tcp.mainnet.algorand.network 8.8.8.8```

**Comment by OnfireMrHuang** [comment]
> The node on your computer seems to have difficulties retrieving the list of relays.
> Could you please see what happen when you type:
> `nslookup -q=srv _algobootstrap._tcp.mainnet.algorand.network`
> and
> `nslookup -q=srv _algobootstrap._tcp.mainnet.algorand.network 8.8.8.8`

I got  server can't find _algobootstrap._tcp.mainnet.algorand.network: SERVFAIL
