### ISSUE TITLE
The official docker  image FAST_CATCHUP setting wipes clean state on new image update.

### ISSUE THREAD

**Issue by pbennett** [algorand/go-algorand#5739]
### Subject of the issue

The FAST_CASTCHUP env variable when set to 1 causes the Algorand docker image to initiate a fast catchup on start.  This works fine, and well.

However, once caught up, a persistent file of some sort indicating fast catchup was run should be placed into the /algod/data directory.  On restart with a new algod image (ie: going from 3.17.0 to 3.18.0), FAST_CATCHUP should be a no-op because this file is present.

### Steps to reproduce

1. Start image (w/ persistently mounted data volume) with FAST_CATCHUP set.  Let it fully sync and run in caught-up state.
2. Stop instance, update image to newer version and the already caught up node will get reset, performing a full fast catchup again.

**Comment by Murasame233** [comment]
We need close this issue, cause this problem has already solved in #5756

**Comment by pbennett** [comment]
From reading #5756 it appears to address the issue.  Closing
