### ISSUE TITLE
logging.config "Enable" setting is ignored on startup of docker container

### ISSUE THREAD

**Issue by tom-gnade** [algorand/go-algorand#5744]
### Subject of the issue

If "Enable":"true" is set in logging.config override file, it is ignored when the docker container is started. Telemetry is always disabled, regardless of the config file values. Other values in the logging.config file do seem to persist to the runtime file.

### Steps to reproduce

1. Provide a compose.yaml file for docker compose:

  algorand:
    image: algomon/algorand/algod:latest
    ...
    volumes:
      - ./algorand/data:/algod/data
      - ./algorand/config.json:/etc/algorand/config.json
      - ./algorand/logging.config:/etc/algorand/logging.config
    environment:
      - NETWORK=mainnet
      - FAST_CATCHUP=1
      - START_KMD=1
      - TOKEN=a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1

2. Provide an override logging.config file in ./algorand:
 
{
  "Enable": true,
  "SendToLog": true,
  "URI": "http://testing-values",
  "Name": "algomon-algonode",
  "GUID": "",
  "FilePath": "",
  "UserName": "",
  "Password": "",
  "MinLogLevel": 4,
  "ReportHistoryLevel": 4
}

3. Observe the runtime values using $ docker exec -it algomon-algonode cat /algod/data/logging.config

### Expected behaviour

The runtime values should match the override - Enabled: true

### Actual behaviour

The runtime value for Enabled is instead "false". The telemetry state is always "disabled" on initialization of the container. It would be nice if the telemetry state were instead initialized by the "Enabled" setting in logging.config, or if an environment variable, like TELEMETRY_ENABLED=1 could force telemetry to be initialized on startup.

**Comment by Jbekker** [comment]
Current behavior is that is you set TELEMETRY_NAME, telemetry is automatically enabled.
https://github.com/algorand/go-algorand/blob/ea20873156c4d9a39aacd2e6feac6faf4f2892cb/docker/files/run/run.sh#L102

Maybe there should be a TELEMETRY_ENABLED for those who wish to not provide a name.

**Comment by winder** [comment]
Does it work if you mount the file to `/home/algorand/.logging`?

Sounds like we should handle `logging.config` in the same way `config.json` is handled.

**Comment by tom-gnade** [comment]
Mount to /home/algorand/.logging had the same result - it did pick up the
telemetry name from the config file, but telemetry was not enabled on
startup of the container. Will test TELEMETRY_NAME env var next.

**Comment by tom-gnade** [comment]
Using TELEMETRY_NAME did enable telemetry. The first description here
https://hub.docker.com/r/algorand/algod is " If set on a public network,
telemetry is reported with this name." - so I thought it was just an
override for the logging.config "Name" key. The second description under
"Explanation of parts:" mentions that it enables telemetry.

   - -e TELEMETRY_NAME=name *enables telemetry reporting* to Algorand for
   network health analysis. The value of this variable takes precedence over
   the name attribute set in /etc/algorand/logging.config.

A simple fix would be to change the firrst text from

TELEMETRY_NAME If set on a public network, telemetry is reported with this
name.
to

TELEMETRY_NAME Enables telemetry reporting, and uses this name. If set on a
public network, telemetry is reported with this name.
I would also suggest picking up the values
from /etc/algorand/logging.config" if they are provided, and handling this
config file the same way as logging.config.

**Comment by winder** [comment]
As Jbekker pointed out, it looks like we specifically disable telemetry if no telemetry name is set.

I suppose this behavior is to allow telemetry to be turned on and off by toggling that environment variable for a given docker container.

Perhaps this is still desirable behavior, since it would ensure you've set a telemetry name.

Alternatively, we could skip disabling telemetry if a `logging.config` file is provided.
