### ISSUE TITLE
IncomingConnectionsLimit limits short lived connections

### ISSUE THREAD

**Issue by urtho** [algorand/go-algorand#5766]
## Status

IncomingConnectionsLimit param is designed to limit longed lived connections (websocket) only.
With the current implementation is rejects requests for catchups and blocks on gossip port. 
Also makes it impossible to monitor relay health if IncomingConnectionsLimit is reached. 

## Expected

IncomingConnectionsLimit should limit concurrent websocket connections only.

**Comment by urtho** [comment]
IncomingConnectionsLimit  is set a as an Accept socket limit on gossip port - so TCP stack rejects any requests when gossip is already at IncomingConnectionsLimit  -  including catchup/block/health

There are separate checks later in the code path that make sure IncomingConnectionsLimit  is not exceeded.
My request is to set the limit on the gossip socket Accept to wn.config.IncomingConnectionsLimit+wn.config.RestConnectionsSoftLimi

The REST/Websocket limits are enforced in other places.
Here is the fix:

https://github.com/algorand/go-algorand/commit/4024245948922c0f692741eaacb3dc52d1f8df7c

**Comment by urtho** [comment]
I do not care about the REST API /v2/ endpoints. Only solving a relay issue here.

IncomingConnectionsLimit is supposed to limit long lived connections and this websocket connections limit (up to IncomingConnectionsLimit) is enforced later in the code path.

The same socket serves short lived connections - if not for catchups and blocks then for stuff like the AF relay monitoring.

If I try to protect my relay against an overload by long lived gossip/websocket connections I also make it unavailable to the AF monitoring and basic catchup/block functions.

This might not be critical now but once relays go P2P users might want to set the limit low but still allow others to bootstrap off off them while the gossip limiter is in place. 

So either change the description for IncomingConnectionsLimit to ANY connections on gossip port or add extra room on the socket Accept to allow for vital short lived functions and make IncomingConnectionsLimit indeed limit long lived connections only.

**Comment by gmalouf** [comment]
Closing this in favor of the solution merged with #6009
