### ISSUE TITLE
Events emitted to locally-hosted elasticsearch node are rejected as "bad requests".

### ISSUE THREAD

**Issue by tom-gnade** [algorand/go-algorand#5778]
### Subject of the issue

Events emitted to a locally-hosted elasticsearch node are rejected as "bad requests". I have not been successful in capturing the body of a request yet to inspect it, but it is clear that the initial connection to the elasticsearch node succeeds, because the index has been created - but no events to publish data to the index succeed, they all fail.

### Your environment

Software Version: 3.18.0
Operating System: Official Algorand Docker image/container

config.json:
{
  "Archival": false,
  "BaseLoggerDebugLevel": 3,
  "EnableMetricReporting": true,
  "NodeExporterPath": "/node/bin/node_exporter",
  "EnableRuntimeMetrics": true,
  "EnableLedgerService": true,
  "EnableBlockService": true
}

logging.config:
{
  "Enable":true,
  "SendToLog":false,
  "URI":"http://localhost:9200",
  "Name":"",
  "GUID":"",
  "FilePath":"",
  "UserName":"elastic",
  "Password":"elastic",
  "MinLogLevel":3,
  "ReportHistoryLevel":3
}

compose.yaml:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: algomon-elasticsearch
    hostname: algomon-elasticsearch
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data # note: $ chown -R 1000:1000 ./data
      - ./elasticsearch/elasticsearch.yaml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=elastic
      - xpack.security.enabled="false"

  algorand:
    image: algomon/algorand/algod:latest
    container_name: algomon-algonode
    hostname: algomon-algonode
    build: ./algorand
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./algorand/data:/algod/data
      - ./algorand/config.json:/etc/algorand/config.json
      - ./algorand/logging.config:/etc/algorand/logging.config
    environment:
      - NETWORK=mainnet
      - FAST_CATCHUP=1
      - START_KMD=1
      - TELEMETRY_NAME=algomon-algonode
      - TOKEN=a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1

### Steps to reproduce

1. Run elasticsearch node and algorand node containers using Docker Compose
2. Observe the error logs on the algorand node

### Expected behaviour

The initial request to create the index should succeed, as well as subsequent calls to publish events to the elasticsearch node.

### Actual behaviour

The initial request to create the index succeeds, but subsequent attempts to emit events to the endpoint are rejected as bad requests.

**Comment by urtho** [comment]
Current telemetry implementation requires ElasticSearch 6.X :(

**Comment by tom-gnade** [comment]
Ok that was an easy fix - I updated compose.yaml to:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.23
    # image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2

I can now see the index and the event data:

$ curl -s localhost:9200/_cat/indices
$ curl -s localhost:9200/stable-mainnet-v1.0 | jq
$ curl -s localhost:9200/stable-mainnet-v1.0/_search | jq

One issue I now have is that Grafana no longer supports Elasticsearch versions <7.0, and I'm unable to query the index through their UI. Is there any plan to support a more recent version of Elasticsearch on the roadmap?

**Comment by urtho** [comment]
I solved it by switching away from the default telemetry to this pipeline:
alogd logs -> fluentbit -> opensearch/elasticsearch

**Comment by tom-gnade** [comment]
The solution I'm working on can't use direct access to the log files, but that is a good proposed solution, thank you. I was able to solve it by using the Opensearch data source plugin for Grafana, which is compatible with older versions of Elasticsearch. I do think it would be a good idea to update the supported version of Elasticsearch to something more recent, though.
