### ISSUE TITLE
Leverage DHT for Peer-based Discovery/Advertisements

### ISSUE THREAD

**Issue by gmalouf** [algorand/go-algorand#5828]
We would like algod nodes to be able to discover peers of various types/capabilities via a DHT implementation (as opposed to existing usage of SRV Record lookups). The two would co-exist after this ticket (with configuration-based priority).

The discovery capabilities we need specifically:

- block service providers
- catchpoint service providers
- gossip service providers

Similarly, nodes need the ability to advertise their services on the DHT:

- block service
- catchpoint service
- gossip service

**Comment by algorandskiy** [comment]
Fixed in
https://github.com/algorand/go-algorand/pull/5827
https://github.com/algorand/go-algorand/pull/5833
https://github.com/algorand/go-algorand/pull/5867
