### ISSUE TITLE
ensure deb/rpm upgrades work

### ISSUE THREAD

**Issue by tsachiherman** [algorand/go-algorand#583]
## Upgradable rpm installers
Our last release had some bumps in the generation of the rpm installers.
We need to figure out what need to be changed to support upgradable installers and integrate that into our scripts.

**Comment by algobolson** [comment]
unless someone has specific issues to report I'm going to guess this was actually about the ubuntu/debian installers which had a hiccup around GPG key changes.

**Comment by algobolson** [comment]
**Plan** install previous version rpm and previous version deb, watch them upgrade to current version.

**Comment by algobolson** [comment]
verified upgrading 1.0.30 to 2.0.1 for both rpm and deb
deb had the known key-change issue which can be fixed by re-running the key part of the install
```
curl -O https://releases.algorand.com/key.pub
sudo apt-key add key.pub
```
