### ISSUE TITLE
Official docker images are incompatible with windows server workers on github actions

### ISSUE THREAD

**Issue by aorumbayev** [algorand/go-algorand#5845]
### Subject of the issue

Getting:
```
docker: no matching manifest for windows/amd64 10.0.20348 in the manifest list entries
```

Error in github actions when trying to pull official algod, conduit, indexer images in github actions running on windows server. 
More details in https://github.com/algorandfoundation/algokit-utils-py/actions/runs/7006734023/job/19059268379

### Your environment

Default windows-latest worker on github actions

### Steps to reproduce

1. pipx install algokit 
2. algokit localnet start (which is equivalent to running docker compose up)
3. observe the error. 

### Expected behaviour

Windows server is supported, allowing devs to use official images in docker environments on github actions windows workers.

### Actual behaviour

Pulling images fails.

**Comment by aorumbayev** [comment]
[compose.zip](https://github.com/algorand/go-algorand/files/13476880/compose.zip)
alternatively this compose setup can be used for easier steps to reproduce, simply running docker compose run against it on `windows-latest` worker in github action will produce the same error. Alternatively running docker pull on latest algod image can demonstrate the error as well

**Comment by excalq** [comment]
Algod and its Docker image are built with `linux/amd64` and `linux/arm64) architecture targets. As noted in [Algokit's documentation](https://github.com/algorandfoundation/algokit-cli/blob/main/docs/features/localnet.md#prerequisites), running AlgoKit in a Windows environment requires Windows Subsystem for Linux 2 (WSL2) or the Hyper-V backend for Docker. This ensures that Docker in Windows is running with a Linux kernel. 

As for GitHub actions, there seem to be [roundabout ways](https://github.com/marketplace/actions/setup-wsl) to run WSL-1, but [this GitHub issue](https://github.com/actions/runner-images/issues/5920)) suggests that WSL-1 is not supported in GitHub actions.

**Comment by gmalouf** [comment]
Closing this, it reads as a better fit for discussion on the Algokit repo.
