### ISSUE TITLE
Compiler-free rpm/deb packaging

### ISSUE THREAD

**Issue by tsachiherman** [algorand/go-algorand#585]
### Compiler-free rpm/deb packaging
Once we have the rpm/deb packaging automated, we want to have them re-package a pre-existing ( i.e. precompiled binaries ).

The goal of this task is to take a tar.gz file, and "convert" it into rpm/deb packaging.

**Comment by algobolson** [comment]
scripts/build_rpm.sh and scripts/build_deb.sh accept an environment variable NO_BUILD so that they skip the build step and use what has already been built in a release-build checkout.

**Comment by onetechnical** [comment]
This is already done.
