### ISSUE TITLE
Test deployment packages using docker

### ISSUE THREAD

**Issue by tsachiherman** [algorand/go-algorand#587]
### Test deployment packages using docker

Add a post-package generation step to the release process that would generate dynamic docker containers for various platforms ( i.e. Ubuntu 18, Ubuntu 16, Centos 28, etc. ).
Then it would use the various deployment methods that we have to deploy a node on these containers.

**Comment by algobolson** [comment]
This exists in scripts/build_release.sh (and subordinate scripts) for ubuntu18 and centos7
