### ISSUE TITLE
Make a consistent test env docker image

### ISSUE THREAD

**Issue by tsachiherman** [algorand/go-algorand#588]
## Static deployment test for release packages
Extending the previously generated docker testing features, we want to separate the docker image creation and docker image testing.
The docker image should be created only once and re-used. That would ensure that we always use the *same* docker image when testing a release.

**Comment by ian-algorand** [comment]
Specifically, we want to test algod -v (or maybe some other simple smoke tests)

**Comment by onetechnical** [comment]
We think this is covered / deprecated.
