### ISSUE TITLE
The `DisableAPIAuth` config option causes requests to error if any auth token is present

### ISSUE THREAD

**Issue by jasonpaulos** [algorand/go-algorand#5883]
The `DisableAPIAuth` config option is supposed to make development easier by not requiring requests to use an auth token. However, if a request does include an auth token, it's rejected with a 401 error.

Seems like we should be ignoring this header entirely if `DisableAPIAuth` is true.

**Comment by joe-p** [comment]
This seems like a duplicate of #5747

**Comment by jasonpaulos** [comment]
Good point, closing
