### ISSUE TITLE
Remove dead upgrade code

### ISSUE THREAD

**Issue by ian-algorand** [algorand/go-algorand#59]
Summary: There's a lot of upgrade code in agreement that can be removed since we are resetting mainnet. The reason why this needs to be relatively highly prioritized is because this simplifies consensus code and improves correctness.

**Comment by algoradam** [comment]
PR #87 removes some (but not all) of the dead upgrade code

**Comment by algoradam** [comment]
PR #101 removed upgrades through v7, the rest has been split into issues #109 and #110 because this turns out to be a larger task than expected
