### ISSUE TITLE
Optimize proposal evaluation timeline

### ISSUE THREAD

**Issue by tsachiherman** [algorand/go-algorand#591]
### Optimize proposal evaluation timeline
Currently, we wait for the soft voting to complete before start evaluating the proposal.
That's all fine, but would be even better if we could already "conclude" magically that "this proposal is good to go".

This could be done if we start evaluating the proposal as soon as they arrive, one proposal at a time. If we receive a proposal with a lower hash, we cancel the previous proposal verification and start with the new one.

**Comment by ian-algorand** [comment]
Old issue, closing and reopening if it comes up in the future
