### ISSUE TITLE
Catchpoint is very slow

### ISSUE THREAD

**Issue by alecalve** [algorand/go-algorand#5916]
### Subject of the issue

We're upgrading an existing archival node to be a follower so that it can be used with Conduit.

Conduit initiated a catchpoint on the node, and it's been in the same state for multiple days now. Here's the last catchpoint related message (4+ days ago):

```
resuming catchpoint catchup from state 4
```

Since then the node is constantly using a CPU core but no progress seems visible. Here's the output of `/v2/status`:

```json
{
  "catchpoint": "35090000#ZA2AJ5T4LCC3FYOHFHWAHYGUYQG5T56J655ZNXMMMVXA6422CSQA",
  "catchpoint-acquired-blocks": 0,
  "catchpoint-processed-accounts": 0,
  "catchpoint-processed-kvs": 0,
  "catchpoint-total-accounts": 0,
  "catchpoint-total-blocks": 0,
  "catchpoint-total-kvs": 0,
  "catchpoint-verified-accounts": 0,
  "catchpoint-verified-kvs": 0,
  "catchup-time": 431808494216297,
  "last-catchpoint": "",
  "last-round": 35258080,
  "last-version": "https://github.com/algorandfoundation/specs/tree/abd3d4823c6f77349fc04c3af7b1e99fe4df699f",
  "next-version": "https://github.com/algorandfoundation/specs/tree/925a46433742afb0b51bb939354bd907fa88bf95",
  "next-version-round": 35275315,
  "next-version-supported": true,
  "stopped-at-unsupported-round": false,
  "time-since-last-round": 431808493818968
}
```

Is that expected?

### Your environment

Algorand 3.21.0

**Comment by urtho** [comment]
Hi. Stop your follower, point it to a fresh/empty data dir , start it and request a catchup or let the conduit request the catchup.
Starting with an empty data dir solves 99% of stuck catchups.

**Comment by alecalve** [comment]
Thanks, I'll try that and keep you updated

**Comment by alecalve** [comment]
The Conduit instance is now working, thanks!
