### ISSUE TITLE
Setting the default wallet with goal

### ISSUE THREAD

**Issue by algonautshant** [algorand/go-algorand#595]
~/node/testnetdata
$ goal -d PublisherNode/  wallet  list
##################################################
Wallet:	user1wallet
ID:	def8a1b9f2bb6865172198112ca57fb2
##################################################
~/node/testnetdata
 $ goal -d PublisherNode/  wallet  -f user1wallet
Set wallet 'user1wallet' to be the default wallet
~/node/testnetdata
 $ goal -d PublisherNode/  wallet  list
##################################################
Wallet:	user1wallet
ID:	def8a1b9f2bb6865172198112ca57fb2
##################################################
~/node/testnetdata
 $ goal -d PublisherNode/  account list 
Wallet with ID '8ac8f31b48aa137176e23ef8ad7cf04a' not found. Was the default wallet deleted?

issue resolved after hiding: 
goal.cache/walletHandles.json
testnet-v1.0/accountList.json

**Comment by bbroder-algo** [comment]
This seems to work:
  118  goal -d . wallet new
  119  goal -d . wallet new bob
  120  goal -d . wallet list
  123  goal wallet -f bob
  126  goal account new
  127  goal account list
