### ISSUE TITLE
goal information message should have -- instead of - for the flags

### ISSUE THREAD

**Issue by algonautshant** [algorand/go-algorand#597]
$ goal -d /Users/shantkarakashian/node/testnetdata/Node/ asset   info 
Either [-assetid] or [-asset and -creator]  must be specified

~/node/testnetdata/Node
 $ goal -d /Users/shantkarakashian/node/testnetdata/Node/ asset   info  -assetid 11825
Error: unknown shorthand flag: 'a' in -assetid

**Comment by EvanJRichard** [comment]
Comment/note for later sprint planning: this would cause breaking changes in many scripts
