### ISSUE TITLE
goal asset  destroy parameters message error 

### ISSUE THREAD

**Issue by algonautshant** [algorand/go-algorand#598]
goal asset  destroy 
Either [-assetid] or [-asset and -creator]  must be specified

~(--) instead of (-) -~ use of -- vs - discussed in other ticket
asset happens to be the Unit name.
1) unit name is a strange choice
2) should say unit instead of "asset"

**Comment by EvanJRichard** [comment]
Editing out `--` part of ticket; included in another ticket
