### ISSUE TITLE
goal asset info required flags message is incomplete:

### ISSUE THREAD

**Issue by algonautshant** [algorand/go-algorand#599]
The required flags should be listed from the begenning. 

$ goal asset info
Error: required flag(s) "creator" not set

$ goal asset info --creator CBIHC
One of -assetid and -asset must be specified

**Comment by winder** [comment]
Unfortunately cobra doesn't provide a good way to deal with conditionally required flags, so this is pretty much the best we have.

In this example "creator" is an actually required flag (thought that seems to have changed in the last 9 months), and we manually verify that one of the other flags is also set.
