### ISSUE TITLE
goal asset send command required flags message is incomplete: missing asset or assetid

### ISSUE THREAD

**Issue by algonautshant** [algorand/go-algorand#600]
The required flags are: amount, creator, to, and asset or assetid, but the error message does not mention asset or assetid.

Here is an example: 

$ goal asset send
Error: required flag(s) "amount", "creator", "to" not set
Usage:
  goal asset send [flags]

$ goal asset send  -a 0 --creator ES3JZQSHLIPFPSLZNPHKIICQFJAJ45OLCNMUPHEXXXXMQWKK4FO7QD4ZIY --to ES3JZQSHLIPFPSLZNPHKIICQFJAJ45OLCNMUPHEXXXXMQWKK4FO7QD4ZIY

One of -assetid and -asset must be specified

**Comment by ian-algorand** [comment]
@winder is saying there isn't really a good way to do this. Will, can you add some more color here please?

**Comment by winder** [comment]
This is a limitation of the argument parsing library we use.

Cobra doesn't support conditionally required parameters. So in this case there are 3 unconditionally required parameters reported, and then some conditionally required parameters that we manually verify. In the future we should try to avoid conditional parameters.
