### ISSUE TITLE
3.24.0 - make - version of quic-go not supporting Go 1.21

### ISSUE THREAD

**Issue by kheil117** [algorand/go-algorand#6008]
### Subject of the issue

Issue generating executables via Make due to incompatibility with quic-go version and Go 1.21.

### Steps to reproduce

1. make
2. 

### Expected behaviour

Generate executable files

### Actual behaviour
Error:

..\go\pkg\mod\github.com\quic-go\quic-go@v0.36.3\internal\qtls\go121.go:5:13: cannot use "The version of quic-go you're using can't be built on Go 1.21 yet. For more details, please see https://github.com/quic-go/quic-go/wiki/quic-go-and-Go-versions." (untyped string constant "The version of quic-go you're using can't be built on Go 1.21 yet. F...) as int value in variable declaration

**Comment by gmalouf** [comment]
@kheil117 is this issue with the current release? We are on quic-go 0.42 as of our upgrade to Go 1.21 support, and would not have been able to build the binaries unless these worked. The link you posted in the description says at the top it is applicable for "versions of quic-go 0.37 and below" as well.
