### ISSUE TITLE
Algod docker image configuration support for ColdDataDir

### ISSUE THREAD

**Issue by gokhanbarisaker** [algorand/go-algorand#6011]
## Problem

ColdDataDir is not configurable on the [algod docker image](https://hub.docker.com/r/algorand/algod)

This forces docker images to utilise nvme ssd

## Solution

It would have been nice to support configuration of ColdDataDir.

As a bonus, it would have been nicer to support other [configuration settings](https://developer.algorand.org/docs/run-a-node/reference/config/#algod-configuration-settings) for algod

## Dependencies

n/a

## Urgency

Low

**Comment by gmalouf** [comment]
Thank you for reaching out. `/etc/algorand/config.json` allows you to specify overrides of any of the default config parameters (note you have to set the version property for the right defaults to diff against). This of course includes `ColdDataDir`.
