### ISSUE TITLE
P2P HTTP Implementation: open problems

### ISSUE THREAD

**Issue by algorandskiy** [algorand/go-algorand#6042]
There are a few open questions about p2p http risen in the p2p feature branch [merge PR](https://github.com/algorand/go-algorand/pull/5939):

1. If the ledgerService / catchpoint downloader grabs GetHTTPRequestConnection and grabs the underlying stream, does this mean it will break any other HTTP requests that are already using that stream (or might use it concurrently)? Just trying to understand what happens when you give away the underlying streams like this

_Originally posted by @cce in https://github.com/algorand/go-algorand/pull/5939#discussion_r1657461379_

2. Maybe in a follow up PR we should get rid of StreamChainingHost and split by using a dedicated protocol for downloading ledger files or something? Just wondering whether it is possible with getStream() to end up with two HTTP requests trying to write/read from the same underlying stream at the same time?

_Originally posted by @cce in https://github.com/algorand/go-algorand/pull/5939#discussion_r1657466374_
            
3. An idea for the future, maybe RegisterHTTPHandler sets up a separate protocol for each handler, rather than all sharing algorandP2pHTTPProtocol with our own gorrila mux router on top? Then I think it would be better able to support support concurrent HTTP requests for different handlers over different streams? Or maybe the libp2p http stuff already provides for multiple concurrent HTTP reqs? I was imagining they all share a single stream, but maybe that's not true.

_Originally posted by @cce in https://github.com/algorand/go-algorand/pull/5939#discussion_r1657612730_

**Comment by algorandskiy** [comment]
> AFAICT most of the code added to the RequestTracker from https://github.com/algorand/go-algorand/pull/1390 (and mirrored in feature/p2p for p2p http conns) can be replaced with two lines by the Go 1.20 ResponseController feature https://tip.golang.org/doc/go1.20#http_responsecontroller like in their example — vastly easier than managing a conn tracking middleware system
> 
> > The ResponseController type provides a clearer, more discoverable way to add per-handler controls. Two such controls also added in Go 1.20 are SetReadDeadline and SetWriteDeadline, which allow setting per-request read and write deadlines. For example:
> > func RequestHandler(w ResponseWriter, r *Request) {
> >   rc := http.NewResponseController(w)
> >   rc.SetWriteDeadline(time.Time{}) // disable Server.WriteTimeout when sending a large response
> >   io.Copy(w, bigData)
> > }

**Comment by algorandskiy** [comment]
Item (2) was fixed in https://github.com/algorand/go-algorand/pull/6044

**Comment by algorandskiy** [comment]
I guess item (3) can be taken as an enhancement for p2p milestone 2.

**Comment by gmalouf** [comment]
Captured for milestone 2
