### ISSUE TITLE
Get Accounts for AssetID

### ISSUE THREAD

**Issue by rfustino** [algorand/go-algorand#614]
It would be very useful to have a function in the REST API/SDKs to find all of the accounts that have a particular assetid.

For example, I could create an Algorand Blockchain game with a leader board. So, I need for find out which players (accounts) have my assetID for the game. I can then do a sort on the top 10 asset token holders to build my leader board.

It would be also useful for inventory purposes. Which accounts have how many assets?

**Comment by algorotem** [comment]
Hi there, 
this can be done with indexer `v2/accounts?asset-id={assetID}`
