### ISSUE TITLE
Unable to Close Account with ASA Balance in a Single Transaction

### ISSUE THREAD

**Issue by ryanRfox** [algorand/go-algorand#618]
### Use Case

As an Algorand account holder, I desire the ability to close all balances to the specified account in a single transaction. 

### Environment

* Software version: `2.0.8.beta [rel/beta] (commit #5d2626dc)`
* Node status if applicable: `snyced to betanet-v1.0`
* Operating System: Ubuntu 18.04 

#### Create ASA

    goal asset create --creator $CREATOR_ACCOUNT --total 10000 --name $ASSET_NAME -d $DATA

#### Create and fund a new account

    goal account new -d $DATA
    goal clerk send -a 200000 -f $CREATOR_ACCOUNT -t $NEW_ACCOUNT -d $DATA

#### Create an opt-in transaction for your ASA

    goal asset send -a 0 --assetid $ASA_ASSET_ID -f $NEW_ACCOUNT -t $NEW_ACCOUNT -d $DATA

#### Fund new account with your ASA

    goal asset send -a 10 --assetid $ASA_ASSET_ID -f $CREATOR_ACCOUNT -t $NEW_ACCOUNT -d $DATA

#### Close the new account to the Creator account

    goal clerk send -a 0 --close-to $CREATOR_ACCOUNT -f $NEW_ACCOUNT -t $CREATOR_ACCOUNT -d $DATA

### Expected Behaviour

$CREATOR_ACCOUNT should receive the remaining MicroAlgo and all ASA balances from $NEW_ACCOUNT as described in [code](https://github.com/algorand/go-algorand/blob/494e74553d90ab8ade9bc3a976a919b7d17fc654/data/transactions/payment.go#L35).

### Actual behaviour

    Couldn't broadcast tx with algod: HTTP 400 Bad Request: TransactionPool.Remember: transaction <TXID>: cannot close: 1 outstanding assets

**Comment by algobolson** [comment]
I suspect that this will work if first there's an asset close-to transaction
`goal asset send --close-to $CREATOR_ACCOUNT -a 0 -t $CREATOR_ACCOUNT -f $NEW_ACCOUNT --assetid $ASA_ASSET_ID`

**Comment by ryanRfox** [comment]
I noticed an error in my OP within the "Close the new account to the Creator account" section in which the `--from` was incorrectly $NEW_ACCOUNT. I've updated the OP to reflect $CREATOR_ACCOUNT properly.

**Comment by ryanRfox** [comment]
@algobolson Your solution gets me partially there. Yes, that allows me to close a balance of a single ASA to another account. But, it is my desire (and understanding from the code) that `goal clerk send -a 0 -c ...` will close out **all** balances in a single transaction. Using `goal asset send --close-to ...` would require a transaction per ASA.

**Comment by ryanRfox** [comment]
I tightened up the scope of this _bug_ to focus more on my desire for a single transaction to close an account holding any balances. Perhaps it could be reclassified as a feature request, as I'm not clear on the design for closing out balances from an account. Thanks in advance for clarifying.

**Comment by algobolson** [comment]
I'd call this a feature request to make the process nicer (closing the account is possible, but requires a little extra work). It could either be handled at the `goal` layer by perhaps taking a `--auto-cleanup` option that would detect asset balances and issue transactions close them all out to the same destination address. I think this is the easier path. Or it could be handled at the network layer with nodes allowing for closing an account with 0-balance assets instead of requiring them to be closed-out to remove the 0-balance record. There could be reasons why it might better to keep things simple and be a bad idea to add that complication to the accounting logic. This would require a protocol specification change and there's extra overhead ind coordinating those and they happen less often.

**Comment by ryanRfox** [comment]
I too follow KISS principles. It is likely this would require a protocol change, but it should be quite limited in scope.

Building on the OP example, the $CREATOR_ACCOUNT has, by default, performed an _opt-in_ transaction. Whereas, a newly introduced $THIRD_ACCOUNT has not. 

Therefore, existing validation logic could be extended to iterate the set of non-zero balance assets held by `--from` and ensure `--close-to` has performed an _opt-in_ for each. If any asset validation check fails, the transaction must fail because `--close-to` is not authorized to receive all non-zero balance assets.  If `--from` holds a zero balance asset, the validation logic should skip the `--close-to` check, as it will not receive any as a result.



should hold that $NEW_ACCOUNT is unable to `--close-to` $THIRD_ACCOUNT but is allowed to $CREATOR_ACCOUNT.

**Comment by earlobeheard** [comment]
$THIRD_ACCOUNT is to be allowed to ??

**Comment by ryanRfox** [comment]
Sorry @earlobeheard I was not clear in my most recent comment. The point is, $THIRD_ACCOUNT (which has not performed any _opt-in_ transactions) should be denied the ability to close a balance to their account for all ASA, and $CREATOR_ACCOUNT should be allowed to close all balances of $NEW_ACCOUNT (holding just the single ASA) in a single transaction.  As @algobolson mentioned above, this is more a feature request, because multiple transactions may be submitted to achieve the desired result.

I recently build an [ASA HTLC TEAL template](https://github.com/ryanRfox/go-algorand/blob/template-asa-htlc/tools/teal/templates/docs/asa-htlc.teal.md) which performs the two-step close process in Step 16 of the walkthrough. It would be _nice_ to perform a single transaction as `clerk send --close-to $OWNER ...` and have it sweep any remaining ASA and Algos from the escrow account.

**Comment by ryanRfox** [comment]
Closing. This is a "nice to have" feature, but not worth the effort at this time in my opinion. I've not heard others requesting this.
