### ISSUE TITLE
Rename error logs on restart

### ISSUE THREAD

**Issue by mxmauro** [algorand/go-algorand#644]
Hi, the goal of this improvement is to avoid losing important information on error scenarios.

Problem:

When a node is restarted, some log files including the error one, are overwritten.

If the node crashes for some reason and is restarted, some important information might be lost.

Improvement:

Rename existing log files to .old before recreating it.

Regards,
Mauro.

**Comment by ian-algorand** [comment]
Hey @mxmauro I know this is an old issue (trying to clean up issues we may have missed), but are you still seeing these log files overwritten?

**Comment by mxmauro** [comment]
Hi @ian-algorand. Luckily we didn't suffer crashes so far in the latest releases.

I'll try to see if it happens when you manually restart the node.

Kind regards.

**Comment by bbroder-algo** [comment]
Rolling old log files could be part of the user's restart script control.
