### ISSUE TITLE
my node stop at 3735695

### ISSUE THREAD

**Issue by bitcodernull** [algorand/go-algorand#646]
### Subject of the issue
my node don't sync , stop at 3735695

### Your environment
* Software version: `algod -v`
     2.0.1.stable
* Node status if applicable: `goal node status`
       Last committed block: 3735695
    Time since last block: 0.0s
   Sync Time: 333.2s
  Last consensus protocol: 
 https://github.com/algorandfoundation/specs/tree/0e196e82bfd6e327994bec373c4cc81bc878ef5c
Next consensus protocol: https://github.com/algorandfoundation/specs/tree/4a9db6a25595c6fd097cf9cc137cc83027787eaa
Round for next consensus protocol: 3735696
Next consensus protocol supported: false
Has Synced Since Startup: false
Genesis ID: mainnet-v1.0
   Genesis hash: wGHE2Pwdvd7S12BL5FaOP20EGYesN73ktiC1qzkkit8=

* Operating System details. 
    ubutu 16.04

* In many cases log files and cadaver files are also useful to include. Since these files may be large, an Algorand developer may request them later. These files may include public addresses that you're participating with. If that is a concern please be sure to scrub that data.

{"file":"fetcher.go","function":"github.com/algorand/go-algorand/rpcs.(*NetworkFetcher).FetchBlock","level":"info","line":217,"msg":"networkFetcher.FetchBlock: asking client r-mn.algorand-mainnet.network:4160 for block 3735696","time":"2019-12-19T01:55:00.442684+08:00"}
{"Context":"sync","file":"service.go","function":"github.com/algorand/go-algorand/catchup.(*Service).fetchAndWrite","level":"warning","line":201,"msg":"fetchAndWrite(3735697): block contents do not match header (attempt 974)","name":"","time":"2019-12-19T01:55:00.549124+08:00"}
{"file":"fetcher.go","function":"github.com/algorand/go-algorand/rpcs.(*NetworkFetcher).FetchBlock","level":"info","line":217,"msg":"networkFetcher.FetchBlock: asking client r-br.algorand-mainnet.network:4160 for block 3735697","time":"2019-12-19T01:55:00.549299+08:00"}
{"Context":"sync","file":"service.go","function":"github.com/algorand/go-algorand/catchup.(*Service).fetchAndWrite","level":"warning","line":201,"msg":"fetchAndWrite(3735697): block contents do not match header (attempt 975)","name":"","time":"2019-12-19T01:55:00.768303+08:00"}
{"file":"fetcher.go","function":"github.com/algorand/go-algorand/rpcs.(*NetworkFetcher).FetchBlock","level":"info","line":217,"msg":"networkFetcher.FetchBlock: asking client r-ne.algorand-mainnet.network:4160 for block 3735697","time":"2019-12-19T01:55:00.768465+08:00"}
{"Context":"sync","file":"service.go","function":"github.com/algorand/go-algorand/catchup.(*Service).fetchAndWrite","level":"warning","line":201,"msg":"fetchAndWrite(3735696): block contents do not match header (attempt 1054)","name":"","time":"2019-12-19T01:55:01.083861+08:00"}
{"file":"fetcher.go","function":"github.com/algorand/go-algorand/rpcs.(*NetworkFetcher).FetchBlock","level":"info","line":217,"msg":"networkFetcher.FetchBlock: asking client r-tb.algorand-mainnet.network:4160 for block 3735696","time":"2019-12-19T01:55:01.084024+08:00"}

### Steps to reproduce
Tell us how to reproduce this issue.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

**Comment by derbear** [comment]
> `Next consensus protocol supported: false`

It looks like your `algod` process is of an old version. Try installing updated binaries and restarting your node (`goal node stop; goal node start`).

**Comment by Priegle** [comment]
@bitcodernull hey there, ok to close this issue out?

**Comment by ian-algorand** [comment]
no movement on this for a long time, closing. @bitcodernull let us know if you have any other issues
