### ISSUE TITLE
how to connect mainnet?

### ISSUE THREAD

**Issue by Alteryy** [algorand/go-algorand#65]
goal node status
-------------------------
Last committed block: 0
Time since last block: 0.0s
Sync Time: 254.4s
Last consensus protocol: https://github.com/algorand/spec/tree/a26ed78ed8f834e2b9ccb6eb7d3ee9f629a6e622
Next consensus protocol: https://github.com/algorand/spec/tree/a26ed78ed8f834e2b9ccb6eb7d3ee9f629a6e622
Round for next consensus protocol: 1
Next consensus protocol supported: true
Genesis ID: mainnet-v1.0
Genesis hash:
--------------------
is chang "network": "devnet", to "network": "mainnet",? thx.

-------log--------
{"file":"fetcher.go","function":"github.com/algorand/go-algorand/rpcs.(*NetworkFetcher).FetchBlock","level":"info","line":221,"msg":"networkFetcher.FetchBlock: asking client r-lu.algorand-mainnet.network:4160 for block 1","time":"2019-06-20T11:11:47.131498+08:00"}
{"Context":"sync","file":"service.go","function":"github.com/algorand/go-algorand/catchup.(*Service).fetchAndWrite","level":"warning","line":198,"msg":"fetchAndWrite(2): cert did not authenticate block (attempt 1010): unauthenticatedBundle.verify: vote {_struct:{} R:{_struct:{} Sender:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA Round:0 Period:0 Step:0 Proposal:{_struct:{} OriginalPeriod:0 OriginalProposer:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA BlockDigest:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA EncodingDigest:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA}} Cred:{_struct:{} Weight:0 VrfOut:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA DomainSeparationEnabled:false Hashable:{_struct:{} RawOut:[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] Member:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA Iter:0} UnauthenticatedCredential:{_struct:{} Proof:[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]}} Sig:{Sig:[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] PK:[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] PKSigOld:[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] PK2:[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] PK1Sig:[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] PK2Sig:[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]}} (index 1) was invalid in bundle: unauthenticatedVote.verify: could not verify FS signature on vote by EYOZMULFFZZ5QDDMWQ64HKIMUPPNEL3WJMNGAFD43L52ZXTPESBA given [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]: {_struct:{} R:{_struct:{} Sender:EYOZMULFFZZ5QDDMWQ64HKIMUPPNEL3WJMNGAFD43L52ZXTPESBA Round:2 Period:0 Step:2 Proposal:{_struct:{} OriginalPeriod:0 OriginalProposer:HHZQOGQKMQDLBEL3HXMDX7AGTNORYVZ4JFDWVSL5QLWMD3EXOIAA BlockDigest:XFQ7KBE2JDSBNE3JWLR2VA3EAAZ5T7CW7H42YHCNQML7Q5MAOBVA EncodingDigest:LYMX344RIQMQ6FEUVOPTUB2H45PIB6YMQFXDNUJQCBHS7AQFQV4A}} Cred:{_struct:{} Proof:[193 255 24 1 125 88 232 52 116 237 224 168 45 29 158 227 30 18 35 197 163 249 167 69 163 164 249 37 143 167 214 195 196 146 85 175 243 225 40 138 23 205 106 210 56 155 169 209 69 204 143 136 213 96 5 238 101 88 28 232 56 89 167 83 120 197 165 158 107 125 145 147 198 36 63 35 248 14 123 6]} Sig:{Sig:[229 223 7 250 55 218 88 247 254 31 198 152 201 238 134 19 116 231 251 0 164 254 22 201 202 113 130 202 26 204 112 203 35 102 176 212 204 230 115 197 156 165 166 117 90 108 208 155 35 146 2 111 40 35 48 94 184 74 91 196 89 81 252 2] PK:[81 95 248 132 247 164 242 180 87 108 45 149 51 57 164 249 235 31 241 233 58 61 245 166 208 129 90 216 139 38 189 236] PKSigOld:[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] PK2:[41 60 53 140 207 49 172 202 201 254 49 183 30 86 174 236 70 98 134 172 79 155 187 102 33 9 148 32 164 172 181 82] PK1Sig:[154 112 34 72 181 70 65 20 107 35 86 186 163 135 141 63 39 211 152 182 101 158 248 124 182 251 157 208 8 253 180 248 99 228 225 43 34 153 49 142 130 151 140 172 238 112 92 108 241 5 93 201 23 122 214 68 26 209 51 222 193 146 18 8] PK2Sig:[36 181 232 31 107 203 246 107 143 104 233 32 83 183 198 39 248 27 237 245 150 192 118 90 198 165 221 174 198 224 81 79 178 104 109 245 76 217 230 205 73 240 102 10 237 87 144 119 181 230 250 229 188 239 160 124 88 26 76 137 43 53 29 3]}}","name":"","time":"2019-06-20T11:11:47.382353+08:00"}
{"file":"fetcher.go","function":"github.com/algorand/go-algorand/rpcs.(*NetworkFetcher).FetchBlock","level":"info","line":221,"msg":"networkFetcher.FetchBlock: asking client r-he.algorand-mainnet.network:4160 for block 2","time":"2019-06-20T11:11:47.382611+08:00"}

**Comment by Karmastic** [comment]
What is the question?  The `goal status` response does indicate that you are connected to the live MainNet (mainnet-v1.0).
