### ISSUE TITLE
Goal should be systemd aware

### ISSUE THREAD

**Issue by ian-algorand** [algorand/go-algorand#656]
debian installs as system d service with auto restart.

if you use goal node stop, systemd will restart it.  we should handle that better cause it can basically block upgrades.

**Comment by algobolson** [comment]
When installed with `systemd` managing `algod`, `goal node stop` is wrong and `systemctl stop algorand` is the right way. `goal node ...` currently has no way to know if `algod` is managed by `systemd`. The simplest is probably to set value in ${ALGORAND_DATA}/system.json . We currently use that file to note systems that have a demon user (`algorand`).

**Comment by bricerisingalgorand** [comment]
Looking into the problem, it appears that goal's node start, stop and restart commands all need to be updated to interact with systemd in our rpm and debian installations. I like the approach of noting that whether we're on an OS using systemd in system.json. I'll move forward with that implementation for now

**Comment by bricerisingalgorand** [comment]
Talked with @tsachiherman during standup, providing dialog to the user on the appropriate way to stop/start/restart the service using systemctl is the preferred approach. I will be continuing by developing that.

**Comment by bricerisingalgorand** [comment]
Putting this on hold temporarily until the process for automating building rpm/dpkg packages is finished. The implementation of this task depends on the output of that one

**Comment by algobolson** [comment]
Isn't this just changing `installer/system.json` to add `"systemd_managed":true` and adding the code to interpret that value? system.json is picked up by parts of the deb and rpm packaging that probably won't change, and every deb/rpm install is a systemd distro.
If we wanted to get fancy we could add some post-install scripting to deb/rpm to check for the presence of `systemctl` or something.
