### ISSUE TITLE
how to create transaction?

### ISSUE THREAD

**Issue by Alteryy** [algorand/go-algorand#67]
https://developer.algorand.org/docs/kmd-rest-models#SignTransactionRequest
-----------------------
API V1 POST TransactionSignRequest is the request for POST /v1/transaction/sign
transaction (optional) byte[] format: binary
wallet_handle_token (optional) String
wallet_password (optional) String
-----------------------
Do you have more detailed descriptions of parameter names and types? all optional ? thx.

**Comment by Vervious** [comment]
This issue tracker is not appropriate for most questions - including support for our API. 

General, developer or support questions concerning Algorand should be directed to the Algorand Forums https://forum.algorand.org/. Try posting there.

I will close the issue barring any objections.

**Comment by Ogcoolestmc** [comment]
Please someone should please teach me how to sign algorand transaction
