### ISSUE TITLE
transaction.RelevantAddrs doesn't take clawback sender into account 

### ISSUE THREAD

**Issue by rotemh** [algorand/go-algorand#678]
### transaction.RelevantAddrs doesn't take clawback sender into account 
When it scans a AssetTransferTx, the function checks the receiver and CloseTo but not the sender in a case of Clawback. 

### Expected behaviour
Should check for the clawback sender as well. 

### Actual behaviour
Tell us what happens instead

**Comment by ian-algorand** [comment]
Fixed by @winder
