### ISSUE TITLE
A possible bug in lastRelevant

### ISSUE THREAD

**Issue by xixisese** [algorand/go-algorand#710]
The lastRelevant tries to get the latest period relevant to the specified proposal value, the code is:
https://github.com/algorand/go-algorand/blob/307790071c8afb6c785f8e244785a856bca11a58/agreement/proposalStore.go#L370-L382

It's possible the result period got from the function has nothing to do with the parameter pv. 
shouldn't it be updated as follows?

	for per := range store.Relevant {
		if (per > p) && (store.Relevant[per] == pv) {
			p = per
		}
	}
	return

**Comment by derbear** [comment]
I think you're right. We're looking into it right now to see what the impact of this missing condition could be.

Good find!

**Comment by derbear** [comment]
We were able to reproduce the bug and find a fix for it. The results of our investigation are in #746. Thank you for reporting this bug to us!

**Comment by ian-algorand** [comment]
@xixisese, thanks for your contribution! When you get a chance, would you email me at ian@algorand.com ? Thanks!
