### ISSUE TITLE
Minor Issues of Split Payment Template

### ISSUE THREAD

**Issue by stechu** [algorand/go-algorand#723]
During the effort of formally verifying our current templates, I find the following two minor issues of `split.teal.tmpl`:

1. In the close case, the size of transaction group is not  specified. I guess this is sort of OK since there is no real harm for this specific case in the sense that the attacker will gain nothing. But it might still be nice to specify the group size explicitly. 
2. In the payment case, the template only ensures the amount transferred in the first transaction is greater or equal than TMPL_MINPAY. This does quite match the behavior specified in the document:
`TMPL_MINPAY: minimum amount to be paid out of the account`. Either the template or the documentation should be changed.

@derbear @justicz

**Comment by ian-algorand** [comment]
Closing this issue for now, will reopen if we need to address it.
