### ISSUE TITLE
Optimize the synchronization between catchup service and agreement service

### ISSUE THREAD

**Issue by xixisese** [algorand/go-algorand#725]
Currently the agreement service will start at once, independent of the catchup service。it works well, but we can consider an optimization

when the local node's round lag far behind the network, the agreement service is doing  unnecessary work, issuing useless network message possibly.

We need to wait for the catchup service finishing the initial network synchronization,  then start the agreement service。 The agreement service will keep almost the same state with the overall network.

just take use of  the  InitialSyncDone channel in the catchup service will solve the problem easily

**Comment by tsachiherman** [comment]
There is a conceptual issue in your suggestion - it requires that the catching up node would know what round the network is at. That knowledge require some degree of trust, which isn't obvious.
