### ISSUE TITLE
Add restrictions to avoid creation of useless/indestructible assets.

### ISSUE THREAD

**Issue by mxmauro** [algorand/go-algorand#734]
Hi,

The node makes several checks for accepting TXs but does not verify, in the creation of an asset, if at least the amount is not zero.

This is an example of a non-sense asset 441 on betanet, output from node: `Asset 441: {"creator":"PXDZ4HZHCFEM47PV6IYXCBV7T5GM3ANJPWCMLU22YBKG4TF3B6C3YFYSJU","total":0,"decimals":0,"defaultfrozen":false,"managerkey":"","reserveaddr":"","freezeaddr":"","clawbackaddr":""}`

Regards,
Mauro.

**Comment by yaovi-a** [comment]
Need to confirm if assets that are created with amount 0 are indestructible

**Comment by winder** [comment]
Assets with a total of 0 are not indestructible. Please re-open if there is a specific reason why this restriction should be added.

```
$ ./sandbox goal asset create --total 0 --creator QJ66I5T3OPHL4WFRWJPMEEGR6JMPLHKTNEAU2Y5YUTY62K4HPHAFVON3ZM
Issued transaction from account QJ66I5T3OPHL4WFRWJPMEEGR6JMPLHKTNEAU2Y5YUTY62K4HPHAFVON3ZM, txid FGRFI2KEYEN5T2CMAMGJWTLVTIIANGUEXA4WDRPFHVFAUPZ7WACA (fee 1000)
Transaction FGRFI2KEYEN5T2CMAMGJWTLVTIIANGUEXA4WDRPFHVFAUPZ7WACA still pending as of round 32
Transaction FGRFI2KEYEN5T2CMAMGJWTLVTIIANGUEXA4WDRPFHVFAUPZ7WACA still pending as of round 33
Transaction FGRFI2KEYEN5T2CMAMGJWTLVTIIANGUEXA4WDRPFHVFAUPZ7WACA committed in round 34
Created asset with asset index 3

$ ./sandbox goal account list --info
[offline]	EUVVPGD7IBC7W32NR4JVC3G4KDZ7YBAOLLTI32HYD3YWH4FOFCNOBVSJUU	EUVVPGD7IBC7W32NR4JVC3G4KDZ7YBAOLLTI32HYD3YWH4FOFCNOBVSJUU	4000020000000000 microAlgos
Created Assets:
	<none>
Held Assets:
	<none>
Created Apps:
	<none>
Opted In Apps:
	<none>
[online]	QJ66I5T3OPHL4WFRWJPMEEGR6JMPLHKTNEAU2Y5YUTY62K4HPHAFVON3ZM	QJ66I5T3OPHL4WFRWJPMEEGR6JMPLHKTNEAU2Y5YUTY62K4HPHAFVON3ZM	4000019999996995 microAlgos	[created asset IDs: 3 (0 )]
Created Assets:
	ID 3, <unnamed>, supply 0 units
Held Assets:
	ID 3, <unnamed>, balance 0 units
Created Apps:
	<none>
Opted In Apps:
	<none>
[offline]	XHQF2AOENWKFOB4SNLIJ4DQAF5LASOKHLOJW2V3CLCASBLR6HAISKDBWFM	XHQF2AOENWKFOB4SNLIJ4DQAF5LASOKHLOJW2V3CLCASBLR6HAISKDBWFM	1000005000000000 microAlgos
Created Assets:
	<none>
Held Assets:
	<none>
Created Apps:
	<none>
Opted In Apps:
	<none>


$ ./sandbox goal asset destroy --creator QJ66I5T3OPHL4WFRWJPMEEGR6JMPLHKTNEAU2Y5YUTY62K4HPHAFVON3ZM --assetid 3
Issued transaction from account QJ66I5T3OPHL4WFRWJPMEEGR6JMPLHKTNEAU2Y5YUTY62K4HPHAFVON3ZM, txid QYIDISQEC2SDVMS464ZOEMUDOHNHCKOZ43NX3UZIDJUQ7OWM4O4Q (fee 1000)
Transaction QYIDISQEC2SDVMS464ZOEMUDOHNHCKOZ43NX3UZIDJUQ7OWM4O4Q still pending as of round 232
Transaction QYIDISQEC2SDVMS464ZOEMUDOHNHCKOZ43NX3UZIDJUQ7OWM4O4Q still pending as of round 233
Transaction QYIDISQEC2SDVMS464ZOEMUDOHNHCKOZ43NX3UZIDJUQ7OWM4O4Q committed in round 234

$ ./sandbox goal account list --info               8.3s  Mon 24 May 2021 12:30:22 PM EDT
[offline]	EUVVPGD7IBC7W32NR4JVC3G4KDZ7YBAOLLTI32HYD3YWH4FOFCNOBVSJUU	EUVVPGD7IBC7W32NR4JVC3G4KDZ7YBAOLLTI32HYD3YWH4FOFCNOBVSJUU	4000020000000000 microAlgos
Created Assets:
	<none>
Held Assets:
	<none>
Created Apps:
	<none>
Opted In Apps:
	<none>
[online]	QJ66I5T3OPHL4WFRWJPMEEGR6JMPLHKTNEAU2Y5YUTY62K4HPHAFVON3ZM	QJ66I5T3OPHL4WFRWJPMEEGR6JMPLHKTNEAU2Y5YUTY62K4HPHAFVON3ZM	4000019999995995 microAlgos
Created Assets:
	<none>
Held Assets:
	<none>
Created Apps:
	<none>
Opted In Apps:
	<none>
[offline]	XHQF2AOENWKFOB4SNLIJ4DQAF5LASOKHLOJW2V3CLCASBLR6HAISKDBWFM	XHQF2AOENWKFOB4SNLIJ4DQAF5LASOKHLOJW2V3CLCASBLR6HAISKDBWFM	1000005000000000 microAlgos
Created Assets:
	<none>
Held Assets:
	<none>
Created Apps:
	<none>
Opted In Apps:
	<none>
```

**Comment by mxmauro** [comment]
Hi @winder and @yaovi-a 

`goal` sets the manager to the same account than the creator if none is specified.

Force it to be empty and because of [this](https://github.com/algorand/go-algorand/blob/master/ledger/apply/asset.go#L114) you will have an indestructible dummy asset.

Regards.

**Comment by winder** [comment]
@mxmauro could provide the commands for reproducing the scenario you have in mind and what errors you are expecting to see instead of the actual behavior?

**Comment by mxmauro** [comment]
Hi @winder , basically I created the TX using the javascript SDK and sent to the network.

In my opinion, I would reject the creation of assets with total amount of zero or, at least, enforce a manager to be non-nil, for the creation (later can be changed with asset config)

First, to avoid filling the blockchain with dummy TXs in the same way you can send dummy asset xfer TXs with amount zero and specify any asset id no matter if it was created or not, because the code omits some checks when the amount is zero.

 Second, because an account has a limited amount of assets it can create.

I repeat, is my opinion. If it were a serious bug, I would tag it different :)
