### ISSUE TITLE
Deploy build artifacts to staging rather than directly to production

### ISSUE THREAD

**Issue by btoll** [algorand/go-algorand#752]
After the initial release pipeline has built the artifacts, they should be deployed to a staging area such as `algorand-builds` rather than directly to a publicly-accessible (production) bucket such as `algorand-dev-deb-repo`.

**Comment by algobolson** [comment]
could be as simple as re-targeting the script to a different bucket+path.

I felt originally there was no reason _not_ to have the build publicly downloadable but unlisted. (Everything is open source, no secrets.) There aren't any URLs to download from unless we `aws s3 ls ...` and give someone a URL to donwload from. But a testing partner could download from there if we wanted them to.
