### ISSUE TITLE
Algorand Install Should Follow FHS 3.0 and Secure Deployment Best Practices

### ISSUE THREAD

**Issue by jecassis** [algorand/go-algorand#77]
### Is your feature request related to a problem?

The Algorand node behaves differently depending on who the user is or how the utilities are called. In addition, upgrades revert some customizations but not others. Permissions are not consistent with other system components. Some environment setups cause unexpected behavior (e.g. inability to generate multisig transactions correctly).

### Describe the solution you'd like

Follow [FHS 3.0](http://refspecs.linuxfoundation.org/FHS_3.0/fhs/index.html) as closely as possible:

| Name                                  | Path                                     | Owner    | Directory Permissions | File Permissions                |
|---------------------------------------|------------------------------------------|----------|-----------------------|---------------------------------|
| Daemon and utility programs directory | /usr/bin                                 | root     |       drwxr-xr-x      |            -rwxr-xr-x           |
| Libraries directory                   | /usr/lib/algorand                        | root     |       drwxr-xr-x      |    -rwxr-xr-x and -rw-r--r--    |
| Data directory i.e. ALGORAND_DATA     | /var/lib/algorand                        | algorand |       drwxr-x---      |        most: -rw-r--r--       |
| PID and lock files                    | /var/lib/algorand/algod.{pid,lock}       | algorand |       drwxr-x---      | PID:-rw-r-----, lock:-rw------- |
| Systemd service file                  | /lib/systemd/system/algorand.service     | root     |       drwxr-xr-x      |            -rw-r--r--           |
| System configuration files            | /etc/apt/apt.conf.d/51algorand-upgrades  | root     |       drwxr-xr-x      |            -rw-r--r--           |
| Miscellaneous files directory         | /usr/share/doc/algorand                  | root     |       drwxr-xr-x      |            -rw-r--r--           |

**Both** `algorand` user and group should be created as `nogroup` [shouldn't own any files](https://wiki.debian.org/SystemGroups). Running the `algod` daemon with its own user and group tends to be best practice nowadays for secure deployments.

Debian package example changes:
```
adduser --system --group --home /var/lib/algorand --no-create-home algorand >/dev/null
chown -R algorand:algorand /var/lib/algorand
```
Consequently, if doing so, `algorand.service` must change to run as `Group=algorand`.

In addition, for Debian package specifically, add `algorand.service` and `system.json` to `conffiles` as these should not be replaced during an upgrade if they are modified.

The following can be added to `postinst` for the reasons specified [here](https://github.com/algorand/go-algorand/tree/master/daemon/kmd#preventing-memory-from-swapping-to-disk) to improve default KMD install security: 
```
setcap cap_ipc_lock+ep /usr/bin/kmd
```

For non-DEB/RPM installs consider using `/usr/local/algorand/bin` and adding that to PATH or also `/usr/local/bin` to better follow FHS 3.0.

### Additional context

Other important areas for discussion, some of which depend or should match with the intent of those who designed this `algorand` node implementation, are:
 - Environment variables and their recommended use, i.e. `ALGORAND_DATA` and `ALGORAND_KMD` at the very least.
 - How to ensure data consistency. For example, a single user can create a state where `goal` commands return different data depending on how its invoked due to `.algorand` location resolution (it would be helpful if this is documented better and explicitly).
 - In DEB/RPM installs several goal commands have side-effects that require elevated user privileges such as those dealing with participation keys--these should be called out explicitly. This is really due to the fact that binary utilities such as `goal` are powerful and don't need to go through `algod` API-like to perform some operations. In my mind this is good, but requires deep thought as to how the underlying data is owned, accessed, and modified.

**The end goal to strive for predictable and reasonable behavior such that no end user is required to refer to the source code in this repo to diagnose issues in their production systems.**

**Comment by zeldovich** [comment]
Thanks, this all seems like reasonable stuff we should do!

**Comment by jecassis** [comment]
In case it is helpful, here is a [script](https://gist.githubusercontent.com/jecassis/455d647ef0ce8740ab4b9933e8b135ff/raw/71cf91c6aa1ab2705afc7f6a65d25674791be7b2/post-algorand-install.sh) with several of the changes outlined above that we're doing on top of the default install.

**Comment by zeldovich** [comment]
Do you have any reference for systemd unit files being conffiles?  (You say that we should be making `algorand.service` a conffile in the debian package.)  A cursory check suggests that other Debian packages on my Ubuntu machine don't follow this plan, and I couldn't find anything in the Debian documentation saying that systemd unit files should be conffiles.

**Comment by algobolson** [comment]
making the systemd unit file a conffile makes sense to me because if someone wanted to move the data directory (e.g. to fast SSD storage) they'd have to edit the systemd unit file.

**Comment by zeldovich** [comment]
A common way of doing that would be to make `/var/lib/algorand` a symlink to the disk where the operator wants to store the data, or mount the fast SSD storage with `/var/lib/algorand` as a mountpoint.

**Comment by jecassis** [comment]
In my configurations `/var/lib/algorand` is the mountpoint. I benchmarked those 2 options using Phoronix Test Suite and symlink came back over 100% slower in run time.

That said, to avoid marking the systemd file as a conffile, you can do what I did in the script which is use an environment file to set ALGOD_OPTS. Of course, then, you'd also want that file as a conffile. Kind of a Catch-22.

**Comment by algobolson** [comment]
Something I learned about systemd in the last couple weeks is that one doesn't _need_ to edit `algorand.service` because it's possible to create `algorand.service.d/override.conf` ("override" can be anything, or multiple things, and they're evaluated in order as successive overlays to the base `algorand.service`). So, I don't think we need to add the algorand.service file as a 'conf' file in either package manager.

**Comment by algobolson** [comment]
@jecassis see pull #169 for what should be most of these improvements

**Comment by jecassis** [comment]
Finally got around to making and installing a specific build with this patch and tested it on our dev server. Looks good to me.
