### ISSUE TITLE
Deadlock crashes algod process very frequently

### ISSUE THREAD

**Issue by Antyrael** [algorand/go-algorand#784]
### Subject of the issue
After running for a couple of minutes, anywhere between 3 and 20 minutes so far, the algod process crashes.

### Your environment
* Software version: `algod -v`
```
$ algod -v
8589995310
2.0.60718.master [master] (commit #983456f6)
go-algorand is licensed with AGPLv3.0
source code available at https://github.com/algorand/go-algorand
```

* Node status if applicable: `goal node status`
```
$ goal node status
Last committed block: 4704189
Time since last block: 2.7s
Sync Time: 0.0s
Last consensus protocol: https://github.com/algorandfoundation/specs/tree/4a9db6a25595c6fd097cf9cc137cc83027787eaa
Next consensus protocol: https://github.com/algorandfoundation/specs/tree/4a9db6a25595c6fd097cf9cc137cc83027787eaa
Round for next consensus protocol: 4704190
Next consensus protocol supported: true
Genesis ID: mainnet-v1.0
Genesis hash: wGHE2Pwdvd7S12BL5FaOP20EGYesN73ktiC1qzkkit8=
```

* Operating System details. 
Latest Rasbian Buster on Raspberry Pi 4 (4GB RAM model)

* In many cases log files and cadaver files are also useful to include. Since these files may be large, an Algorand developer may request them later. These files may include public addresses that you're participating with. If that is a concern please be sure to scrub that data.

### Steps to reproduce
starting algo as usual: goal node start
Let it run for a while, deadlock occurs and process crashes.

### Expected behaviour
I expect the process not to crash, so I can participate with an active node.

### Actual behaviour
The algod process crashes.

### Additional information
Uploaded node.log and algod-err.log.
[node.log](https://github.com/algorand/go-algorand/files/4160857/node.log)
[algod-err.log](https://github.com/algorand/go-algorand/files/4160858/algod-err.log)

**Comment by pzbitskiy** [comment]
Thank for the report. A little bit info from log files:
```
dbatomic: tx took 2.578283247s
dbatomic: tx took 11.986205188s
dbatomic: tx took 12.222784613s
dbatomic: tx took 17.941909794s
...

POTENTIAL DEADLOCK:
Previous place where the lock was grabbed
goroutine 7247 lock 0x312eda8
go-algorand/node/node.go:744 node.(*AlgorandFullNode).oldKeyDeletionThread { node.mu.Lock() } <<<<<

Have been trying to lock it again for more than 30s
goroutine 7121 lock 0x312eda8
go-algorand/node/node.go:705 node.(*AlgorandFullNode).OnNewBlock { node.mu.Lock() } <<<<<
go-algorand/ledger/notifier.go:66 ledger.(*blockNotifier).worker { listener.OnNewBlock(blk.block, blk.delta) }

Here is what goroutine 7247 doing now
goroutine 7247 [chan receive]:
github.com/algorand/go-algorand/data.(*AccountManager).DeleteOldKeys(0x32239c0, 0x47c747, 0x0, 0x2710, 0x0, 0x2328, 0x0, 0x222e0, 0x0, 0x0, ...)
	/home/user/go-algorand/data/accountManager.go:142 +0x118
github.com/algorand/go-algorand/node.(*AlgorandFullNode).oldKeyDeletionThread(0x312ed80)
	/home/user/go-algorand/node/node.go:745 +0x338
created by github.com/algorand/go-algorand/node.(*AlgorandFullNode).Start
	/home/user/go-algorand/node/node.go:340 +0x228
```

How many accounts do you run on your node?
There is a known problem: if here are too many online (participating/voting) accounts on a node it might take significant amount of time to regenerate these keys.
Recommendation: either decrease amount of account, or make them offline, or use faster CPU.

@tsachiherman FYI

**Comment by tsachiherman** [comment]
Few more notes to what @pzbitskiy already wrote above -
1. You're trying to run it on Raspberry Pi4. While this is a great low-power device, it still won't compare to a full scaled desktop.  The cpu optimizations around the cryptography library, for instance, are not as extensive on arm64 as they are on amd64.
2. The build you're running is a private build. While there is nothing wrong with that, we naturally haven't tested that particular build. Note that on a public build ( that was built off rel/stable or rel/beta ), the deadlock detection would not have been enabled, and this would not be an issue. ( see `./scripts/compute_branch_deadlock_default.sh` )
3. The failure point is quite clear - the generating of new participation keys exceeded the expected time. I would suggest you would delete the participation keys and regenerate them. When generating them, try to select a low key dilution value. The default value is 10,000. I suggest that you'll try to set it to 100 when creating the participation keys.

**Comment by tsachiherman** [comment]
I'm closing this issue as there hasn't been any activity here for the past 5 months. If you believe it's still an issue, please try to reproduce it with the latest build and create a new ticket.
