### ISSUE TITLE
Verify signatures on all packages in algorand-releases and algorand-dev-deb-repo

### ISSUE THREAD

**Issue by btoll** [algorand/go-algorand#792]
We recently found some older tarballs that had been signed by a revoked key that was included in a Medium article.

We should go through all buckets and verify all the signatures.

The article is https://medium.com/algorand/how-to-securely-generate-keys-and-transact-on-the-algorand-blockchain-81bee5312de3 which has a segment on running an offline node. The package is https://releases.algorand.com/install/offline_install_stable_linux-amd64.tar.gz and I was able to download https://releases.algorand.com/install/offline_install_stable_linux-amd64.tar.gz.sig The sig validation says the subkey as been revoked.
```
$ gpg --verify offline_install_stable_linux-amd64.tar.gz.sig offline_install_stable_linux-amd64.tar.gz
gpg: Signature made Thu Jun 20 11:49:05 2019 EDT
gpg:        using RSA key 1947DC00165768D2
gpg: Good signature from “Algorand developers <dev@algorand.com>” [unknown]
gpg: WARNING: This subkey has been revoked by its owner!
gpg: reason for revocation: Key is superseded
gpg: WARNING: This key is not certified with a trusted signature!
gpg:     There is no indication that the signature belongs to the owner.
Primary key fingerprint: 611D E94A 396F 0135 9C72 AF56 EDAC D29D A10A 4EA6
   Subkey fingerprint: F2EB 1031 BCF5 A93E 6AE6 C27E 1947 DC00 1657 68D2
```

**Comment by onetechnical** [comment]
Probably part of a larger restructuring we should do; not prioritizing for now.
