### ISSUE TITLE
Tests temporarily skipped that need attention

### ISSUE THREAD

**Issue by algonautshant** [algorand/go-algorand#802]
agreement/cryptoVerifier_test.go-func TestCryptoVerifierBuffers(t *testing.T) {
agreement/cryptoVerifier_test.go:	t.Skip("Test is flaky")
https://github.com/algorand/go-algorand/issues/2297

logging/telemetryhook_test.go-func TestAsyncTelemetryHook_QueueDepth(t *testing.T) {
logging/telemetryhook_test.go:	t.Skip("flakey test can fail on slow test systems")
https://github.com/algorand/go-algorand/issues/2299

network/wsNetwork_test.go-func TestFloodingPeer(t *testing.T) {
network/wsNetwork_test.go:	t.Skip("flaky test")
Ran 100 times on mac. * * * **Seems to be passing no problem** * * * 
Enabled in https://github.com/algorand/go-algorand/pull/2326

network/wsNetwork_test.go TestSlowOutboundPeer
This test is failing because it is expecting the slow peer to be closed. 
In commit https://github.com/algorand/go-algorand/commit/ea855418b0b928435c0f883e3847456b938ab293
the peer is no longer closed. @tsachiherman is it okay to reverse the check from closed to not closed?
This is now followed in: https://github.com/algorand/go-algorand/issues/2325

node/node_test.go-func TestSyncingFullNode(t *testing.T) {
node/node_test.go:	t.Skip("This is failing randomly again - PLEASE FIX!")
node/node_test.go-func TestInitialSync(t *testing.T) {
node/node_test.go:	t.Skip("flaky TestInitialSync ")
node/node_test.go-func TestSimpleUpgrade(t *testing.T) {
node/node_test.go:	t.Skip("Randomly failing: node_test.go:~330 : no block notification for account. Re-enable after agreement bug-fix pass")
These are now followed in https://github.com/algorand/go-algorand/issues/2318

test/e2e-go/features/transactions/transactionPool_test.go-func TestTransactionPoolOrderingAndClearing(t *testing.T) {
test/e2e-go/features/transactions/transactionPool_test.go:	t.Skip("test is flaky as of 2019-06-18")
This was disabled long time ago https://github.com/algorand/go-algorand/pull/45
Now never passes. 
This issue is now followed in https://github.com/algorand/go-algorand/issues/2323

test/e2e-go/features/participation/onlineOfflineParticipation_test.go:	t.Skip() // temporary disable the test since it's failing.
This issue is now followed in:
https://github.com/algorand/go-algorand/issues/2323

**Comment by yaovi-a** [comment]
Needs to be broken up.
