### ISSUE TITLE
Skipped tests that need updating

### ISSUE THREAD

**Issue by algonautshant** [algorand/go-algorand#803]
Note - the task here is to create separate tickets for each of the following individual tests:

network/wsNetwork_test.go-func TestSlowOutboundPeer(t *testing.T) {
network/wsNetwork_test.go:	t.Skip() // todo - update this test to reflect the new implementation.

rpcs/txSyncer_test.go-func TestStartAndStop(t *testing.T) {
rpcs/txSyncer_test.go:	t.Skip("TODO: replace this test in new client paradigm")

TestOnSwitchToUnSupportedProtocol is currently being skipped, as it creates random failures on travis.

**Comment by yaovi-a** [comment]
Check if txSyncer is still relevant and decide on next steps.

**Comment by algonautshant** [comment]
I verified these issues are still open issues and require attention.
The following tickets include more information about each case. 

https://github.com/algorand/go-algorand/issues/2189
https://github.com/algorand/go-algorand/issues/2191
https://github.com/algorand/go-algorand/issues/2200
https://github.com/algorand/go-algorand/issues/2201
