### ISSUE TITLE
Improve goal support for shell pipelines.

### ISSUE THREAD

**Issue by derbear** [algorand/go-algorand#83]
Certain `goal` commands accept filenames as input and output parameters. However, they do not accept `stdin` or `stdout`, which are convenient for use in shell pipelines. For instance, `goal clerk sign` accepts a `-i` input file and a `-o` output file but not stdin/stdout.

Adding support to goal for accepting stdin/stdout will simplify scripting.

**Comment by algoradam** [comment]
It's worth noting that `-i /dev/stdin` and `-o /dev/stdout` should work, but it would be nicer and more idiomatic to accept `-i -` and `-o -`

**Comment by algoradam** [comment]
Fixed by #153

**Comment by Vervious** [comment]
Thanks @jsign!
