### ISSUE TITLE
Provide More Contract Languages on Higher Level

### ISSUE THREAD

**Issue by ghost** [algorand/go-algorand#833]
(did not find a relevant top-level repository, please move issue as you see fit)

Ensure that languages like

https://github.com/algorand/pyteal

are prioritized, as it is a bad DX to write stuff in assembly. Python is fine, TypeScript would be nice (e.g. use one language for app and dapp code)

See e.g. Tezos, has multiple languages:

https://developers.tezos.com/

**Comment by ian-algorand** [comment]
This is being tracked on our product roadmap. Sorry that no one ever got back to you on this, and thanks for your contribution!
