### ISSUE TITLE
`_tx_lock` options does not exist

### ISSUE THREAD

**Issue by mxmauro** [algorand/go-algorand#838]
Hi, just a minor fix:

On https://github.com/algorand/go-algorand/blob/add8ea7f0a8698f6142c4546cfb4bbccd8e87cd5/daemon/kmd/wallet/driver/sqlite.go#L47

`_tx_lock` is referenced but the correct option is `_txlock`

Regards,
Mauro.

**Comment by justicz** [comment]
Great find! Just opened a PR (#871) to fix this. Thanks for auditing/reporting.
