### ISSUE TITLE
Fix inconsistencies in `goal` long arguments.

### ISSUE THREAD

**Issue by derbear** [algorand/go-algorand#84]
### Subject of the issue
Some goal commands accept `addr` while others accept `address` as long-form arguments.

### Your environment
* Software version: `algod -v`: 1.0.39516.dev [master] (commit #db5c6d56+)

* Operating System: Any 

### Steps to reproduce
`goal account balance` shows `  -a, --address string   Account address to retrieve balance (required)`
while
`goal account delete` shows `  -a, --addr string   Address of account to delete`

### Expected behaviour
The long-form options should either both be `--address` or `--addr`.

### Actual behaviour
One of the options is `--address` and the other is `--addr`.

**Comment by rotemh** [comment]
Fixed by #147
