### ISSUE TITLE
Agreement service votes validation conflicts with ledger balance history

### ISSUE THREAD

**Issue by tsachiherman** [algorand/go-algorand#914]
## Issue
The issue that we've observed was logged as follows:
```
malformed proposal for (5487228, 0): unauthenticatedVote.verify: could not get membership parameters: Service.initializeVote (r=5487228): Failed to obtain balance record for address IVKDCE6MS44YVGMQQFVXCDABW2HKULKIXMLDS2AEOIA6P2OGMVHVJ64MZI in round 5486908: round 5486908 before dbRound 5486910
```

The above has few variation ranging between proposal and vote verification.

## Analysis
The verification code is relying on the `membership` function, which is turn is using the `balanceRound` to calculate the round at which we obtain the balance for the account in question. The round number is calculated as : 
balanceRound = vote/proposal round - 2 * SeedRefreshInterval * SeedLookback =  vote/proposal round - 2 * 80 * 2 = vote/proposal round - 320

On the other hand, the ledger account manager is holding back the balances for the past MaxBalLookback round ( = 320 ).

If the agreement service was the only party that is moving the ledger forward, this would not be an issue. However, since the catchup is moving the ledger as well, it does get to scenarios where such as : 
1. ledger round is 1000 ( earliest balance round is 680 ).
2. the agreement service received a message to be verified for round 1000. That went onto a background queue.
3. the catchup service moved the ledger to round 1001 ( earliest balance round is 681 ).
4. the verifier is trying to verify the message and needs the balance for round 1000-320=680. however, this balance is no longer available.

**Comment by derbear** [comment]
This should be safe--if the catchup service has already moved on to the next round, then it's fine to try to send votes from old rounds.

Perhaps it would make sense to drop the logging level to `info` in such a case? Is this something worth doing?

**Comment by tsachiherman** [comment]
Yes, this sounds correct. If we could confirm that this is the case, then we should lower the logging level as well as log a different message. ( i.e. message that explain why this membership isn't really required )

**Comment by derbear** [comment]
Okay. Something to keep in mind is that this is only fine in this case--if the failure is due to something else, then something has definitely gone wrong.

I think we'll need to have the `LedgerReader` methods return an error of a specific type and then switch on it at the top.

**Comment by derbear** [comment]
Or, something easier might be to check the current round and suppress the warning if we've moved past it.

**Comment by tsachiherman** [comment]
Yes; also, we need to make sure not to disconnect from the source of the message in that case.
