### ISSUE TITLE
pseudonode.MakeVotes call failed

### ISSUE THREAD

**Issue by tsachiherman** [algorand/go-algorand#916]
## Issue
Reviewing the nightly build logs revealed the following log entry:
```
Errors:
        (33) pseudonode.MakeVotes call failed(attest) pseudonode input channel is full
```

**Comment by tsachiherman** [comment]
@derbear  could you please further triage this issue to determine its severity ?

**Comment by derbear** [comment]
If this is a transient/intermittent event, it seems fine to ignore for now--the only effect of this is for for a node to drop some outbound votes. This issue warrants investigation if this event is pervasive or frequent.

**Comment by tsachiherman** [comment]
sounds reasonable. Let's ask @onetechnical to create some monitoring task for this one, so that if it becomes an issue, we'll know that we need to fix this.

**Comment by onetechnical** [comment]
I don't think we've seen this in a while, so closing this.
