### ISSUE TITLE
Add a goal ledger command to dump a block or range of blocks

### ISSUE THREAD

**Issue by algoradam** [algorand/go-algorand#92]
Right now there's no convenient way to dump and examine a raw block. It'd be nice if there were a command like `goal ledger dumpblock 400` to dump block 400 as base64 encoded msgpack to stdout. Perhaps it could have a `--json` flag to translate it to json, `msgpacktool`-style.

This would be useful for debugging (what's going on in this block header?) and also just a fun way to see what's going on in the blocks.

**Comment by Vervious** [comment]
What's the rationale for keeping it encoded as canonical msgpack?

**Comment by tsachiherman** [comment]
> What's the rationale for keeping it encoded as canonical msgpack?

You mean in the sqlite database ? We keep it encoded so that it would be faster when requested by the catchup. That should also align with the way that we received the block from the network.

**Comment by algobolson** [comment]
#621 implements the algod side of this by adding a local API for fetching raw block bytes
