### ISSUE TITLE
TEAL - unconditional jump

### ISSUE THREAD

**Issue by jeapostrophe** [algorand/go-algorand#930]
In TEAL, I can do an unconditional jump by pushing on 1 and then doing a `bnz`, like:

```
int 1
bnz label
```

If there is opcode space, it would be nice to have an instruction for this to conserve instruction space.

**Comment by algobolson** [comment]
Another reasonable possibility. I'd guess the next two branch variants would be `b` branch unconditionally and `bz` branch-if-zero to provide the logic flip of `bnz` branch-if-not-zero

**Comment by jeapostrophe** [comment]
Yes, `bz` would be useful to me, because I generate a lot of `!\nbnz label` sequences right now.
