### ISSUE TITLE
TEAL - how bytes interact with operations (maybe feature request)

### ISSUE THREAD

**Issue by jeapostrophe** [algorand/go-algorand#931]
Is the `==` operation intended to compare bytes as well as uint64 data? The reference says `Pops: ... stack, {any A}, {any B}`, so I assume yes.

Similarly, the `load`/`store` operations say they work on `any`s, so this appears to mean that when you put something into the scratch space, its type is remembered. I believe that the intention of the limited 256-sized scratch space is to limit memory usage, but if you can store arbitrary bytes there, then there doesn't appear to a bound, unless there is a bound on byte size, but I don't see such a limit in the reference.

**Comment by derbear** [comment]
> Is the `==` operation intended to compare bytes as well as uint64 data?

Yes.

> when you put something into the scratch space, its type is remembered.

Correct.

> I believe that the intention of the limited 256-sized scratch space is to limit memory usage, but if you can store arbitrary bytes there, then there doesn't appear to a bound, unless there is a bound on byte size, but I don't see such a limit in the reference.

Currently, one effective limit on byte blob size is 1K, which is the maximum size of a TEAL program. We don't yet have operations to modify the size of a byte blobs (but there are plans to have basic operations such as concatenation, subslicing, etc., which place a blob size limit of 4K).

**Comment by jeapostrophe** [comment]
Thank you very much!
