### ISSUE TITLE
TEAL - non-panic halt

### ISSUE THREAD

**Issue by jeapostrophe** [algorand/go-algorand#932]
TEAL appears to only have two ways of exiting the program: running `err`, which fails, and dropping off the end of the end of the program, which returns whatever is at the top of the stack. This makes compilation a bit awkward, because I have to have all branches that terminate jump to the end of the program so they can fall off. I'd like a `halt` or `return` instruction that exits with the top of the stack as the answer.

**Comment by algobolson** [comment]
It's a reasonable idea. Definitely belongs on the maybe-TODO list. Success anywhere could be
```
int 1
return
```
or more likely
```
...misc logic...
&&
return
```
