### ISSUE TITLE
Fix travis Ubuntu Deploy installer download failure

### ISSUE THREAD

**Issue by onetechnical** [algorand/go-algorand#933]
### Subject of the issue

When a non-PR build is triggered on a rel/* branch, the Ubuntu Deploy step in the deploy stage will fail.

### Your environment
N/A

### Steps to reproduce

Trigger a non-PR go-algorand build on rel/beta.

### Expected behaviour

Successful completion of Ubuntu Deploy step of deploy stage.

### Actual behaviour

Error appears here:

```
[./test_release.sh] Running ubuntu:16.04-test...
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
install.sh: line 27: ./update.sh: No such file or directory
[install.sh] Testing: algod -v
install.sh: line 30: ./node/algod: No such file or directory
[./test_release.sh] Running ubuntu:18.04-test...
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
install.sh: line 27: ./update.sh: No such file or directory
[install.sh] Testing: algod -v
install.sh: line 30: ./node/algod: No such file or directory
[./test_release.sh] The following images could not be run:
 - centos:7
 - centos:8
 - ubuntu:16.04
 - ubuntu:18.04
The command "scripts/travis/test_release.sh" exited with 1.
cache.2
store build cache
```
The issue was in ./test/packages/install.sh -the command `curl --silent -L https://github.com/algorand/go-algorand-doc/blob/master/downloads/installers/linux_amd64/install_master_linux-amd64.tar.gz?raw=true | tar xzf -` fails, probably because it's missing the quotes around the URL which contains a question mark.

**Comment by onetechnical** [comment]
I guess we need to re-verify this is still a bug.

**Comment by onetechnical** [comment]
The nightly build failed in the Ubuntu Deploy stage.

It appears that though there are messages to upload it to s3://algorand/builds/channel/nightly, the binary never makes it. Hence, the failing tests.

Noted:

- 10/8
- 10/7 (re-run, successful)
- 9/24

Possibly other times. A re-run of the job will fix the issue.

**Comment by onetechnical** [comment]
Not failing anymore, going to icebox for now.

**Comment by ian-algorand** [comment]
Looked at this again 11/23, going to keep open for now to track any future instances of these failed tests
