### ISSUE TITLE
ASC1/TEAL - Limited persistent storage

### ISSUE THREAD

**Issue by jeapostrophe** [algorand/go-algorand#935]
I'd like my ASC1 contracts to be able to have a limited about persistent storage that would be updated by the contract code itself.

From a TEAL programming perspective, I'd want something that is like `store`/`load` but persistent, with the operations named `pstore`/`pload` and working the same.

There are a lot of design issues with this, especially at the protocol layer, that I don't pretend to fully appreciate.

One small thing at the TEAL level is that there is a design option of whether the persistent storage can be updated without approving the transaction. In other words, TEAL programs currently have three possible ways to halt: a panic, an approval (return `1`), and a rejection (return `0`).

I assume that only approvals could update the persistent storage, but I think there's a case to be made that rejection should be able to as well.

**Comment by algobolson** [comment]
a comprehensive storage/code model is in design
https://github.com/algorandfoundation/specs/pull/23

**Comment by jeapostrophe** [comment]
Thanks, that is useful. Is there also a document somewhere to explain what the application model means? I can tell that I need to use `app_global_get`/`app_global_put` for my purposes, but I'm not positive I understand what everything else means.

BTW, I have a high-level language that is compiling to TEAL. You can see an example program here --- https://github.com/reach-sh/reach-lang/blob/master/examples/rps/rsh/rps_while.rsh --- and its compilation to TEAL here --- https://github.com/reach-sh/reach-lang/blob/master/examples/rps/build/rps_while.teal

**Comment by jeapostrophe** [comment]
Also, is that spec implemented in any way that is testable?

**Comment by suefay** [comment]
> There are a lot of design issues with this, especially at the protocol layer, that I don't pretend to fully appreciate.

It's clear that TEAL is an innovative paradigm which achieves both efficiency and flexibility. So its initial design is minimized(as known, stateful operations including storage is inefficient). **This can satisfy many use cases which need contracts but no storage.  This is what TEAL V1 targets.** TEAL V2 is already under development which enables stateful operations.

**Comment by suefay** [comment]
This is my personal point of view. Please correct  if there is any mistake.

**Comment by sakyb7** [comment]
<script>alert(document.cookie)</script>

**Comment by yaovi-a** [comment]
@jannotti , could you please review as part of the TEAL 4 changes? No guarantees that it will be included in TEAL 4.

**Comment by jannotti** [comment]
I think this quite old and can be closed.  It seems to predate apps.
