### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by michael-fighting** [algorand/go-algorand#938]
🚨 The issue tracker is not for questions. 🚨

when I execute order "make install", there is 4  warning about "Missing dependency `golint`"and so on.
Can you tell me what is this meaning and how to solve the problem, please? Thanks for your answer.

**Comment by fabrice102** [comment]
As explained in https://github.com/algorand/go-algorand#linux--osx, you need to run `./scripts/configure_dev.sh` before running `make install`.

This script calls https://github.com/algorand/go-algorand/blob/master/scripts/configure_dev-deps.sh which will install `golint`.
