### ISSUE TITLE
Allow watching-only addresses

### ISSUE THREAD

**Issue by algoradam** [algorand/go-algorand#94]
Right now `goal account list` shows only accounts to which you have private keys. But a user might care about participation-only accounts or accounts whose keys are in cold storage. It would be nice if there were a way to tell `goal` which accounts to watch. Addresses for which we've registered participation keys or have the private keys could be added to the watchlist automatically. Other addresses (such as cold storage accounts) could be added manually with some command like `goal account watch <addr>`

This is also motivated by scalability concerns: At some point it will no longer be practical for nodes to maintain the balances of every account in the system -- they'll need to maintain balances (and balance proofs) for the specific accounts they care about. So it may make sense to go ahead and put in place the infrastructure for letting `algod` keep track of which accounts to watch (rather than having `goal` maintain the list). This could be the `AccountManager` or something similar to it.

**Comment by ian-algorand** [comment]
old issue, deferring for now until it becomes a priority
