### ISSUE TITLE
Update API documentation or parameter handling for /v1/account/{address}/transactions path

### ISSUE THREAD

**Issue by jecassis** [algorand/go-algorand#972]
### Subject of the issue
For the API path **GET /v1/account/{address}/transactions** I suggest to update the documentation to specify explicitly that for the parameters `fromDate `and `toDate` a user must use both. There is a hard-coded conditional falling through to using `max` if only one of them is used. It appears that `firstRound` and `lastRound` behave similarly and these parameters are mutually exclusive from the date ones. That would be useful to document as well. This behavior occurs when querying the node directly without any SDK.

### Your environment
* Software version: `2.0.5.stable [rel/stable] (commit #8b0be452)`
* Operating System details: `Linux 4.15.0 x86_64`

### Steps to reproduce
On an indexed and archival node the following returns last 100 (`max `parameter default) transactions:
`$ curl "http://$(cat $ALGORAND_DATA/algod.net)/v1/account/<account>/transactions?fromDate=2020-04-13" -s -H "X-Algo-API-Token: $(cat $ALGORAND_DATA/algod.token)"`

### Expected behaviour
Preferably should assume `time.Now()` for `toDate` if only fromDate is specified. Or alternatively return some error status code. Similarly for `firstRound`, assume `lastRound` is closest committed block on node or return error status code. Should also be explicit about implemented behavior in the documentation including mutual exclusivity between date and round parameter pairs.

### Actual behaviour
Returns last 100 (`max `parameter default) because falls through if/else conditionals in `handlers.go`. On the mutual exclusive front preference is given to rounds over dates, but `max` applies to everything.

**Comment by algoanne** [comment]
I know this is old, v1 APIs were deprecated a while ago at this point and are about to be fully retired, so closing this.
