### ISSUE TITLE
v1 transactions api doesn't return tx date

### ISSUE THREAD

**Issue by roccomuso** [algorand/go-algorand#978]
`/v1/account/{address}/transactions` doesn't return the tx date.

How to get that?

**Comment by rotemh** [comment]
Thanks for the question. The transaction contains the round number which has a time field associated with. 
To put it simply, once you have the transaction, you can query the relevant block using `/v1/block/{round number}` and get the time.

**Comment by roccomuso** [comment]
So inefficient if I gotta get the whole block though :s 

Another question. I saw they have like the `fromDate` or `toDate` params. What is the date format that gotta be used?

**Comment by roccomuso** [comment]
Does the v2 api solves this?
